### ISSUE TITLE
Mysql Connections - Can't configure Databases/Catalog Filters

### ISSUE THREAD

**Issue by hc-danieltiziani** [dbeaver/dbeaver#10071]
#### System information: 
- Operating system (distribution) and version: MacOSX Mojave
- DBeaver version: Version 7.2.2.202010041557
- Additional extensions

#### Connection specification:
- Database name and version: Mysql
- Driver name: Mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The filter Databases/Catalogs is gray/disabled for Mysql Connections:

![image](https://user-images.githubusercontent.com/58551089/96109498-fae87900-0ede-11eb-8379-be9f33a19ee6.png)
![image](https://user-images.githubusercontent.com/58551089/96109534-0471e100-0edf-11eb-849c-66f3d4aa464d.png)

#### Steps to reproduce, if exist:
Edit Connection and go to General Tab and try to create a filter.
I wanted to filter tables like sys, tmp, innodb, etc.

**Comment by uslss** [comment]
thanks for the bug report.
As a workaround you could use filters, that are available in context menu in DB Navigator
![image](https://user-images.githubusercontent.com/31996417/96112930-0f7f3e00-0eec-11eb-82df-4676a60e732b.png)

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.1.
Ability to choose Database/Catalogs in Connection page added, and tab Schemas/Users disabled.

Also ability to choose Database/Catalogs in Connection page added to Snowflake connection.

**Comment by uslss** [comment]
filter applying has no effect. Excluded databases are still shown. Also, there is no sync with a filter in DB Navigator

**Comment by uslss** [comment]
filters aren't applied if the database wasn't reconnected after applying in settings
![2020-12-07_13h13_10](https://user-images.githubusercontent.com/31996417/101339717-d6ca6800-388f-11eb-907f-94d7c40c6f0e.gif)

**Comment by uslss** [comment]
verified
