### ISSUE TITLE
Problem after updating office plugin

### ISSUE THREAD

**Issue by Bakrain** [dbeaver/dbeaver#10234]
#### System information: 
- windows 10 pro 2004
- all dbeaver versions I have tried from 6.3.0 to 7.2.4

#### Connection specification:
- Oracle 8i

#### Describe your question:
when I update office plugin which export the data to excel,after updating the plugin the program still blinking with splash screen for at least 30 minutes and I can not force stop the dbeaver while blinking.
I do not know is it an issue or I have to do something to prevent this happen every time I upgrade the office plugin?

You can see the short video here
https://streamable.com/izqi1g

**Comment by uslss** [comment]
Hi @Bakrain ,
could you check if there is something in the [Log](https://github.com/dbeaver/dbeaver/wiki/Log-files)? 
Thanks in advance

**Comment by uslss** [comment]
there are no updates on the issue for a long time.
If it is still actual for you - feel free to reopen the ticket with an additional info

**Comment by gstordeur** [comment]
Hi,
I have the same issue as Bakrain, after updating the office plugin, Dbeaver restart over and over again. Sometimes it fianlly works, sometimes not, and I have to install a previous version.
I have a siilar configuration (windows 10 20H2), and I works mainly with Oracle.

For example today, it has finally started after 50 restart.
I have attecahed the logs, I hope you cand find something.

Thanks a lot !
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5722871/dbeaver-debug.log)

**Comment by chriswatkins314** [comment]
I have had this same problem for over a year when installing the Office plug-in after upgrading the dbeaver version.  Usually, a system re-boot will fix the issue.

**Comment by Bakrain** [comment]
Anyone faced the same issue, I fixed it by checking the box for me instead of for all users during installing dbeaver.

**Comment by chriswatkins314** [comment]
Thanks, I will try that at the next upgrade. The reboot worked again for me this time. On reboot, I still get the blinking splash screen at first, but it eventually opens after a couple of min.

**Comment by chriswatkins314** [comment]
> Anyone faced the same issue, I fixed it by checking the box for me instead of for all users during installing dbeaver.

Update:  I tried this on my recent upgrade to v 21.0.4 and that resolved the issue for me.  Thanks for the suggestion!

**Comment by monosabio** [comment]
Solved easily by renaming **org.eclipse.osgi** folder located in %userprofile%\\.eclipse\org.jkiss.dbeaver.product_21.2.1_1535670467_win32_win32_x86_64\configuration

By renaming the **org.eclipse.osgi**  folder  the splash screen immediately stops blinking.

Edit: Just delete the **.manager** folder to solve the splash screen issue: %userprofile%\\.eclipse\org.jkiss.dbeaver.product_xxxxxx\configuration\org.eclipse.osgi\\.manager
