### ISSUE TITLE
Firebird database views are not visible in version 7.2.5

### ISSUE THREAD

**Issue by yiwan74** [dbeaver/dbeaver#10392]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.5

Database name and version: Firebird

In version 7.2.5 database views could not be found.

![image](https://user-images.githubusercontent.com/14015195/99369757-1c14fe80-28bd-11eb-9f04-1622cdb85f0b.png)

**Comment by LonwoLonwo** [comment]
Thanks for bug report! fix it soon

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
#10411 created
verified

**Comment by teklstudio** [comment]
> Fixed

I have tried 7.3.0 from https://dbeaver.io/files/ea/  just now and views in Firebird are still not shown.  I see them as regular tables.

**Comment by uslss** [comment]
@teklstudio what firebird version do you use?

**Comment by teklstudio** [comment]
> @teklstudio what firebird version do you use?
@uslss Firebird version 2.5.5

**Comment by uslss** [comment]
@teklstudio cannot reproduce it
![image](https://user-images.githubusercontent.com/31996417/100100680-3b3dfe00-2e72-11eb-9614-104d23f65227.png)
Is there something in the logs?

**Comment by teklstudio** [comment]
@uslss where can I send you my database?

**Comment by teklstudio** [comment]
@uslss maybe helps, that I have view which consist from union of two selects

**Comment by uslss** [comment]
@teklstudio you can send the database to diana@jkiss.org
Thanks in advance

**Comment by uslss** [comment]
@teklstudio thanks for the help with the investigation of the issue.
The new issue is created #10492 
Close this issue as resolved.

**Comment by teklstudio** [comment]
@uslss  thank you. it will  be in early access  7.3.2 I expect

**Comment by DorwinDT** [comment]
@uslss , I have downloaded EA version 7.3.2 and issue is not resolved...
