### ISSUE TITLE
Move to next row does not refresh data display | MacOS Big Sur

### ISSUE THREAD

**Issue by QuirkyFox** [dbeaver/dbeaver#10409]
#### System information: 
- Operating system (distribution) and version: MacOS Big Sur (MacOS 11.0)
- DBeaver version : Community 7.2.5
- Additional extensions - none

#### Connection specification:
- Database name and version: MySQL 5.7 in Google Cloud SQL
- Driver name: com.mysql.jdbc.JDBC4CommentClientInfoProvider
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: Yes, Google Cloud SQL Proxy, connecting via localhost.

#### Describe the problem you're observing:
When exploring the data in a table, when clicking on the "move to next row" button or using the shortcut key, the display does not change even though the new data is selected. When any alterations are made or arrow keys are pressed, then the display is refreshed. The same holds true for Record View too.

#### Steps to reproduce, if exist:
1) Go into the data view for a table.
2) Select one cell.
3) Click on the "Move to next row" button, or use the key combination to move to the next row.
4) Should see that no data display refresh occurs.
5) Same for the Record View (press tab and try again).
6) Alter the data for one of the cells or press an arrow key or click on the data, and the data will refresh.

#### Include any warning/errors/backtraces from the logs

No logs because no error is produced.

**Comment by JHyeok** [comment]
I have the same issue.

**Comment by MarcoFiletti** [comment]
Other views also don't refresh, for example Database > Administer > Session Manager

**Comment by QuirkyFox** [comment]
Just to update: 
For me this is on a MacBook Pro Early 2015.

**Comment by JHyeok** [comment]
It seems that this problem is fixed in version 7.3.0. This problem no longer appears on my PC.

**Comment by duncan-lumina** [comment]
Still an issue for me - have updated to 7.3.0 and still giving the same issues.

**Comment by akilovich** [comment]
Fixed in the scope of https://github.com/dbeaver/dbeaver/issues/10535.

**Comment by kseniiaguzeeva** [comment]
You can check the fix in 7.3.1 EA https://dbeaver.io/files/ea/

**Comment by akilovich** [comment]
Closed.
