### ISSUE TITLE
Autocomplete problem with tables as synonyms

### ISSUE THREAD

**Issue by michal-roman** [dbeaver/dbeaver#10441]
on Oracle DB 12c -Admin Client 
DBeaver 7.2.5
Win 10 x64

Created synonym for table sys_outoo_system.order_table as order_table. 
Using synonym in SQL select from order_table - works ok
Using alias in SQL with synonym does not.

select * from order_table o where o.[ctrl+space] does nothing ...
select * from sys_outoo_system.order_table o wher o.[ctrl+space] works

**Comment by LonwoLonwo** [comment]
@michal-roman hello.
Please test the [new versions](https://dbeaver.io/). Some changes have taken place in SQL Editor, perhaps the problem has been resolved.

**Comment by uslss** [comment]
there is no update on issue for a long time. 
if issue is still actual for you - feel free to reopen it

**Comment by MatteoR23** [comment]
Can someone reopen this issue? The problem is still there on DBeaver v.21.0.2.202104042040

**Comment by LonwoLonwo** [comment]
Hello @MatteoR23
you can add more details about your problem here or create new Issue.

**Comment by LonwoLonwo** [comment]
@MatteoR23 also you can check our [Early Version](https://dbeaver.io/files/ea/). We fixed some problems with autocomplete in this version.

**Comment by MatteoR23** [comment]
@LonwoLonwo unfortunately also the early version has the same problem.

**Comment by MatteoR23** [comment]
Hello, can you reopen this bug please? 
The issue is still there also on latest version
![image](https://user-images.githubusercontent.com/25712297/115253744-f66e7880-a12c-11eb-8d3a-a416bc59c9aa.png)
![image](https://user-images.githubusercontent.com/25712297/115253893-2158cc80-a12d-11eb-8000-5bd999f3dcbf.png)
![image](https://user-images.githubusercontent.com/25712297/115253998-3a617d80-a12d-11eb-878c-5cec035200be.png)

**Comment by MatteoR23** [comment]
Hello,

I checked also on the latest released version (21.0.3), but the issue is still there.
Can you please reopen this bug? I feel useless to open a new one.

Thank you.
Best regards,
Matteo


![image](https://user-images.githubusercontent.com/25712297/115254558-c07dc400-a12d-11eb-86b7-505d157c19fc.png)
![image](https://user-images.githubusercontent.com/25712297/115254646-d5f2ee00-a12d-11eb-941f-ab9e36e2821f.png)
![image](https://user-images.githubusercontent.com/25712297/115254677-df7c5600-a12d-11eb-86cc-4fef96cc3b11.png)

**Comment by LonwoLonwo** [comment]
Hello @MatteoR23 
What database do you use?
Can you provide DDL of table an synonym, please?

**Comment by MatteoR23** [comment]
Hello @LonwoLonwo 

I post here:
![Screenshot 2021-04-20 150456](https://user-images.githubusercontent.com/25712297/115400747-ed8fac80-a1e9-11eb-9da1-788c46790f8c.png)
![Screenshot 2021-04-20 150429](https://user-images.githubusercontent.com/25712297/115400781-f54f5100-a1e9-11eb-96b3-6331c2f63e8c.png)

The DDL is:
`-- BIDTMS.BID_CALENDAR1 definition

CREATE TABLE "BIDTMS"."BID_CALENDAR1" 
   (	"CALENDAR_DATE" NUMBER(14,0), 
	"DAY_NUMBER_IN_MONTH" VARCHAR2(2 CHAR), 
	"DAY_ID" NUMBER(14,0), 
	"LASTDAYOFMONTH_FLG" VARCHAR2(10 CHAR), 
	"MONTH_NUMBER" VARCHAR2(2 CHAR), 
	"MONTHNAME_NUM" VARCHAR2(100 CHAR), 
	"MONTH_NAME_LONG" VARCHAR2(36 CHAR), 
	"MONTH_NAME" VARCHAR2(12 CHAR), 
	"YEAR_NUMBER" VARCHAR2(4 CHAR), 
	"AGREEMENTDATE_AA_FLG" VARCHAR2(1 CHAR), 
	"PAYMENTDATE_AA_FLG" VARCHAR2(1 CHAR), 
	"AGREEMENTDATE_TR_FLG" VARCHAR2(1 CHAR), 
	"PAYMENTDATE_TR_FLG" VARCHAR2(1 CHAR), 
	"PAYMENTDATE_ER_FLG" VARCHAR2(1 CHAR), 
	"AGREEMENTDATE_CR_FLG" VARCHAR2(1 CHAR), 
	"PAYMENTDATE_CR_FLG" VARCHAR2(1 CHAR), 
	"AGREEMENTDATE_LQ_FLG" VARCHAR2(1 CHAR), 
	"PAYMENTDATE_LQ_FLG" VARCHAR2(1 CHAR), 
	"REFDATE_CASHMONITORING" VARCHAR2(1 CHAR), 
	"REFDATE_PERFORMANCE" VARCHAR2(1 CHAR), 
	"REFDATE_DASHBOARD" VARCHAR2(1 CHAR), 
	"ORIGINATING_SYSTEM_NO" NUMBER(14,0), 
	"CURRENT_VERSION" VARCHAR2(10 CHAR), 
	"DATA_SOURCE" VARCHAR2(50 CHAR), 
	"DWH_CREATED_DATE" DATE, 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_CHANGE_TS" TIMESTAMP (6), 
	"ETL_LAST_CHANGE_TS" VARCHAR2(100 CHAR), 
	"VALID_FROM_DATE" TIMESTAMP (6), 
	"VALID_TO_DATE" TIMESTAMP (6), 
	"BATCH_ID" VARCHAR2(100 CHAR), 
	"CALENDAR_IK" NUMBER(14,0), 
	"CALENDAR_KEY" DATE, 
	"REFDATE_RISK" VARCHAR2(1 CHAR), 
	 CONSTRAINT "PK_BID_CALENDAR1" PRIMARY KEY ("CALENDAR_IK") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BIDTMSDAT" ;`

**Comment by MatteoR23** [comment]
I'm going to open a new issue, while this issue is closed and out of my control

**Comment by LonwoLonwo** [comment]
@MatteoR23 yep, this is a good idea

**Comment by MatteoR23** [comment]
Done, I opened the issue #12190
I will switch to it

Thank you for your patience :-)
