### ISSUE TITLE
Some views are shown as tables 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10492]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.2.5

#### Connection specification:
- Database name and version firebird 2.5
#### Describe the problem you're observing:
Some views (where UNION ALL is used) are shown as tables:
ibexpert:
![image](https://user-images.githubusercontent.com/31996417/100215213-caeeb580-2f21-11eb-8ceb-5f4d77b3ae86.png)
isql:
![image](https://user-images.githubusercontent.com/31996417/100215273-d8a43b00-2f21-11eb-8f24-dbdd1ef1e269.png)
dbeaver:
![image](https://user-images.githubusercontent.com/31996417/100215375-f83b6380-2f21-11eb-9a48-35506e71e35f.png)

**Comment by mkgrgis** [comment]
Other issue about incorrect sorting of table catalogue https://github.com/dbeaver/dbeaver/issues/8181

**Comment by serge-rider** [comment]
It seems to be 32-bit specific issue

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/104888439-ce307b80-597d-11eb-9c5c-bc0e05723d2b.png)

**Comment by DorwinDT** [comment]
in  which version it will be fixed?

**Comment by LonwoLonwo** [comment]
@teklstudio Hello. 
Fixed in 7.3.4.
Will be available [here](https://dbeaver.io/) at 2020-02-01

**Comment by DorwinDT** [comment]
@LonwoLonwo hello
I have just downloaded **7.3.4.202101211823** from early access, but bug is still there... will be implemented later?

**Comment by LonwoLonwo** [comment]
@teklstudio Hello. Have you tested new versions? Is bug still there?

**Comment by DorwinDT** [comment]
yes, I have bug...
my version is
[cid:image001.png@01D7078D.6DA78FC0]
and view are between tables:
[cid:image002.png@01D7078D.6DA78FC0]

best regards
Peter

**Comment by DorwinDT** [comment]
> @teklstudio Hello. Have you tested new versions? Is bug still there?

again :) yes. I have version 7.3.5.202102151746
andviews are still between tables...

**Comment by LonwoLonwo** [comment]
Can you please show result of this query 
`SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='SIZELIST1'`
Because this is the system table from which we read all the data about tables and views.

**Comment by DorwinDT** [comment]
> Can you please show result of this query
> `SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='SIZELIST1'`
> Because this is the system table from which we read all the data about tables and views.

here it is uploaded:
https://ibb.co/0fktkNk

**Comment by flambchap** [comment]
Another fix has been introduced, I hope it will work.

**Comment by DorwinDT** [comment]
@akilovich great, and in which version it will be available?

**Comment by flambchap** [comment]
@teklstudio It will be available in 21.0.1, the first 21.0.1 EA containing the fix will be built somewhere in the next week, I'll let you know.

**Comment by flambchap** [comment]
@teklstudio [The EA version](https://dbeaver.io/files/ea/) with the fix is out.

**Comment by DorwinDT** [comment]
@akilovich - works great! thank you

**Comment by flambchap** [comment]
Hooray!
