### ISSUE TITLE
Long "case when" query freeze dbeaver CE forever

### ISSUE THREAD

**Issue by maslopop** [dbeaver/dbeaver#10704]
Executing CREATE OR REPLACE VIEW
 
- Operating system (distribution) and version  : **Windows 10 build 18363**
- DBeaver version  : **7.3.0 CE**
- Java version:  **1.8**
 

- Database name and version  : **Vertica 9.2.1**
- Driver name  : 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

Apps that only with long **case when** query, like the following,
the dbeaver CE freeze forever

```
create or replace view v_name as
select f1,   f2, 
case when f3 <5   then 5    else 
case when f3 <=10 then 10 else
case when f3 <=15 then 15 else
case when f3 <=20 then 20 else
case when f3 <=25 then 25 else
case when f3 <=30 then 30 else
case when f3<=35 then 35 else
case when f3<=40 then 40 else
case when f3<=50 then 50 else
case when f3<=60 then 60 else
case when f3<=70 then 70 else
case when f3<=80 then 80 else
case when f3<=90 then 90 else
case when f3<=100 then 100 else
case when f3<=120 then 120 else
case when f3<=150 then 150 else
case when f3>150  then 999 end 
end end end end end end end end end end end end end end end end as ff, 
max(year(current_timestamp)) yy,
group by 1,2;

```

Grazie, 
Massimo

**Comment by kseniiaguzeeva** [comment]
What do you mean when tell freeze? The query cannot be finished or you can't do anything in DBeaver at all?

**Comment by maslopop** [comment]
Hi kseniiaguzeeva, I apologize for the late reply ... 
dbeaver no longer responds, I can't do anything at all ... and the query really never starts.

**Comment by kseniiaguzeeva** [comment]
Please send also logs https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by maslopop** [comment]
Sorry but it's impossible ... 
Dbeaver stops to respond and no log are produced during 
or after the killing it.

Massimo

**Comment by maslopop** [comment]
To reproduce:

`create table public.ff ( f1 varchar(3), f2 varchar(3), f3 integer);

insert into public.ff (f1,f2,f3) values ('a','a',10);
insert into public.ff (f1,f2,f3) values ('b','b',20);
insert into public.ff (f1,f2,f3) values ('c','c',30);
insert into public.ff (f1,f2,f3) values ('d','d',50);
insert into public.ff (f1,f2,f3) values ('e','e',100);
insert into public.ff (f1,f2,f3) values ('f','f',200);

select f1,   f2, 
case when f3 <5   then 5    else 
case when f3 <=10 then 10 else
case when f3 <=15 then 15 else
case when f3 <=20 then 20 else
case when f3 <=25 then 25 else
case when f3 <=30 then 30 else
case when f3<=35 then 35 else
case when f3<=40 then 40 else
case when f3<=50 then 50 else
case when f3<=60 then 60 else
case when f3<=70 then 70 else
case when f3<=80 then 80 else
case when f3<=90 then 90 else
case when f3<=100 then 100 else
case when f3<=120 then 120 else
case when f3<=150 then 150 else
case when f3>150  then 999 end 
end end end end end end end end end end end end end end end end as ff, 
max(year(current_timestamp)) yy
from public.ff
group by 1,2;

`

Run the query  and then  the fog

![image](https://user-images.githubusercontent.com/5228900/104749245-dd7fb100-5752-11eb-9be2-fc032a9b3344.png)





Massimo

**Comment by kseniiaguzeeva** [comment]
I reproduced it in PostgreSQL too.

**Comment by LonwoLonwo** [comment]
It's again looks like a bug in @JSQLParser library

**Comment by manticore-projects** [comment]
Greetings!
This has been solved and my PR https://github.com/JSQLParser/JSqlParser/pull/1208 to SQLParser has been accepted. If you guide me on how to update the Third Party Dependencies for DBeaver, I could create a PR for you.

**Comment by LonwoLonwo** [comment]
Hello @manticore-projects 
Thanks for the report and for contribution.
Now we need to wait for the official release of the next JSqlParser version.

**Comment by LonwoLonwo** [comment]
Hello @manticore-projects 
Maybe you can take a look at the other problem associated with JSQLParser https://github.com/dbeaver/dbeaver/issues/10680

**Comment by manticore-projects** [comment]
Greetings, 

it is solved to a very large extend in JSQLParser 4.1 Snapshot although
the Generic Parser will always struggle with Super Deeply Nested
Complex Expressions.

We will need to implement a solution together, which starts JSQLParser
within a separated thread to timeout eventually and fail gracefully
without freezing.


Cheers
Andreas

**Comment by LonwoLonwo** [comment]
@manticore-projects I've tested new JSQLParser 4.1 Snapshot in DBeaver
It helps with problem of this ticket (many case when), but DBeaver still hangs with
```sql
SELECT
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(0
,0),0),0),0),0),0),0),0)
,0),0),0),0),0),0),0),0)
,0),0),0),0),0),0),0),0)
,0),0),0),0),0),0),0),0)
```
unfortunately

**Comment by manticore-projects** [comment]
Thank you for your feeback. What snapshot exactly have you used please
and have you compiled from GIT?
(I am sorry, I have no authority on the release policy of JSQLParser).

However, we have 2 testcased which test the mentioned statement
successfully!

@Test(timeout = 2000)
public void testIssue1103Long() throws JSQLParserException {
assertSqlCanBeParsedAndDeparsed(
"SELECT\n"
+ "ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(\n"
+ "ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(\n"
+ "ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(\n"
+ "ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(0\n"
+ ",0),0),0),0),0),0),0),0)\n"
+ ",0),0),0),0),0),0),0),0)\n"
+ ",0),0),0),0),0),0),0),0)\n"
+ ",0),0),0),0),0),0),0),0)",
true);
}

--> passes.

Do you want me to provide you with a snapshot JAR?

**Comment by manticore-projects** [comment]
This SNAPSHOT jar parses the sample without problems.

[jsqlparser-4.1-SNAPSHOT.jar.zip](https://github.com/dbeaver/dbeaver/files/6598715/jsqlparser-4.1-SNAPSHOT.jar.zip)

**Comment by manticore-projects** [comment]
Please, how exactly have you called the Parser in your test?
Either
```java

new CCJSqlParser(SQL_STRING).withAllowComplexParsing(false).Statements();
```
or
```java
CCJSqlParserUtil.parse(SQL_STRING,null);
```

They key is to disallow ComplexParsing for deeply nested expressions. The second call will determine this automatically while you will have to set it explicitly within the first call. Both ways achieve the same result.

**Comment by LonwoLonwo** [comment]
@manticore-projects yes, I see. Many-round-query works with withAllowComplexParsing(false)

**Comment by manticore-projects** [comment]
Btw, you can test your statements [Online and Interactively here](jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBKB7ArgOwCYAoEo9paWOh+uRBexlF5ZpJVtDN91djrTbz7LH-fQb2E9R3cUQAMAGliTYASlnylcxcvVrVKjds06tuo4ZMGz+i3qvHz105ZsOtAKADcQA+) and share direct links to the examples.

It uses the a fixed JSQLParser with Nested With Statements, Value Lists as With Statements, Nested Expression Performance fixes, Complex Expression as Function Paramaters and Group By with Brackets.

You can even test the original 96kbyte Query Monster successfully although it takes 2 seconds to parse.

Please do let me know what else was needed and how to assist.
Cheers

![image](https://user-images.githubusercontent.com/18080123/120872672-90995b80-c5c9-11eb-8fef-0d886ebe384f.png)

**Comment by serge-rider** [comment]
JSQLParser version updated to 4.1-SNAPSHOT.
We'll also update after 4.1 release.

**Comment by uslss** [comment]
DBeaver still freezes when trying to execute query like
```sql
SELECT
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(
ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(ROUND(0
,0),0),0),0),0),0),0),0)
,0),0),0),0),0),0),0),0)
,0),0),0),0),0),0),0),0)
,0),0),0),0),0),0),0),0)

```

**Comment by uslss** [comment]
verified
