### ISSUE TITLE
"Can't navigate" error show up when reference panel is open after query execution 

### ISSUE THREAD

**Issue by SamFrost85** [dbeaver/dbeaver#11201]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.5 LTS
- DBeaver version: 7.3 (but I had this issues in past versions of DBeaver)
- Java version : 11
- Additional extensions

#### Connection specification:
- Database name and version: Oracle Database 18c 
- Driver name: oracle jdbc 12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Often, when I have the Reference panel open the new references aren't loaded and I receive an error in this format:
Attribute ACC_ID, type=NUMBER, pos=2 is missing in result set

#### Steps to reproduce, if exist:
- Run a normal query (E.G. SELECT  * FROM ACCOUNT ab)
- open the reference panel and select one item from the drop down menu
- run another query this one is giving me the problem consistently:
SELECT DISTINCT (acc_id) FROM ACCOUNT_BALANCE ab
- click on any of the result rows
- A popup with the menu title "Can't navigate" will show up, only way of stopping it is to close the panels.

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Feb 03 10:55:10 GMT 2021
Attribute ACC_ID, type=NUMBER, pos=2 is missing in result set

**Comment by uslss** [comment]
Hi @SamFrost85 ,
can you provide tables ddl?

**Comment by SamFrost85** [comment]
@uslss , I created a new test schema with just two tables:

`CREATE TABLE "TEST"."ACCOUNT" 
   (	"ACC_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ACC_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"ACC_CODE" VARCHAR2(50), 
	 CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ACC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;`


`CREATE TABLE "TEST"."ACCOUNT_DATA" 
   (	"ACD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ACD_ADDRESS" VARCHAR2(100), 
	"ACD_POSTCODE" VARCHAR2(9), 
	"ACD_ACC_ID" NUMBER(10,0), 
	 CONSTRAINT "ACCOUNT_DATA_PK" PRIMARY KEY ("ACD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ACCOUNT" FOREIGN KEY ("ACD_ACC_ID")
	  REFERENCES "TEST"."ACCOUNT" ("ACC_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;`

I also attached a couple of screenshots

![Annotation 2021-02-05 115633](https://user-images.githubusercontent.com/49839098/107030896-3e763400-67a9-11eb-8819-b5ee04eada0e.jpg)
![Annotation 2021-02-05 115625](https://user-images.githubusercontent.com/49839098/107030898-3fa76100-67a9-11eb-9a68-cd067da3450f.jpg)

**Comment by uslss** [comment]
thanks for clarification

**Comment by flambchap** [comment]
This problem is not specific to Oracle.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
still reproducible
![2021-04-27_14h35_16](https://user-images.githubusercontent.com/31996417/116234922-e296c800-a765-11eb-94ad-1be93fb51b52.gif)

**Comment by flambchap** [comment]
Fixed once again.

**Comment by uslss** [comment]
verified

**Comment by uslss** [comment]
FKs aren't shown in reference panel
![image](https://user-images.githubusercontent.com/31996417/116559442-26760280-a909-11eb-81dc-608fb592fe49.png)
![image](https://user-images.githubusercontent.com/31996417/116559596-486f8500-a909-11eb-8539-71363e3cf900.png)

**Comment by flambchap** [comment]
This problem is specific to Redshift and is not a side-effect of my fix.
