### ISSUE TITLE
When exporting large ER diagram to SVG the result is cropped

### ISSUE THREAD

**Issue by knutwannheden** [dbeaver/dbeaver#11365]
I had a look and I found this related issue: #3099 and I also found a comment explaining a workaround (see https://github.com/dbeaver/dbeaver/issues/3099#issuecomment-490088699), but I couldn't get it to work.

Please find attached the SVG as produced by DBeaver. When I open it with my system viewer (I have Chrom and Edge for Windows), it only shows one small part of the diagram. Zooming out doesn't help. However, I was able to manually add the `width` and `height` attributes to the top-level `<svg>` element to get the whole diagram to show (in my case I used `<svg width="2400" height="6700">`). Possibly there are better ways to achieve the same thing, but I have as good as no knowledge about SVG, so I wouldn't really know.

Possibly this is a limitation of the viewer (like Chrome), but somehow I doubt that and rather suspect that some attribute is missing in the XML.

#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.5
- Additional extensions: SVG Extension 1.0.87

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by knutwannheden** [comment]
Here is the diagram as exported by DBeaver (I've zipped the SVG as GitHub wouldn't allow me to upload the SVG directly): [export.zip](https://github.com/dbeaver/dbeaver/files/5988418/export.zip)

**Comment by knutwannheden** [comment]
Having absolutely no idea what I am doing, but I now set `<svg height="500%">` and that worked perfectly in my case.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report and for the workaround. Looking for a free space in future milestones to fix it.

**Comment by ShadelessFox** [comment]
Hello @knutwannheden,

I believe this was fixed in #11467. Can you please check it out?

Thanks!

**Comment by knutwannheden** [comment]
I am using DBeaver	21.0.1.202103211229 and DBeaver SVG Extension	1.0.87.202102141704. There I still have the problem with the clipped SVG diagrams.

**Comment by ShadelessFox** [comment]
That's unfortunate. Can you provide more details?

**Comment by knutwannheden** [comment]
AFAICT the result still looks the same. I can upload the generated SVG for you.

**Comment by ShadelessFox** [comment]
Yes, please, I'd take a look. Can you also provide the screenshot of the ER diagram GUI in DBeaver? I'm interested in the entities' placement, scroll position and the grid scale.

**Comment by knutwannheden** [comment]
Here is a screenshot: ![image](https://user-images.githubusercontent.com/408765/112150576-8ed21580-8be0-11eb-892e-ebf7f8f77a43.png)

And here the SVG (zipped): [test.zip](https://github.com/dbeaver/dbeaver/files/6189821/test.zip)

The contents is all there, but I can only see what fits on the screen (using Chromium-based browser as viewer), and when trying to zoom out (using browser functionality), the diagram gets clipped.

**Comment by ShadelessFox** [comment]
To be really sure, can you install the Early Access version? https://dbeaver.io/files/ea/

Thanks again.

**Comment by knutwannheden** [comment]
Yes! With the Early Access it now works as expected. The version of the SVG extension is now also updated: 1.0.89.202103211229. I was assuming I would only have to update the existing plug-in.
