### ISSUE TITLE
Changing ERD Setting Print Page Mode disables Printing

### ISSUE THREAD

**Issue by stevepowell2000** [dbeaver/dbeaver#11393]
#### System information: 
- Operating system (distribution) and version - Win 10
- DBeaver version 7.3.2.202101032114
- Additional extensions  n/a

#### Connection specification:
- Database name and version - N/A. This is an ERD issue
- Driver name - N/A. This is an ERD issue
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - N/A. This is an ERD issue

#### Describe the problem you're observing:

When changing the ERD Settings. I changed the Page Mode to Fit Page under the Print section. I hit Apply and Close, then the print icon disables, so I can't print the ERD. If I close the ERD and reopen it, I'm able to print.

#### Steps to reproduce, if exist:

described above

#### Include any warning/errors/backtraces from the logs
none I see

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
As a dirty workaround you can use <kbd>Refresh Diagram</kbd> button in the toolbar menu.

**Comment by uslss** [comment]
Print button is disabled for Schema/Table ERD until custom diagram creation. But even when it becomes highlighted it doesn't work
![2021-03-11_15h37_41](https://user-images.githubusercontent.com/31996417/110788557-d58a4c00-827f-11eb-94d7-db67523647b4.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Still reproducible for non-custom diagran (e.g. for tables). Button is active, but do nothing after click on it.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
