### ISSUE TITLE
Save script confirmation dialog is shown twice

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11929]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.2 EA

#### Describe the problem you're observing:
Save script confirmation dialog is shown twice
#### Steps to reproduce, if exist:
1. Connect to database
2. Open Script dialog with Ctrl+]
3. Make some changes in script window
4. Close DBeaver

**Actual result**
1. Exit confirmation dialog is shown - choose Yes
2. Save resources dialog is shown - choose Don't save
3. Save resources dialog is shown once again
![2021-03-31_11h40_29](https://user-images.githubusercontent.com/31996417/113116768-6ff20580-9216-11eb-80e4-806c32dbd31d.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
An issue with sql editor - fixed.
issue with data editor - still reproduced

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
