### ISSUE TITLE
Invalidate/Reconnect resets active catalog/schema to default

### ISSUE THREAD

**Issue by n8falke** [dbeaver/dbeaver#12022]
#### System information: 
- Windows 10
- DBeaver version 21.0.2.202104042040
- with git

#### Connection specification:
- Database: Oracle 12.1.0.2
- Driver: com.oracle.database.jdbc:ojdbc8:RELEASE 12.2.0.1

#### Describe the problem you're observing:
Reconnect by button, menu > Database > Invalidate/Reconnect or by network timeout resets active schema to default of connect instead of chosen.

#### Steps to reproduce, if exist:

- Connect to database
- Open new SQL script editor
- Choose different schema from default in drowdown "Active catalog/schema"
- Select from any table only in chosen schema
- Press Invalidate/Reconnect
- Try Select again

Results in: `SQL Error [942] [42000]: ORA-00942: table or view does not exist`

With SELECT this is not a problem. But with DROP TABLE you might drop a table from wrong schema. Once I created a view in wrong schema, because of network connection loss automatic reconnect and sending query to default schema.

As workaround currently I try to full qualify schema in all DDL / DML.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified on Oracle, but this Editor behavior still persists when working on PostgreSQL

**Comment by flambchap** [comment]
Fixed.

**Comment by flambchap** [comment]
The problem is also present in Derby and Vertica, which indicates a problem with all generic drivers.

**Comment by flambchap** [comment]
Fixed. Hopefully, once and for all.

**Comment by Matvey16** [comment]
Verified
