### ISSUE TITLE
Update/Delete statement is wrongly generated

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12126]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.0.2

#### Connection specification:
- Database name and version Clickhouse

#### Steps to reproduce, if exist:
1. Select Generate SQL Statement>Update in a table context menu
2. Copy the generated statement and execute in SQL Editor

**Expected**: the statement is successfully executed
**Actual result**: the statement execution fails because of wrong SQL:
```
UPDATE jindie2.test_2103
SET Column1_string='ew'
WHERE id=5;
```
instead of
```
ALTER TABLE jindie2.test_2103 UPDATE Column1_string='w'
	WHERE id=5
```

The same situation is with Delete statement.

**Comment by LonwoLonwo** [comment]
Fixed in DBever 21.1.2

**Comment by Matvey16** [comment]
Delete statement is still incorrect
![2021-06-22_18h34_11](https://user-images.githubusercontent.com/82543000/122955329-ad36e100-d388-11eb-9f5d-5946f5a02ce5.png)

**Comment by Matvey16** [comment]
Verified
