### ISSUE TITLE
PostgreSQL and SSH issue since DBeaver 21.0.3

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#12149]
#### System information: 
- Operating system (distribution) and version : Ubuntu 18.04
- DBeaver version : 21.0.3

#### Connection specification:
- Database name and version : PostgreSQL 11, 12 and 13
- Driver name : PostgreSQL JDBC (official)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
Since version 21.0.3 upgrade, it is no more possible to open PostgreSQL connections through SSH.
I get the following error message:

> Could not initialize class com.sun.jna.Native

If I try to reopen the connection, then the error message becomes:

> Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary

I had to downgrade DBeaver to avoid the issue, back to 21.0.2

Thanks in advance for your help.

Regards,
Cedric

**Comment by mrevjd** [comment]
System information:
- Operating system (distribution) and version : Ubuntu 20.04
- DBeaver version : 21.0.3

Connection specification:
- Database name and version : PostgreSQL and MariaDB
- Driver name : org.postgresql.Driver and org.mariadb.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Using SSH tunnels and SSH Agent. If I change the connection to use a key instead it works.

**Comment by ced75** [comment]
More detail about my tunnel SSH connection:

- Authentication method: Agent
- Implementation: JSch

**Comment by yennor** [comment]
System information:

    Operating system: Debian testing
    DBeaver version: dbeaver-ce 21.0.3

Connection specification:

SSH Tunnel, using ssh agent
Describe the problem you're observing:

Since updating, dbeaver can't access databases over an ssh tunnel anymore.
Steps to reproduce, if exist:
Include any warning/errors/backtraces from the logs

    Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.76.202104181339]
    Start DBeaver SSH implementation (JSch) [org.jkiss.dbeaver.net.ssh.jsch 1.1.65.202104181339]
    Start Java Native Access [com.sun.jna 5.6.0.v20200716-0148]
    2021-04-20 09:14:49.922 - pageant connect exception
    com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-x86-64/libjnidispatch.so) not found in resource path (/usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar)
    at com.jcraft.jsch.agentproxy.connector.PageantConnector.(PageantConnector.java:65)
    at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:116)
    at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
    at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:884)
    at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
    at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
    at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
    at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
    at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
    at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:71)
    at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
    at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
    at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
    at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    2021-04-20 09:14:49.924 - java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
    java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
    at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary.(JNAUSocketFactory.java:47)
    at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory.open(JNAUSocketFactory.java:114)
    at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.open(SSHAgentConnector.java:93)
    at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.(SSHAgentConnector.java:54)
    at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.(SSHAgentConnector.java:44)
    at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:124)
    at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
    at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:884)
    at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
    at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
    at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
    at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
    at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
    at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:71)
    at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
    at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
    at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
    at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by zeridon** [comment]
System Info:
```
OS: Ubuntu 20.04
ARCH: x86_64
Dbeaver Version: 21.0.3 (from tar.gz)
```

Expected: Connect to db

Actual: 
```
> Start DBeaver SSH implementation (JSch) [org.jkiss.dbeaver.net.ssh.jsch 1.1.65.202104181339]
> Start Java Native Access [com.sun.jna 5.6.0.v20200716-0148]
2021-04-20 11:16:12.724 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-x86-64/libjnidispatch.so) not found in resource path (/home/zeridon/tools/dbeaver-21.0.3//plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar)
	at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:65)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:116)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:216)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1673)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2021-04-20 11:16:12.782 - Could not initialize class com.sun.jna.Native
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary.<clinit>(JNAUSocketFactory.java:47)
	at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory.open(JNAUSocketFactory.java:114)
	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.open(SSHAgentConnector.java:93)
	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:54)
	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:44)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:124)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:216)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1673)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.700.v20200511-1530]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.500.v20210108-0738]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.5.0.v20201013-0853]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.7.0.v20210114-1216]
```

Steps to reproduce:
* Create new connection
* Configure ssh tunel (using jsch)
* Test tunel

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed.

Problem was caused by Eclipse-2021-03 migration. It contains two version of JNA and this led to JNA binaries loading conflict.

**Comment by ced75** [comment]
Thanks for the quick fix.

**Comment by uslss** [comment]
still reproducible
![Kazam_screenshot_00014](https://user-images.githubusercontent.com/31996417/116364034-715e2000-a80c-11eb-9b10-770164df1616.png)

**Comment by serge-rider** [comment]
Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572370

By some reason linux build keeps jna 5.6.0 dependency instead of good 4.5.1. Looking into it..

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
