### ISSUE TITLE
Autocomplete does not appear if I write SQL using table synonyms with Oracle 12 database

### ISSUE THREAD

**Issue by MatteoR23** [dbeaver/dbeaver#12190]
#### System information: 
- Operating system (distribution) and version: Windows  10 Pro 20H2
- DBeaver version
![Screenshot 2021-04-19 163307](https://user-images.githubusercontent.com/25712297/115514851-d5b93680-a284-11eb-8bbf-52fb96441c87.png)
- Additional extensions: Office integration

#### Connection specification:
- Database name and version
![Screenshot 2021-04-20 150429](https://user-images.githubusercontent.com/25712297/115514937-eb2e6080-a284-11eb-950d-7aa44e9b5ac7.png)
- Driver name: Oracle (JDBC)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NetScaler Access Gateway

#### Describe the problem you're observing:
On SQL Editor:
- If I use the table name directly on "FROM" clause, SQL Autosuggestion appears as expected
- If I use the table synonym on "FROM" clause, the SQL Autosuggestion does not appear anymore

#### Steps to reproduce, if exist:
- Create a sample table:
CREATE TABLE "BIDTMS"."BID_CALENDAR1"
(
 "CALENDAR_DATE" NUMBER(14,0),
 "CALENDAR_KEY" DATE
)SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "BIDTMSDAT" ;

- Create the Synonym:
![115400747-ed8fac80-a1e9-11eb-9da1-788c46790f8c](https://user-images.githubusercontent.com/25712297/115515846-cf778a00-a285-11eb-8bff-2fc45c9c1e5b.png)

- On SQL editor:
SELECT f.[hit ctrl + space => SQL suggestion appears] FROM table_name;
SELECT f.[hit ctrl + space => Nothing happens] FROM synonym_name;

![115254558-c07dc400-a12d-11eb-86b7-505d157c19fc](https://user-images.githubusercontent.com/25712297/115515141-1d3fc280-a285-11eb-8bc0-313afce34c1f.png)
![115254646-d5f2ee00-a12d-11eb-941f-ab9e36e2821f](https://user-images.githubusercontent.com/25712297/115515148-20d34980-a285-11eb-8eb9-37048f860f05.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.0

**Comment by Matvey16** [comment]
Verified

**Comment by MatteoR23** [comment]
I tried to build Dbeaver from devel branch, in order to check if it works.
Unfortunately, the problem is still there, exactly the same behavior

I'm sure that the merged pull request is there, because the java file has the expected change.

**Comment by LonwoLonwo** [comment]
Hello @MatteoR23 
As I can see on your images, you use schema identifier with synonym name.
do you use another default schema in SQL Editor?
It works for me without schema identifier for default schema:

![2021-05-21 12_47_31-](https://user-images.githubusercontent.com/45152336/119118409-d3d4c580-ba32-11eb-9419-4ea276c6477f.png)

and for another schema, if global search is enabled

![2021-05-21 12_48_50-DBeaver Enterprise 21 0 5 - _orcl_ Script-119](https://user-images.githubusercontent.com/45152336/119118560-fcf55600-ba32-11eb-9171-f2bf4c33c0b2.png)

**Comment by MatteoR23** [comment]
Effectively, I try to access from another schema.
Anyway, even if I check that setting, the problem is not resolved.

Here some screenshots from my devel version of DbEaver (I cloned the git repo yesterday after 6 PM CEST tz):
![Screenshot 2021-05-21 123509](https://user-images.githubusercontent.com/25712297/119124877-73915400-ba31-11eb-8df7-eaee93b38273.png)
![Screenshot 2021-05-21 123605](https://user-images.githubusercontent.com/25712297/119124900-78560800-ba31-11eb-9d39-fa942bbfa30a.png)
![Screenshot 2021-05-21 123630](https://user-images.githubusercontent.com/25712297/119124913-7be98f00-ba31-11eb-9261-656354fd61fb.png)

**Comment by MatteoR23** [comment]
@Matvey16 could you please reopen this bug? The problem is not resolved.

**Comment by Matvey16** [comment]
Verified

**Comment by LonwoLonwo** [comment]
Hello @MatteoR23 
In scope with this ticket https://github.com/dbeaver/dbeaver/issues/11327 we added new connection setting for Oracle.
Enabling this setting will help with solving the problem of auto-completion with fully qualified names.

![2021-05-26 10_44_55-DBeaver Enterprise 21 1 0 - _none_ Script-104](https://user-images.githubusercontent.com/45152336/119622858-3f8ea800-be10-11eb-8c09-2c4f85d0f7d0.png)

**Comment by MatteoR23** [comment]
@LonwoLonwo I compiled the new version and... it works!! Thank you very much, guys 💯 🥇

**Comment by LonwoLonwo** [comment]
@MatteoR23 Hooray!
