### ISSUE TITLE
Can't install SSHJ: installation fails with dependency error on org.bouncycastle.bcpkix

### ISSUE THREAD

**Issue by ronjouch** [dbeaver/dbeaver#12218]
This is a follow-up of https://github.com/dbeaver/dbeaver/issues/9989#issuecomment-824908370 . I want to connect to a PostgreSQL db through a SSH tunnel, but connection fails with default implementation `JSch` with error `process hasn't exited` (see https://github.com/dbeaver/dbeaver/issues/9989), so I'm following the suggestion from multiple commenters at https://github.com/dbeaver/dbeaver/issues/9989 to switch to SSHJ (instead of the default JSch).

Sadly, I'm unable to follow this advice to switch to SSHJ, because I'm unable to install it. When I try to install it (from `Install New Software` → `DBeaver SSHJ extension - https://dbeaver.io/update/sshj/latest/` → `Next`), installation fails with:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SSHJ 1.0.76.202104181339 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.76.202104181339)
  Missing requirement: SSHv2 library for Java 0.27.3 (org.jkiss.bundle.sshj 0.27.3) requires 'osgi.bundle; org.bouncycastle.bcpkix 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver SSH implementation (SSHJ) 1.0.76.202104181339 (org.jkiss.dbeaver.net.ssh.sshj 1.0.76.202104181339)
    To: osgi.bundle; org.jkiss.bundle.sshj 0.0.0
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.76.202104181339 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.76.202104181339)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh.sshj [1.0.76.202104181339,1.0.76.202104181339]
```

Am I missing something?

### System information

- Ubuntu 20.10, fully up-to-date
- DBeaver 21.0.3.202104181339 (latest as of today, installed from the official deb package)
- Zero additional extensions

**Comment by serge-rider** [comment]
BC deps config has been fixed

**Comment by ronjouch** [comment]
> BC deps config has been fixed

@serge-rider confirmed! Thanks. Closing.

**Comment by mbelang** [comment]
Still having this issue with dbeaver Version 21.2.2.202110030714 and Ubuntu 20.04.

**Comment by somerandomam** [comment]
error still present

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SSHJ 1.0.88.202110151816 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.88.202110151816)
  Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.69.0.v20210713-1924 (org.bouncycastle.bcpkix 1.69.0.v20210713-1924) requires 'java.package; org.bouncycastle.asn1.bsi [1.69.0,1.70.0)' but it could not be found
  Cannot satisfy dependency:
    From: SSHv2 library for Java 0.27.4 (org.jkiss.bundle.sshj 0.27.4)
    To: osgi.bundle; org.bouncycastle.bcpkix 0.0.0
  Cannot satisfy dependency:
    From: DBeaver SSH implementation (SSHJ) 1.0.88.202110151816 (org.jkiss.dbeaver.net.ssh.sshj 1.0.88.202110151816)
    To: osgi.bundle; org.jkiss.bundle.sshj 0.0.0
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.88.202110151816 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.88.202110151816)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh.sshj [1.0.88.202110151816,1.0.88.202110151816]
```

**Comment by jbsilva** [comment]
Same problem in Version 21.2.2.202110082155 on Arch Linux:

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: DBeaver SSHJ 1.0.88.202110151816 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.88.202110151816)
>   Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.69.0.v20210713-1924 (org.bouncycastle.bcpkix 1.69.0.v20210713-1924) requires 'java.package; org.bouncycastle.asn1.bsi [1.69.0,1.70.0)' but it could not be found
>   Cannot satisfy dependency:
>     From: DBeaver SSHJ 1.0.88.202110151816 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.88.202110151816)
>     To: org.eclipse.equinox.p2.iu; org.bouncycastle.bcpkix [1.69.0.v20210713-1924,1.69.0.v20210713-1924]

On Arch Linux it's also possible to install the plugin from the community repo: https://archlinux.org/packages/community/any/dbeaver-plugin-sshj/. It fails with a different error:

> Missing implementation of resolved method 'abstract void setupTunnel(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, org.jkiss.dbeaver.model.net.DBWHandlerConfiguration, org.jkiss.dbeaver.model.net.ssh.config.SSHHostConfiguration[], org.jkiss.dbeaver.model.net.ssh.config.SSHPortForwardConfiguration)' of abstract class org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.

**Comment by mbelang** [comment]
I installed 21.3.xx manually (without snap) and all of this is fixed

**Comment by yvhr** [comment]
I'm having the same problem on `21.2.4`. Same error, the thing is, my initial issue is #7424.
```
Can't initialize tunnel
   Unable to initialize SSH agent
```
I've read that JSCh doesn't work, recommended *SSHJ*, now I'm stuck. lol

**Comment by JRRSMVF** [comment]
I'm having the issue on DBeaver-ce v 21.3.3.202201221033, up to date Ubuntu 20.04

Can't ssh tunnel into work DB through DBeaver = no DBeaver usage + MySQL Workbench usage - please patch! Thanks.

**Comment by ronjouch** [comment]
@JRRSMVF it works for me now. Please create a new bug with your error & version details

**Comment by Imobach** [comment]
I have the same error on 22.0.0 and 22.0.5:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SSHJ 1.0.93.202112211454 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.93.202112211454)
  Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.69.0.v20210713-1924 (org.bouncycastle.bcpkix 1.69.0.v20210713-1924) requires 'java.package; org.bouncycastle.asn1.bsi [1.69.0,1.70.0)' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.93.202112211454 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.93.202112211454)
    To: org.eclipse.equinox.p2.iu; org.bouncycastle.bcpkix [1.69.0.v20210713-1924,1.69.0.v20210713-1924]
```

**Comment by adrianbienias** [comment]
Same here. I wanted to use SSH tunneling but encountered an error. I found that I had to install SSHJ, but got another error while installing it (`dependency error on org.bouncycastle.bcpkix`) ...

```
Linux Pop!_OS 22.04
Kernel 5.17.5-76051705-generic
```

**Comment by six0h** [comment]
This should be re-opened as the issue is not resolved. I'm experiencing the same on 22.0.4. This is a real show-stopper for anyone that has to access their DB through a bastion host. I can't use DBeaver at this point.

**Comment by adrianbienias** [comment]
I found that SSHJ is already included in the latest DBeaver (no idea in which version they've added it),
so there's no need to install it separately.

In `Connection settings`, in `SSH` tab after checking `Use SSH Tunnel`, expand `Advanced settings` and choose `SSHJ` from `Implementation` selection.

**Comment by Imobach** [comment]
For those who are having errors configuring the bastion host: If a DNS is used instead of the IP of the bastion host, the SSH connection works.

**Comment by six0h** [comment]
I can confirm, SSHJ is indeed included, and is working, I just tested on my laptop where I was having the issue. Thank you.

**Comment by avnav0** [comment]
also not able to create an ssh tunnel trough dbeaver.

```
Cannot add identity key
    invalid privatekey: [B@494c30b7
```

i'm using an openssh key that works everywhere else...

**Comment by femosso** [comment]
Is https://dbeaver.io/update/sshj/latest/ down again?
![image](https://user-images.githubusercontent.com/3494622/183500929-87dee213-b9a6-4698-b41c-55e16dd44184.png)
![image](https://user-images.githubusercontent.com/3494622/183501043-ca46456f-ae0d-40ca-96f8-6a492fb6b6ad.png)

**Comment by E1izabeth** [comment]
@femosso, we don't distribute it as an extension anymore, that's why this link is not working. This dependency is included in DBeaver.

**Comment by femosso** [comment]
Oh, thank you @E1izabeth! I didn't realize that. It's working fine now :)
