### ISSUE TITLE
Boolean checkbox jumps in Metadata Editor/Data transfer dialog

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12471]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5 EA

#### Steps to reproduce, if exist:
Open create new column dialog and click a checkbox

**Expected**: the checkbox is enabled
**Actual result**: the checkbox jumps to the center of the dialog and it is not enabled

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
The issue still remains on Mac. The case will be added to https://github.com/dbeaver/dbeaver/issues/12472

**Comment by DariaMarkaryan** [comment]
Verified for windows
