### ISSUE TITLE
JZ006: Caught IOException: java.io.IOException: JZ0TS: Truncation error trying to send DBeaver 7.0.0 - SQLEditor <Script-2994.sql>. JZ006: Caught IOException: java.io.IOException: JZ0TS: Truncation error trying to send DBeaver 7.0.0 

### ISSUE THREAD

**Issue by adolfoleonardiarval** [dbeaver/dbeaver#12539]
#### System information: 
- Operating system (distribution) and version: Win10 64bit
- DBeaver version: 7.0.0
- Additional extensions

#### Connection specification:
- Database name and version Sybase Ver 16
- Driver name com.sybase.jdbc4.jdbc.SybDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In every sql query there is the error: 
JZ006: Caught IOException: java.io.IOException: JZ0TS: Truncation error trying to send DBeaver 7.0.0 - SQLEditor <Script-2994.sql>.

**Comment by LonwoLonwo** [comment]
Hello @adolfoleonardiarval 
May be issue was fixed in previous releases.
Please test new DBeaver version https://dbeaver.io/ or last stable version https://dbeaver.io/files/21.0.0/

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info

**Comment by so0lid** [comment]
It's been a while, but this issue still exists in version 22.0.5 when using a Sybase connection. Could you please advise? @adolfoleonardiarval, were you able to have it fixed?

**Comment by pjpringlenom** [comment]
You can use JTDS driver instead of jconnect and it looks to work ok
