### ISSUE TITLE
Tables from different schemas are not linked

### ISSUE THREAD

**Issue by healiseu** [dbeaver/dbeaver#12819]
#### System information: 
- Operating system (distribution) and version: Linux Cinnamon, Ubuntu 20.1
- DBeaver version: 21.1.0 vs 21.0.0

#### Connection specification:
- Database name and version: MSSQL AdventureWorks2019
- Driver name: Microsoft JDBC Driver for SQL Server

#### Describe the problem you're observing:
I am creating a new ER diagram and then I drug and drop tables from different schemas in Microsoft Adventure Works 2019 database. In version 21.1.0 tables from different schemas are not shown linked in the diagram, i.e. the dotted or solid line that connects FK with PK  is missing. I did not experience this problem with DBeaver ver. 21.0.0 so I had to uninstall the latest version and install this earlier one. 

Please let us know if that is a bug or if it is some option which is not enabled.

BTW: IMHO DBeaver is one of the best database GUI managers out there and its ERD functionality is pretty good, kudos to all contributors and to Serge Rider for providing an excellent free community edition. Generally speaking I consider visualizing easily and correctly Table relationships on ERD super important for software engineers and developers. Perhaps for that reason that issue deserves some high priority in your busy schedule :-)

**Comment by ShadelessFox** [comment]
Hello @healiseu,

Thanks for the report. I believe this issue was fixed in #12765.

Can you try upgrading to the [EA version](https://dbeaver.io/files/ea/)?

**Comment by healiseu** [comment]
Hi @ShadelessFox,
thank you for your prompt reply, it seems the issue I am reporting here is partially fixed. There are other than #12765 linking cases to cover e.g. PK--PK. To illustrate this, I am embedding two ERD schema images of MSQL Adventure Works 2019 created with:

### DBeaver 21.0.0 
![AdventureWorks2019_dbeaver_21 0 0](https://user-images.githubusercontent.com/14239698/121692123-6ddadb80-cad0-11eb-97f9-e80f2b6554c2.png)

### DBeaver 21.1.0.EA
![AdventureWorks2019_dbeaver_21 1 0 ea](https://user-images.githubusercontent.com/14239698/121692128-6fa49f00-cad0-11eb-83c6-f1105b9cc901.png)

Hope this will help you to solve sufficiently the problem

PS: Attached images have been created by me and I give full rights for anyone to publish and use them for whatever purpose. They demonstrate how powerful and easy it is to build complex ERD schemas with DBeaver.

**Comment by ShadelessFox** [comment]
Looks like our EA version is slightly outdated and does not feature the fix mentioned earlier, sorry.

I will let you know when it's updated.

**Comment by ShadelessFox** [comment]
Can you try again, please? Thanks.

https://dbeaver.io/files/ea/

**Comment by healiseu** [comment]
Hi, I confirm that your fix in the DBeaver EA from the repository of your link in the previous comment works fine. 
It produces exactly the first diagram above. 
Thank you

**Comment by healiseu** [comment]
I confirm that the problem of linking  tables from different schemas is fixed in the new release of
DBeaver Version 21.1.1.202106210824
Release date: June 21, 2021
