### ISSUE TITLE
Firebird execution plan doesn't work

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13096]
#### System information: 
- Windows 10
- DBeaver CE 21.1.2

#### Connection specification:
- Firebird 2.5

#### Describe the problem you're observing:
Trying to get execution plan for query SELECT * FROM "9551", but get no explanations
![image](https://user-images.githubusercontent.com/43252954/124433249-354eba80-dd7b-11eb-9495-d3a3599f7c2b.png)

 Errors are thrown when double click on plan tree items

#### Include any warning/errors/backtraces from the logs
java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(SWT.java:4870)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:438)
	at org.eclipse.swt.widgets.Tree.getColumn(Tree.java:3039)
	at org.jkiss.dbeaver.ui.controls.ViewerColumnController.getColumnData(ViewerColumnController.java:518)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl.getColumnByIndex(ObjectListControl.java:278)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl.getCellValue(ObjectListControl.java:667)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl$EditorActivationStrategy.isEditorActivationEvent(ObjectListControl.java:930)
	at org.eclipse.jface.viewers.ColumnViewerEditor.handleEditorActivationEvent(ColumnViewerEditor.java:427)
	at org.eclipse.jface.viewers.ColumnViewer.triggerEditorActivationEvent(ColumnViewer.java:680)
	at org.eclipse.jface.viewers.ColumnViewer.handleMouseDown(ColumnViewer.java:655)
	at org.eclipse.jface.viewers.ColumnViewer.access$0(ColumnViewer.java:651)
	at org.eclipse.jface.viewers.ColumnViewer$1.mouseDown(ColumnViewer.java:100)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible
![image](https://user-images.githubusercontent.com/31996417/124569857-00139c80-de4f-11eb-997b-98bba6dc42a3.png)

**Comment by uslss** [comment]
verified
