### ISSUE TITLE
Get column name of "Auto-generated SQL script" double quoted

### ISSUE THREAD

**Issue by cydonialis** [dbeaver/dbeaver#13120]
I want to manipulate a table, which is column name case sensitive and for some reasons that I can't disable case sensitive, So When I update a value and click **Save**, I got this:

 [errorCode=GS-00601, SQLState='28000', reason='errLine = 3, errColumn = 8, errMsg=Sql syntax error: invalid column name 'ID',

Then I check the **Auto-generated SQL script** by click **Script**. found that the column name is not double quoted.like this:

`UPDATE TABLE_NAME
	SET name='update'
	WHERE id=0x4CEB5A4DB82A52EE854BED032CB5868E;`

where the **name** and **id** are different column names,
When I particularly double quoted the column name and put it in script editor, like this:

`UPDATE TABLE_NAME
	SET "name"='update'
	WHERE "id"=0x4CEB5A4DB82A52EE854BED032CB5868E;`

Then run the script will get right result.
So I am curious about "is there some options that I can get **Auto-generated SQL script** double quoted?Thus we can straightly manipulate databases without running sqls at some simple situations.

BTW,In my understanding, double quoted means column name is case sensitive, In addition ,**backquote**（`） is equals to **double quote** (") in above example.

**Comment by uslss** [comment]
@hahacyd which database do you use?

**Comment by cydonialis** [comment]
> @hahacyd which database do you use?
Currently we are using [GaussDb](https://dbdb.io/db/gaussdb),A database derived from Postgres .
In addition, I find that when column name is not double quoted,the database server will think the destinated table is not column name sensitive, then the column names in the SQL are converted to uppercase, that's why the error message is:" invalid column name 'ID'",because "id" is transformed to "ID",

**Comment by uslss** [comment]
@hahacyd 
seems Use case-sensetive names in DDL statements option should fix the issue. Could you check if it solves your issue?
![image](https://user-images.githubusercontent.com/31996417/124726988-f6ee0280-df16-11eb-81de-29dcf004a10f.png)

**Comment by cydonialis** [comment]
@uslss 
I choosed this option and the error still occurs, for example, the **Auto-generated SQL script** still is:
![image](https://user-images.githubusercontent.com/23192880/124734373-9f1bbf80-df47-11eb-9f44-ed5b9f994d11.png)
The column names are not double quoted.
I wonder does there have an option which is "Use case-sensitive names in **DML** statements" 🤣 thus the column name will be double quoted.

**Comment by LonwoLonwo** [comment]
Hello @hahacyd 

And what driver do you use?
Also, can you show your table DDL?

**Comment by cydonialis** [comment]
Hello @LonwoLonwo 
We used driver developed and maintained by database team which serves [GaussDb](https://dbdb.io/db/gaussdb), Not common on the market😂

below is tables DDL:
`CREATE TABLE CMDBCORESVRDB.I_DCNCMLAG (  
	id VARBINARY(16) NOT NULL,
	class_Name VARCHAR(384) NOT NULL,
	class_Id BINARY_BIGINT NOT NULL,
	collectorId VARCHAR(36),
	reportSn BINARY_BIGINT,
	last_Modified BINARY_BIGINT NOT NULL,
	tenantId VARCHAR(64),
	regionId VARBINARY(16),
	createTime BINARY_BIGINT,
	name VARCHAR(765) NOT NULL,
	remark VARCHAR(3072),
	nativeId VARCHAR(765),
	ownerId BINARY_BIGINT,
	minimumLinks BINARY_INTEGER,
	idInPublicCloud VARCHAR(384),
	locationName VARCHAR(768),
	bandwidth VARCHAR(768),
	regionName VARCHAR(768),
	deviceName VARCHAR(768),
	tags CLOB,
	accountId VARBINARY(16),
	vlan BINARY_INTEGER,
	jumboFrameCapable BOOLEAN,
	location VARCHAR(768),
	state VARCHAR(192),
	providerName VARCHAR(768),
	CONSTRAINT _PK_SYS_1_449 PRIMARY KEY (id)
);`

**Comment by LonwoLonwo** [comment]
Can you please tell me more about GaussDb? Does it support upper case or mixed case? Why "id" and "name" must be quoted? Are they keywords or reserved words GaussDb? Or they must be quoted because they are in lower case?

**Comment by cydonialis** [comment]
@LonwoLonwo 

1. [This  is official website of Gaussdb.](https://support.huaweicloud.com/intl/en-us/productdesc-gaussdb/introduction.html)
2. why the column name need to be quoted:
    - The table was created with "Column name case sensitive", and "id"、"name" both are lower case and user defined, there may be another lower case column name like "age" 、"salary" etc. When a "non column name quoted" sql was executed,I guess the database server will treat this sql as a column name insensitive,then it will convert column name to upper case(I think the way of database supporting column name insensitive is by converting "non quoted" column name to upper case),
   -  From this type error message:
**[errorCode=GS-00601, SQLState='28000', reason='errLine = 3, errColumn = 8, errMsg=Sql syntax error: invalid column name 'ID',**  
      The 'ID' in error message could be another like 'AGE'、'SALARY', So they are not keywords or reserved words in Gaussdb.
     ps: When a table is crated with "column name case insensitive" or "column name is case sensitive but has upper case column name and a sql use this upper case column name",there is no problem.

**Comment by cydonialis** [comment]
@LonwoLonwo 
In addition, Gaussdb is extended from PostgreSql😀

**Comment by cydonialis** [comment]
@LonwoLonwo Hello,I realized that the database server we used, is just extended from Gaussdb and the sql grammer is much like Oracle, my question is as the below said:
[oracle-db-quote-column-names](https://stackoverflow.com/questions/38328169/oracle-db-quote-column-names)

When the database table is created with case sensitive, then there need to use "double quoted"  to refer it:
 

> It doesn't have to do with objects or tables, it has to do with how these objects/tables have been created.
> If you do create table "blabla" then you always need to address this table with "blabla", if you do create table blabla then you can address this 
> table via BLABLA or blabla or bLabLa. Using "   " makes the name case sensitive and that is the reason why most developers don't use "   " because usually you don't want case sensitive names .

At the end, When a table is case sensitive, how to generate sqls of "double quoted" to execute.

**Comment by LonwoLonwo** [comment]
How works Dbeaver with column and table names? DBeaver gets information about database Identifier Case from the driver first of all. Next, if the column or table name case does not coincide with the database Identifier Case, DBeaver wraps such a name in quotes. 

So I think, that this is driver issue.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCSQLDialect.java#L139 
This is the place, where we reading database case info from the driver.

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.

**Comment by cydonialis** [comment]
Thanks for answer :)  Get it.
