### ISSUE TITLE
Standard Eclipse shortcuts are overwritten by DBeaver extension

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13318]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.3

#### Describe the problem you're observing:
I experienced a minor bug when working with DBeaver inside Eclipse. The
feature (it's actually two of them) works great, and I really like it a
lot, but it seems to disable the Eclipse standard key combination
Alt-Left (Go back in history). 
Every time I start my IDE this particular
key binding is gone, and I have to reassign it to make it work again.

This happens even with the default key configuration (no user key
bindings involved), and it's pretty annoying tbh. Maybe other commands
are affected,too. I didn't notice any, though.

**Comment by optik-aper** [comment]
I don't normally use the Eclipse plugin but the full installation has that binding.  I did install Eclipse and the plugin.  I still see the keybinding.  Perhaps there are some more specifics about what you're doing?  Have you removed the plugin and if so, does the binding remain?

**Comment by sebastianruff** [comment]
I have the same problem. The eclipse default keybinding ist still there, but doesn't work until I open the shortcut preferences on time. Don't need to apply it again, only open it.

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
The issue still persists. The shortcut doesn't work after initial Eclipse start. If keys tab in preferences window is opened they start working.

**Comment by bender270** [comment]
Thanks. 
Congratulations for the good work you do with this great software.

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
