### ISSUE TITLE
[Redshift] Show permissions in DDL generates double quotes in wrong place

### ISSUE THREAD

**Issue by tamarascalva** [dbeaver/dbeaver#13477]
**System information:**

- DBeaver version 21.1.4

**Connection details:**
- Database : Redshift
- Cluster version: 1.0.28330
- Driver name: RedshiftJDBC42-no-awssdk-1.2.45.1069 (managed by DBeaver)

**Describe the problem you're observing:**
Wrong group grants after obtaining the DDL of a redshift table with a particular grant over a redshift group. Steps:

1.  Right Click on a table -> Generate SQL -> DDL
2. Settings -> Show permissions enabled
3. Wrong grant -> _GRANT SELECT ON TABLE <table_name> TO **"**group <group_name>**"**;_

grant should be: _GRANT SELECT ON TABLE <table_name> TO **group "<group_name>"**;_

**Comment by deepaksenthilkumar** [comment]
Thanks for reporting this. We noticed the same. Did you also notice the security definer in procedure ddls are missing (it’s available in properties though), have you already file a bug for that?

**Comment by Matvey16** [comment]
Another wrong DDL is generated `GRANT ALL ON TABLE public.users TO group "\""test group2\""";`

**Comment by deepaksenthilkumar** [comment]
Is that an existing, but different issue?--
SD

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Still not as expected, one quote just moved to the beginning of `group` keyword
```sql
 GRANT ALL ON TABLE public.sales TO "group \""test group2\"""; 
```

**Comment by serge-rider** [comment]
Fixed. Roles names are stored in quoted and escaped form. 

Please test it in PostgreSQL as well.

**Comment by Matvey16** [comment]
Verified
