### ISSUE TITLE
Redshift data import issues

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13542]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.4

#### Connection specification:
- Database name and version: Redshift 1.0.29551 
- Driver name: https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.45.1069/RedshiftJDBC42-no-awssdk-1.2.45.1069.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc) SSH

#### Describe the problem you're observing:
Following 2  scenarios while performing data import
1. Using an upper-case table name "UPPERFILE" and running an import fails, as Redshift stores that as "upperfile" by default. 
2. Using special characters like "-", " ", "(" escapes the column name with double quotes. For example a column name like "company-name" is escaped. And subsequently, the data import fails in all such scenarios

#### Steps to reproduce, if exist:

Use the below sample file and try to import it to a new table "test_status_detail"
[smallest_file_column_complicated.csv](https://github.com/dbeaver/dbeaver/files/6989467/smallest_file_column_complicated.csv)

![image](https://user-images.githubusercontent.com/36084950/129504591-bd41166b-09e4-4aaa-be35-d0fb598480e9.png)

Use the same sample file and try to import it to a new table "TEST_STATUS_DETAIL"
![image](https://user-images.githubusercontent.com/36084950/129504758-b4c928d1-a078-4976-91ce-b89eb2fd1725.png)

**Comment by serge-rider** [comment]
It is not Redshift-specific issue. It is a side effect of #7911 fix.

Fixed

**Comment by deepaksenthilkumar** [comment]
Using an upper-case table name "UPPERFILE" and running an import fails, as Redshift stores that as "upperfile" by default still fails. That's a REDSHIFT issue.

**Comment by Matvey16** [comment]
Verified

**Comment by drfugazi** [comment]
I have the same issue with MySQL to SQLite export/import. On 21.1.4 and 21.1.5, rollback to 21.1.3 works fine as workaround.
