### ISSUE TITLE
SQL editor result tab action buttons disabled after database reconnect/invalidate

### ISSUE THREAD

**Issue by BERRELION** [dbeaver/dbeaver#13817]
After a reconnect/invalidate of a connection (or just a refresh of the database/table), the action buttons (**Save**, **Cancel**, **Script**) of the query result pane are disabled, any modification applied on the result tab cannot be saved or canceled.

_This issue sometimes affects the other action buttons; not only Save, Cancel, Script._

The image below illustrates the buttons being disabled after the modification of a value (done after reconnect/invalidate of the database connection of the current SQL editor) :

![image](https://user-images.githubusercontent.com/87428742/132297477-0d256294-c5ed-44c8-a319-4d6eafcd01c0.png)

A fix for this issue is to reset the value or apply any other value from the context editor (`Edit` > `Set to NULL` / `Set to default` / `Reset changes`). After appling that change on the atered cell(s), the buttons comes back to normal until connection gets reconnected/invalidated again.

**Comment by Matvey16** [comment]
What DBeaver version are you using? It looks like a bug that was fixed in 21.2.0

**Comment by BERRELION** [comment]
Dbeaver v21.2.0 .... still having the issue

Version screenshots below
![image](https://user-images.githubusercontent.com/87428742/132311352-66bd34c6-4c4d-43bb-a4d6-84ca5bcef258.png)
![image](https://user-images.githubusercontent.com/87428742/132311310-1b79b63e-16d6-413e-88be-62b70e13e24d.png)

**Comment by Matvey16** [comment]
@BERRELION It looks like your version is earlier than the latest release version. Can you try this against the latest version from https://dbeaver.io/download/

**Comment by BERRELION** [comment]
@Matvey16 Installed the latest dbeaver release version proposed on official download page.
![image](https://user-images.githubusercontent.com/87428742/132330460-dd2286da-f891-4fb1-962c-870dac0229d6.png)

The bug still presists. In the GIF below I illustrate the issue (along with the temporary fix I use) after invalidating my database connection.

![bug_presisting](https://user-images.githubusercontent.com/87428742/132329340-2537bc0f-b389-401b-8084-ef59db97a235.gif)

_**NB** : I observed that if the result tab is already opened, bug does not occur (edition of values can be Saved, Canceled, etc); but if a new result tab is opened (e.g from a query execution) and database connection has been invalidated, then bug occurs._

**Comment by Matvey16** [comment]
@BERRELION Thank you for the report, I reproduced it. We will work on that.

**Comment by BERRELION** [comment]
Awesome 👍

**Comment by Matvey16** [comment]
@BERRELION  Can't reproduce anymore. Can you check it against 21.2.5?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
