### ISSUE TITLE
Wrong path is opened when clicking browse in embedded database connection

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14843]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.1 EA

#### Steps to reproduce, if exist:
1. Open connection settings for embedded database (e.g. SQLite)
2. Click on **Browse..**

**Expected:** Path to the database location is opened
**Actual:** Last opened path is opened

![Yi9J43CKXd](https://user-images.githubusercontent.com/82543000/145221363-36db0b59-d084-4f4a-9b11-b1395741b772.gif)

**Comment by LonwoLonwo** [comment]
Fixed for generic Databases (like SQLite, FireBird)

**Comment by Matvey16** [comment]
Still doesn't work

![dbeaver_Gp0ZzI9aOJ](https://user-images.githubusercontent.com/82543000/155680011-8ec8d1e1-80d5-4e68-b282-8e46a6550e86.gif)

**Comment by LonwoLonwo** [comment]
Suddenly it turned out to be an Eclipse issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=577190

Hopefully, the bug will be corrected in the new version of Eclipse.

**Comment by Matvey16** [comment]
Fixed in the latest eclipse version
