### ISSUE TITLE
Program crashs on startup!

### ISSUE THREAD

**Issue by Dominiquini** [dbeaver/dbeaver#14877]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64 Version 21H2 (OS Build 19044.1387)
- DBeaver version: 21.3.1
- Additional extensions: ---

#### Connection specification:
- Database name and version: ---
- Driver name: ---
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: ---

#### Describe the problem you're observing:
The program crashs as soon I start it!

#### Steps to reproduce, if exist:
- Just click in the icon on the start menu.

#### Include any warning/errors/backtraces from the logs
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/7699876/dbeaver.log)

** **This start happens in this new version. The previous version works fine!**

Thanks.

**Comment by BenjaminWKI** [comment]
21.3.1 is broken! 
I've reverted to 21.3.0 to get DBeaver working again. 
Logs appear to indicate some configuration incompatibility when it tries to load a past session. 
[log.txt](https://github.com/dbeaver/dbeaver/files/7700074/log.txt)

**Comment by PzaThief** [comment]
> 21.3.1 is broken! I've reverted to 21.3.0 to get DBeaver working again. Logs appear to indicate some configuration incompatibility when it tries to load a past session. [log.txt](https://github.com/dbeaver/dbeaver/files/7700074/log.txt)

Thanks, I was on the same issue and after reverting it, it's working now.
Here is my log file same with yours just excluding language format.
[log.txt](https://github.com/dbeaver/dbeaver/files/7700582/log.txt)

**Comment by ZZIIKKemd** [comment]
Experienced the same issue with DBeaver 21.3.1 and Win10 21H1 (fully updated). Attaching crash log.
[log.log](https://github.com/dbeaver/dbeaver/files/7701275/log.log)

Reverted to 21.3.0 - it still has no crashes and works great)

**Comment by sudeep-hk** [comment]
Experienced the same issue.
@Dbeaver team please see in to this.

**Comment by mpapachristoforou** [comment]
Same issue here on Linux Mint with the following kernel:
Linux 5.13.0-22-generic 22~20.04.1-Ubuntu x86_64 GNU/Linux

Reverted to 21.3.0 to get DBeaver working again.

Log file:  [log.txt](https://github.com/dbeaver/dbeaver/files/7701668/log.txt)

**Comment by reddyshyam** [comment]
Hi @serge-rider, now that you have fixed the issue, do we wait for another release or revert back to 21.3?

**Comment by serge-rider** [comment]
The bug was fixed and version 21.3.1 was re-published (with hotfix).
You can re-download from dbeaver.io or from github.

**Comment by reddyshyam** [comment]
> The bug was fixed and version 21.3.1 was re-published (with hotfix). You can re-download from dbeaver.io or from github.

Ah! Timestamp of 12 hours ago, got me confused. I downloaded and installed without any issues. Christmas feeling set in with this release. 🎄 ⛄ Thanks @serge-rider, Much appreciated! 👏 

Wishing everyone Merry Christmas and a Happy New Year!

**Comment by markozcvetkovichtec** [comment]
I've downloaded and re-installed latest version from dbeaver.io and it still showed same error with URI parsing. Then I went to github and downloaded the .exe from the assets collection for 21.13.1 release, re-installed it and now it works fine. I suggest that you check the link on your main website if it points to the correct .exe file of installation.

**Comment by Matvey16** [comment]
Verified

**Comment by mpapachristoforou** [comment]
Just updated and tested with the latest version and I can confirm that i works OK on Linux Mint with the following kernel:
Linux 5.13.0-22-generic 22~20.04.1-Ubuntu x86_64 GNU/Linux

Best wishes to the entire DBeaver team !! :)

**Comment by kaamid** [comment]
Hi. I am using 22.3.0 version of Dbeaver. My app was working 30 min ago and it won't launch now.  Run it as Admin and getting this message. Is there a way to fix the issue before running to unistall/reinstall part? Thank you
<img width="442" alt="image" src="https://user-images.githubusercontent.com/121185258/223249089-10cdfd77-7913-4172-9792-2712015a9e3b.png">
