### ISSUE TITLE
Error at app start appears for MS Store version

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14882]
#### System information: 
- Operating system (distribution) and version Windows 10 Pro 21H1 19043.1348 **Not reproducible against win10 pro 20H2 19042.1052, 19042.1348**
- DBeaver version 21.3.0

#### Describe the problem you're observing:
Error appears after application start for version that was installed from MS Store

![image](https://user-images.githubusercontent.com/31996417/145777730-82b112f9-dc7d-47dc-9dc0-b87058d47c98.png)
```

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.eclipse.core.jobs
Error
Mon Dec 13 10:30:33 MSK 2021
An internal error occurred during: "AutoRegisterSchemeHandlersJob".
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path (C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_21.3.2.0_x64__1b7tdvn0p0f9y\\plugins/org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar)
    at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1033)
    at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989)
    at com.sun.jna.Native.<clinit>(Native.java:195)
    at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:52)
    at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:48)
    at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:736)
    at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:717)
    at org.eclipse.urischeme.internal.registration.WinRegistry.getValueForKey(WinRegistry.java:44)
    at org.eclipse.urischeme.internal.registration.RegistryWriter.getRegisteredHandlerPath(RegistryWriter.java:80)
    at org.eclipse.urischeme.internal.registration.RegistrationWindows.getSchemesInformation(RegistrationWindows.java:89)
    at org.eclipse.urischeme.AutoRegisterSchemeHandlersJob.run(AutoRegisterSchemeHandlersJob.java:87)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
https://github.com/dbeaver/dbeaver/issues/14927#issuecomment-996576620

**Comment by rahlquistqq** [comment]
I reproduced this 2x on;
Windows 10 21H2 build 19044.1415 
Java 64 bit 8 update 311 (build 1.8.0_311-b11)

Of note, I switched to the MS store version because the 64 bit installer from the Dbeaver site throws an error as well;
"Version 1.8.0_311 of the JVM is not suitable for this product. Version: 11 or greater is required."

<img width="1275" alt="2021-12-29 12_27_46-Settings" src="https://user-images.githubusercontent.com/93665497/147688255-7b88aa08-bf15-4e69-89ec-0cccc4e7dc89.png">

**Comment by ramonmpacheco** [comment]
Same error here with Java 11

![image](https://user-images.githubusercontent.com/43766601/148651902-dfb6c70e-f49e-478d-8cc8-51c92f033cc1.png)
![image](https://user-images.githubusercontent.com/43766601/148651987-26f5734e-d013-4102-b55b-e3d55df78a7c.png)

**Comment by HohesP** [comment]
I can reproduce this error with DBeaver Version 21.3.0.202112091630 (from Microsoft Store) when trying to create a new Oracle database connection. 
See attached log file for details.

Workaround: copy present Oracle database connection und configure the new connection details
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/7844646/dbeaver-debug.log)
.

**Comment by elmarlegrange** [comment]
Using Windows 11 and getting the same issue on application start:
![image](https://user-images.githubusercontent.com/40075458/149285110-c7998384-da40-49c8-ab49-238b7b60f39a.png)

Version: MS Store
![image](https://user-images.githubusercontent.com/40075458/149285242-9b645fab-ec1a-446b-9d94-1d09ccd023ad.png)

**Comment by magespawn** [comment]
![DBeaver  About 2022-01-13_15-15](https://user-images.githubusercontent.com/9950525/149337027-d6233c52-83d3-4185-af8f-ed3614feafd8.png)
![Dbeaver Error 2022-01-13_15-14](https://user-images.githubusercontent.com/9950525/149337050-0dd1d022-870a-4447-89b6-9afbc8bd2965.png)
 Windows 10.

**Comment by serge-rider** [comment]
I think the problem is in dll libraries packaging. In new Eclipse version dlls (like jnidispatch) must be placed in corresponding subfolders.
Packaging has been fixed, we will update Windows Store product along with 21.3.3 release

**Comment by uslss** [comment]
App start after update:
![image](https://user-images.githubusercontent.com/31996417/150749012-1df62b98-8c65-4ed1-9d70-a4e335d330f1.png)
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.core.jobs
Error
Mon Jan 24 11:33:54 MSK 2022
An internal error occurred during: "AutoRegisterSchemeHandlersJob".

java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path (C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_21.3.3.0_x64__1b7tdvn0p0f9y\\plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1033)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:52)
	at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:48)
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:736)
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:717)
	at org.eclipse.urischeme.internal.registration.WinRegistry.getValueForKey(WinRegistry.java:44)
	at org.eclipse.urischeme.internal.registration.RegistryWriter.getRegisteredHandlerPath(RegistryWriter.java:80)
	at org.eclipse.urischeme.internal.registration.RegistrationWindows.getSchemesInformation(RegistrationWindows.java:89)
	at org.eclipse.urischeme.AutoRegisterSchemeHandlersJob.run(AutoRegisterSchemeHandlersJob.java:87)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```


Error while trying to create Oracle connection:
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui
Error
Mon Jan 24 11:39:15 MSK 2022
Unhandled event loop exception

java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:52)
	at com.sun.jna.platform.win32.WinReg$HKEYByReference.<init>(WinReg.java:48)
	at com.sun.jna.platform.win32.Advapi32Util.registryKeyExists(Advapi32Util.java:623)
	at com.sun.jna.platform.win32.Advapi32Util.registryKeyExists(Advapi32Util.java:607)
	at org.jkiss.dbeaver.ext.oracle.oci.OCIUtils.readWinRegistry(OCIUtils.java:198)
	at org.jkiss.dbeaver.ext.oracle.oci.OracleHomeDescriptor.<init>(OracleHomeDescriptor.java:42)
	at org.jkiss.dbeaver.ext.oracle.oci.OCIUtils.addOraHome(OCIUtils.java:125)
	at org.jkiss.dbeaver.ext.oracle.oci.OCIUtils.findOraHomes(OCIUtils.java:146)
	at org.jkiss.dbeaver.ext.oracle.oci.OCIUtils.checkOraHomes(OCIUtils.java:68)
	at org.jkiss.dbeaver.ext.oracle.oci.OCIUtils.getOraHomes(OCIUtils.java:62)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.getDefaultLocalClientLocation(OracleDataSourceProvider.java:166)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDefaultClientLocation(DriverDescriptor.java:1422)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard.getActiveDataSource(ConnectionWizard.java:126)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.getActiveDataSource(ConnectionPageSettings.java:301)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.getDialogPages(ConnectionPageSettings.java:379)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.createProviderPage(ConnectionPageSettings.java:209)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.activatePage(ConnectionPageSettings.java:109)
	at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:56)
	at org.eclipse.jface.wizard.WizardDialog.showStartingPage(WizardDialog.java:1279)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:637)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.open(NewConnectionDialog.java:103)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:121)
	at org.jkiss.dbeaver.ui.actions.datasource.NewConnectionDriverSelectorContributor$NewConnectionAction.run(NewConnectionDriverSelectorContributor.java:73)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:268)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by sharryheb** [comment]
This error is still happening on v21.3.3. Is there an update on when this will be fixed?

**Comment by bcutter** [comment]
Freshly installed as new user using MS Store. First thing to see after initial start: "AutoRegisterSchemeHandlersJob" error.

Looking forward to a fix, thank you.

**Comment by uslss** [comment]
fixed in 21.3.4

**Comment by sarthaksh21** [comment]
same error in new DBeaver version 24.0.1
![image](https://github.com/dbeaver/dbeaver/assets/165733477/690f7156-ccc5-4bff-bc3c-61e6048809cc)

![image](https://github.com/dbeaver/dbeaver/assets/165733477/e54c0fa1-a267-490e-89ad-e99f3114cff1)

**Comment by uoloki** [comment]
Same error, DBeaver CE 24.0.4
[.log](https://github.com/dbeaver/dbeaver/files/15368099/default.log)
