### ISSUE TITLE
"Typed" (enum) field filtering

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#14986]
When I try to filter column of enum type - I cannot enter values by text (only by checking them), cannot filter the list when typing (it becomes empty).
And I cannot make partial filter - e.g. I want to filter: 
field_of_enum_type::text like 'something%'

But I cannot ((((
![dbeaver_typed_column](https://user-images.githubusercontent.com/11477081/147060381-826ca640-b626-4bb2-9a1e-d0ae6e12d831.png)

**Comment by ShadelessFox** [comment]
Hello @plotn,

Would you please rewrite your issue using our bug template?

A minimal reproducible example would be handly.

**Comment by plotn** [comment]
I think there is no need to "reproducable example", because it is a "core" problem, but i'll try

1. Create enum type:
CREATE TYPE enum_type_example AS ENUM (
	'VALUE1',
	'VALUE2');
2. Create table with column of this type;
3. Fill any data;
4. Try to filter.

**Comment by ShadelessFox** [comment]
What database is it?

**Comment by plotn** [comment]
I'm sorry!
It is Postgres

**Comment by ShadelessFox** [comment]
I'm unable to reproduce your issue.

![image](https://user-images.githubusercontent.com/35821147/147090927-720b8d81-6473-43be-a0a3-9b79175eb074.png)

Is there something up to the enum's prefix? Is that schema name (`public`, `mcs`)?

**Comment by LonwoLonwo** [comment]
And what DBeaver version do you use? @plotn

**Comment by plotn** [comment]
21.3.0
your idea could be a glue!
see my metadata - enum is in another scheme:

CREATE TABLE repl.repl_statements (
	id bigserial NOT NULL,
	entity repl_log."t_log_entity" NULL, -- Имя сущность

**Comment by LonwoLonwo** [comment]
Ok. Can you test it in [the newest DBeaver version](https://dbeaver.io/download/), please?
We fixed a related bug in the latest release.
https://github.com/dbeaver/dbeaver/issues/14314

**Comment by plotn** [comment]
I tested. Bug still exists. Could you try your test with the different schemas?

**Comment by plotn** [comment]
I did the test:

```
CREATE TYPE test.test_enum AS ENUM (
	'TEST1',
	'TEST2',
	'TEST3');

CREATE TYPE test2.test_enum AS ENUM (
	'T2EST1',
	'T2EST2',
	'T2EST3');

create table test.test_table_enum (
 f1_enum test.test_enum,
 f2_enum test2.test_enum,
 f3_text text 
)
```

Both filters (f1_enum and f2_enum) behave as the same (both with bugs)

**Comment by uslss** [comment]
Thanks for the report and clarification.
The error appears when trying to enter some text to the filter field

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Jan 11 14:20:47 MSK 2022
ERROR: operator does not exist: test.test_enum ~~* unknown
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 66

org.postgresql.util.PSQLException: ERROR: operator does not exist: test.test_enum ~~* unknown
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 66
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn.getValueEnumeration(JDBCTableColumn.java:238)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.lambda$0(GenericFilterValueEdit.java:344)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.readEnumeration(GenericFilterValueEdit.java:342)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$KeyLoadJob.run(GenericFilterValueEdit.java:633)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```
