### ISSUE TITLE
Dbeaver 21.3.2.202112271055 asks to perform a commit on exit even when no transaction is made (It shouldn't do it, bug), 

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#15102]
**Is your feature request related to a problem? Please describe.**
Dbeaver asks you to perform a commit on exit in the opened sql editor even when you didn't execute any script or insert or update statements. It should not ask for it if no transaction is made, or if just sql select statemetns were executed.

**Comment by Matvey16** [comment]
@yevon Sorry, your title and post sound kind of contradicting. Did I understand correctly that you don't want to confirm commit on exit if you had only selects in transaction? We have smart commit mode that will open transactions only for DM queries and will autocommit any select query. There are some situation where you want to execute select in transaction so commiting it automatically without user confirmation can end badly.

**Comment by yevon** [comment]
No no, what I mean is that latest dbeaver version asks you to commit pending transactions even when you have not executed any. If you open a new connection, execute a select * from dual, and you close it, it asks you to commit pending transactions. A select is not a transaction that makes any change to the db, so it should not ask you to commit anything.

**Comment by Matvey16** [comment]
@yevon Thank you for clarification. I will change this ticket to a bug, because it is indeed a bug.

The expected behavior is to not ask for confirmation if transaction had only select queries and it works until any other query is executed in a transaction, after that the confirmation will always pop up regardless of query type in a transaction

STR:
1. Enable manual transactions
2. Execute any data modifying query and either commit or rollback a transaction
3. Execute any select query in the same editor and try to close it

**Expected:** The editor closes without confirmation
**Actual:** A window with transaction commit confirmation pops up.

![dbeaver_WQupT9mBgo](https://user-images.githubusercontent.com/82543000/149510869-fb2d8b61-4783-443e-9b51-d9d0d87404d4.gif)

**Comment by ShadelessFox** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified

**Comment by gjohnson-apll** [comment]
I'm on Version 25.0.2.202504061727 and this still appears to be an issue? If I open a new query, SELECT * FROM DUAL and close, I'm asked to commit my transactions.
