### ISSUE TITLE
GIS visualization crashes on snap store CE version 22.0.2

### ISSUE THREAD

**Issue by bagabool** [dbeaver/dbeaver#16076]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version: 22.0.2, CE, snap-store
- Additional extensions: I'm on emacs and EXWM

#### Connection specification:
- Driver name: Postgresql + PostGIS
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The app instantly crashes when clicking on a geo value in a table in ordre to visualize it

#### Steps to reproduce, if exist:
Load geo datas on a postgis database and click on one of them

#### Include any warning/errors/backtraces from the logs
```
# Problematic frame:
# C  [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
```

**Comment by serge-rider** [comment]
Thanks you for the bug report.

It is a known issue with embedded browsers in snap packages.

**Comment by Matvey16** [comment]
@GabagoolOverHere It should have been fixed in the latest snap package. Is this still actual for you in 22.0.5?

**Comment by bagabool** [comment]
i redownloaded the snap version and gave it a try, still crashes

**Comment by Matvey16** [comment]
@GabagoolOverHere Did you install version 22.0.5? There are 3 options in snap store right now and only one of them is unconfined.

**Comment by bagabool** [comment]
i installed it with `sudo snap install dbeaver-ce` which i believe, install the correct version https://snapcraft.io/dbeaver-ce

**Comment by Destrolaric** [comment]
@GabagoolOverHere  Hi, can you try to install DBeaver with `sudo snap install dbeaver-ce --classic`? It should fix the issue with GIS.
P.S. Sorry, I thought classic confinement was already available, it's not available for that package for now.

**Comment by bagabool** [comment]
got this warning during the installation.

`Warning: flag --classic ignored for strictly confined snap dbeaver-ce`

this installed me the community version, so it still crashes when I try to visualize spatial datas (multipolygon)

**Comment by Destrolaric** [comment]
@GabagoolOverHere, Sorry for waiting, I downloaded the latest DBeaver snap and it looks like it was fixed. Could you look if it's still reproducible?

**Comment by Matvey16** [comment]
The client doesn't crash completely, but can't show anything from the browser (both the map for geometry data and any web page), only this error will be show instead

`GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox`

**Comment by Brakistad** [comment]
Same issue here. Seems like the snap is not allowed to access DBus by apparmor.
ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
dbeaver snap:
```
Name               Version                     Rev    Tracking       Publisher     Notes
dbeaver-ce         22.2.3.202210231354         212    latest/stable  dbeaver-corp  -
```
running dbeaver-ce command. 
Which provides debug log.

This happens at startup:
`Gtk-Message: 10:34:17.165: Failed to load module "canberra-gtk-module"`

Then i query a table containing Geography(Point, srid=4326)

Select point and expect to view a OpenStreetMap map. I have selected the correct projection EPSG: 4326.

The log shows these messages:
```log
(process:15554): GLib-GIO-WARNING **: 10:35:28.113: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
Gtk-Message: 10:35:28.317: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:35:28.322: Failed to load module "canberra-gtk-module"

** (WebKitWebProcess:15569): WARNING **: 10:35:30.534: Failed to get atspi registered event listeners: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.37" (uid=1000 pid=15569 comm="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWeb" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.a11y.atspi.Registry" member="GetRegisteredEvents" error name="(unset)" requested_reply="0" destination=":1.1" (uid=1000 pid=1536 comm="/usr/libexec/at-spi2-registryd --use-gnome-session" label="unconfined")


** (WebKitWebProcess:15569): WARNING **: 10:35:30.542: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:15569): WARNING **: 10:35:30.542: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
```

**Comment by arhayka** [comment]
Hi @bagabool and @Brakistad!
The dbeaver-ce Snap package now uses classic confinement.
Please try installing the latest DBeaver version using:
`sudo snap install dbeaver-ce --classic`

All issues reported in this ticket should now be resolved.

**Comment by arhayka** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
