### ISSUE TITLE
Kerberos share ticket cache on macOS

### ISSUE THREAD

**Issue by riccardocesarini** [dbeaver/dbeaver#16865]
#### System information: 
- macOS Monterey 12.4 on M1 Pro Processor
- DBeaver version 22.1.0

#### Connection specification:
- Impala
- Impala 2.6.27.1032 ImpalaJDBC41.jar
- jdbc:impala://hostname:21050;AuthMech=1;KrbRealm=MYREALM;KrbHostFQDN=_HOST;KrbServiceName=impala
#### Describe the problem you're observing:

In a MacOS M1 Pro machine when try to connect to a kerberized Cloudera Cluster with Impala Driver I receive the following error:

[Cloudera][ImpalaJDBCDriver](500168) Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .
  Unable to obtain Principal Name for authentication 
  Unable to obtain Principal Name for authentication 

The kerberos ticket are correctly requested and is presente on cache as visible with the command klist.

MacBook-Pro-*******:~ ********$ klist
Credentials cache: API:*******-****-****-****-************
        Principal: *******@ MYREALM

  Issued                Expires               Principal
Jun 23 10:32:16 2022  Jun 23 12:32:16 2022  krbtgt/MYREALM@MYREALM

On the same machine if I try to connect with the same driver and the same url connection with the software RazorSQL based on java, I connect correctly.

A specular configuration on a Mac with intel processor work correctly.

I think that for some reason dbeaver do not share api cache of kerberos implementation of macOS on ARM Processor.

**Comment by dabrign** [comment]
Same setup, same problem...

Any update?

**Comment by LonwoLonwo** [comment]
I'm sorry for not getting back to you sooner.
For now, we can't reproduce this issue.
Can you please check the latest DBeaver version? Maybe, the JAVA update helps.

**Comment by Alwin4Zhang** [comment]
> I'm sorry for not getting back to you sooner. For now, we can't reproduce this issue. Can you please check the latest DBeaver version? Maybe, the JAVA update helps.

I also get this error,macos m1pro 13.2.1；dbeaver 22.3.5

**Comment by dabrign** [comment]
I tried different JVM versions (8, 11, 17) and a couple of dbeaver version (including the last one). 
Still cannot solve the problem

**Comment by riccardocesarini** [comment]
Confirm, I have updated to the latest version of dbeaver and the problem is not resolved. Using another software using a connection with the same parameters works correctly.

**Comment by dabrign** [comment]
> Confirm, I have updated to the latest version of dbeaver and the problem is not resolved. Using another software using a connection with the same parameters works correctly.

Can you share the software you used, pls?

**Comment by LonwoLonwo** [comment]
Maybe this answer will be helpful https://stackoverflow.com/a/42506620 ?

**Comment by Alwin4Zhang** [comment]
> https://stackoverflow.com/a/42506620

I know that he use RazorSQL,but I don't know how to config it.

**Comment by Alwin4Zhang** [comment]
> > Confirm, I have updated to the latest version of dbeaver and the problem is not resolved. Using another software using a connection with the same parameters works correctly.
> 
> Can you share the software you used, pls?

I know that he use RazorSQL,but I don't know how to config it.

**Comment by LonwoLonwo** [comment]
Hello @riccardocesarini 

Does this issue still actual for you on the last DBeaver release?

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by shatteringlass** [comment]
I have the same issue on DBeaver CE 25.1.5.202508171444 on macOS 26.1

**Comment by dabrign** [comment]
> I have the same issue on DBeaver CE 25.1.5.202508171444 on macOS 26.1

Finally I solved with the latest version of DBeaver. However it wasn't enough, since I was using conda for managing the python environments and I found out that when you use kerberos you should deactivate the `base` conda environment otherwise your commands points to a version of kerberos not used by DBeaver. 

I hope it helps you as well

**Comment by shatteringlass** [comment]
Thanks for the info, unfortunately the issue persists with DBeaver 25.2.4 (latest release) and I don't see how python is relevant in the context of this problem.

**Comment by dabrign** [comment]
>  I don't see how python is relevant in the context of this problem.

You’re right, Python itself isn’t directly related to the issue.
However, in my case, Conda was interfering because it ships its own krb5 libraries. When the base environment is active (usually on each new terminal session), Kerberos commands use Conda’s version instead of the system one, and DBeaver couldn’t recognize the cached ticket.

After deactivating the Conda environment (so the system’s Kerberos is used), DBeaver worked correctly.
Hopefully, this helps others who might run into the same situation.
