### ISSUE TITLE
Scheduled tasks not running as expected

### ISSUE THREAD

**Issue by dzar-aker** [dbeaver/dbeaver#17353]
### Description

I have a couple of scheduled tasks that I have set to run each morning at 7 AM. I think this did work once or twice, but it's no longer creating any output, although the "Last Run" is updated each morning to indicate it did run. When I run them manually, they do produce the output I expect in the location I expect.

Any ideas on how I can debug this or make it work? 

My machine is not sleeping at this time. I did check that! I do see the Windows Task Scheduler task is created, and, again, it does something as the dates are updated, although no output is produced.

UPDATE: I do see that when these run, there is an error: 

![image](https://user-images.githubusercontent.com/52180004/184894497-160aac39-a9a2-4934-a3c1-3496e29aab72.png)

There is no data source. But, of course, there is, as I can run it manually, and when I edit the task, I see that my query is "attached" to a specific database.

### DBeaver Version

Version 22.1.0.202206131757

### Operating System

Microsoft Windows 11

### Database and driver

1. Database: PostgreSQL 12
2. Database Driver: PostgreSQL JDBC Driver

### Steps to reproduce

1. Create a task to produce a CSV from a query
2. Schedule an hourly task to run in the future
3. Wait for time to pass

I see the "Last Run" and "Next Run" updated, but no output was produced.

4. Manually running the same task will work to produce the output as expected

**Comment by flambchap** [comment]
Hi @dzar-aker. Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by dzar-aker** [comment]
Well... my email response seems to have not added my log files to this! Not sure what happened. 

Here is the .log file. 
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/9580228/dbeaver.log)

The dbeaver-debug.log file is empty (0 length). Anything else you may want?

Also, I looked into the CLI a bit and I get the same problem if I manually try to run the script from the CLI, myself, in PowerShell (I'm on Windows).

PS C:\Users\dzar> & 'C:\Program Files\DBeaverEE\dbeaver-cli.exe' -runTask "@General:USCDC WO Status"
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 22.1.0.202206131757]
> Start DBeaver LM Core [com.dbeaver.lm.core 2.0.112.202206131757]
> Start DBeaver Advanced Application [com.dbeaver.app.advanced 22.1.0.202206131757]
> Start DBeaver Enterprise Application [com.dbeaver.app.enterprise 22.1.0.202206131757]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.300.v20220114-0859]
> Start DBeaver License Manager [org.jkiss.lm 1.0.136.202206131757]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.18.500.v20220215-1304]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 22.1.0.202206131757]
2022-08-25 08:14:36.733 - Initializing DBeaver Enterprise 22.1.0
2022-08-25 08:14:36.734 - Host plugin: com.dbeaver.app.enterprise 22.1.0.202206131757
2022-08-25 08:14:36.734 - Initialize Core...
2022-08-25 08:14:36.882 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.9.300.v20220121-1426]
> Start Core Resource Management [org.eclipse.core.resources 3.16.100.v20220214-1012]
> Start Team Support Core [org.eclipse.team.core 3.9.300.v20220204-0611]
> Start DBeaver EE Runtime [com.dbeaver.ee.runtime 2.0.112.202206131757]
2022-08-25 08:14:37.172 - Initialize base platform...
2022-08-25 08:14:37.183 - Core initialized (449ms)
> Start DBeaver advanced networking [com.dbeaver.remote.client 1.0.2.202206131757]
2022-08-25 08:14:37.197 -       Initialize license manager for dbeaver-ee
2022-08-25 08:14:37.988 - [TASK] Execute task USCDC WO Status
> Start DBeaver Data Transfer [org.jkiss.dbeaver.data.transfer 2.0.67.202206131757]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.73.202206131757]
> Start DBeaver PostgreSQL Support [org.jkiss.dbeaver.ext.postgresql 2.1.156.202206131757]
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.107.202206131757]
2022-08-25 08:14:38.593 - [TASK] Task finished USCDC WO Status
2022-08-25 08:14:38.625 - Shutdown Core...
2022-08-25 08:14:38.687 - Shutdown completed in 62ms

It produces no output and I get the "No input database error" same as when it's run from the scheduler.

Thanks for looking into this. I'm fairly sure it worked in the past, but it has not worked for several weeks for me, now.

**Comment by flambchap** [comment]
@dzar-aker, I'm sorry for the late response. Please create a ticket on our support system on our website, and we'll gladly help.

**Comment by dzar-aker** [comment]
I cannot create a ticket as I am an education customer. I was told to use this site to report the issue.

**Comment by miguelpaz93** [comment]
@dzar-aker hi!, i got the same problem. Did you achieve to solve the problem? I hope you will.

**Comment by miguelpaz93** [comment]
@n5a5 Hi!, This problem was solved?

**Comment by dzar-aker** [comment]
> @dzar-aker hi!, i got the same problem. Did you achieve to solve the problem? I hope you will.

The last time I checked, it was not resolved, but I have not needed this in many months. I may need it again soon, and I will update you if I find it is now working.

**Comment by HarryPaul93** [comment]
Hi,
I have this problem as well.
I am able to run a job manually, but when I leave it to the scheduler it fails with this error.
![image](https://user-images.githubusercontent.com/65289778/234878828-9db2868f-8c3f-4ab3-98b9-f936e0978fa8.png)
Currently have to manually run this job every day.

This is the log for a failed scheduled run:

2023-04-24 09:30:04.971 - Total database drivers: 121 (121)
2023-04-24 09:30:04.996 - Connect with 'Simba Presto' (odbc-187931c6665-2c738f777298a88d)
2023-04-24 09:30:04.997 - Connect to jdbc:dbodbc:Simba Presto
2023-04-24 09:30:04.998 - 	Connect to data source
2023-04-24 09:30:05.082 - Execution context opened (Simba Presto; Main; 0)
2023-04-24 09:30:05.086 - Connection failed (odbc-187931c6665-2c738f777298a88d)
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.putAll(Unknown Source)
	at java.base/java.util.Properties.putAll(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getAllConnectionProperties(JDBCDataSource.java:289)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:137)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at com.dbeaver.db.odbc.model.OdbcDataSource.<init>(OdbcDataSource.java:45)
	at com.dbeaver.db.odbc.model.OdbcMetaModel.createDataSourceImpl(OdbcMetaModel.java:32)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer$ObjectSerializer.lambda$0(DatabaseTransferProducer.java:391)
	at org.jkiss.dbeaver.model.runtime.MonitorRunnableContext.run(MonitorRunnableContext.java:33)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer$ObjectSerializer.deserializeObject(DatabaseTransferProducer.java:366)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer$ObjectSerializer.deserializeObject(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.deserializeObject(JSONUtils.java:295)
	at org.jkiss.dbeaver.tools.transfer.DataTransferSettings.getNodesFromLocation(DataTransferSettings.java:672)
	at org.jkiss.dbeaver.tools.transfer.DataTransferSettings.<init>(DataTransferSettings.java:125)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$0(DTTaskHandlerTransfer.java:69)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:135)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeTask(DTTaskHandlerTransfer.java:62)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:130)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-04-24 09:30:05.090 - org.jkiss.dbeaver.model.exec.DBCException: Error instantiating data producer
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer$ObjectSerializer.deserializeObject(DatabaseTransferProducer.java:416)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer$ObjectSerializer.deserializeObject(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.deserializeObject(JSONUtils.java:295)
	at org.jkiss.dbeaver.tools.transfer.DataTransferSettings.getNodesFromLocation(DataTransferSettings.java:672)
	at org.jkiss.dbeaver.tools.transfer.DataTransferSettings.<init>(DataTransferSettings.java:125)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$0(DTTaskHandlerTransfer.java:69)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:135)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeTask(DTTaskHandlerTransfer.java:62)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:130)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Internal error connecting to Simba Presto
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1111)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer$ObjectSerializer.lambda$0(DatabaseTransferProducer.java:391)
	at org.jkiss.dbeaver.model.runtime.MonitorRunnableContext.run(MonitorRunnableContext.java:33)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer$ObjectSerializer.deserializeObject(DatabaseTransferProducer.java:366)
	... 11 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.putAll(Unknown Source)
	at java.base/java.util.Properties.putAll(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getAllConnectionProperties(JDBCDataSource.java:289)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:137)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at com.dbeaver.db.odbc.model.OdbcDataSource.<init>(OdbcDataSource.java:45)
	at com.dbeaver.db.odbc.model.OdbcMetaModel.createDataSourceImpl(OdbcMetaModel.java:32)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	... 14 more
2023-04-24 09:30:05.117 - Initialize pipes
2023-04-24 09:30:05.118 - Perform data transfer
2023-04-24 09:30:05.124 - Transfer data from "?" into "test_extract_202304240930.txt"
2023-04-24 09:30:05.130 - Error transfering data from ? to test_extract_202304240930.txt
org.jkiss.dbeaver.DBException: No input database object found
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:135)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.runDataTransferJobs(DTTaskHandlerTransfer.java:154)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeWithSettings(DTTaskHandlerTransfer.java:89)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeTask(DTTaskHandlerTransfer.java:77)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:130)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-04-24 09:30:05.150 - Post transfer work


All the best,

**Comment by arhayka** [comment]
It seems that different issues could cause all these cases.

@dzar-aker @miguelpaz93 
Could you please send the log files? 
You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Hi @HarryPaul93

We are working on the ODBC connection problems right now. So I will message you when we end it.

**Comment by arhayka** [comment]
Hi @HarryPaul93,

We have released [new ODBC driver](https://github.com/dbeaver/dbeaver/wiki/ODBC-JDBC-Driver). Please check if your issue is reproduced with it.

The new ODBC driver is available in DBeaver Enterprise Edition. You can get a free 14-day trial period [here](
https://dbeaver.com/trial/).

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
