### ISSUE TITLE
Statistics tab always becomes active when running a SQL script

### ISSUE THREAD

**Issue by jyinpci** [dbeaver/dbeaver#17763]
### Description

This is related to a previously closed ticket  https://github.com/dbeaver/dbeaver/issues/7704.

The issue had resurfaced in the past 3 releases, still happening in the current 22.2.1 release.  Whenever one executes a script having a variable (or more than SQL statements), the Statistics tab will be displayed first.  One has to click on the Result tab to actually see the result.  And to make it worse, if one has to scroll down in the data editor and fetch more rows, it would jump back to the Statistics tab every time more rows are retrieved, very annoying.  Would appreciate it greatly if this can be fixed soon.  Thanks!

### DBeaver Version

Community edition 22.2.1 (and previous 2 releases)

### Operating System

Windows 10 Pro.

### Database and driver

Oracle ojdbc8 and orai18n.

### Steps to reproduce

@set myvar='foo'
select * from my_table
where name= :myvar
order by id;

**Comment by bickgr** [comment]
Adding to follow this issue, also still happening for me.

**DBeaver Version**
CE Version 22.2.1.202209251341

**OS**
macOS 12.6

Seeing the status tab shown as default when running a script with variables or multiple selects.  Also when multiple results windows are open, when refreshing one view jumps back to the stats tab.

**Comment by LonwoLonwo** [comment]
Hello.

Can you provide some video of the issue?

**Comment by bickgr** [comment]
Sure thing, here's a video in action

https://user-images.githubusercontent.com/46910221/192897153-0c93b05c-e224-4df3-9c2b-be17c2d0c08f.mp4

I would expect that after running the script the default view would be the last query run, the tab labeled Demographics.  After clicking to the Demographics tab and clicking the refresh I would expect the view to remain on the Demographics tab.

**Comment by ShadelessFox** [comment]
Thanks for the bug report

**Comment by William-Robert-Robertson** [comment]
Hi,

I've just noticed this problem as well - at first I thought I must have made a mistake while I was tired but I realized that it seemed to have started just after upgrading.

When I run a select query or hit the Save button to send changes to the results back to the database the query runs then the Statistics tab immediately gets focus so that I have to click on the Results tab each time to get back to the results exactly as shown in the video above except that my SQL only has a single Select statement and a few comments.

Help -> About
Version 22.2.1.202209251341

Here's the database back end (MySQL):
SHOW VARIABLES LIKE 'version';
version	8.0.30

Here's the OS version for DBeaver:
C:\>systeminfo

Host Name:                 DESKTOP-R6CPGL1
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00325-95817-75573-AAOEM
Original Install Date:     14-Aug-22, 7:52:38 PM
System Boot Time:          24-Sep-22, 11:55:14 AM
System Manufacturer:       HP
System Model:              HP Laptop 15-bs1xx
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~2001 Mhz
BIOS Version:              Insyde F.32, 23-Nov-17
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              de-ch;German (Switzerland)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     16,301 MB
Available Physical Memory: 1,928 MB
Virtual Memory: Max Size:  33,840 MB
Virtual Memory: Available: 4,995 MB
Virtual Memory: In Use:    28,845 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-R6CPGL1
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5017024
                           [02]: KB5007575
                           [03]: KB5012170
                           [04]: KB5017328
                           [05]: KB5018291
Network Card(s):           6 NIC(s) Installed.
                           [01]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.56.1
                                 [02]: fe80::f5e6:6d2:dffa:8492
                           [02]: ExpressVPN TAP Adapter
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [03]: TAP-NordVPN Windows Adapter V9
                                 Connection Name: Ethernet 4
                                 Status:          Media disconnected
                           [04]: Intel(R) Dual Band Wireless-AC 7265
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.114
                                 [02]: fe80::a08e:2234:f178:833d
                                 [03]: 2a02:1210:8603:6b00:44f0:b1d1:d54f:7d2d
                                 [04]: 2a02:1210:8603:6b00:a08e:2234:f178:833d
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [06]: Nlwt Tun
                                 Connection Name: NordLynx
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by Obeydullah** [comment]
> Sure thing, here's a video in action
> 
>  2022-09-28_15-03-33.mp4 
> I would expect that after running the script the default view would be the last query run, the tab labeled Demographics. After clicking to the Demographics tab and clicking the refresh I would expect the view to remain on the Demographics tab.

Exactly same issue for me too,

**Comment by ValmeI** [comment]
Also experiencing same issue on Version 22.2.1.202209251341

**Comment by ghost** [comment]
Same issue here, but additionally it seems to be a coin toss whether the Statistics or Result panel is shown, sometimes I get the Result panel, and sometimes the Statistics.  
After executing the script in the editor 20 times subsequently (<kbd>F9</kbd> in my shortcuts) I got the Results panel 9 times and the Statistics panel 11 times.

- Version 22.2.1.202209251341
- MySQL version (found with `SHOW VARIABLES LIKE 'version'`): 5.7.39-log
- Windows 10, 21H2, build 19044.2130

**Comment by qupear** [comment]
Upvoting this issue. But for me it happens only with 22.2.5 version. BTW is it possible to disable a tab with statistics through dbeaver settings until fix?

**Comment by LonwoLonwo** [comment]
The consequences of this ticket https://github.com/dbeaver/dbeaver/issues/16605

**Comment by LonwoLonwo** [comment]
Fixed.
Fix will be available [here](https://dbeaver.io/) on 2022-12-26 in DBeaver 22.3.1

**Comment by briandhuff** [comment]
Still happening to me on scripts that do not have a results tab to display.
BUT only on the second + time the script is run.
First time works as expected

Version 22.3.1.202212251901

Steps to recreate:

Open New Script
Add:
PRINT 'statistics tab will show'

Run script the first time, Statistics and Output window show with Output as the tab in focus

Run script again, Statistics will now be the tab in focus and will continue to be on all other script execution

**Comment by paleocomburo** [comment]
I just updated to 22.3.1 today, which according to a comment above should fix the issue, however, where I did not have this issue before, now I do have this issue.

edit to add a little more info:
I have a big SQL script file with multiple queries that I need to run often. I select the query I want to run and click the "execute script" button the side. Then both the result and statistics panels show up, with the statistics panel being the one in the front.

**Comment by E1izabeth** [comment]
@paleocomburo does it still reproducible on the DBeaver 23.0.0? If yes, please, provide concrete steps, as I can't reproduce it anymore

**Comment by LonwoLonwo** [comment]
Hello @briandhuff @paleocomburo 

Please provide examples of inconsistent behavior.

For now, after executing the script, DBeaver focused, in my case, on the statistics tab only if I do not have the SELECT statement in the end. But It has the correct focus if my last statement in the script is the SELECT statement.

![2023-03-15 14_39_19-DBeaver Ultimate 23 0 0 - _postgres_ Script-94](https://user-images.githubusercontent.com/45152336/225300355-b3fda167-639b-4e06-a545-badbc84d9746.png)

![2023-03-15 14_45_30-DBeaver Ultimate 23 0 0 - _postgres_ Script-94](https://user-images.githubusercontent.com/45152336/225300359-2bb29ddf-1dba-4334-9473-bfc89f81a59d.png)

And I do not think that this is incorrect behavior.

**Comment by briandhuff** [comment]
@LonwoLonwo 

I'll just point back to my original STR above:

Steps to recreate:

> Open New Script
> Add:
> PRINT 'statistics tab will show'
> 
> Run script the first time, Statistics and Output window show with Output as the tab in focus
> 
> Run script again, Statistics will now be the tab in focus and will continue to be on all other script execution

This behavior still exists in 23.0.0.202303040621 released March 6, 2023

The video I provided above also shows the same.

**Comment by LonwoLonwo** [comment]
> The video I provided above also shows the same.

Unfortunately, I do not see any video from you. Could you please point to it?

**Comment by briandhuff** [comment]
@LonwoLonwo very sorry about that, here you go.


https://user-images.githubusercontent.com/4779934/226389720-efdc95e5-9e97-4651-b527-0a9a06045bda.mp4

**Comment by paleocomburo** [comment]
> is issue.
> 
> edit to add a little more info: I have a big SQL script file with multiple queries that I need to run often. I select the query I want to run and click the "execute script" button the side. Then both the result and statistics panels show up, with the statistics panel being the one in the front.

The bevaviour I saw for my use-case is fixed. I get the results window focussed every time I run a statement.

**Comment by LonwoLonwo** [comment]
Now I can see in this ticket many different cases, not always connected with the main topic.

Please, @briandhuff , create a new ticket for your issue.

**Comment by LonwoLonwo** [comment]
And I'm closing this, because main issue is fixed.
