### ISSUE TITLE
White Scroll Bars with Dark Mode

### ISSUE THREAD

**Issue by hozdenoren** [dbeaver/dbeaver#17787]
**Is your feature request related to a problem? Please describe.**

Scroll bars do not adapt to the dark theme as shown in the screenshot. Is there a way to change this behavior? 

**Describe the solution you'd like**

Scroll bars to look like VS Code or WhatsApp (or many other apps) where they adapt to the theme.

**Describe alternatives you've considered**

I have tried both the Microsoft Store version (22.2.0) and the installer version (22.2.1). 

OS information:

Edition	Windows 11 Pro
Version	22H2
Installed on	‎28/‎09/‎2022
OS build	22621.521
Experience	Windows Feature Experience Pack 1000.22634.1000.0

**Additional context**

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/56940207/193274220-ecc20b99-21b1-4908-aba3-c45dcce00bd7.png">

**Comment by hozdenoren** [comment]
It could be related to not being able to get the system theme correctly. Windows is set to dark mode; however, if I set the theme to "System" on DBeaver, it gets the light theme. If I enable Contrast themes on windows, on the other hand, it changes the scrollbar colors accordingly.

**Comment by LonwoLonwo** [comment]
Hello @hozdenoren 

Thanks for the report.

**Comment by hassaanmasood** [comment]
This issue starts happening after Windows 11 22H2. The menus are also white now in dark mode. Previously both scrollbars and menus were dark with dark theme. 

As I understand, Microsoft has made some changes to their dwmapi for 22H2. This could be a reason why dark mode is not working right for dbeaver.

**Comment by E1izabeth** [comment]
@hassaanmasood thank you for investigation

**Comment by E1izabeth** [comment]
Connected to #17508

**Comment by hozdenoren** [comment]
Hey, even though this is marked for the 22.3.5 update, the scroll bars now reflect the dark mode for me on 22.3.3. 

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/56940207/214332188-5e0d7bb5-0685-4254-9a34-77f3fd75454d.png">

**Comment by E1izabeth** [comment]
Thank you for feedback. It's a good news.

**Comment by E1izabeth** [comment]
@hassaanmasood could you check if this issue is still reproducible for you?

**Comment by hassaanmasood** [comment]
@E1izabeth this issue seems to have resolved with version 22.3.2.202301060755

**Comment by E1izabeth** [comment]
Thank you for checking. Then I'm closing this issue. Please, let me know if you meet this bug again.

**Comment by rubendejong** [comment]
Still happening in 24.2.4 in a clean install of Windows 11 24H2:
![image](https://github.com/user-attachments/assets/9ca416cc-c04b-4e63-a69a-4d9eece28abb)

**Comment by kartas39** [comment]
Menus are light as well 
![image](https://github.com/user-attachments/assets/d8c3955c-b582-4427-8f7e-cd7b6af26fc9)

**Comment by rubendejong** [comment]
Just tagging @E1izabeth

**Comment by srbanesq** [comment]
Hi, @E1izabeth! I am still experiencing this issue on Windows ARM64, DBeaver Version 25.3.0.202511301802, using black default theme, the darkest theme, etc. The menus are also white. Switching from Black to Contrast Theme in Windows does change the colour, but it is not a viable solution for me. Any resolution or workaround, please? Thanks!

**Comment by srbanesq** [comment]
Hey, I've just updated to 25.3.3 and the issue persists. Any clue if this is just on my side, or if it can be sorted via update? @serge-rider, I'd much appreciate a response.

**Comment by serge-rider** [comment]
I've seen such an issue on Windows Server machines.
So far no ideas, we need to investigate it.
I'll move it to the next release spring.

**Comment by serge-rider** [comment]
It is marked as resolved on Eclipse repo (https://github.com/eclipse-platform/eclipse.platform.swt/issues/1546).
But in fact we still can reproduce it.
Proposed workaround (with disabling/enabling high contrast theme didn't help me).
Keep investigating..
