### ISSUE TITLE
Failed to fetch table data (Out of memory)

### ISSUE THREAD

**Issue by bernardiego** [dbeaver/dbeaver#17865]
### Description

Immediately after updating to 22.2.2, I couldn't access certain tables (On which I suppose, the data to show -first 200 rows- were to big), and other tables took _minutes_ to show.

- No internet problems were present.
- RAM availability wasn't a problem, neither from system nor database.

I downgraded to 22.2.1 and problems went away.

[.log](https://github.com/dbeaver/dbeaver/files/9747926/dot_log.txt) file attached

### DBeaver Version

Community Edition 22.2.2

### Operating System

Windows 10

### Database and driver

PosgreSQL 11.5

### Steps to reproduce

1. Start application.
2. Double-click on a PosgreSQL table.
3. Data fetching takes a lot of time to appear (if ever)

**Comment by BobbySchnipke** [comment]
I'm having the same issue immediately after updating to 22.2.2 though the error I'm seeing is: SQL Error: Internal jdbc driver error

The details do mention a memory issue though:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:294)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:331)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 7 more
Caused by: java.lang.OutOfMemoryError: Java heap space


This isn't necessarily a performance issue as it makes some tables not load at all, not just slow.

**Comment by LonwoLonwo** [comment]
Hello. Thanks for the bug report.

We are looking into it.

A workaround for now is to enable this setting in the connection settings:

![2022-10-11 03_04_34-Connection _dvdrental_ configuration](https://user-images.githubusercontent.com/45152336/194970198-1d11db13-a188-4244-bb5e-7a2884e36b48.png)

**Comment by BobbySchnipke** [comment]
I may give that a try later. For now rolling back one version solved the problem for me.

**Comment by serge-rider** [comment]
Fixed. 
It was a side effect of prepared statements disablement in Greenplum.

**Comment by uslss** [comment]
verified

**Comment by spencermathews** [comment]
This seems to be the reference issue for this bug. It makes sense to close the related issues as duplicates, by why close this issue when the problem is not yet fixed?

**Comment by E1izabeth** [comment]
@spencermathews the fix is ready and will be available in the next release.

**Comment by JeamesHorn** [comment]
any fixes for Mac OS Dbeaver?

**Comment by E1izabeth** [comment]
@JeamesHorn please, try workaround mentioned here https://github.com/dbeaver/dbeaver/issues/17865#issuecomment-1273928373
The fix will be available in the next release.

**Comment by JeamesHorn** [comment]
Hi - I cannot find the connection settings in the Mac OS userface unforunately, best I can get is PostGRE SQL driver settings but that box is not there for selecting

**Comment by LonwoLonwo** [comment]
Use can use F4 on your connection in the Database Navigator to open Connection settings

**Comment by neslihann2525** [comment]
Actually there is another solution for this issue, you could click the "Edit Connection" of the connection, and there  "Data Editor" menu, enable the Datasource "connectionName" settings on the top of the window and enable "Use SQL to limit fetch size". After that, for the Community Edition 22.2.2 version, it gets datas fast as older versions.

![image](https://user-images.githubusercontent.com/45585428/197358667-223a584e-c108-45a8-a156-ede9d1bf335a.png)
