### ISSUE TITLE
SQL autocompletion key word to uppercase does not work since 22.2.4

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#18131]
### Description

After upgrading to DBeaver 22.2.4, the autocompletion of keywords to transform them in uppercase does not work anymore.
It used to word in DBeaver .

### DBeaver Version

Community Edition 22.2.4

### Operating System

Ubuntu 22.04

### Database and driver

Database version : PostgreSQL 14.5

### Steps to reproduce

In preferences, check "keywords conversion" in Editors => SQL Editor => Code Editor.
It used to have a combo to choose between upper or lower case, but this combo does not appear anymore.

In SQL script, type "select" and hit space, the word stays in lowercase.

**Comment by E1izabeth** [comment]
You can find this setting in Editors->SQL Editor->Code Completion
![image](https://user-images.githubusercontent.com/28875055/200305759-797a5fe9-22da-4982-b032-f814dfc1bdae.png)

**Comment by E1izabeth** [comment]
Which previous DBeaver version are you talking about?

**Comment by ced75** [comment]
Thanks for your answer and your help.
I'm talking about DBeaver 22.2.3

The setting you are showing is not for SQL keywords, but to convert database objects (schema, name, column, etc.) to uppercase.
The feature I'm thinking of is changing case of SQL keywords automatically. It used to work in DBeaver 22.2.3 if correctly configured.

**Comment by E1izabeth** [comment]
The setting I mentioned converts keywords case on Enter. At least, it works for me,

**Comment by ced75** [comment]
OK. I must be more precise.
In version 22.2.3, a keyword was automatically converted to uppercase "on the fly" when writting the whole word ("select" for instance) and the typing a space. After the space, the conversion to uppercase appeared.
This is no more the case.

It works if I type the beginning of a keyword and select it in the list of autocompletion words. But this is not the feature I'm thinking about.
Hope it is clearer now...

**Comment by E1izabeth** [comment]
Thank you for clarifying. I got it.

We used to have a bug - DBeaver almost always converted keyword to upper case while autocompletion. It was annoying for many people, so we fixed this bug, which caused that your use case stopped working.
We'll try to look deeper to your use case and think out something.

Thank you for reporting to us.

**Comment by ced75** [comment]
And thank you for your help.
Hope it will come back, because automatic conversion to uppercase for keywords improve query readability, to my point of view.

**Comment by dahmmme** [comment]
> Thank you for clarifying. I got it.
> 
> We used to have a bug - DBeaver almost always converted keyword to upper case while autocompletion. It was annoying for many people, so we fixed this bug, which caused that your use case stopped working. We'll try to look deeper to your use case and think out something.
> 
> Thank you for reporting to us.

Hey @E1izabeth, I agree with @ced75. It is a lot nicer and easier to write SQL if the keyword converts “on the fly” instead of having to select them with “enter” or a click. I also do not really know if it was a bug, since people that didn't like it could just set the preferences as they wanted the formatting to be.

**Comment by dabekf** [comment]
I can confirm that the latest change broke things. After update I can't get the Auto format to work on any keywords. While before it was 99% correct, with an occasional "my column is named a bit like a keyword" inconvenience, now it doesn't work at all.

And using enter to change case would be really cumbersome, not to mention it doesn't seem like an option either: I can write "update[ENTER](changes to 'UPDATE ') sometable set[ENTER](line break because SET is not on the list)". Case unchanged. Or maybe existing table is first on the list and my keyword changes to that.

**Comment by jshmlr** [comment]
+1 to confirmation that this no longer works having updated to 22.2.4 today. Having keywords automatically convert to uppercase is an important feature for my workflow and I'd like to request that this option return.

Appreciate the hard work.

**Comment by brunoleal0** [comment]
+1 to confirmation that this no longer works at 22.2.4. Please make an option so keywords can be converted on the fly, instead of having to press enter everytime we type it =/

**Comment by Donal-Goggin** [comment]
+1 vote for this update being reverted. Convert case automatically should work on-the-fly like others have said. My queries just look "wrong" with the keywords in lowercase and pressing enter to get the uppercase working is just too much effort with how many keywords there can be.

**Comment by fcole90** [comment]
Hi, I report having the same exact issue. Keywords such as `SELECT` do not get _uppercased_ on the fly anymore when pressing space (with enter it works instead). 

Until 22.2.3 it worked as I described and it stopped with 22.2.4 :blush:

**Comment by da20rs** [comment]
I just updated my version and also missed the "on the fly auto-upper" of keywords. If it was a bug, it was a beautiful butterfly, please don't kill it  =P

**Comment by E1izabeth** [comment]
Fix will be available in the next release.

**Comment by BorisPoscredit** [comment]
With version 22.2.5 the bug is fixed. Thank you!

**Comment by jshmlr** [comment]
Thank you team for turning this around so quickly!

**Comment by atjtest** [comment]
I'm version 23.1.1 and have choose "Upper case" for "Insert case" in preference->Editors->SQL Editor->Code Completion. When I type select and space, it still shows lowercase. Is there any other options I need to check/uncheck?

**Comment by Tha-Fox** [comment]
> I'm version 23.1.1 and have choose "Upper case" for "Insert case" in preference->Editors->SQL Editor->Code Completion. When I type select and space, it still shows lowercase. Is there any other options I need to check/uncheck?

I have the same version and there is setting in preference->Editors->SQL Editor->Formatting->Keyword case which I changed to `upper`.

**Comment by ced75** [comment]
In preference->Editors->SQL Editor->Code Editor, I have the option "Key words conversion" that is ticked.
I wish it would help you.

**Comment by ced75** [comment]
> I have the same version and there is setting in preference->Editors->SQL Editor->Formatting->Keyword case which I changed to `upper`.
Yes, but first you must select "Default formatter" in "Formatter" list.
Then you can select "Upper" for Keyword case.

**Comment by salmanshafiq00** [comment]
> 

same here in that version. Have any solution?

**Comment by ThorstenWeberGER** [comment]
Hi, 

I am Confused with all the options. 

I would like to have all keywords being automatically (on the fly) being formatted upper
Code while the rest stays lower case. 

What do I need to select in settings?
