### ISSUE TITLE
After update, Intersystems Cache driver doesn't work

### ISSUE THREAD

**Issue by TychoBrahe34756** [dbeaver/dbeaver#18420]
### Description

Using version 22.2.5.202211202223

The following happend to 3 of my co-workers recently as well.

After upgrading DBeaver to the above version, on connecting to an Intersystems Cache DB I received the following message:
![First message](https://user-images.githubusercontent.com/119688918/205345382-4d73c508-ac21-42aa-951e-53eb75e845c8.png)

I clicked the Download button, DBeaver finishes but then cannot connect to any Intersystems Cache DB.  I then get this message:
![Second message](https://user-images.githubusercontent.com/119688918/205345711-112fb2dc-7162-4db6-8458-864f0c7933e0.png)

I then had to go to Driver Manager, edit the Cache driver, click on the Libraries tab and add this file I already had locally (I already had it from before?  Or this is what DBeaver downloaded when I clicked Download earlier?):
![Browse for driver file](https://user-images.githubusercontent.com/119688918/205346724-bd268117-6324-4c5d-b6ff-75913f52c9b0.png)

Finally, I was able to connect to an Intersystems Cache DB.   But this is a bug, right?   I was not having an issue until the update - which either did not properly download the file or removed it from being part of the DBeaver Cache driver.   Hoping that a future update doesn't cause it to occur again.

### DBeaver Version

22.2.5.202211202223

### Operating System

Windows 10

### Database and driver

Intersystems Cache

**Comment by LonwoLonwo** [comment]
Hello @TychoBrahe34756 
Thanks for the bug report. This issue fixed here: https://github.com/dbeaver/dbeaver/issues/18015
Fix will be available on Monday

**Comment by TychoBrahe34756** [comment]
Thanks for fixing the issue.   I am able to still connect to Intersystems Cache DBs after the update, however just an FYI that I am still seeing this dialog after an update, but perhaps that was expected.   I clicked the Download button (not know what the right action should be) and am experiencing no problems, so I need no further assistance.   Thanks again for your quick patch and I love the Christmas splash screen.

![Dialog 2022-12-05](https://user-images.githubusercontent.com/119688918/205722406-da950aae-d0ae-4c21-8952-26e352a7526a.png)

**Comment by LonwoLonwo** [comment]
Thanks for the answer @TychoBrahe34756 

And yes, for now, this downloading behavior is expected.
