### ISSUE TITLE
query result column data type is wrong!

### ISSUE THREAD

**Issue by yr220919** [dbeaver/dbeaver#18476]
### Description

query result column data type changed!
TABLE DEFINE:
![image](https://user-images.githubusercontent.com/120081138/206368836-3af085b2-77f8-4b3c-9e3d-5552ea228af6.png)

QUERY 1:
![image](https://user-images.githubusercontent.com/120081138/206368941-431482ac-4d44-4af5-8189-0db4b79a83f1.png)

QUERY 2:
![image](https://user-images.githubusercontent.com/120081138/206369005-b9dd8b1e-f955-4037-804e-e63d4c88dd08.png)

The StartTime data type is changed!

### DBeaver Version

22.2.4.202211061524

### Operating System

Windows 10 专业版  22H2 19045.2251

### Database and driver

Oracle Database 11g Release 11.2.0.1.0 - 64bit Production

### Steps to reproduce

query 1 then deselect column IDC,execute query 2,can see the StartTime Column Data Type has been changed!

**Comment by yr220919** [comment]
The same steps in sql developer,the result are:
query 1:
![image](https://user-images.githubusercontent.com/120081138/206369470-d6440c9c-dbb4-4082-8b82-154b5b4d5f47.png)

query 2:
![image](https://user-images.githubusercontent.com/120081138/206369516-4d501100-e3f6-4cd6-998d-4731ce198348.png)

**Comment by yr220919** [comment]
I find the lastest version 22.3,the issue is already exist!

**Comment by LonwoLonwo** [comment]
Hello. Please provide your query text as text here for tests.

**Comment by E1izabeth** [comment]
Does this issue still actual for the latest DBeaver version 22.3.3?

**Comment by E1izabeth** [comment]
I'm closing this issue as it was solved.
If you meet this issue again, please let me know.

**Comment by JovitaBhekti** [comment]
Hi, this issue still happening right now until the newest version (24.2.2).
Here is the capture..

--query create table and insert data
create table bcadw.test_column_1(
	coll_key int,
	coll_test string,
	coll_date timestamp
);

insert into bcadw.test_column_1 values ('1', 'abc', current_date());
insert into bcadw.test_column_1 values ('2', 'def', current_date());
insert into bcadw.test_column_1 values ('3', 'ghi', current_date());

select * from bcadw.test_column_1;
![image](https://github.com/user-attachments/assets/b2d53dc0-e01e-4bdc-87ca-a04f728228a9)

--run the select query : 
select coll_test, coll_date, coll_key
from
(select coll_key, coll_test, coll_date from bcadw.test_column_1)x
;
![image](https://github.com/user-attachments/assets/77796730-4ef9-4776-8a5d-d43f8b5b9076)

As you can see in the picture, the column data types in the result are wrong --> coll_test should be character, coll_date should be timestamp, and coll_key should be integer.
