### ISSUE TITLE
Autosuggest duplicates and unremovable

### ISSUE THREAD

**Issue by user-yalif** [dbeaver/dbeaver#18578]
### Description

While writing queries in SQL Editor autosuggest appears and can't be removed by buttons (Esc for example)
By pressing whitespace button and continuing writing autosuggest duplicates
![db-autosuggest](https://user-images.githubusercontent.com/54711192/209329512-b6ca11e1-0187-4fee-85e7-3a15e2f2341b.png)

### DBeaver Version

22.3.0.202212070729

### Operating System

Win 10

### Database and driver

Microsoft SQL Server
Driver: com.microsoft.sqlserver.jdbc.SQLServerDriver

### Steps to reproduce

1. Open SQL Editor
2. Write a query that contains column names so that autosuggest can appear (e.g select * from [DBName].[dbo].[TableName] d where d.Id Id)

**Comment by E1izabeth** [comment]
Thank you for bug report. I can't reproduce it for now. Could you turn on these settings and record a video showing your issue?

![image](https://user-images.githubusercontent.com/28875055/209334708-b7719950-d81b-42c0-8ced-8056b9c451a3.png)

**Comment by user-yalif** [comment]
Hi Elizabeth!
Yes, surely!
Video attached to this email.

Regards

**Comment by E1izabeth** [comment]
Attached to email media unfortunatelly doesn't come to github. Could you go to the issue on the github and attach it here?

**Comment by user-yalif** [comment]
https://user-images.githubusercontent.com/54711192/209342742-06f808f8-bae4-483b-94a6-8817993c4022.mp4

Sorry for inconvenience
Here is the video

**Comment by E1izabeth** [comment]
Thank you

**Comment by user-yalif** [comment]
I noticed that autosuggests can be removed by clicking on it with right button of the mouse and pressing Esc button

**Comment by E1izabeth** [comment]
@user-yalif could you reproduce this issue again and send me the log files?
You can find instruction here https://dbeaver.com/docs/wiki/Log-files/

**Comment by user-yalif** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/10443335/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10443336/dbeaver-debug.log)
Hi there!
Here two log files you asked me about
Issue had been reproduced on 18 Jan 2023

**Comment by E1izabeth** [comment]
Thank you

**Comment by E1izabeth** [comment]
@user-yalif Could you try early access version https://dbeaver.io/files/ea/ (or new release version on Monday) to see if the issue was fixed for you?

**Comment by user-yalif** [comment]
[E1izabeth](https://github.com/E1izabeth)
I'm wondering if autosuggest is displayed in two windows now?
Or such a behavior can be customized?
Let me know in case it is true then I cannot reproduce this issue.
Regards
![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/54711192/213428850-5841333d-dd37-4534-b1f6-e4e463eaee0a.png)

**Comment by E1izabeth** [comment]
Yes, this is expected. It shows additional information (a new feature #16197). Do you need a preference to turn off this feature?

**Comment by user-yalif** [comment]
Yes, it would be desirable to turn it off because it hides a half of screen :)
Is there a possibility to turn it off now?

**Comment by E1izabeth** [comment]
It's not possible now, but I create an issue https://github.com/dbeaver/dbeaver/issues/18811. Hope we will implement it soon.

**Comment by E1izabeth** [comment]
Thank you for your feedback

**Comment by Gercius** [comment]
https://github.com/dbeaver/dbeaver/assets/52923556/42d9ad28-d3cf-467c-8986-c0d60ddcfd48

Same/similar issue

**Comment by milkandrelish** [comment]
Did this get resolved? I am having the same issue, although I don't have a duplicate showing up. The auto-suggest window won't close unless I accept a suggestion - this is quite prohibitive to my coding!

**Comment by E1izabeth** [comment]
@milkandrelish please provide a video showing your issue and log files.

**Comment by E1izabeth** [comment]
This issue was resolved.

**Comment by milkandrelish** [comment]
Weird, this still happens for me! Is there a particular setting I need to change? I just updated to the latest version today.

Edit: I will take a video of this soon and post!

**Comment by ferrarimartin** [comment]
I have the same problem. I'm using Version 23.1.1.202306251800 on Windows. It's extremely cumbersome to close the popups. I would expect them to automatically close when they don't make more sense in the context. I ended up disabling automatic activation of the popups.

**Comment by E1izabeth** [comment]
If you have any suggestions of how to make DBeaver better please create a new issue. This one described a particular bug that was fixed and the issue is closed

**Comment by ferrarimartin** [comment]
Hi Elizabeth, you're right, sorry, I wasn't clear and it didn't sound good. I was seeing the issue exactly as reported, but if I enable/disable autosuggest at some point it starts working perfectly. I will add a video if I can repro again.
