### ISSUE TITLE
Sort/filter icons look-and-feel customization

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#18671]
We need to add config optiuon to customize sort and filter icons in data viewer columns header.

Original ticket: #18589

**Comment by lemon-juice** [comment]
Let me share my 2 cents on this issue. I think the new design of having the triangle to set sorting is not a bad idea in itself and I like the fact that I can easily choose my desired sort type without having to click on the sort arrow multiple times until dbeaver switches to the one I want. The only problem is that the old behaviour of changing the sort type by a single click has been removed because it was also very convenient.

I think there is a way to keep both features while not cluttering the UI with multiple icons: simply keep the visual sort icons like in the previous versions and get rid of the new triangle. When I left click the arrow then the sort is changed immediately like in the previous version and when I use the right click then I get the new context menu sort options that are accessible in the new version under the triangle. This way we need only one icon and get both functionalities. Of course, this could be further configurable - for those who want to prevent accidental clicks by disabling the instant click sort behaviour, etc. Then we would get the best of both worlds.

**Comment by wisc17** [comment]
imo this almost feels like a microsoft update .. making good things worse.
This is really inconvenient now.
Now that i learned that this is a "feature" i will go back to prev version
thanks

**Comment by serge-rider** [comment]
Sorting and filters menu config was fixed.  
Now you can enable old behavior in preferences.  
By default sort icons are disabled.

![image](https://user-images.githubusercontent.com/6398845/217185515-bf8c17a3-3b32-49de-8928-9f8ea3213aab.png)

**Comment by vatsake** [comment]
> Sorting and filters menu config was fixed. Now you can enable old behavior in preferences. By default sort icons are disabled.
> 
> ![image](https://user-images.githubusercontent.com/6398845/217185515-bf8c17a3-3b32-49de-8928-9f8ea3213aab.png)

Just tried it, not fixed. "Show attribute ordering" does absolutely nothing.

**Comment by uslss** [comment]
@vatsake this fix will be available in v.22.3.5 (Release date: February 19, 2023)

**Comment by wisc17** [comment]
@serge-rider 
> Sorting and filters menu config was fixed. Now you can enable old behavior in preferences. By default sort icons are disabled.

I tried it today and it works. thx a lot.
But i had serious problems finding the option by myself even i had that settings page opend.
It turns out that the german translation is not very good.
Instead of "Attributanordnung anzeigen" i would suggest "Attributsortierung anzeigen" which the correct translation for "order" in this case IMO
