### ISSUE TITLE
Cannot run program "/usr/bin/mysqldump" since version 22.3.4 (Permission denied)

### ISSUE THREAD

**Issue by HendrikJan** [dbeaver/dbeaver#18958]
### Description

I try to do a mysqldump and get the error 
```
Error executing process
  Cannot run program "/usr/bin/mysqldump" (in directory "/usr/bin"): error=13, Permission denied
  Cannot run program "/usr/bin/mysqldump" (in directory "/usr/bin"): error=13, Permission denied
    error=13, Permission denied
    error=13, Permission denied
```

### DBeaver Version

Community Edition 22.3.4

### Operating System

Ubuntu 22.04.1 LTS

### Database and driver

1. Server version: 10.6.11-MariaDB-0ubuntu0.22.04.1
2. Driver name: MySQL 5

### Steps to reproduce

1. Upgrade to dBeaver version 22.3.4 (dbeaver-ce_22.3.4_amd64.deb)
2. Open a database
3. Go to Tools > Dump database
4. Click on Next and Start
5. Get the error

After downgrade back to 22.3.3 it works again.

**Comment by npetrovopt** [comment]
I have the same error, but when I try to connect to databases using SSH tunnel.
DBeaver Version
Community Edition 22.3.4

Operating System
Ubuntu 22.04.1 LTS

After downgrading back to 22.3.3 it works again. :+1:

**Comment by Matvey16** [comment]
> 1. Upgrade to dBeaver version 22.3.4 (dbeaver-ce_22.3.4_amd64.deb)

According to this, I assume you installed DBeaver package manually and not from Snap or Flatpack. Am I correct?

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/5845, #8508, #7521 related?

**Comment by crossworth** [comment]
Same problem, but with Postgres:
Pop!_OS 22.04 LTS
Version 22.3.4, installed with [`apt-get`](https://dbeaver.io/2022/02/28/best-alternative-ways-to-download-dbeaver-community-edition/)
Local and remote databases

```
2023-02-06 09:00:24.615 - IO error: Cannot run program "/usr/bin/pg_dump" (in directory "/usr/bin"): error=13, Permission denied
2023-02-06 09:00:24.615 - java.io.IOException: Cannot run program "/usr/bin/pg_dump" (in directory "/usr/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 7 more
```

For some reason the Product Version is empty as well:
![image](https://user-images.githubusercontent.com/1251151/216969909-3a8a95aa-9f83-4970-96c4-3f4f86ce2810.png)

Logs for the Product Version:
```
ENTRY org.jkiss.dbeaver.model 2 0 2023-02-06 09:22:45.049
!MESSAGE Error reading PostgreSQL native client version from /usr/bin/psql
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2023-02-06 09:22:45.049
!MESSAGE Cannot run program "/usr/bin/psql": error=13, Permission denied
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2023-02-06 09:22:45.049
!MESSAGE error=13, Permission denied
!STACK 0
java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.getFullServerVersion(PostgreDataSourceProvider.java:255)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.getProductVersion(PostgreDataSourceProvider.java:155)
	at org.jkiss.dbeaver.ui.dialogs.connection.ClientHomesPanel.selectHome(ClientHomesPanel.java:204)
	at org.jkiss.dbeaver.ui.dialogs.connection.ClientHomesPanel$1.widgetSelected(ClientHomesPanel.java:108)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.connection.ClientHomesPanel.chooseClientHome(ClientHomesPanel.java:327)
	at org.jkiss.dbeaver.ui.dialogs.connection.ClientHomesSelector.manageHomes(ClientHomesSelector.java:109)
	at org.jkiss.dbeaver.ui.dialogs.connection.ClientHomesSelector$1.widgetSelected(ClientHomesSelector.java:87)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.tasks.ui.nativetool.NativeToolWizardDialog.openClientConfiguration(NativeToolWizardDialog.java:111)
	at org.jkiss.dbeaver.tasks.ui.nativetool.NativeToolWizardDialog.buttonPressed(NativeToolWizardDialog.java:101)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreToolBackup.execute(PostgreToolBackup.java:39)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:382)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:296)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by activeNathan** [comment]
Maybe worth noting that can not restore/import either.

```Error executing process
  Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
  Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
    error=13, Permission denied
    error=13, Permission denied
```

**Comment by GeoBSI** [comment]
Hi, same issue with DEB package version 22.3.4, can not use pg_dump or pg_restore.
Downgrade to 22.3.3 fixed the issue

> Start Debug Core [org.eclipse.debug.core 3.20.0.v20220811-0741]
2023-02-06 16:33:13.175 - error=13, Permission denied
java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by tridoxx** [comment]
same error, with versión 22.3.4 using mariadb, its work using the 22.2.5 version, i am using pop_os based debian, i installed it with the .deb package from website

**Comment by HendrikJan** [comment]
> > 1. Upgrade to dBeaver version 22.3.4 (dbeaver-ce_22.3.4_amd64.deb)
> 
> According to this, I assume you installed DBeaver package manually and not from Snap or Flatpack. Am I correct?

Indeed. I install using the `dpkg` command.

**Comment by ced75** [comment]
Hi.
Same error with several PostgreSQL tools (pg_dump, pg_format, etc.), with version 22.3.4 installed by .deb package using dpkg.
Downgrade to version 22.3.3 works fine. So the issue seems to stick to version 22.3.4.
I hope it will help.

**Comment by mlemmens** [comment]
Same issue here when trying to import a database dump.

```2023-02-07 10:41:58.747 - IO error: Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
2023-02-07 10:41:58.748 - java.io.IOException: Cannot run program "/usr/bin/mysql" (in directory "/usr/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 8 more
```

Version 22.3.4.202302060909

Session Data:
```eclipse.buildId=unknown
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=nl_NL
Command-line arguments:  -os linux -ws gtk -arch x86_64```

**Comment by serge-rider** [comment]
Most likely it is a result of Java 17 upgrade.
We are investigating this and going to fix it in the next version.

**Comment by acantepie** [comment]
Downgrade to version 22.3.3 solve the problem.

=> https://dbeaver.io/files/22.3.3/

**Comment by serge-rider** [comment]
We fixed Java version and packaging. It should fix the problem with native executables.

Could you test it in the Early Access version? (https://dbeaver.io/files/ea/)

**Comment by richmondb** [comment]
Tested the early access version (22.3.4.202302090438) from early access, problem still persist on my system running Pop Os 22.04 LTS. Downgraded to 22.3.3 solves the issue for now.

**Comment by elring** [comment]
Doesn't work for me (22.3.4.202302090438), Linux Mint 21.

**Comment by mushketer888** [comment]
I have this issue too
DBeaver Version
Community Edition 22.3.4

Operating System
Ubuntu 22.04.1 LTS

**Comment by mkgrgis** [comment]
The same with pg_dump, Community Edition 22.3.4, Linux Mint

**Comment by serge-rider** [comment]
Could you try it one more time? (fresh EA was just published)

**Comment by elring** [comment]
Now it works (no pg_dump error while backup, no ssh-keygen error while connecting via SSH JSch) in 22.3.4.202302091626. Thank you!

**Comment by Matvey16** [comment]
Verified

**Comment by ced75** [comment]
Thanks a lot for the quick fix!

**Comment by XThenuwara** [comment]
Same issue, was using snap version of dbeaver (24.2.0.202409011551). switched to apt version.

**Comment by chiragwootag** [comment]
Same issue using snap version  of dBeaver 24.2.2.202410061621

**Comment by mjcallao** [comment]
Same issue using version of dBeaver 24.3.0.202412011650

**Comment by mydogspies** [comment]
Same issue using version 24.3.3.202501191612 of dBeaver unfortunately

**Comment by todorg-consensus** [comment]
Same issue using snap Version 24.3.4.202502021521

**Comment by muhammedaksam** [comment]
I am having the same issue with Version 24.3.4.202502021521.

**Comment by de-angelov** [comment]
Same for Flatpack Version 24.3.5.202502162012

**Comment by riednyko** [comment]
While we fix this permissions issue, you can use two workarounds for snap:
1) Run dbeaver-ce application from `/snap/dbeaver-ce/current/usr/share/dbeaver-ce`
2) Install local postgresql or mysql client in snap-readable directory (/home, or something like /mnt) and choose it from dbeaver for dump

**Comment by torbjorn-stabo** [comment]
Hi. I just got this while trying to export a mariadb database(in a docker container, but I guess that shouldn't matter), using dbeaver 25.0.0.202503021833 in Ubuntu installed via snap. mysqldump is installed, if I try `$ mysqldump` from bash it starts just fine. Is this related?

To reproduce:
1. Right click on the database to export in Database Navigator
2. Select Tools -> Dump database
3. In the 'MySQL dump' window, select the database to be exported.
4. Click Next.
5. Select Structure only.
6. Set Output folder to '/tmp'
7. Click on Start.

I'm not sure if all the above steps are needed to reproduce the error, but I list them for completeness.

`2025-03-12 16:08:47.979 - IO error: Utility 'mysqldump' not found in client home '/usr/bin' (/usr/bin)
2025-03-12 16:08:47.981 - java.io.IOException: Utility 'mysqldump' not found in client home '/usr/bin' (/usr/bin)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getNativeClientBinary(RuntimeUtils.java:152)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.fillProcessParameters(MySQLDatabaseExportHandler.java:102)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.fillProcessParameters(MySQLDatabaseExportHandler.java:1)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.getCommandLine(MySQLNativeToolHandler.java:76)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.getCommandLine(MySQLDatabaseExportHandler.java:83)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.getCommandLine(MySQLDatabaseExportHandler.java:1)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:218)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:285)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:88)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
`

**Comment by riednyko** [comment]
Hi. dbeaver-ce snap package now has classic confinement. Please try installing the latest DBeaver version using:
`sudo snap install dbeaver-ce --classic`
All permission issues should now be resolved

**Comment by HendrikJan** [comment]
I havn't had this problem for a long time now.
Closing the issue.
