### ISSUE TITLE
Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available

### ISSUE THREAD

**Issue by gogosofta** [dbeaver/dbeaver#18962]
### Description

The following error occurs whenever I try to browse table's data, or execute an arbitrary query:
Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available

### DBeaver Version

22.3.4.202302060909

### Operating System

Linux Mint 21.1 Cinnamon

### Database and driver

Databricks using com.simba.spark.jdbc.Driver
file: SimbaSparkJDBC42-2.6.22.1040.zip

### Steps to reproduce

<img width="913" alt="image" src="https://user-images.githubusercontent.com/13131218/216963120-3c44d4ea-45bc-4ad4-9377-e93cd56799f8.png">

### Additional context

This issue is not present in version 22.3.3.202301211053

**Comment by ShadelessFox** [comment]
Hello @gogosofta,

Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by gogosofta** [comment]
> Hello @gogosofta,
> 
> Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

@ShadelessFox , here you are:

[dbeaver-debug-1675684414858.log.copy.gz](https://github.com/dbeaver/dbeaver/files/10662924/dbeaver-debug-1675684414858.log.copy.gz)

**Comment by ShadelessFox** [comment]
I see, thank you.

Can you try adding the following line at the end of the `dbeaver.ini` file located under the installation directory?
```
--add-opens=jdk.unsupported/sun.misc=ALL-UNNAMED
```

This is what you should get:
```
-vmargs
...
--add-opens=jdk.unsupported/sun.misc=ALL-UNNAMED
```

After that, restart DBeaver and try again. Please let me know if it helps.

**Comment by gogosofta** [comment]
> 

It didn't help. Still get the error.

Here's the content of the ini file:

$ cat /usr/share/dbeaver-ce/dbeaver.ini
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=deb
--add-opens=jdk.unsupported/sun.misc=ALL-UNNAMED

**Comment by ShadelessFox** [comment]
Thanks for testing this. We need to investigate other solutions.

**Comment by Destrolaric** [comment]
@gogosofta could you try adding `-Dio.netty.tryReflectionSetAccessible=true` write me if it helps.

**Comment by Destrolaric** [comment]
@gogosofta, Sorry we were unable to reproduce mentioned issue, if there are any information which will allow to do so, it will be reopened.

**Comment by gogosofta** [comment]
It's fixed in Version 23.0.0.202303040621

**Comment by Destrolaric** [comment]
@gogosofta Thank you for the information. I think this happened due to the update to Java 17. We reverted to 11 for a time due to several similar issues after migration.

**Comment by gogosofta** [comment]
> 

The problem re-appears with version 23.0.2 onwards and still exists.

**Comment by E1izabeth** [comment]
Does it https://github.com/dbeaver/dbeaver/issues/18962#issuecomment-1424406392 helps?

**Comment by gogosofta** [comment]
> Does it [#18962 (comment)](https://github.com/dbeaver/dbeaver/issues/18962#issuecomment-1424406392) helps?

23.0.1.202303250535 is the latest working version for me.

**Comment by ShadelessFox** [comment]
@gogosofta does adding the specified flag solve the issue?

**Comment by gogosofta** [comment]
> @gogosofta does adding the specified flag solve the issue?

neither then nor now.

**Comment by ShadelessFox** [comment]
Can you please show your `dbeaver.ini` file's contents?

**Comment by gogosofta** [comment]
> 

$ cat /usr/share/dbeaver-ce/dbeaver.ini
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=deb


! this is the 20.0.1... version ini file

**Comment by gogosofta** [comment]
here's the dbeaver.ini content for version 23.0.4 with the additional flag added:

$ cat /usr/share/dbeaver-ce/dbeaver.ini
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
-Dosgi.requiredJavaVersion=17
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
--add-opens=java.base/sun.security.action=ALL-UNNAMED
--add-opens=java.base/sun.security.util=ALL-UNNAMED
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=deb
-Dio.netty.tryReflectionSetAccessible=true



Still it produces the same error:
SQL Error [500618] [HY000]: [Simba][SparkJDBCDriver](500618) Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available

**Comment by serge-rider** [comment]
Simba driver is deprecated. New databricks driver (native one) should be used instead.
You can re-create connection with the new driver. You can use the same JDBC URL but replace `simba` with `databricks` after `jdbc:`.

We will remove legacy driver in future versions of DBeaver.

**Comment by gogosofta** [comment]
> Simba driver is deprecated. New databricks driver (native one) should be used instead. You can re-create connection with the new driver. You can use the same JDBC URL but replace `simba` with `databricks` after `jdbc:`.
> 
> We will remove legacy driver in future versions of DBeaver.

I can't find a driver named "Databricks" when creating new connection and there is no "simba" in the jdbc connection string. It's like this:
jdbc:spark://<host>:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/endpoints/<endpoint>

Do you mean the className, which is: "com.simba.spark.jdbc.Driver"?

**Comment by gogosofta** [comment]
Found Azure Databricks (Native), and changed "spark" to "databricks" in jdbc connection string, so the connection succeeded. Now a different error occurs when trying to execute an arbitrary query (e.g. "select 1"): 
SQL Error [500540] [HY000]: [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 37. Background thread ID: 281. Error caught: Could not initialize class com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.

**Comment by serge-rider** [comment]
@gogosofta could you send full stacktrace of the error? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by gogosofta** [comment]
> @gogosofta could you send full stacktrace of the error? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

Here:

```
!ENTRY org.eclipse.ui 2 2 2023-05-11 18:00:29.411
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-05-11 18:00:51.763
!MESSAGE SQL Error [500540] [HY000]: [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 44. Background thread ID: 58. Error caught: null.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-05-11 18:00:51.763
!MESSAGE [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 44. Background thread ID: 58. Error caught: null.
!STACK 0
com.databricks.client.support.exceptions.GeneralException: [Databricks][DatabricksJDBCDriver](500540) Error caught in BackgroundFetcher. Foreground thread ID: 44. Background thread ID: 58. Error caught: null.
	at com.databricks.client.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.deserializeRecordBatch(MessageSerializer.java:363)
	at com.databricks.client.spark.arrow.ArrowBuffer.deserializeBatch(Unknown Source)
	at com.databricks.client.spark.arrow.ArrowBuffer.handleInitializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HiveServer2BaseBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.RowsetBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.getRowSetInformation(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchFromServer(Unknown Source)
	at com.databricks.client.spark.jdbc.DowloadableFetchClient.fetchNRows(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchRows(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:136)
	... 19 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @689cd453
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)
	... 19 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-05-11 18:00:51.763
!MESSAGE ExceptionInInitializerError
!STACK 0
java.lang.ExceptionInInitializerError
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.deserializeRecordBatch(MessageSerializer.java:363)
	at com.databricks.client.spark.arrow.ArrowBuffer.deserializeBatch(Unknown Source)
	at com.databricks.client.spark.arrow.ArrowBuffer.handleInitializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HiveServer2BaseBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.RowsetBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.getRowSetInformation(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchFromServer(Unknown Source)
	at com.databricks.client.spark.jdbc.DowloadableFetchClient.fetchNRows(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchRows(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:136)
	... 19 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @689cd453
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)
	... 19 more
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2023-05-11 18:00:51.764
!MESSAGE Failed to initialize MemoryUtil.
!STACK 0
java.lang.RuntimeException: Failed to initialize MemoryUtil.
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:136)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.deserializeRecordBatch(MessageSerializer.java:363)
	at com.databricks.client.spark.arrow.ArrowBuffer.deserializeBatch(Unknown Source)
	at com.databricks.client.spark.arrow.ArrowBuffer.handleInitializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HiveServer2BaseBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.RowsetBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.getRowSetInformation(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchFromServer(Unknown Source)
	at com.databricks.client.spark.jdbc.DowloadableFetchClient.fetchNRows(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchRows(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @689cd453
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)
	... 19 more
!SUBENTRY 4 org.jkiss.dbeaver.model 4 0 2023-05-11 18:00:51.764
!MESSAGE Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @689cd453
!STACK 0
java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @689cd453
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
	at com.databricks.client.jdbc42.internal.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
	at com.databricks.client.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.deserializeRecordBatch(MessageSerializer.java:363)
	at com.databricks.client.spark.arrow.ArrowBuffer.deserializeBatch(Unknown Source)
	at com.databricks.client.spark.arrow.ArrowBuffer.handleInitializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HiveServer2BaseBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.RowsetBuffer.initializeBuffer(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.getRowSetInformation(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchFromServer(Unknown Source)
	at com.databricks.client.spark.jdbc.DowloadableFetchClient.fetchNRows(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.fetchRows(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by serge-rider** [comment]
It is a known issue: https://github.com/apache/spark/pull/33947

It has to be fixed in the latest driver version (02.06.32). Could you click on the Test Connection button on the connection edit dialog? What it says about driver and server versions?

**Comment by gogosofta** [comment]
Server: SparkSQL 3.1.1
Driver: DatabricksJDBC 02.06.32.1054

I should stick to DBeaver version 23.0.1 then, right?

**Comment by LonwoLonwo** [comment]
Hello @gogosofta 

Could you please check the latest Early Access DBeaver version https://dbeaver.io/files/ea/?

**Comment by gogosofta** [comment]
> Hello @gogosofta
> 
> Could you please check the latest Early Access DBeaver version https://dbeaver.io/files/ea/?

Hi @LonwoLonwo. It's still present:
"SQL Error [500618] [HY000]: [Simba][SparkJDBCDriver](500618) Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available"

**Comment by gogosofta** [comment]
Just FYI - it's still present in 23.1.3. 
The latest working version for me is 23.0.1.

**Comment by matthiasvop** [comment]
I'm initially hit by this in 23.3.2 after upgrading through windows store.
It's affecting snowflake connections ... the only solution seems to be to downgrade ... ?

**Comment by arielromeo** [comment]
Hi!, 
I found back this bug back on version 24.3.4, however downgrading it to 24.3.3 it is working well. Please could you patch this in the latest version ?

Thanks.

**Comment by ShadelessFox** [comment]
I believe DBeaver now uses Java 21, which could be the culprit.

Can you please try the following suggestions and let me know if they help? @arielromeo 
- https://github.com/dbeaver/dbeaver/issues/18962#issuecomment-1419011188
- https://github.com/dbeaver/dbeaver/issues/18962#issuecomment-1424406392

**Comment by mlups** [comment]
I had the same error connecting to Databricks, for me the solution was to update the JDBC jar to the latest one as some method signatures changed in Java 21, my guess is that the issue was solved once I updated the jar to the latest one.

**Comment by serge-rider** [comment]
Driver updated to the most recent version (2.7.1 for native and Simba)

**Comment by LonwoLonwo** [comment]
Verified on the CB Team side in all products.
https://github.com/dbeaver/dbeaver/pull/37019

**Comment by TomAtGithub** [comment]
Had a similar bug with the databricks connector (which is spark based) on mac os (dbeaver-ce-24.3.4-macos-aarch64.dmg).
Downgrading to [24.3.3](https://github.com/dbeaver/dbeaver/releases/tag/24.3.3) solved it.

**Comment by ShadelessFox** [comment]
@TomAtGithub the issue is fixed in 24.3.5. It can be downloaded here: https://dbeaver.io/files/ea/.

**Comment by TomAtGithub** [comment]
I still get the same error with and without the ini file: 

`SQL-Fehler [500618] [HY000]: [Databricks][JDBCDriver](500618) Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available`

```
cat ./Applications/Dbeaver.app/Contents/Eclipse/dbeaver.ini 
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=deb
--add-opens=jdk.unsupported/sun.misc=ALL-UNNAMED
```

Version 25.0.0.202502140022 (dbeaver-ce-25.0.0-macos-aarch64.dmg)

**Comment by ShadelessFox** [comment]
Please try upgrading the driver version. It should be `2.7.1`.

**Comment by arielromeo** [comment]
I confirm that upgrading dbeaver up to v25.0.0 and using the latest Databricks driver v2.7.1 (https://www.databricks.com/spark/jdbc-drivers-download) Everything works as expected. 

Thanks!

**Comment by cvcore** [comment]
> I confirm that upgrading dbeaver up to v25.0.0 and using the latest Databricks driver v2.7.1 (https://www.databricks.com/spark/jdbc-drivers-download) Everything works as expected.
> 
> Thanks!

For me it also works now with dbeaver `Version 24.3.5.202502162012` and Databricks driver `v2.7.1` with 

`--add-opens=jdk.unsupported/sun.misc=ALL-UNNAMED` 

appended to 

`/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini`.
