### ISSUE TITLE
Select results are no more editable

### ISSUE THREAD

**Issue by jozso** [dbeaver/dbeaver#19434]
### Description

Even a the simplest select is not editable. In a data view I can edit:
![image](https://user-images.githubusercontent.com/1370564/226380606-ecc1ef84-17c2-48a8-b4c0-43b9f1b19cc7.png)

But if I make a simple select for this table (like select * from leiro) no more chance to edit:
![image](https://user-images.githubusercontent.com/1370564/226381017-265d80bd-fcde-49da-a0ff-cb0255380607.png)

Every field says: (Read only: No row indentifier found)

### DBeaver Version

Community edition 23.0.0

### Operating System

Windows 10

### Database and driver

Postgresql

**Comment by LonwoLonwo** [comment]
Hello @jozso 

Could you please provide your table DDL?
Please create another screen with a visible zone of active datasource/database above.

Like in the picture:

![2023-03-20 18_28_50-DBeaver Ultimate 22 3 2 - _DBC_ Script-107](https://user-images.githubusercontent.com/45152336/226388831-8aa3bf66-006e-4f65-8b8d-1083a8c37257.png)

**Comment by jozso** [comment]
Here then screen shot, although is not a table related problem, I just wanted to give the simplest example. Since couple of releases none of the select are editable.

![image](https://user-images.githubusercontent.com/1370564/226526517-e1e5aecc-4da7-4e5f-bdac-fde25576db56.png)

**Comment by LonwoLonwo** [comment]
No, I need a screen from the SQL Editor. 

Also, will

`select * from public.leiro`

have another result? Or also read-only?

Could you please run your query and provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by jozso** [comment]
Sorry, you mean this?
![image](https://user-images.githubusercontent.com/1370564/226914427-5493f79a-33e4-4c76-8af2-151e23ce9c7a.png)

Unfortunatelly also read only.

And one more information, there is not any log entry after the querries running.

**Comment by LonwoLonwo** [comment]
Do you have this issue with this and other tables? In any schemas?

**Comment by jozso** [comment]
All schemas, all databases Postgresql, MS SQL, all querries.

**Comment by LonwoLonwo** [comment]
Please try to test our Early Access version. https://dbeaver.io/files/ea/
Maybe problem is fixed there.

**Comment by jozso** [comment]
I waited for the final 23.0.1, but the problem remained. No row identifier found for every querries' every field.

I think it is some general setting I couldn't find.

**Comment by LonwoLonwo** [comment]
Hello @jozso 

Please provide me with a screen from the Preference page. Preferences -> Editors -> Data Editor.

**Comment by jozso** [comment]
![image](https://user-images.githubusercontent.com/1370564/229030867-521a67dc-8c3c-4eba-92b1-73e3552d2bf8.png)

**Comment by LonwoLonwo** [comment]
Ok.. Could you please enable [the Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) with all enabled filters? Execute your SELECT and provide a screen from your Query manager. I will see metadata reading queries then.

**Comment by LonwoLonwo** [comment]
Additionally, I'll repeat it - please provide log files https://dbeaver.com/docs/wiki/Log-files/

**Comment by jozso** [comment]
Here the Query Manager's output:
![image](https://user-images.githubusercontent.com/1370564/229439896-fad38615-f8c8-4dfb-a50b-c9a8d3bd9873.png)

(the text now always fully visible, so here an another copy-paste:
SHOW search_path
SELECT current_schema(),session_user
select * from leiro
LIMIT 1000
SELECT c.relname,a.*,pg_catalog.pg_get_expr(ad.adbin, ad.adrelid, true) as def_value,dsc.description
FROM pg_catalog.pg_attribute a
INNER JOIN pg_catalog.pg_class c ON (a.attrelid=c.oid)
LEFT OUTER JOIN pg_catalog.pg_attrdef ad ON (a.attrelid=ad.adrelid AND a.attnum = ad.adnum)
LEFT OUTER JOIN pg_catalog.pg_description dsc ON (c.oid=dsc.objoid AND a.attnum = dsc.objsubid)
WHERE NOT a.attisdropped AND c.oid=380389104 ORDER BY a.attnum
SELECT pp.oid as poid, pp.* FROM pg_catalog.pg_proc pp WHERE pp.proname ILIKE '%selec%' AND pp.pronamespace IN (2200,11) ORDER BY pp.proname LIMIT 100
SELECT pc.oid,pc.relname,pc.relnamespace,pc.relkind FROM pg_catalog.pg_class pc WHERE pc.relkind in('r','v','m','f','p') AND pc.relname ILIKE '%selec%' AND pc.relnamespace IN (2200,11) ORDER BY pc.relname LIMIT 100
SELECT c.oid,c.*,d.description
FROM pg_catalog.pg_class c
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=c.oid AND d.objsubid=0 AND d.classoid='pg_class'::regclass
WHERE c.relnamespace=2200 AND c.relkind not in ('i','I','c')
SET search_path = public,public,"$user"
SHOW search_path
SELECT current_schema(),session_user
Connected to "kumasi"
SELECT t.oid,t.*,c.relkind,format_type(nullif(t.typbasetype, 0), t.typtypmod) as base_type_name, d.description
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_type et ON et.oid=t.typelem 
LEFT OUTER JOIN pg_catalog.pg_class c ON c.oid=t.typrelid
LEFT OUTER JOIN pg_catalog.pg_description d ON t.oid=d.objoid
WHERE t.typname IS NOT NULL
AND (c.relkind IS NULL OR c.relkind = 'c') AND (et.typcategory IS NULL OR et.typcategory <> 'C')
SELECT typcategory FROM pg_catalog.pg_type WHERE 1<>1 LIMIT 1
SELECT version()
select * from pg_catalog.pg_settings
SELECT db.oid,db.* FROM pg_catalog.pg_database db WHERE datname='kumasi'
SHOW search_path
SELECT current_schema(),session_user
Connected to "kumasi"
SHOW search_path
SELECT n.oid,n.*,d.description FROM pg_catalog.pg_namespace n
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=n.oid AND d.objsubid=0 AND d.classoid='pg_namespace'::regclass
 ORDER BY nspname
SELECT current_schema(),session_user
Connected to "kumasi"

And here the error log. It seems that this two errors just pop up at startup:
![image](https://user-images.githubusercontent.com/1370564/229440364-d6c20168-46cd-4c3f-8755-5cce8d6e32c8.png)

**Comment by jozso** [comment]
Ok, wait, wait wait. There is a preferences (Window, Preferences, Data Editor)

![image](https://user-images.githubusercontent.com/1370564/229441648-eae57bb1-a13c-420b-8624-e9f459b0a278.png)

It's looks fine, but there is a similar preferences:

![image](https://user-images.githubusercontent.com/1370564/229441796-6e0d1bbe-07d2-4294-a82b-a307641c2354.png)

where this two options was checked out. I checked in and now it seems like working!

**Comment by LonwoLonwo** [comment]
> It's looks fine, but there is a similar preferences:

These are data source preferences, meaning they are bound to the specific data source. 

So, does your issue solved now?

**Comment by jozso** [comment]
I think yes, it's solved. 

Thank you!

**Comment by LonwoLonwo** [comment]
Thanks for the answer @jozso
