### ISSUE TITLE
`Open Declaration` not working with Oracle Packages inside Queries

### ISSUE THREAD

**Issue by romiof** [dbeaver/dbeaver#19514]
### Description

Hello,

At my query, when I click on objects names, like tables name / views / functions, and press <kbd>F4</kbd> , for all of them, the object declaration is nicely open in a new tab.

But it doesn't work for `Packages`, when the package is inside the query text.
Doesn't work in any form: <kbd>F4</kbd> or <kbd>CTRL</kbd> + <kbd>Click</kbd> or `Context Menu`

But if the Package is outside the query text, and is only the package name, without `.function_call` the action (Open Declaration) will work.

It's very odd, because in Oracle, a package must be called with `.function_name` or `.procedure_name` as pakage are just to groups logically related objects.

### DBeaver Version

CE 22.3.3

### Operating System

Windows 11

### Database and driver

- Oracle Database 12.1
- Driver ojdbc8-12.2.0.1.jar

### Steps to reproduce

1. Call a package function in Query Text, to return a column, like a normal function will return;
2. Try to press <kbd>F4</kbd> over the package or the package.function_name;
3. Nothing will happen;
4. The same occurs with the option at context menu (_right click_)
5. But if the package name is alone on other part of the query editor, without `.function_call` the <kbd>F4</kbd> action will work.

### Additional context

Images under details:

<details>

**Inside Query Text, doesn't work**
![image](https://user-images.githubusercontent.com/54966010/228242257-0ae705e3-131a-4237-8e6e-06d049366df8.png)

**Package alone in Query Editor, <kbd>F4</kbd> works**
![image](https://user-images.githubusercontent.com/54966010/228242350-a1d4090d-2248-4de6-8b2c-f58b0c18697e.png)

**For functions inside a query texts, it works fine**
![image](https://user-images.githubusercontent.com/54966010/228241992-46bd59e9-7d7d-4754-a0b1-0f8c7ff3b460.png)

</details>

**Comment by ShadelessFox** [comment]
Hello @romiof,

What's a "package inside query"? Can you please provide a minimal reproducible example?

**Comment by romiof** [comment]
> Hello @romiof,
> 
> What's a "package inside query"? Can you please provide a minimal reproducible example?

Hello!

I've put some images inside _Additional context_ tag.

Let me know if it's enough or if do you need more examples.

**Comment by ShadelessFox** [comment]
I'm not sure what's going on in these screenshots, sorry.

**Comment by romiof** [comment]
@ShadelessFox sorry for the delay to reply you.

I've some cases in Oracle, that pressing <kbd>F4</kbd> (or even <kbd>CTRL + Click</kbd>) over a PACKAGE NAME doesn't open the object declaration.

I'm logged with same user who owns the object.
There is a error message at the bottom:
`Can't find metadata object for name 'BR_COM_FORMACAO_PRECO_VENDA.BUSCA_VALOR_INCIDENCIA'`

<details>

![image](https://user-images.githubusercontent.com/54966010/235145418-665295ea-80ae-48b1-868f-0768d9ca1cb7.png)
</details>

But if the package name is without de `.FUNCTION_NAME` pressing <kbd>F4</kbd> works fine.

<details>

![image](https://user-images.githubusercontent.com/54966010/235146195-ab54dd0f-6b94-4763-b6ec-4907f1528b20.png)
</details>

I embed a GIF, showing the problem:
<details>

![dbeaver_9FEmJRl2PD](https://user-images.githubusercontent.com/54966010/235147567-fbd9da1b-87d5-4d7d-a25b-938d43a651e5.gif)
</details>

This package has a lot of functions inside, whit a lot of paramteres. And the package body has obfuscation (a form that Oracle uses to hide PL/SQL code). But the package specification is in plain text.

Since yesterday, I've tried to create new packages/functions to reproduce this error, using obfuscation/ not using; using functions with parameters and whitout parameters... 
But I couldn't reproduce the same problem with a new package.

--

I hope that my examples help to understand this issue.

**Comment by LonwoLonwo** [comment]
> Since yesterday, I've tried to create new packages/functions to reproduce this error, using obfuscation/ not using; using functions with parameters and whitout parameters...
> But I couldn't reproduce the same problem with a new package.

Did you try to refresh your schema after the first package creation? Because DBeaver doesn't know anything about the newly created package before schema refreshing. Maybe because of that, your Declaration command didn't work.

**Comment by romiof** [comment]
@LonwoLonwo 

Unfortunately I didn't create this package. It already exists at my schema, as show in my gif.

**Comment by E1izabeth** [comment]
Could you try the latest DBeaver version? Probably, your issue has been already fixed. At least, I can't reproduce it on DBeaver 23.0.4

**Comment by romiof** [comment]
Hi @E1izabeth !
With the last version, this bug stills. But I found something new.

If I wrote the schema owner and a `.` (dot) , before the package name, I can open the object using `Open Declaration`.

I was connect at my database with the same user (and of course schema) which owns the package.
![image](https://github.com/dbeaver/dbeaver/assets/54966010/ef377706-28db-4777-b0b7-a2baedbe72a9)


Tests with last version of DBeaver.
<details>

![dbeaver_YbE2XbCcee](https://github.com/dbeaver/dbeaver/assets/54966010/53611a8f-813f-4df9-aed5-d336dc42a714)

Oracle Object:
![image](https://github.com/dbeaver/dbeaver/assets/54966010/b0921d6f-42bb-4fa4-856d-b3ba9acf186f)
</details>


Is there any way, to DBeaver check the object inside the schema used by the connection, if it was not found at first attempt?

**Comment by E1izabeth** [comment]
Thank you for checking. We actually check objects inside schema, but probably something went wrong. It makes delivering the fix slower, because we can't reproduce the issue, but I hope we will figure out the fix.

**Comment by E1izabeth** [comment]
Could you send the log files? 
You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by romiof** [comment]
> Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

Attached!

[dbeaver_logs.zip](https://github.com/dbeaver/dbeaver/files/11511089/dbeaver_logs.zip)

--

I realized today, that another package has same issue when trying to `Open Declaration`.

I'll try to reproduce the issue by creating a new Package/Function and if I do, I'll reply.

**Comment by arhayka** [comment]
Thank you for your report.
