### ISSUE TITLE
Object search doesn't find  table names starting with capital letters

### ISSUE THREAD

**Issue by lajerca** [dbeaver/dbeaver#21248]
### Description

Hi, in my db I have some table names lowercase (snake_case) and other tables with uppercase initials (a mix of snake_case and PascalCase, like Table_Example).
Only lowercase table names are found in Object search

### DBeaver Version

Community Edition 23.2.0

### Operating System

Ubuntu 23.04  - Kernel Linux 6.2.0-32-generic

### Database and driver

DB = docker image mysql:8.0
CONNECTOR =  com.mysql.cj.jdbc.Driver (mysql-connector-java-8.0.29.jar)

### Steps to reproduce

1. Create 2 tables: `table_example` and `Table_Example`
2. Navigate > Open Database Object  (CTRL+SHIFT+D)
3. type `table` or `Table`

result: `table_example` is found but `Table_Example` is NOT found (with both inputs)

Interestingly if I search for "_" (underscore) both results appear

### Additional context

similar to this issue:
https://github.com/dbeaver/dbeaver/issues/1232

but with MySQL

**Comment by LonwoLonwo** [comment]
Related ticket: https://github.com/dbeaver/dbeaver/issues/9049

**Comment by LonwoLonwo** [comment]
Hello @lajerca 

As I understand, it can be related to the server setting https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

![2023-09-21 12_30_07-DBeaver Ultimate 22 3 2 - Address_Binar](https://github.com/dbeaver/dbeaver/assets/45152336/5becb7c4-e0f5-4f7c-8b25-9b8f5bdf2725)

![2023-09-21 12_30_22-DBeaver Ultimate 22 3 2 - Address_Binar](https://github.com/dbeaver/dbeaver/assets/45152336/5aaa666c-7c6d-4774-bf06-a36a5cc694e1)

Could you please provide your lower_case_table_names value?


![2023-09-21 12_34_10-DBeaver Ultimate 22 3 2 - Session Variables](https://github.com/dbeaver/dbeaver/assets/45152336/ab0254fd-2317-43e8-824d-4a83519dd8fc)

**Comment by lajerca** [comment]
Hi @LonwoLonwo, it is `0` (zero)
![image](https://github.com/dbeaver/dbeaver/assets/47744877/a93f6f4a-ba5a-4192-9a97-fed06449f965)

**Comment by LonwoLonwo** [comment]
Could you please check your [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) with enabled filters during the search operation?

Your query will be like:

`SELECT TABLE_SCHEMA,TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME LIKE 'test%' AND TABLE_SCHEMA = 'test' ORDER BY TABLE_NAME LIMIT 1000`

Could you provide your query?

**Comment by lajerca** [comment]
sure, here you go

```sql
SELECT TABLE_SCHEMA,TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME LIKE 't%' ORDER BY TABLE_NAME LIMIT 1000
```
I don't see a query with 'test%'  though, even if I type `test` in the search input, only the first letter seems to be used in the query. But maybe it is the expected behaviour for performance since subsequent searches are subsets of the initial search?

Anyway... I played with the SQL Editor and manually running the query with capital letter like 

```sql
SELECT TABLE_SCHEMA,TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME LIKE 'T%' ORDER BY TABLE_NAME LIMIT 1000
```

actually returns the table names as expected.
**However when using Object search the input is lowercased**, thus not returning table names.

_____

After playing around a little bit more I found out that with `'t%'` if I override the collation like this, I get the same results as with `'T%'`.

```sql
SELECT TABLE_SCHEMA,TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME COLLATE utf8mb3_general_ci  LIKE 't%'  ORDER BY TABLE_NAME LIMIT 1000
```

after inspecting `information_schema` properties I noticed column `TABLE_NAME` has a default collation `utf8mb3_bin`, probably that's why the search is not case insensitive.

Provided that this is the issue, I am not sure what should be fixed though, if the input being converted to lowercase or the collation of column `TABLE_NAME`


just for reference I had a look here for collation searches..
https://dev.mysql.com/doc/refman/8.0/en/charset-collation-information-schema.html

**Comment by MashaKorax** [comment]
Thanks for the report!

**Comment by E1izabeth** [comment]
Case from #21257
>When the database table name is uppercase, you cannot press and hold the Ctrl key to click the table name directly in the SQL editor。But if you add the database name, you can click on it again

![image](https://github.com/dbeaver/dbeaver/assets/43339563/4c66fe8e-2e21-40aa-9112-78c375ff63f2)

**Comment by E1izabeth** [comment]
Was fixed in the linked PR.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/52f2e0cd-9b3b-4ff6-87af-35dd0821d21c)

**Comment by E1izabeth** [comment]
Fix will be available in DBeaver 23.3.3 version.
If you find out that it's still reproducible, please let me know.

**Comment by lajerca** [comment]
> Fix will be available in DBeaver 23.3.3 version. If you find out that it's still reproducible, please let me know.

It is still reproducible

![image](https://github.com/dbeaver/dbeaver/assets/47744877/bee0201a-9d1a-40d4-a8bb-2ab36e55b357)

**Comment by E1izabeth** [comment]
What MySQL version do you use?

**Comment by lajerca** [comment]
> What MySQL version do you use?

MySQL 8.0

**Comment by LonwoLonwo** [comment]
Just to check my thoughts, could you please execute this query:

```sql
SELECT TABLE_SCHEMA,TABLE_NAME 
FROM information_schema.TABLES 
WHERE TABLE_NAME  LIKE BINARY  't%'  
ORDER BY TABLE_NAME LIMIT 1000
```

Does it work in your case? (Without collation part and with BINARY instead)

**Comment by lajerca** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/47744877/da86fa69-21b5-4d4c-a97b-4cf81a454e0a)

nope, only table_Test is found but not TableA and TableB

**Comment by lajerca** [comment]
however the opposite happens if I do like this instead
```sql
WHERE TABLE_NAME  LIKE BINARY  'T%' 
  ```
  
![image](https://github.com/dbeaver/dbeaver/assets/47744877/a49c59b2-4a2e-42c4-8761-3de9218d7666)

**Comment by LonwoLonwo** [comment]
Sad...
Because I do not want to use the `COLLATE utf8mb3_general_ci` workaround. It is too specific. Not for our multiple MySQL/MariaDB versions tool.

Ok, and how about the case from the documentation?

```sql
SELECT TABLE_SCHEMA,TABLE_NAME 
FROM information_schema.TABLES 
WHERE UPPER(TABLE_NAME)  LIKE 'T%'  
ORDER BY TABLE_NAME LIMIT 1000
```

**Comment by lajerca** [comment]
this actually works, all three tables are returned. User input should be uppercased too though

**Comment by informatik01** [comment]
Related discussion: [Tables are not found if their names are in upper case](https://github.com/orgs/dbeaver/discussions/22580#discussion-6128580).
