### ISSUE TITLE
Problem with memory/GC while doing DB migration. 

### ISSUE THREAD

**Issue by pdelteil** [dbeaver/dbeaver#2125]
I'm doing a database migration from Oracle tables to SQL Server tables. Two of the three tables were successful during the first try, mostly because they didn't have that many rows as the third (about 3,5 million rows with around 30 columns). I took me around 15 attempts to accomplish the migration process, because Dbeaver use all the RAM available (around 14 GB).

Migration using 10.000/100.000 segments, CPU use to 100% for many minutes, Dbeaver crashed because the JVM use all assigned memory.
After increasing the JVM memory to 14 GB, migration crashed because the system didn't have more RAM available.

I did change the segment size many times with no results. I ended up using the 'direct Query' and after 1,5 hours it finished successfully.

The question is: Why Dbeaver keeps using RAM without GC cleaning it? How can I change the beauvoir of the GC to be more 'eager'?

Thanks.

**Comment by serge-rider** [comment]
Short answer: DBeaver shouldn't consume so much memory.
Long answer: everything depends on configuration.

Oracle supports results streaming so you don't need to use cursors at all. Use "Single query" export.
Also you should disable transactions (set connection to auto-commit mode) - this will improve performance.
In such configuration export of 1 million rows takes just a few seconds.
However import of rows in SQL server maybe much slower.

In any case even export by segments shouldn't consume much memory. What Oracle driver do you use?

**Comment by pdelteil** [comment]
Hello there,

Thanks for replying. I guess the main problem with the migration itself is that memory is not clean/release. Each time I tried to migrate the database the amount of RAM used increase, the only way to clean it was to restart the app. I think GC (garbage colletion)  should have clean them after a while, since those objects were only used to attempt the migration process.

**Comment by serge-rider** [comment]
In our test environment memory is always released (you can monitor this in heap status - it can be enabled on Preferences->General page).
However this can be a system-specific bug. 
What is your OS?

**Comment by pdelteil** [comment]
I'll try again in a few weeks. I'm using Ubuntu 17.04.

**Comment by serge-rider** [comment]
Ok, thank you.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. Perhaps, this problem was solved. However, if you think that it is actual just let us know.

**Comment by niben-singh** [comment]
Looks like this is a problem when data transfer is done using transaction on both source and destination. I tried with transaction with fetch size of like 10000 from Oracle source to destination. It appears the memory consumption used keeps increasing and eventually heap runs out of space.

Using single query and no transaction like serge-rider mentioned seems to work well.

I am using Windows 10. The total rows was about 9 million.

**Comment by assismauro** [comment]
Windows dBeaver still showing this "Java heap space" error in import tasks.

I'm using Version 21.1.0.202106012023.
