### ISSUE TITLE
Stalls when accessing a large number of tables

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#2152]
When I try to open the database and list tables (about 7000 tables in the DB), on Ubuntu 16.04.3 LTS, the program stalls. 

Here is the terminal output from when starting the program:
```
$ dbeaver

2017-09-15 14:03:51.635 - Create display
2017-09-15 14:03:51.770 - DBeaver 4.2.0 is starting
2017-09-15 14:03:51.771 - Install path: '/usr/share/dbeaver'
2017-09-15 14:03:51.771 - Instance path: 'file:/home/benyanke/.dbeaver4/'
2017-09-15 14:03:51.771 - Memory available 77Mb/910Mb
2017-09-15 14:03:51.779 - Starting RMI server at 51628
2017-09-15 14:03:51.859 - Run workbench
2017-09-15 14:03:53.352 - Initializing DBeaver 4.2.0
2017-09-15 14:03:53.359 - Host plugin: org.jkiss.dbeaver.core.application 4.2.0
2017-09-15 14:03:53.362 - Initialize Core...
2017-09-15 14:03:53.513 - Core initialized (151ms)
2017-09-15 14:03:53.518 - Configure workbench window
2017-09-15 14:03:53.598 - Create actions
2017-09-15 14:03:53.603 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2017-09-15 14:03:53.607 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2017-09-15 14:03:53.974 - Initialize workbench window
2017-09-15 14:03:53.988 - Finish initialization
2017-09-15 14:03:55.723 - Connect with '[redacted: database name]' (mssql_ms-15e862216e2-1a754ec176f9da15)
2017-09-15 14:03:56.117 - Connected (mssql_ms-15e862216e2-1a754ec176f9da15, Microsoft JDBC Driver 4.0 for SQL Server [4.0.2206.100])
```

EDIT: Also found the -debug option:

```
$ dbeaver -debug 

Install location:
    file:/usr/share/dbeaver/
Configuration file:
    file:/usr/share/dbeaver/configuration/config.ini loaded
Configuration location:
    file:/home/benyanke/.eclipse/org.jkiss.dbeaver.product_4.2.0_620785679_linux_gtk_x86_64/configuration/
Configuration file:
    file:/home/benyanke/.eclipse/org.jkiss.dbeaver.product_4.2.0_620785679_linux_gtk_x86_64/configuration/config.ini loaded
Loading timestamp file from:
	 file:/home/benyanke/.eclipse/org.jkiss.dbeaver.product_4.2.0_620785679_linux_gtk_x86_64/configuration/   .baseConfigIniTimestamp
	No timestamp file found
Timestamps found: 
	 config.ini in the base: 1504466020000
	 remembered -1
Shared configuration location:
    file:/usr/share/dbeaver/configuration/
Framework located:
    file:/usr/share/dbeaver/plugins/org.eclipse.osgi_3.11.3.v20170209-1843.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.200.v20160504-1419.jar
	eclipse.properties not found
Framework classpath:
    file:/usr/share/dbeaver/plugins/org.eclipse.osgi_3.11.3.v20170209-1843.jar
    file:/usr/share/dbeaver/plugins/
    file:/usr/share/dbeaver/plugins/org.eclipse.osgi.compatibility.state_1.0.200.v20160504-1419.jar
Splash location:
    /home/benyanke/.eclipse/org.jkiss.dbeaver.product_4.2.0_620785679_linux_gtk_x86_64/configuration/org.eclipse.equinox.launcher/org.jkiss.dbeaver.core.application_4.2.0/splash.bmp
Debug options:
    file:/home/benyanke/vagrant-boxes/grandcentral/.options not found
Time to load bundles: 3
Starting application: 574
2017-09-15 14:10:38.288 - Create display
2017-09-15 14:10:38.428 - DBeaver 4.2.0 is starting
2017-09-15 14:10:38.429 - Install path: '/usr/share/dbeaver'
2017-09-15 14:10:38.429 - Instance path: 'file:/home/benyanke/.dbeaver4/'
2017-09-15 14:10:38.429 - Memory available 77Mb/910Mb
2017-09-15 14:10:38.437 - Starting RMI server at 22143
2017-09-15 14:10:38.512 - Run workbench
2017-09-15 14:10:40.139 - Initializing DBeaver 4.2.0
2017-09-15 14:10:40.168 - Host plugin: org.jkiss.dbeaver.core.application 4.2.0
2017-09-15 14:10:40.173 - Initialize Core...
2017-09-15 14:10:40.389 - Core initialized (216ms)
2017-09-15 14:10:40.411 - Configure workbench window
2017-09-15 14:10:40.523 - Create actions
2017-09-15 14:10:40.530 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2017-09-15 14:10:40.534 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2017-09-15 14:10:41.046 - Initialize workbench window
2017-09-15 14:10:41.069 - Finish initialization
Application Started: 4479
2017-09-15 14:10:42.948 - Connect with '[redacted: database name]' (mssql_ms-15e862216e2-1a754ec176f9da15)
2017-09-15 14:10:43.477 - Connected (mssql_ms-15e862216e2-1a754ec176f9da15, Microsoft JDBC Driver 4.0 for SQL Server [4.0.2206.100])
```

**Comment by benyanke** [comment]
I also know it's likely not a server issue, the windows client works fine with the same config.

**Comment by serge-rider** [comment]
Does `Stalls` mean UI freeze?

- If so - could you make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) when DBeaver will freeze next time?
- Does this happen always or only with come particular databases?

**Comment by benyanke** [comment]
Yes, freezing, and as Ubuntu applications do when they freeze for more than a second or two, the entire app grays out.

I will take a dump on Monday and collect more information.

I haven't tested on a bunch of databases, only the one MS-SQL db. I have access to some MySQL databases, so I will try those.

The windows version, however, I was able to connect to the same database with no issues, by the way.

**Comment by benyanke** [comment]
Dump:
[dump.txt](https://github.com/serge-rider/dbeaver/files/1311673/dump.txt)

**Comment by benyanke** [comment]
Just confirmed that it does *not* stall when accessing a MariaDB/MySQL database.

**Comment by serge-rider** [comment]
Looks odd. UI freezes on tree item (native OS components) creation.
Is there anything special about your MS SQL databse? Maybe a lot of tables or some weird table names with special characters?

**Comment by benyanke** [comment]
Yes, it is quite a large database, on the order of hundreds-of-millions of records and hundreds of tables. Not sure about all the table names, I'm inheriting the database, so I haven't fully scrubbed it yet, but I do know there are spaces and `$` in most, if not all of the tables. If it's any assistance, it's the underlying storage for a Microsoft Navision 2013 R2 instance.

The thing that struck me as odd was that it worked instantly on the Windows version...

**Comment by serge-rider** [comment]
This seems to be GTK specific and this is a kind of SWT bug (sometimes it hangs on huge trees).
Similar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=354842 or https://bugs.eclipse.org/bugs/show_bug.cgi?id=383733.

Probably it is fixed in Eclipse 4.7 (we are going to migrate DBeaver to it after 4.3 version or you can try Eclipse plugin version in the most recent Eclipse 4.7). 
Also you can try workaround proposed in 354842 bug.  Execute
```
export SWT_WEBKIT2=1
export SWT_LIB_VERSIONS=1
```
before running DBeaver from console.

**Comment by serge-rider** [comment]
Could you test this on the recent DBeaver version (it is based on Eclipse 4.7)?

**Comment by benyanke** [comment]
Yes, still occurs on [4.2.3](https://github.com/serge-rider/dbeaver/releases/tag/4.2.3).

**Comment by serge-rider** [comment]
That's bad. Means 4.7 doesn't fix this. However bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=383733 is still open.
Could you say what window manager do you use? Any other details?
Trying to figure out how to reproduce this.

**Comment by benyanke** [comment]
I'm using a pretty standard unity setup on Ubuntu 16.04 LTS... Lmk if there's any other info that would be helpful.

**Comment by mmceldowney** [comment]
I'm having the same issue, version 4.2.5 on Linux Mint 8, Cinnamon desktop.  Microsoft SQL, latest java driver, database with 9888 tables.  I would prefer NOT to have to work in Windows, if I have to do that then I may as well use the Microsoft tools for this and don't need DBeaver at all.

**Comment by serge-rider** [comment]
@mmceldowney GTK + some particular hardware (drivers) seems to be the reason. UI hangs during tree control population. I still have no ideas how to solve this.

And yes, workaround you described will solve the issue, thanks for noticing.

**Comment by benyanke** [comment]
Not a resolution, but a potential workaround: use filters to shorten the list of tables.

Our DB has a structure of about 1500 tables with a prefix in the table name of app1_, another 1500 tables for app2_, for a total of about 7000 tables. However, I'm only developing using the app1 tables, so I set up a filter like so:

![image](https://user-images.githubusercontent.com/4274911/33958002-de51a936-e008-11e7-9b96-18ca8611dd6c.png)

This means the app only has to (apparently?) load info about 1500 tables. It's far from a work around, and the app still stalls for 2-3 seconds, but it does now load, making the app usable for this specific usecase. 

Not a solved problem by any means, but perhaps a workaround usable for some users, depending on their workload and DB structure. 

Do keep a windows VM around if you need to access other tables not matching that filter though...

**Comment by geraldodev** [comment]
For me It happens with ubuntu 16.04 with xfce with oracle with more than 3100 tables about 800 views and 6000 indexes

**Comment by brightball** [comment]
Same problem here on Ubuntu 18.04 on a large Postgres database.

**Comment by serge-rider** [comment]
Since 5.2 you can configure how many objects should be visible in the navigator tree:
![image](https://user-images.githubusercontent.com/6398845/45914416-c152fa00-be4d-11e8-904b-227aacdafa46.png)

Hint: you can view all objects in schema editor (double click on "Tables" element). It is much more convenient than navigator tree.
