### ISSUE TITLE
Can't restore tables tabs after start

### ISSUE THREAD

**Issue by manuel-molina** [dbeaver/dbeaver#22936]
### Description

I upgrade DBeaver to last version, its was ok when started first time restoring all tabs, but when close application an started it again all my tabs "fails trying to get a new connection to db2". It never happend with previous releases. It only happend in tables tabs, in scripts tabs it works.

When I select a table tab I see it in place of:

> Navigator node 'node://General/datasources/Testing/db2-18dc28e2a58-4ae5ca11711259cd/schema/LIVEBET/table/LIV_T_APUESTA' not found
> 
> Possible reasons:
>  - The connection view was changed
>  - The object this editor was opened for no longer exists in the database

then I need to close the tab and reopen it before start to work again. In error log I have the following:

> Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

> No se encuentra el rastreo de pila de la excepción.

> eclipse.buildId=unknown
> java.version=17.0.6
> java.vendor=Eclipse Adoptium
> BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=es_UY
> Framework arguments:  -eclipse.keyring /home/desarrollo/.local/share/DBeaverData/secure/secure_storage
> Command-line arguments:  -os linux -ws gtk -arch x86_64

Image after open a table from database navigator
![image](https://github.com/dbeaver/dbeaver/assets/25434775/1fbe0316-6c59-4018-953d-6243c745614b)

The same table after restart Dbeaver
![image](https://github.com/dbeaver/dbeaver/assets/25434775/3ab5f752-7384-491f-aab8-b4e36c78cf87)

in my Preferences I change "Abrir una conexión separada para cada editor" to "Always" with no success
![image](https://github.com/dbeaver/dbeaver/assets/25434775/84b24ffb-059c-46bc-92e0-5f1528c7fdc9)

### DBeaver Version

Community Edition 23.3.5

### Operating System

Ubuntu 22.04.3 LTS

### Database and driver

DB2 9.5
Driver: BD2 fro LUW {Group: com.ibm.db2, Artifact: jcc, version: 11.5.9.0}
jcc-11.5.0.0.jar

### Steps to reproduce

1. Create a connection with Db2 for Luw to a database
2. Open a table to view data/structure
3. (optional) Create a new Script in this conection and put some valid sql and exec it 
4. Close Dbeaver
5. Start dbeaver again, the table tab shows an error but script function with no problem

**Comment by LonwoLonwo** [comment]
Hello @manuel-molina 

Could you please check the latest DBeaver Early Access version? https://dbeaver.io/files/ea/
I hope that this case is fixed here: https://github.com/dbeaver/dbeaver/issues/22655

**Comment by manuel-molina** [comment]
I download it, close and drop my DBeaver instance an install Early Acces version but the problem is still here
![image](https://github.com/dbeaver/dbeaver/assets/25434775/b11e5a73-a9cb-42ce-bfdc-9e895ca92351)

It only happend with tables, scripts works, maybe the problem is in datasources config?

> {
	"folders": {
		"Local": {},
		"Testing": {},
		"Testing": {
			"parent": "Testing"
		},
	},
	"connections": {
		"db2-18dc28e2a58-4ae5ca11711259cd": {
			"provider": "db2",
			"driver": "db2",
			"name": "T1LIVEBE",
			"save-password": true,
			"folder": "Testing/Testing",
			"configuration": {
                ...
			}
		},
	},
}

> org.jkiss.dbeaver.DBException: Navigator node 'node://General/datasources/Testing/**db2-18dc28e2a58-4ae5ca11711259cd**/schema/LIVEBET/table/LIV_T_OPCION_APUESTA' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:312)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:171)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ShadelessFox** [comment]
Hello @manuel-molina,

Can you confirm that you did reopen tabs after installing a new version and before restarting DBeaver to see if the issue is gone?

**Comment by manuel-molina** [comment]
I think there is somenthing wierd obtaining connections. In scripts the combobox show me all connections I have. In table I have two views, both without any connection info.

**--- Combobox connectios whe select one of my scripts ---**
![image](https://github.com/dbeaver/dbeaver/assets/25434775/cc0af599-72fd-42d4-aa87-d512be873567)

**--- Combobox and table view after start DBeaver ---**
![image](https://github.com/dbeaver/dbeaver/assets/25434775/f58c483d-a18e-4a5c-8e55-c9fd5378685d)

**--- Combobox and table view after I select it in database navigator ---**
![image](https://github.com/dbeaver/dbeaver/assets/25434775/fb921083-9260-4317-80cf-6994bb69ebf1)

**Comment by manuel-molina** [comment]
I reopen LIV_T_APUESTA tab as show in last image. Now, when open the connections combobox show only one for table, but scripts show me all connections like first image in previous post. After reopen tab, I restart application and table show me data, but combobox remains with then problems, or its the default behaviour?

**Comment by ShadelessFox** [comment]
Hello @manuel-molina,

Can you please try installing the latest version (24.0.1) to see if the issue is gone there? https://dbeaver.io/download/

**Comment by manuel-molina** [comment]
I test it with 24.0.2 and now the problem disappear.

**Comment by LonwoLonwo** [comment]
Thanks for the update @manuel-molina 

I'm closing this ticket.
If this issue happens again, please write here or create a new ticket.

**Comment by zardojunior** [comment]
Same issue here:
Navigator node 'node://General/datasources/postgres-jdbc-18ededb6011-472ad2480a111f6b/database/COMMERCEDB_16394/schema/public_1341732/table/torderpaymentdata_1344808' not found

Possible reasons:
 - The connection view was changed
 - The object this editor was opened for no longer exists in the database

I'm using version 25.1.2
