### ISSUE TITLE
Canceling the query takes forever

### ISSUE THREAD

**Issue by antonyr** [dbeaver/dbeaver#3094]
![image](https://user-images.githubusercontent.com/539454/37041455-47d1020c-2182-11e8-906b-98695a97c2a0.png)

My DB is on VPN. I accidentally hit execute query, later I came to know I didn't connect to VPN. Now I decide to cancel the query in execution. I cancelled it, but still it can't cancel it. It takes forever now, before it can stop execution.

**Comment by MarcinWieczorek** [comment]
Confirmed. Is there a solution?

**Comment by alex-ant** [comment]
Same thing when working with local databases.

**Comment by serge-rider** [comment]
IT is a bug in 5.2.2, will be fixed in 5.2.3 (fix is already in Early Access - https://dbeaver.io/files/ea)

**Comment by cloud-66** [comment]
Hello, i use dbeaver for oracle database, but cancellation of query don't working. I see thig bug in version 5.2.5 . it was not fixed in 5.2.3, i don't see any imrovements.
I like this apps but some problems are very frustrating.
![screenshot_1](https://user-images.githubusercontent.com/41143306/48962151-490fce80-ef8d-11e8-81ea-59d4ec3e248c.png)

**Comment by reichg** [comment]
Confirmed cloud-66s observation that this bug still exists in 5.2.5. If you try to cancel a long running query it will not cancel unless you close dbeaver.

**Comment by MFernstrom** [comment]
Still happening in 5.3.4 (Feb 3, 2019 release)

**Comment by jordanmat** [comment]
Still happening in 6.0.0.201903101945

**Comment by drmaquino** [comment]
still happening in version 6.0.3 ......

**Comment by Dania02525** [comment]
Still a problem in 5.3.3:

**Comment by suricat89** [comment]
Same problem here with Oracle Database on Dbeaver 6.1.1.201906240635

**Comment by larvinloy** [comment]
Same issue with RedShift queries. Redshift console shows that the query has already been cancelled, but DBeaver is still stuck trying to cancel the query. Occasionally it causes the app to crash.

**Comment by namansachdeva** [comment]
Still happening in 6.1.4

**Comment by serge-rider** [comment]
See #3616
Generally query cancel support is provided by database driver.
Some drivers just don't support it. We can't fix it from DBeaver side :(

**Comment by namansachdeva** [comment]
Force quiting DBeaver and restarting it solves the problem. It reconnects
the database. Maybe a hack to resolve the problem?

**Comment by rdp** [comment]
See also https://github.com/dbeaver/dbeaver/issues/6755

**Comment by barretod** [comment]
This is still broken on 6.2.3, very annoying.

**Comment by DanielWFrancis** [comment]
still broken interfacing with postgres 11 on AWS RDS

**Comment by anveshragi** [comment]
This is still happening on 6.2.5 with AWS Redshift as source

**Comment by mikkk3l** [comment]
Still happens in 6.3.2 with ojdbc7.jar

**Comment by jedeleh** [comment]
Same. Honestly I've always had this issue but it wasn't until recently that the "cancel query" spun forever until I restart dbeaver

**Comment by janpxr** [comment]
Same issue with:
dbeaver-ce-6.3.5-x86_64
and
dbeaver-ce-7.0.0-x86_64

Even in the cases where query never gets to the database or has finished really quick there and for some reason Dbeaver does not get the error/resultset back before you click the "Cancel" button then it will keep showing that it is executing. Example:
![image](https://user-images.githubusercontent.com/17978580/75985725-7455cd00-5ef5-11ea-98fb-eea2e0650182.png)

So it is not related to the database drivers and issues in those cases, just the Cancel button hangs and there is nothing else you can do with it than restart Dbeaver.

This kind of issue over several versions and in 2020, really?

**Comment by TimonKK** [comment]
Same issue with dbeaver-ce-7.0.1-x86_64 on Ubunti 19.10

**Comment by archismandinda** [comment]
Issue still persists in Version 7.0.0.202003021717.

The greater issue here is that if there is a valid long running query which you want to cancel, even if you close DBeaver and restart the app, the query still keeps getting executed on the database. 
Restarting DBeaver doesn't actually kill the query.

So many times I get flagged by my DB Admins because some long running query would be running even though I would have thought that they got cancelled since I restarted DBeaver.

**Comment by disk-edit** [comment]
Issue still in latest stable build.
Running 7.0.3.202004191823 on Ubuntu 18.04

**Comment by akbarumar88** [comment]
Issue still persis in 7.0.3 it was really annoyying, do you guys have another recommendations for multi DBMS Database tool?

**Comment by janpxr** [comment]
@archismandinda the initial issue here is not about getting the database session killed (as in the described case the VPN was not connected then the query never got to the database anyway; to get you database sessions killed then there are separate issues for that; also if in your case the sessions stay active on the database side then it might not be DBeavers fault - it might be also be in the JDBC driver, network issues etc.).

So lets just keep the issue here concentrated to the issue that if I hit the cancel button then the expected result is at least that I would not need to restart the DBeaver application.

@akbarumar88 there are many such tools around SQuirreL SQL Client, DbVisualizer, DataGrip etc. All of them have issues alongside with great functionality. Still DBeaver is i general great tool, just then with its own issues.

**Comment by joshcrichman** [comment]
Can we please un-close this issue?  It's clearly not resolved in any way.  Definitely still an issue for me.  Always has been and feels like always will be...

**Comment by serge-rider** [comment]
Well, it is tricky.

Cancel works for PostgreSQL, MySQL, some Oracles and for some other databases.
It doesn't work for, e.g., Redshift, some Oracle, etc.

Cancel must be supported by the database server and by the driver. We can't perform cancel on client side.
For drivers which don't support cancel we wait several seconds and then try to disconnect. It works for some drivers as disconnect cancels any active queries.
But some other drivers (e.g. Redshift) don't allow to disconnect when a query is running. It just hangs in a mutex.
For some databases even restarting client application doesn't help. They just do not support query interruption at all. Once started query will run until client session will be terminated by admin or server will be restarted.

If you have any ideas or any workarounds on mind - please share or create a new ticket. 

Probably this should be resolved for particular databases individually in separate tickets.

**Comment by mpaloni** [comment]
Facing the issue with Redshift.

Would it be possible to crash only the connection if the query takes too long(or connection is on redshift database) and then restoring it? For example RStudio  & jupyter notebook has the kernel running as seperate and that can be restarted as many times as you want without crashing the application itself.

(This suggestion comes with 1% of knowledge about dbeaver)

**Comment by andrewkp101** [comment]
Dbeaver MySQL has this issue still.  

Just for example MySQL Workbench with the same query and same database cancels correctly.

By doing
show full processlist

I can still see this process "Sending data"

Given that MySQL Workbench works fine in cancelling an active mysql query suggests Dbeaver might be improved.

**Comment by carlosfg97** [comment]
As many people mention, this is obviously an ongoing issue that bothers a lot. Are we going to receive any news from the developers?

**Comment by zsaltys** [comment]
This is a very annoying issue. Would be great if devs would acknowledge it. Having a way to force kill all background tasks would be good enough.

**Comment by uslss** [comment]
Issue has been fixed in scope of 7.1.3 
#9121

**Comment by joshcrichman** [comment]
It said it was fixed in the 7.1.2 release notes.  Definitely was not for me
using Redshift.  I was supremely disappointed.
[image: image.png]

**Comment by joshcrichman** [comment]
See above - still having issues with this using Redshift (and maybe others, since other people are still complaining).  Can we open this ticket again, please?

**Comment by uslss** [comment]
@joshcrichman , could you create a new ticket with more detailed description of the problem you're observing? 
Thanks in advance :)

**Comment by joshcrichman** [comment]
Sure, though it's exactly the same as the many other tickets already filed,
and I don't want to lose all the people that have commented here and
elsewhere to show how relevant it is.

**Comment by jpierre** [comment]
I also have the same issue with Redshift

**Comment by yuhadooper** [comment]
I've been facing the same issue with redshift/dbeaver from the past 3 years!

**Comment by nguyenvinhlinh** [comment]
August 4, 2020, I got this issue. Please help.

**Comment by pfeiffee** [comment]
Does anyone know if there are any workarounds like driver properties and timeouts that could be set to at least be able to get away with waiting a minute instead of force killing dbeaver?

**Comment by christopher-bonitz** [comment]
Used to have the same issue (since I always connect to client systems through VPN) but in recent 7.2 the problem is gone.
If someone could re-test, to see if this issue is still valid, it would be helpful I think.

**Comment by andrewkp101** [comment]
Previously I had more luck with native as opposed to java drivers, however I did not test this heavily and am not using dbeaver at the current time.  I think anyone facing this problem should try a stable native driver and see if it improves the situation.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by disk-edit** [comment]
I have had this same issue for many versions with queries run against AWS RDS MariaDB and AWS Redshift.

Now I am running DBeaver 7.2.0 with RedshiftJDBC42-no-awssdk-1.2.45.1069.jar in play. I was able to immediately cancel queries run against AWS Redshift. I also had success canceling queries against AWS RDS MariaDB.

Great progress! Thank you.

**Comment by joshcrichman** [comment]
I just upgraded to 7.2.  Will try it out for a week or so and report back.

**Comment by uslss** [comment]
fixed in 7.2

**Comment by yuhadooper** [comment]
Yep, finally fixed in the 7.2

**Comment by mikkk3l** [comment]
Thank you very much! It is fixed un 7.2 with a workaround which is to close the connection y cancel doesn't ack within a timeout period.

There is a little detail still. If you close the connection then the blue arrows show the query as it were still executing:

This is not a big deal, just a graphic bug.

But if, at that point, you try to export a query to CSV it fails saying that you can't excecute simultaneous queries and you are not. The only workaround is exceute another query and, when it finishes, you can then export a query result.

Could you please fix this issue? Thanks!

**Comment by givihuda** [comment]
I'm not even seeing where to cancel... it's just counting up an Executing timer, nothing I do cancels it except closing DBeaver and my database program.

**Comment by francescosalvi** [comment]
(running Version 22.2.5.202211202223) 

whenever I forget to re-establish a _lost_ VPN connection before (mistakenly) launching a query using an _open_ (at least in the eyes of dbeaver) connection based on the aforementioned VPN, I get softlocked in the application. Cancelling doesn't do anything, just hangs like the original query execution.

![image](https://user-images.githubusercontent.com/17246673/204473451-0b9c68ce-99e8-409c-be51-39cfde172ba9.png)

Oftentimes, if I quit the program with File > Exit, on next launch I get a "workspace locked" exception, and the only solution is to `kill -9` any leftovers of the previous process.

**Comment by a-salimkhanov** [comment]
Had a similar problem now. If you were updating a table and changed many things and don't want to do that again.
You can just right click on Connection and select **Invalidate/Reconnect**.
Next select **Disconnect**
It will ask if you want to save changes on the table? Select "Yes". 
It worked for me.

**Comment by joelthelion** [comment]
For people using Oracle, this might be of interest: https://stackoverflow.com/questions/16918024/is-there-a-solution-to-jdbc-driver-bug-in-out-of-band-breaks
