### ISSUE TITLE
The server's DateStyle parameter was changed to ISO. The JDBC driver requires DateStyle to begin with ISO for correct operation.

### ISSUE THREAD

**Issue by warenix** [dbeaver/dbeaver#3562]
# Problem

I am having issue connecting to postgres DB (v9.4). A popup dialog showing
> The server's DateStyle parameter was changed to ISO. The JDBC driver requires DateStyle to begin with ISO for correct operation.

Changed format to **yyyy-MM-dd hh:mm:ss** still doesn't help. See below image:

![image](https://user-images.githubusercontent.com/1849536/40902991-71c29090-6808-11e8-9c8a-5eb9982bc09c.png)

I can confirm the postgresql database is set to have right __DateStyle__

```
me@localhost:rds> show DATESTYLE
+-------------+
| DateStyle   |
|-------------|
| ISO, MDY    |
+-------------+
SHOW
Time: 0.221s
```

# Environment
DBeaver Version 5.1.0 (June 4, 2018)
Ubuntu 18.04

**Comment by artemklevtsov** [comment]
Seems realted: pgjdbc/pgjdbc/issues/1080.

**Comment by warenix** [comment]
@artemklevtsov Great! Tested using pgjdbc 42.2.2  problem is resolved

**Comment by gallicht** [comment]
Hi Sorry but it's not working for me.
Using Latest DBeaver 6.0.1 with PostgreSQL driver 42.2.5

Can't change the Data Formatting in DBeaver or set the DateStyle parameter in PostgreSQL

**Comment by devyashish** [comment]
Hi,
Still facing this issue : _The server's DateStyle parameter was changed to Redwood, SHOW_TIME. The JDBC driver requires DateStyle to begin with ISO for correct operation_.

Using Latest DBeaver 6.0.5 with PostgreSQL driver 42.2.6
