### ISSUE TITLE
upgrades remove xmx and xms settings

### ISSUE THREAD

**Issue by DerPeterA** [dbeaver/dbeaver#35685]
### Description

every time I upgrade dbeaver, my xms and xmx settings are lost. they should not be lost.

### DBeaver Version

latest

**Comment by E1izabeth** [comment]
Thank you for report.
I'm closing this issue as a duplicate of #7727 #35391 #7546

**Comment by DerPeterA** [comment]
Hi @E1izabeth - thank you for the links to the 3 other items. But unfortunately I do not understand - how is this solved in the other items? They put a second dbeaver.ini into their home directory? Is that what I am supposed to do? Merci!

**Comment by E1izabeth** [comment]
The issue isn't solved. All linked issues are open. I closed this one to avoid duplication, because it's about the same as mentioned issues
