### ISSUE TITLE
FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta" from DBeaver 24.3.0 Community Edition

### ISSUE THREAD

**Issue by oureffort** [dbeaver/dbeaver#36487]
### Description

Hello Team,

I am trying to connect to a remote PostgreSQL database on a Ubuntu Virtual Machine from my local Windows 10 Laptop.

The settings on the PostgreSQL VM are perfectly fine and reflect the correct TimeZone and the Python test app is working fine and recording the correct timezone values for **Asia/Kolkata** (and **NOT Asia/Calcutta** which is the earlier name).

However, it fails to connect from the DBeaver with an error [FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"] while psql from remote system SSH also works fine.

I tried all possibilities including adding settings with TimeZone value in DBeaver but none of my attempts resolved the issue.

Please also see the attached screen grab to get a little more clarity on the issue.

Hope to get it resolved asap with your support.

Thanks in advance,
RK
![DBeaver TimeZone Issue](https://github.com/user-attachments/assets/d859aa3d-218a-4508-85f7-c87feebd009a)

### DBeaver Version

Community Edition 24.3.0

### Operating System

Local Windows 10 & Remote Ubuntu 17.2-1.pgdg24.04+1

### Database and driver

Remote VM: psql (PostgreSQL) 17.2 (Ubuntu 17.2-1.pgdg24.04+1)

Local: 
PostgreSQL standard JDBC Latest Driver.
Also, tried postgresql-42.7.4 on my Local system with DBeaver Driver Libraries

**Comment by bala-techguy** [comment]
I'm also having the same problem.

**Comment by LakhveerChahal** [comment]
Yes, I'm also facing the same problem when connecting to postgres hosted in WSL from Dbeaver installed in Windows.

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by E1izabeth** [comment]
As a workaround you can try changing driver version to some older one
You can do it this way
1. Open your `Connection setting` and press `Driver settings`
2. Go to the `Libraries` tab. select the driver artifact and press `Download/Update` 
3. Select a newer driver version in the list and press `Download.`
4. Press OK to close the `Driver settings` window and try connecting again

**Comment by SoumyajitD** [comment]
Also to add, I am using driver version 42.5.2 and while accessing I am facing this issue. Tested with PGSQL16.
Unable to reproduce with lower versions.

**Comment by oureffort** [comment]
> As a workaround you can try changing driver version to some older one You can do it this way
> 
> 1. Open your `Connection setting` and press `Driver settings`
> 2. Go to the `Libraries` tab. select the driver artifact and press `Download/Update`
> 3. Select a newer driver version in the list and press `Download.`
> 4. Press OK to close the `Driver settings` window and try connecting again

Thanks for the response and I tried this but, still, this did not work for me

**Comment by Destrolaric** [comment]
@oureffort We had a similar issue before. When you are using the timezone name that was added recently, it might lead to being unable to connect to Postgres. As a temporary workaround I would recommend using legacy timezone name for now.

**Comment by Destrolaric** [comment]
https://github.com/dbeaver/dbeaver/issues/18965 previous similar issue

**Comment by LakhveerChahal** [comment]
By changing the timezone here helped me as a workaround.

![image](https://github.com/user-attachments/assets/3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5)

Credits to @Destrolaric & https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795

**Comment by oureffort** [comment]
> By changing the timezone here helped me as a workaround.
> 
> ![image](https://private-user-images.githubusercontent.com/43540659/394338484-3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MjUxOTQsIm5iZiI6MTczMzkyNDg5NCwicGF0aCI6Ii80MzU0MDY1OS8zOTQzMzg0ODQtM2YxYTg3MTctNmNiMi00MWY0LTk2YTctNmFkNzM2Y2JlOGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDEzNDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NWUxODU5NmViODQ5YWMxMDNiNThjNzNhMjQ0MzVjN2VmZmE1ZGUxOWE5M2MxMTRiNWJlODQxNTdiNDUxODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1LK88WPKo8mOlxbWkhO8sYu8xdJwtcUWwlgD6qcDNdA)
> 
> Credits to @Destrolaric & [#18965 (comment)](https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795)

Thank You @LakhveerChahal this was helpful and solved the issue; 
And Thanks every one for the response and for now this problem is solved.

**Comment by E1izabeth** [comment]
Let's keep it open. We're going to fix it.

**Comment by bala-techguy** [comment]
> By changing the timezone here helped me as a workaround.
> 
> ![image](https://private-user-images.githubusercontent.com/43540659/394338484-3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NDM1NTAsIm5iZiI6MTczMzk0MzI1MCwicGF0aCI6Ii80MzU0MDY1OS8zOTQzMzg0ODQtM2YxYTg3MTctNmNiMi00MWY0LTk2YTctNmFkNzM2Y2JlOGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDE4NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZDZhZjNjMzgxNmZhYThmMTc2ZDhiZTY0MTMzMjkxYjdlOGU3ZDBiMmMyYWI2Yzc1MDM1MmFhMzk2ZWIzYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VLxp53Au955gD-sRIABtlmCz7u7KNaBEwxAhw9BQzCU)
> 
> Credits to @Destrolaric & [#18965 (comment)](https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795)

Thank you. This solution helped me.

**Comment by Destrolaric** [comment]
@bala-techguy @LakhveerChahal, I want to clarify a possible misunderstanding. You don't need to use the Kyiv timezone. You just need to set Asia/Kolkata as a timezone instead of the newer one.

**Comment by oureffort** [comment]
> Let's keep it open. We're going to fix it.

That's great, and yes it should be fixed.

**Comment by serge-rider** [comment]
Could you test the fix in Early Access version https://dbeaver.io/files/ea/

**Comment by sivadinesh1** [comment]
> Could you test the fix in Early Access version https://dbeaver.io/files/ea/

I tried, but still get the same issue, my dbeaver postgresal client is 14 whereas  postgresql installed in 16, will it be a reason for the issue

**Comment by oureffort** [comment]
I tried to test your Early Access Version release and got an error again, indicating my earlier settings as alternate fix were gone and the issue is back.  See the attached screen grab for ref.
![image](https://github.com/user-attachments/assets/57bf674b-bf11-4129-a90d-5ae6f4a693ee)

**Comment by oureffort** [comment]
And now it is not working with the Default timezone or setting it to 'Asia/Kolkata'. 
I need to revert to the earlier version which at least can work with Changing in TimeZone at the User Interface

**Comment by 2tku** [comment]
> By changing the timezone here helped me as a workaround.
> 
> ![image](https://github.com/user-attachments/assets/3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5)
> 
> Credits to [@Destrolaric](https://github.com/Destrolaric) & [#18965 (comment)](https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795)

thank @LakhveerChahal , it help me so much

**Comment by kirannchelak** [comment]
not working !!

**Comment by E1izabeth** [comment]
Please try DBeaver 24.3.5 version

**Comment by kirannchelak** [comment]
no i wrote this inside postgresql itself with config file but still calcutta thing is not changing to kolkata.

**Comment by ec2-learn-instant** [comment]
> By changing the timezone here helped me as a workaround.
> 
> ![image](https://github.com/user-attachments/assets/3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5)
> 
> Credits to [@Destrolaric](https://github.com/Destrolaric) & [#18965 (comment)](https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795)

It's working without any issues, Thanks  @LakhveerChahal

**Comment by shreyaskhamkar** [comment]
thank you this is working

**Comment by ankitsainigit** [comment]
This works for me and I think other can resolve this issue 
issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"

If you're using IntelliJ:
Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options)
In VM options, put:  -Duser.timezone=Asia/Kolkata

thanks

**Comment by shubh1978** [comment]
> This works for me and I think other can resolve this issue issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"
> 
> If you're using IntelliJ: Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options) In VM options, put: -Duser.timezone=Asia/Kolkata
> 
> thanks

thanks worked for me

**Comment by Navichinnu** [comment]
Most of this type of issues coming in AMD architecture systems
so need to symlink.

check below things

timedatectl
ls -l /usr/share/zoneinfo/Asia/ | grep Calcutta
It should have sym link like below
lrwxrwxrwx 1 root root   32 Aug 11 09:51 Calcutta -> /usr/share/zoneinfo/Asia/Kolkata

If symlink is not there, then run below cmd to get the sym link and restart postgres
sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /usr/share/zoneinfo/Asia/Calcutta
sudo service postgresql restart

**Comment by JohnVarkey** [comment]
Still not working even in 25.1.4

**Comment by Biraj-P** [comment]
> This works for me and I think other can resolve this issue issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"
> 
> If you're using IntelliJ: Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options) In VM options, put: -Duser.timezone=Asia/Kolkata
> 
> thanks

Thanks, worked for me. I am using PostgreSQL

**Comment by DataIndev** [comment]
> -Duser.timezone=Asia/Kolkata

thx a lot.!

**Comment by addy-core** [comment]
worked for me as well changed default timezone to Asia/Kathmandu previously it raised Asia/Katmandu for me. missing 'h'

**Comment by kgrajan12** [comment]
in latest version of DBeaver is selecting the time zone of **"Asia/Calcutta"** but _there is no timezone is available_ in postgres DB
that's why this error occur
All Please config **"Asia/Kolkata"** this is the valid one people from other countries will know their proper timezone's i think so
Thanks

**Comment by Reckadon** [comment]
> This works for me and I think other can resolve this issue issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"
> 
> If you're using IntelliJ: Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options) In VM options, put: -Duser.timezone=Asia/Kolkata
> 
> thanks

Worked for me, Thanks!
I am using PostgreSQL in a docker container and connecting with a Spring Boot application.

**Comment by RajvanshTML-11** [comment]
hii,can you please tell me what template did u use ?the templates can be seen on the left side of the edit configuratios window..i have options for gradle,application,junit etc but i dont know which template to use?i am getting the error in the project classes and also in the test cases ...would be really grateful if u could please help

**Comment by XuanNghi19** [comment]
> > By changing the timezone here helped me as a workaround.
> > ![image](https://github.com/user-attachments/assets/3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5)
> > Credits to [@Destrolaric](https://github.com/Destrolaric) & [#18965 (comment)](https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795)
> 
> It's working without any issues, Thanks [@LakhveerChahal](https://github.com/LakhveerChahal)


this solve my problem

**Comment by RajvanshTML-11** [comment]
what helped me was including the below property in the build.gradle.kts file.I was facing this issue while running the test cases and this adding this helped solve the probelm for me

tasks.test {
  systemProperty("user.timezone", "Asia/Kolkata")
}

**Comment by vinaykharayat** [comment]
> > > By changing the timezone here helped me as a workaround.
> > > ![image](https://github.com/user-attachments/assets/3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5)
> > > Credits to [@Destrolaric](https://github.com/Destrolaric) & [#18965 (comment)](https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795)
> > 
> > 
> > It's working without any issues, Thanks [@LakhveerChahal](https://github.com/LakhveerChahal)
> 
> this solve my problem

Thanks, this worked for me.

**Comment by knileshh** [comment]
Hey everyone,

I was building some basic Spring Boot apps and kept getting this error:

<img width="899" height="468" alt="Image" src="https://github.com/user-attachments/assets/dc09bd04-5077-4277-87cc-8c3c459bde98" /> 

I tried all the usual solutions checking my `application.properties`, adding `-Duser.timezone` flags to my run configurations, and even checking my Docker environment. Nothing worked. It turns out the issue was a bit more subtle, and it really took a lot of time to figure out\!

The problem was related to how Maven handles different lifecycle phases and plugins.

I'm using:

  * **Docker** to run a PostgreSQL database.
  * **Flyway** for database migrations.
  * **Maven** to build and test my application automatically.

When I ran `mvn clean install` or used IntelliJ's "Maven lifecycle test" option, Maven was calling the `maven-surefire-plugin` to run my tests. This plugin, by default, was not inheriting the timezone configuration I had set for the main application run. The JVM it started for the tests was defaulting to a timezone that the PostgreSQL JDBC driver translated to `'Asia/Calcutta'`, causing the connection to fail.

<img width="522" height="605" alt="Image" src="https://github.com/user-attachments/assets/2b800115-88f8-4470-93dd-48796793ed64" /> 

The fix was to explicitly configure the `maven-surefire-plugin` to use the correct timezone. This ensures that the system property is passed to the JVM during the test phase, allowing Flyway to connect and run migrations successfully.

Here is the exact code I added to my `pom.xml`:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <argLine>-Duser.timezone=Asia/Kolkata</argLine>
    </configuration>
</plugin>
```

This single change fixed the issue for me.

I hope this helps others who are new to Spring Boot and facing similar issues. Let me know by a reaction if this helped you\!

**Comment by aliyansayeed** [comment]
Add this plugin in your pom.xml this will resolve the issue >     
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>3.2.0</version> 
                <configuration>
                    <jvmArguments>-Duser.timezone=Asia/Kolkata</jvmArguments>
                </configuration>
            </plugin>

**Comment by Sabareesh98421** [comment]
> > This works for me and I think other can resolve this issue issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"
> > If you're using IntelliJ: Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options) In VM options, put: -Duser.timezone=Asia/Kolkata
> > thanks
> 
> Worked for me, Thanks! I am using PostgreSQL in a docker container and connecting with a Spring Boot application.

Sir, please share your understading about this issue and it's solution cause i have this error for 3 days 
please sir

**Comment by knileshh** [comment]
@Sabareesh98421 Can you give me more context? What IDE are you using are you using maven? Are you manually buildling your app? Any screenshots will also be helpful.

**Comment by Sabareesh98421** [comment]
@knileshh  Hi bro,I using eclipse,actually it is an internal application so I can't share any screen shots, so I am sorry , but I barely solved the Time Stamp but I can't solve the password authentication error from java to docker,IDK what caused that issue ,I tried the everything that I know , I am beginner in cyber security, so In my office I do the config mostly for any projects,I tried another container to connect the db it connects but from spring boot I can't , my dev friend also have no idea about this can you guys please help on this one ?



the log of spring that tries to connect is also not being logged,
but the same log from another container or from another computer spring boot it logs , 


i disabled the firewall and everything like antivirus and what so ever in my knowledge.



please Help me guys

**Comment by white-parrot** [comment]
I was also facing the same issue, to fix this go to window -> preferences -> user interface and update the time zone with correct value.
<img width="374" height="313" alt="Image" src="https://github.com/user-attachments/assets/9b8897ee-33f8-4a18-9eb7-6467115dd96c" />

**Comment by aditya-desai-19** [comment]
If you are facing this issue while working on Spring boot project and using postgres as your database. This is the problem of IDE which you are using. I'm using Intellij and I faced the same issue. Here are steps to fix it in IntelliJ IDE:

1. Navigate to Run → Edit Configurations…
2. Select your Spring Boot run configuration (type Spring Boot or Application) in the left pane.
3. Click Modify Options (near the top-right of the configuration panel) → choose Add VM options (or tick VM options).
4. In the VM options box add: 
`-Duser.timezone=Asia/Kolkata`
5. Apply → Run.

**Comment by Sabareesh98421** [comment]
I guess it's not the issue with IDE or DB itself it's on JVM, itself.
I am not a java developer so I am in no place to say this ,I stumble upon this issue in my office my colleague they reached out to me, since I am the one who design the project architecture so , I have this for about 4 days then I got this post so I gave shot at this method it did really worked I just config the JVM in the eclipse that it, the issue solved for me 



** Again I am not a java dev so I am not here to argue over other's post, I am just sharing my experience here **

**Comment by sugoinaman** [comment]
> If you are facing this issue while working on Spring boot project and using postgres as your database. This is the problem of IDE which you are using. I'm using Intellij and I faced the same issue. Here are steps to fix it in IntelliJ IDE:
> 
>     1. Navigate to Run → Edit Configurations…
> 
>     2. Select your Spring Boot run configuration (type Spring Boot or Application) in the left pane.
> 
>     3. Click Modify Options (near the top-right of the configuration panel) → choose Add VM options (or tick VM options).
> 
>     4. In the VM options box add:
>        `-Duser.timezone=Asia/Kolkata`
> 
>     5. Apply → Run.

This worked, thanks @aditya-desai-19

**Comment by Aniketsharma1203** [comment]
In newer versions of dbeaver you can fix this issue by going to metdata then on top right you can clickGlobal Settings. There go to user interface and change to Asia/Kolkata as your zone.

<img width="1267" height="821" alt="Image" src="https://github.com/user-attachments/assets/7a70bfce-e783-4f55-948e-c1e51871eac1" />

<img width="996" height="792" alt="Image" src="https://github.com/user-attachments/assets/5377fbf3-057e-4d91-a84e-adecd2dbc592" />

<img width="975" height="828" alt="Image" src="https://github.com/user-attachments/assets/a167a34f-16f5-4c22-a026-e3818cdeea27" />

**Comment by tezpadhye** [comment]
Also found this workaround in version 25.2.4 in Connection settings > Advanced
<img width="685" height="550" alt="Image" src="https://github.com/user-attachments/assets/0fb6ff58-590c-4aef-8cef-26ca969cdeec" />

**Comment by hd2342-dubey** [comment]
> Also found this workaround in version 25.2.4 in Connection settings > Advanced <img alt="Image" width="685" height="550" src="https://private-user-images.githubusercontent.com/50453172/514754872-0fb6ff58-590c-4aef-8cef-26ca969cdeec.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMyODkzMjQsIm5iZiI6MTc2MzI4OTAyNCwicGF0aCI6Ii81MDQ1MzE3Mi81MTQ3NTQ4NzItMGZiNmZmNTgtNTkwYy00YWVmLThjZWYtMjZjYTk2OWNkZWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE2VDEwMzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNWFkNWZkNTQzMGI5NDJiZjBlZjM0ZDQ4ZjJkOTJiYzA1Nzc0YmU3MDIzNjdlY2I4NDRhODRjN2Y5MWRiN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mDOZ4Jen_ctSJI4u6ACJ7AZuMuvihR9NxlypBmNQQqM">

Thank you, it worked for me

**Comment by satya8999** [comment]
> > > This works for me and I think other can resolve this issue issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"
> > > If you're using IntelliJ: Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options) In VM options, put: -Duser.timezone=Asia/Kolkata

this works for me in my intellij , thanks for the info.

**Comment by mnv28** [comment]
> > > > By changing the timezone here helped me as a workaround.
> > > > ![image](https://github.com/user-attachments/assets/3f1a8717-6cb2-41f4-96a7-6ad736cbe8d5)
> > > > Credits to [@Destrolaric](https://github.com/Destrolaric) & [#18965 (comment)](https://github.com/dbeaver/dbeaver/issues/18965#issuecomment-1434674795)
> > > 
> > > 
> > > It's working without any issues, Thanks [@LakhveerChahal](https://github.com/LakhveerChahal)
> > 
> > 
> > this solve my problem
> 
> Thanks, this worked for me.

This Worked for me! thanks a lot :)

**Comment by Navap-netizen** [comment]
This is issue is of IDE which you are using. I'm using Eclipse(STS) and I faced the same issue. 
Here are steps to fix it in Eclipse: 
If you goto Help->Install New Software-> You can see **What is already installed** click on it-> then go to configuration tab and search for timezone.
You will see something like this below.

<img width="557" height="247" alt="Image" src="https://github.com/user-attachments/assets/752210a6-a1fd-4848-b558-9ca7c0612a83" />

The fix is you need to go to the installed path of the eclipse, you can see the below file. (eclipse.ini)

<img width="769" height="266" alt="Image" src="https://github.com/user-attachments/assets/7b1afb1c-bed9-4ddc-a44a-35c2c9d7ae51" />

Open it in your notepad, If there's already a line like this: 

<img width="720" height="123" alt="Image" src="https://github.com/user-attachments/assets/8d18545c-cb76-4910-abb6-e867608f93b8" />

-Duser.timezone=Asia/Calcutta , edit this with 
-Duser.timezone=Asia/Kolkata
if there's no timezone line. Add this line **-Duser.timezone=Asia/Kolkata** at the end of the file. 
Then save the file and restart the eclipse.
It should definitely work, please check Help->Install New Software-> You can see **What is already installed** click on it-> then go to configuration tab and search for timezone. You will see the newly updated timezone.

**Comment by aiqbal78** [comment]
> > > This works for me and I think other can resolve this issue issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"
> > > If you're using IntelliJ: Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options) In VM options, put: -Duser.timezone=Asia/Kolkata
> > > thanks
> > 
> > 
> > Worked for me, Thanks! I am using PostgreSQL in a docker container and connecting with a Spring Boot application.
> 
> Sir, please share your understading about this issue and it's solution cause i have this error for 3 days please sir
Yes, it is working after setting the VM option -Duser.timezone=Asia/Kolkata. Thanks, buddy! I’d been facing this issue for the last three days.

**Comment by luongtt-dipro** [comment]
> In newer versions of dbeaver you can fix this issue by going to metdata then on top right you can clickGlobal Settings. There go to user interface and change to Asia/Kolkata as your zone.
> 
> <img alt="Image" width="1267" height="821" src="https://private-user-images.githubusercontent.com/122670703/513225383-7a70bfce-e783-4f55-948e-c1e51871eac1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk0MDIyODIsIm5iZiI6MTc2OTQwMTk4MiwicGF0aCI6Ii8xMjI2NzA3MDMvNTEzMjI1MzgzLTdhNzBiZmNlLWU3ODMtNGY1NS05NDhlLWMxZTUxODcxZWFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyNlQwNDMzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzNmNjU1MDYzNjdkOTM3MjU3OWNhNThiMmEzY2ViOGU5MGNiYjdjYjA0NjkxMTlhYmQyYjAwNzNiYThmZTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dKG0-6H-AuyaKq1TKoB9R7fvc3uYbmy4u2hxeHBao4Q"> <img alt="Image" width="996" height="792" src="https://private-user-images.githubusercontent.com/122670703/513225938-5377fbf3-057e-4d91-a84e-adecd2dbc592.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk0MDIyODIsIm5iZiI6MTc2OTQwMTk4MiwicGF0aCI6Ii8xMjI2NzA3MDMvNTEzMjI1OTM4LTUzNzdmYmYzLTA1N2UtNGQ5MS1hODRlLWFkZWNkMmRiYzU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyNlQwNDMzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTU3ZjFjOWM1MDc3ZGI4YTUwNmViYThjOTUwYjNkNDJjYTIxNjhlNTlkNGVkNTg2NDVkZDA5ZGZlZDZjOTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T8S-ceAFwuT6TwW-P2nYX_09goP2nih_4nOeOFNSx90"> <img alt="Image" width="975" height="828" src="https://private-user-images.githubusercontent.com/122670703/513226920-a167a34f-16f5-4c22-a026-e3818cdeea27.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk0MDIyODIsIm5iZiI6MTc2OTQwMTk4MiwicGF0aCI6Ii8xMjI2NzA3MDMvNTEzMjI2OTIwLWExNjdhMzRmLTE2ZjUtNGMyMi1hMDI2LWUzODE4Y2RlZWEyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyNlQwNDMzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzhmZWY5OTBmZWNiMDhlM2JhZmQyYmVhOTU5YWU1Nzc2ZmU5MmMwMTc0ZDZkY2M3MTRhM2MxNDRlNWRlMWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.enPdyf4qp2bD_LC5fTmeBy1yaShYbVcjAHx7U4CHKJc">

Thanks a lot. ^^

**Comment by radthenone** [comment]
Poland timezone this same do i'm returned to Europe/Warsaw and works.

**Comment by abhaypatil1510** [comment]
I was facing the same issue. I tried to pass the UTC through the main class  and the issue get resolved. 

    public static void main(String[] args) {
        java.util.TimeZone.setDefault(java.util.TimeZone.getTimeZone("UTC"));
        SpringApplication.run(MyClass.class, args);
    }

Here I navigated the time zone from our local to UTC.

**Comment by shreshtha2212** [comment]
This issue happens because Java (especially on Windows) may use the legacy timezone Asia/Calcutta, while PostgreSQL expects Asia/Kolkata.

✅ Solution 1: Ensure JVM uses correct timezone

If running via IntelliJ:

Go to:
File → Settings → Build, Execution, Deployment → Build Tools → Maven → Runner
Uncheck: Delegate IDE build/run actions to Maven

Then:

Go to: Run → Edit Configurations → Templates → JUnit

Add VM options:

-ea -Duser.timezone=Asia/Kolkata
✅ Solution 2: If using Maven (recommended for CI)

Add this in your pom.xml:

<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-surefire-plugin</artifactId>
      <configuration>
        <argLine>-Duser.timezone=Asia/Kolkata</argLine>
      </configuration>
    </plugin>
  </plugins>
</build>
✅ Solution 3: DBeaver fix
Right-click DB → Edit Connection
Go to Advanced tab
Enable: "Replace legacy timezone"
⚠️ Optional fallback (not preferred)

If needed, you can force timezone in code:

@BeforeAll
static void setTimezone() {
    TimeZone.setDefault(TimeZone.getTimeZone("Asia/Kolkata"));
}
🧠 Key Insight

If your JVM is launched by Maven, IntelliJ VM options will NOT apply.
Make sure you configure the correct runner.

**Comment by Destrolaric** [comment]
Hi everyone, there is a simpler method to use the legacy timezone. Please take a look at the `Advanced` tab in the PostgreSQL connection page. There is a an option `Replace legacy timezone`
<img width="441" height="253" alt="Image" src="https://github.com/user-attachments/assets/042f873a-bb43-4927-90ac-1b6e7a12dc1d" />

**Comment by rishika-on-git** [comment]
> I was facing the same issue. I tried to pass the UTC through the main class and the issue get resolved.
> 
> ```
> public static void main(String[] args) {
>     java.util.TimeZone.setDefault(java.util.TimeZone.getTimeZone("UTC"));
>     SpringApplication.run(MyClass.class, args);
> }
> ```
> 
> Here I navigated the time zone from our local to UTC.

This worked. Thanks!

Issue was - 

Spring Boot app was trying to connect to PostgreSQL, but in TimeZone configuration I had: (double shift and search "Asia/Calcutta")

`Asia/Calcutta
`
PostgreSQL does not accept this timezone value in my current setup.

So use:
`
Asia/Kolkata`

instead.


- I also tried doing this but since JVM is launched by Maven so IntelliJ VM options don't apply
```

1. Navigate to Run → Edit Configurations…

2. Select your Spring Boot run configuration (type Spring Boot or Application) in the left pane.

3. Click Modify Options (near the top-right of the configuration panel) → choose Add VM options (or tick VM options).

4. In the VM options box add:
   `-Duser.timezone=Asia/Kolkata`

5. Apply → Run.
```

**Comment by rishika-on-git** [comment]
This can also be done 

Add JVM args to Maven itself.

`
.\mvnw.cmd spring-boot:run "-Dspring-boot.run.jvmArguments=-Duser.timezone=Asia/Kolkata"`

**Comment by niv168** [comment]
> This works for me and I think other can resolve this issue issue: FATAL: invalid value for parameter "TimeZone": "Asia/Calcutta"
> 
> If you're using IntelliJ: Go to Run > Edit Configurations (you will see VM option under Modify options right side on the top of the pop up- then click Add VM options) In VM options, put: -Duser.timezone=Asia/Kolkata
> 
> thanks

Thanks it worked !!
