### ISSUE TITLE
Error downloading driver files

### ISSUE THREAD

**Issue by MMartinDo** [dbeaver/dbeaver#37515]
### Description

When creating a new database connection, for example a postgres I get an error about installing driver files. See printscreen

![Image](https://github.com/user-attachments/assets/ff688826-9bab-486d-a59c-f0790c7b7e0d)

### DBeaver Version

CE 25.0

### Operating System

Windows 10

### Steps to reproduce

1. Select Database from the menu
2. Select New Database Connection
3. Select Postgres (or whataver connection)

**Comment by ShadelessFox** [comment]
Hi @MMartinDo, 
1. Do you have an internet connection?
2. Is the following link accessible in a browser? https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/

And please, provide log files. You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by MMartinDo** [comment]
Hi,

It is.

**Comment by ShadelessFox** [comment]
I assume that's the answer to both questions.

Additionally, in case you did attach log files, you cannot do that when replying by mail. Please go to GitHub and attach files there.

**Comment by MMartinDo** [comment]
Yes, we have internet connection and are able to connect to https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/
![Image](https://github.com/user-attachments/assets/e0c98b94-985c-4a93-9ca8-eb26ee6c0820)

!SESSION 2025-03-12 14:24:18.857 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Administrator\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -eclipse.keyring C:\Users\Administrator\AppData\Roaming\DBeaverData\secure\secure_storage

!ENTRY org.eclipse.ui 2 2 2025-03-12 14:25:06.912
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 2 0 2025-03-12 14:25:50.708
!MESSAGE Maven artifact 'org.postgresql:postgresql:RELEASE' not found in any available repository.

!ENTRY org.jkiss.dbeaver.model 2 0 2025-03-12 14:25:50.919
!MESSAGE Maven artifact 'net.postgis:postgis-jdbc:RELEASE' not found in any available repository.

!ENTRY org.jkiss.dbeaver.model 2 0 2025-03-12 14:25:51.135
!MESSAGE Maven artifact 'net.postgis:postgis-geometry:RELEASE' not found in any available repository.

!ENTRY org.jkiss.dbeaver.model 2 0 2025-03-12 14:25:51.350
!MESSAGE Maven artifact 'com.github.waffle:waffle-jna:RELEASE' not found in any available repository.

**Comment by ShadelessFox** [comment]
Do you have the Maven Central repository specified here?

![Image](https://github.com/user-attachments/assets/360e8fcf-5ba1-44c9-aa71-56199f0be259)

**Comment by MMartinDo** [comment]
Yes I have

![Image](https://github.com/user-attachments/assets/9c83905c-c4c3-4fdc-acd5-93038e8acc30)

**Comment by ShadelessFox** [comment]
Okay, can you try updating the driver via Database -> Driver Manager as shown here?

![Image](https://github.com/user-attachments/assets/76e94877-55ed-40bc-a870-9ea1f2b89883)

**Comment by MMartinDo** [comment]
Unfortunately

![Image](https://github.com/user-attachments/assets/03123e9d-4595-40b7-811c-1d96b2174eda)

**Comment by danbu** [comment]
I am seeing the same behavior.  We just built a new Azure Virtual Desktop host with DBeaver 25.0.0 installed and it has this same behavior.  Comparing with an old VM that has 23.0.5 the "maven-central" settings are different but changing them and making all the repositories under there the same results in the same errors regardless of which driver is being download (maria,mssql,mysql,postgress...).

![Image](https://github.com/user-attachments/assets/2d8e1e01-a471-441a-8c63-93195694d365)

We were able to get it working by unchecking  "Use Windows trust store" under Preferences/Connections and restarting DBeaver.  Also downgrading to 23.0.5 and 24.0.0 both work with out checking this box (on 24.0.0 an affected system prompted to uncheck this box but 25.0.0 does not do this.).

Is this related to Microsoft removing Entrust from their Trusted Root Program (https://learn.microsoft.com/en-us/security/trusted-root/2025/february-2025) as we have seen other machines also fully updated that DBeaver works fine on a clean install.

**Comment by MMartinDo** [comment]
Morning!

This seems to be working for us too…. I asked the customer (as I am only the IT engineer) to double check this option and will let you know the outcome.

**Comment by danbu** [comment]
My colleague did some more testing and it appears the issue is a Global Sign cert serial "04000000000121585308a2".  DBeaver seems to install this cert on first launch but does not seem to on a Azure Virtual Desktop MultiSession Host (Win11 24H2, maybe others but that is what we have where this behavior occurs).  Installing the certificate in the cert store also corrects the issue with out turning off the Windows Cert Store. 


![Image](https://github.com/user-attachments/assets/d185d526-3e7c-40d2-8ed7-2fed83605a34)

![Image](https://github.com/user-attachments/assets/6b30da30-46f7-45eb-8d0c-6f9a09168672)

**Comment by E1izabeth** [comment]
I assume the issue is resolved

**Comment by ydinari** [comment]
This still happens, in dbeaver 25.0.5 on mac (Sequoia 15.5).

**Comment by ShadelessFox** [comment]
@ydinari please create a new ticket and provide details required for reproducing the issue
