### ISSUE TITLE
Add delete script support for `Choose SQL script` dialog

### ISSUE THREAD

**Issue by emirozmen07** [dbeaver/dbeaver#37558]
**Is your feature request related to a problem? Please describe.**
According to [this issue](https://github.com/dbeaver/dbeaver/issues/1988), it's possible to delete scripts from the list by selecting them and clicking DEL button. But equivalent of delete in MAC (command + del) doesn't delete the scripts.

Only way I can find to delete is, opening the script then right clicking it's name from the tab view and deleting. 

**Describe the solution you'd like**
It can be possible to delete script by (command + del) combination in mac

**Comment by labanovichttps** [comment]
@emirozmen07 Thank you for your report. Try to use **fn+delete**.

**Comment by emirozmen07** [comment]
> [@emirozmen07](https://github.com/emirozmen07) Thank you for your report. Try to use **fn+delete**.

Unfortunately this does not work for me.

**Comment by labanovichttps** [comment]
@emirozmen07 Could you tell me which device you use? Here's Apple's official documentation for hotkeys https://support.apple.com/en-us/102650
Or you could edit your hotkeys here 

<img width="1002" alt="Image" src="https://github.com/user-attachments/assets/a7f3a9d3-db18-4228-857d-194f32bac8b0" />

<img width="988" alt="Image" src="https://github.com/user-attachments/assets/959d3d2f-ae75-48b5-a38e-5c769da2c8eb" />

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. I suppose the question is solved.

**Comment by emirozmen07** [comment]
Sorry I forgot to write a reply.

It still doesn't work for me. I have the same settings as above but doesn't seem to be working in the SQL scripts list. I use a M2 MAC with latest OS version.

**Comment by E1izabeth** [comment]
@emirozmen07, could you turn on the `Show key binding` options and record a short video showing how you press the shortcut and it doesn't work? This way we'll see if the shortcut matches.

![Image](https://github.com/user-attachments/assets/a2d02dd8-a82a-48a7-ac14-7cd5075137c3)

**Comment by emirozmen07** [comment]
https://github.com/user-attachments/assets/6aea2d2d-9038-40d8-bdbb-7ed3d79e0f4e

**Comment by E1izabeth** [comment]
Thanks! Now the issue is much clearer.
Yes, `Delete`, `Rename`, and other shortcuts don't work in this dialog. However, you can delete your script through Project Explorer. By default, it's open, but if you closed this view, it's available in `Window->Project Explorer`

![Image](https://github.com/user-attachments/assets/48212a01-dc60-4b80-85e8-44dd073abf02)

![Image](https://github.com/user-attachments/assets/de3dd713-be19-4816-99a7-082c0e7178f2)

**Comment by emirozmen07** [comment]
This solution is working, thanks!

**Comment by E1izabeth** [comment]
We want to redesign the `ChooseSQL script` dialog and add the ability to delete the script there.
