### ISSUE TITLE
Can't install vrapper extension

### ISSUE THREAD

**Issue by tonivade** [dbeaver/dbeaver#38488]
### Description

Hi!

I'm trying to install vrapper (stable and unstable) into latest version of dbeaver 25.X but shows this error:

```
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 18.0.0
  Software currently installed: DBeaver 25.1.0.202506011722 (org.jkiss.dbeaver.core.product 25.1.0.202506011722)
  Cannot satisfy dependency:
    From: Quick Search 1.3.0.v20250123-0754 (org.eclipse.text.quicksearch 1.3.0.v20250123-0754)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=21))
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 25.1.0.202506011722 (org.jkiss.dbeaver.app.local.feature.feature.group 25.1.0.202506011722)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.3.0.v20250123-0754,1.3.0.v20250123-0754]
  Cannot satisfy dependency:
    From: DBeaver Community Edition 25.1.0.202506011722 (org.jkiss.dbeaver.ce.feature.feature.group 25.1.0.202506011722)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [25.1.0.202506011722,25.1.0.202506011722]
  Cannot satisfy dependency:
    From: DBeaver 25.1.0.202506011722 (org.jkiss.dbeaver.core.product 25.1.0.202506011722)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [25.1.0.202506011722,25.1.0.202506011722]
```

I was using vrapper into dbeaver for years without issue, but it seems with latest version is not possible.

Any idea?

Thanks!

### DBeaver Version

Community Edition 25.1.0

### Operating System

Ubuntu 24.04

### Steps to reproduce

1. Go to install new software
2. Add a repository for vrapper https://vrapper.sourceforge.net/update-site/stable/
3. Select vrapper extension
4. Click next

**Comment by tonivade** [comment]
Sorry, it seems solved in version 25.1.1.

**Comment by labanovichttps** [comment]
@tonivade  Thank you for your report.

**Comment by mztbc** [comment]
For me it's still happening, sadly.

Dbeaver Community Edition 25.1.1.202506291525 on Arch Linux.

![Image](https://github.com/user-attachments/assets/80276a3b-d534-41f2-9d6c-a94bd0e347ef)

Maybe this has something to do with the [arch packaged version](https://archlinux.org/packages/extra/x86_64/dbeaver/) or the [jre](jre-openjdk)? I've downloaded the standalone `.tar.gz` from the Dbeaver website and it doesn't have the issue.

![Image](https://github.com/user-attachments/assets/fc250a9b-be57-442d-9119-5ec5d35050be)

**Comment by zhaozhiwei1992** [comment]
@mztbc hankyou, the tar.gz works.
