### ISSUE TITLE
Crash when copying data from the detail grid

### ISSUE THREAD

**Issue by CarlosRuiz-globalqss** [dbeaver/dbeaver#38575]
### Description

Since the last two versions DBeaver is crashing sometimes when trying to copy data from the records of a query.

The crash doesn't happen always, but I found a way that is very reproducible.
Sometimes it happens at the first copy, sometimes I need to repeat the steps 5 or more times until it crashes.

### DBeaver Version

Community Edition 25.1.2 installed with flatpak

### Operating System

Linux Mint 22.1 Xia

### Database and driver

Database: PostgreSQL 17.5 (Ubuntu 17.5-1.pgdg24.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0, 64-bit

Driver: postgresql-42.7.2.jar

### Steps to reproduce

1. I connect to a local PostgreSQL database and open the associated editor with the shortcut ^O (or it's opened and connected automatically when I restart it after the crash)
2. Execute for example the following query: ```SELECT to_char(EXTRACT(month FROM now()), '00')```
3. The data grid will show the result as ``` 07```
4. Double click on the ``` 07``` result and execute the shortcut ^C to copy the content of the cell
5. DBeaver closes abruptly (crashes)

if the step 5 doesn't crash, keep repeating step 4 and 5, at some point it crashes.

The console shows this error:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000079ee8c075b91, pid=24, tid=25
#
# JRE version: OpenJDK Runtime Environment 21.9 (21.0.7+2) (build 21.0.7+2)
# Java VM: OpenJDK 64-Bit Server VM 21.9 (21.0.7+2, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libgobject-2.0.so.0+0x3fb91]  g_type_check_instance_is_fundamentally_a+0x11
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h %d" (or dumping to /home/carlos/.dbeaver-drivers/core.24)
#
# An error report file with more information is saved as:
# /home/carlos/.dbeaver-drivers/hs_err_pid24.log
[50,827s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

This is the error file hs_err_pid24.log : 
[hs_err_pid24.log](https://github.com/user-attachments/files/21106682/hs_err_pid24.log)

### Additional context

The database is in localhost

**Comment by Blastd** [comment]
Happens to me, too.

DBeaver 25.1.2.202507061449 flatpak
Java 21.0.7
Command line: -os linux, ARCH=x86_64, WS=gtk, NL=it_IT
On Linux Mint

Clearing error logs and reproducing the bug, it appears to only happen on textual values, here's the latest error in the error panel: 

Unable to create menu item "null", command "com.dbeaver.ai.sql.suggestion" not defined

**Comment by labanovichttps** [comment]
@CarlosRuiz-globalqss @Blastd  Thank you for your report. Seems like SWT + GTK3 is an issue, we'll try to reproduce this issue.

**Comment by fishingdev5** [comment]
Hi, problem occurs also on Linux Mint 22 Wilma, grid editor is crashing app. Version 25.1.5.202508171444

**Comment by Lapeth** [comment]
Happens often when just double-clicking a cell. Doesn't have to be copy-paste.

**Comment by Matvey16** [comment]
@fishingdev5 @Lapeth 
Do you also use DBeaver installed from flatpak? Also a relevent question is what window manager you use in your OS?

**Comment by CarlosRuiz-globalqss** [comment]
> [@fishingdev5](https://github.com/fishingdev5) [@Lapeth](https://github.com/Lapeth) Do you also use DBeaver installed from flatpak? Also a relevent question is what window manager you use in your OS?

hmmmm, this is interesting.

I had DBeaver installed with flatpak, but it stopped updating on 25.2.2

So, I removed the flatpak and installed it with apt-get and installed 25.2.3

And I just noticed that the issue is solved.

I don't know if it was fixed in 25.2.3, or if just the flatpak version is failing.

**Comment by Lapeth** [comment]
> [@fishingdev5](https://github.com/fishingdev5) [@Lapeth](https://github.com/Lapeth) Do you also use DBeaver installed from flatpak? Also a relevent question is what window manager you use in your OS?

DBeaver installed with a .deb file, on Metacity. Issue is observed in 25.2.3

Also see my [comment on a related issue](https://github.com/dbeaver/dbeaver/issues/38982#issuecomment-3461033119)

**Comment by fishingdev5** [comment]
@Matvey16 Hi, i have Linux Mint Cinnamon with Muffin window manager: https://github.com/linuxmint/muffin

DBeaver 25.2.4 is installed via flatpak and problem is still observed.

**Comment by hozgryldz** [comment]
I had the same issue since upgrading to Ubuntu 24.04. Any edits or copies ended up with dbeaver crashing. Try switching from Wayland to X11 with 

GDK_BACKEND=x11 dbeaver

to apply this fix permanently, in /usr/share/applications/dbeaver.desktop:

Exec=env GDK_BACKEND=x11 dbeaver
