### ISSUE TITLE
DBeaver ClickHouse Driver - NullPointerException when displaying Nested columns

### ISSUE THREAD

**Issue by seriouscorey** [dbeaver/dbeaver#38763]
### Description

DBeaver fails to display ClickHouse [nested column data](https://clickhouse.com/docs/sql-reference/data-types/nested-data-structures/nested) and throws a NullPointerException when attempting to render results containing nested data types in the result set viewer. This issue specifically occurs when the ClickHouse table was created with the setting [flatten_nested = 0](https://clickhouse.com/docs/operations/settings/settings#flatten_nested), which preserves nested columns as single arrays of tuples rather than flattening them into separate columns.

When flatten_nested = 0 is set in ClickHouse, nested columns remain as single array-of-tuple structures instead of being flattened into multiple separate columns (e.g., column.field1, column.field2). This is the expected behavior for maintaining true nested data structures, but DBeaver's JDBC handling fails to process these non-flattened nested columns correctly.

```text
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [HY000]: Method: getArray("testNest") encountered an exception.
    at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
    [... stack trace continues ...]
Caused by: java.lang.NullPointerException: Cannot invoke "com.clickhouse.data.ClickHouseColumn.getDataType()" because the return value of "com.clickhouse.data.ClickHouseColumn.getArrayBaseColumn()" is null
    at com.clickhouse.jdbc.ResultSetImpl.getArray(ResultSetImpl.java:1057)
```
<img width="964" height="214" alt="Image" src="https://github.com/user-attachments/assets/87fbe771-0a18-443b-945a-77f144a971c0" />

### DBeaver Version

Community Edition 25.1.3

### Operating System

Windows 11 Enterprise

### Database and driver

1.  Database is ClickHouse 24.3.12.75 and 25.3.2.39
2.  Driver is ClickHouse JDBC 0.8.5

### Steps to reproduce

1.  Connect to database
2.  Create test table
```sql
SET flatten_nested = 0;
CREATE TABLE IF NOT EXISTS nesttest (
    testString String,
    testNest Nested(
        nestString String
    )
)
ENGINE = MergeTree
PRIMARY KEY (testString)
ORDER BY (testString);
```
3.  When table is empty everything is displayed fine in dbeaver
```sql
SELECT
    *
FROM
    nesttest n;
```
4.  Insert data into the table
```sql
INSERT INTO
    nesttest (testString, testNest)
VALUES
    ('A1', [
        ('B1')
    ]);
```
5.  Run query to generate error:
```sql
SELECT
    *
FROM
    nesttest n;
```

<img width="1314" height="213" alt="Image" src="https://github.com/user-attachments/assets/4eec5fdb-35bd-4c74-bb44-44f850f9c1fa" />

6.  Explicitly calling the nested Columns does not generate an error:
```sql
SELECT
    testString,
    testNest.nestString
FROM
    nesttest n;
```

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ShadelessFox** [comment]
The recommended 0.8.5 version of the driver has a bug that prevents us from attempting to fix the issue.

The issue was fixed in 0.9.2 (or maybe in earlier versions), but now a different error arises from the DBeaver side because it doesn't know how to deal with `Nested` types. It's fixable, but since it requires updating the driver, we postponed this ticket to a future milestone when we're going to do so anyway.

**Comment by Hubbitus** [comment]
My PR https://github.com/dbeaver/dbeaver/pull/39230 fixes this issue too:
<img width="643" height="359" alt="Image" src="https://github.com/user-attachments/assets/b99553fe-7fd5-4627-bba5-4fbcadeea160" />

**Comment by seriouscorey** [comment]
@Hubbitus - The bug appears to still exist..  Did you test with SET flatten_nested = 0; when you created your table?   I'm getting a slightly different error after upgrading to 25.2.2.202510052342 and ClickHouse JDBC Driver 0.9.1

`!MESSAGE Can't resolve array data type Nested(nestString String)
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Can't resolve array data type Nested(nestString String)
	at org.jkiss.dbeaver.ext.clickhouse.model.data.ClickhouseArrayValueHandler.getArrayType(ClickhouseArrayValueHandler.java:248)
	at org.jkiss.dbeaver.ext.clickhouse.model.data.ClickhouseArrayValueHandler.getValueFromObject(ClickhouseArrayValueHandler.java:74)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:961)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:726)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:568)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleElement(SQLQueryJob.java:587)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:449)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:1061)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4567)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:128)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:126)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5202)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

<img width="795" height="429" alt="Image" src="https://github.com/user-attachments/assets/84d15404-ba45-4fb8-9ca6-2cb2be63e996" />

**Comment by Hubbitus** [comment]
@seriouscorey, obviously this is another bug. Could you please create a new one and link it there? I possibly could try to look on it.
