### ISSUE TITLE
Window size in Excel export larger than the monitor

### ISSUE THREAD

**Issue by itblago** [dbeaver/dbeaver#38844]
### Description

Hi there,

Window size in Excel export larger than the monitor. Must always be resized because, unfortunately, the set size is not remembered.

Please fix 

### DBeaver Version

Community Edition 25.1.4

### Operating System

Windows 11 (all updates)

### Database and driver

Db2 for IBM i newest JDBC

### Steps to reproduce

The window that appears when you have run an SQL query and click the “Export results” button.

**Comment by E1izabeth** [comment]
@itblago We can't reproduce the issue. Please provide clear steps to reproduce the issue.

**Comment by E1izabeth** [comment]
Also the screenshot would be really helpful

**Comment by E1izabeth** [comment]
Maybe it's related to the bug that we've fixed in #34705. However, it shouldn't exist in 25.1.4 anymore.

**Comment by itblago** [comment]
Thanks E1izabeth, it seems to be related to this you mentioned.  But unfortunately it still exists, see screenshots.

<img width="1555" height="638" alt="Image" src="https://github.com/user-attachments/assets/aab42c51-f8a3-403e-9dbe-881cfb89f286" />

<img width="1555" height="638" alt="Image" src="https://github.com/user-attachments/assets/e2221a7c-59ef-447b-83fc-92d05670a2a6" />

**Comment by E1izabeth** [comment]
@itblago please try to manually resize the sections to the preferred size and then open this dialog again. Does it help?

**Comment by itblago** [comment]
Unfortunately, no. As soon as I open it again, the window resets to its huge size.

**Comment by davestokes** [comment]
@itblago Can you please try upgrading to the newest version to see if the issue is gone there?

**Comment by itblago** [comment]
I have always installed the latest version as soon as possible. The error still occurs in version 25.2.1.202509211659, which I have installed.

**Comment by uslss** [comment]
@itblago could you try to Reset UI Settings using the Help ⇒ Reset Settings... action and check if it helps?

**Comment by itblago** [comment]
How can I back up my current settings beforehand?

**Comment by labanovichttps** [comment]
@itblago You could just copy your workspace. https://dbeaver.com/docs/dbeaver/Workspace-Location/

**Comment by itblago** [comment]
Thanks labanovichttps.

I just noticed that this does not happen if the results table cannot be scrolled to the right because it only has a few columns.

As soon as a table becomes larger again, the above-mentioned problem reappears.
