### ISSUE TITLE
Autocomplete for tables taking too long to show options on PostgreSQL

### ISSUE THREAD

**Issue by marcelodmc3** [dbeaver/dbeaver#39088]
### Description

When I'm writing a query almost always it takes upwards of 20+ seconds to show suggestions for table names. After a table is selected from the list, the table fields suggestions are displayed immediately as usual.

I was used to type one or two letters and it showed me the names for all the relevant tables and as I kept typing the options where filtered accordingly. The issue didn't start on the current version, it's been going for at least couple of weeks and I update as soon as I'm prompted.

My code completion settings (that I never changed):

<img width="978" height="641" alt="Image" src="https://github.com/user-attachments/assets/dccce188-9256-4a92-b6a3-725d15a9c7a1" />

### DBeaver Version

Community Edition 25.1.5.202508171444

### Operating System

Windows 11

### Database and driver

PostgreSQL 16.9
JDBC 42.7.2

### Steps to reproduce

To reproduce I just need to open DBeaver, connect to a database and try to run a simple query like a Select/Join in a couple of tables. 

Please check the video that I've attached.

### Additional context

https://github.com/user-attachments/assets/d615dcf8-9bd9-420c-b9b3-0f76be6f1653

**Comment by ged-yuko** [comment]
Take a look at the `Background Tasks` view please. There should be a clarification along the "Analysing for proposals: doing something".
You can also take a look at the `Query Manager` view (right-click end check-on `Meta` queries):
<img width="479" height="163" alt="Image" src="https://github.com/user-attachments/assets/bbe196b8-c162-40d1-878d-1d85a04a4484" />

Chances are, DBeaver is loading foreign keys information for all the tables to propose. If this is what you are observing, then it was already discovered, that the unwanted behavior is caused by the new feature of the last release, which uses foreign keys information to sort table proposals. Foreign keys information loading was historically implemented on a per-table basis, and so produces a query per table for each table proposal. As a result, table proposals preparation became noticeably slower.
[The fix](https://github.com/dbeaver/dbeaver/pull/39084) is already on the way: the behavior is being modified to apply this reordering only when the keys information is already cached as a result of other operations (like manual expansion of Keys node in the Navigator tree or ERD initialization, which explicitly loads tables' relations information).
Expect the fix to be available no later than 25.2

**Comment by marcelodmc3** [comment]
Yep, checking Background Tasks and "Analyzing query for proposals..." was running all the time while waiting for the table proposals.

<img width="391" height="126" alt="Image" src="https://github.com/user-attachments/assets/cd98e149-50c5-4fe0-86b0-5b46eb978bba" />

Thanks, I'll wait for the fix.

**Comment by arhayka** [comment]
This should be fixed today. Could you please try https://dbeaver.io/files/ea/? The fix will be available on 29/08.

**Comment by marcelodmc3** [comment]
Hi. The problem is still happening on 25.2.1.

It took me more than 1 minute to write a query with 2 join statements while waiting for auto-completion to do it's job.
<img width="444" height="455" alt="Image" src="https://github.com/user-attachments/assets/b56de737-e522-49ee-9980-e87123243d6d" />

https://github.com/user-attachments/assets/0dbd1cb5-c240-47d4-8f21-52a76e61875e

**Comment by marcelodmc3** [comment]
Hi! Just letting you know that I got the latest early access version and the problem still persits.

<img width="784" height="55" alt="Image" src="https://github.com/user-attachments/assets/2456150b-c220-4248-8760-c8af9c705ae2" />

**Comment by E1izabeth** [comment]
We made several enhancements in metadata reading. Please try Early Access version (https://dbeaver.io/files/ea/) or DBeaver 25.2.1 version (will be released at September, 22). Is the reported bug fixed there?

**Comment by marcelodmc3** [comment]
Hi!

It's way better. Instead of 20+ seconds waiting for a suggestion it's taking less than a second now.

The problem is fixed as far as I know.

**Comment by E1izabeth** [comment]
Thanks for checking. I'm closing the issue then
