### ISSUE TITLE
When fix the bug with Analyzing query for proposals... ??

### ISSUE THREAD

**Issue by sauribea** [dbeaver/dbeaver#39139]
### Description

The bug with Analyzing query for proposals... is not fix it yet, is a very trouble wait  until it finish... and sepnding time unnecessary... 

When already  fix it????

### DBeaver Version

Community Edition 25.2.0

**Comment by E1izabeth** [comment]
Please provide any bug description or reference the existing issue

**Comment by Mizar01** [comment]
Me too. I noticed this bug in these days when I had to connect to a mariadb database with 100+ databases.

I also select the default database in the upper menu, above the editor, but when it prints 'Analyzing query for proposals... ?' it hangs forever and I have to kill the connection or dbeaver itself.

My dbeaver version is: 25.1.5.202508171444
Mariadb version: 5.5.5-10.1.48-MariaDB-0+deb9u2 Debian 9.13
Mariadb connector/J: 3.5.2
OS: Windows 11

**Comment by E1izabeth** [comment]
@Mizar01 I believe it's already fixed in the latest DBeaver version 25.2.0

**Comment by li906912102** [comment]
I tried the latest version, but this problem still exists. I'm using mysql data

**Comment by Ozame** [comment]
I am also having the same issue with **Version 25.2.0.202508311659**. The task is stuck at 50%, running on the same steps in a loop. The autocomplete of schemas, tables and columns works very slowly if at all, when using a postgresql DB.

<img width="594" height="95" alt="Image" src="https://github.com/user-attachments/assets/db09f001-1d0b-4717-9e01-8ff26875525c" />


The issue did not exist on the previous version before updating, which was couple minor versions older I think.

**Comment by li906912102** [comment]
I use the first version of dbeaver25.2.1.202509160022 today, task stagnation in the 50% this problem seems to get the repair

**Comment by Mizar01** [comment]
Sorry to say that, but I just downloaded the latest version (25.2.0.202508311659) and the problem still exists.

I'm forced to use a different client for some connections.

**Comment by davestokes** [comment]
@sauribea Can you provide a copy of the queries and a screenshot of this? We do not understand the cause of this situation and would like further details.

**Comment by arhayka** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
