### ISSUE TITLE
Can't copy error messages

### ISSUE THREAD

**Issue by annaH7777777** [dbeaver/dbeaver#39183]
### Description

After update to a version 25.2.0 unable to copy error messages. When I do CTR C, query is being selected, not error message

### DBeaver Version

Community Edition 25.2.0

### Operating System

Windows 11

### Steps to reproduce

<img width="984" height="896" alt="Image" src="https://github.com/user-attachments/assets/d183cc92-4158-4823-9ec3-86cf0f37afd1" />

**Comment by labanovichttps** [comment]
@annaH7777777  Thank you for your report. I could reproduce it

**Comment by arhayka** [comment]
This is already fixed.

**Comment by annaH7777777** [comment]
> This is already fixed.

I updated today to version 25.2.1. and still encounter the error

**Comment by arhayka** [comment]
@annaH7777777 thank you! I was able to reproduce the issue on macOS, DBeaver 25.2.2.

In the meantime, I found a workaround:

1. Place the cursor on the error message
3. Select the message manually (without hotkeys) using the mouse or keyboard
5. Copy it with Cmd + C (macOS) or Ctrl + C (Windows/Linux)

This way, the message is copied to the buffer and can be pasted elsewhere.

**Comment by annaH7777777** [comment]
> [@annaH7777777](https://github.com/annaH7777777) thank you! I was able to reproduce the issue on macOS, DBeaver 25.2.2.
> 
> In the meantime, I found a workaround:
> 
> 1. Place the cursor on the error message
> 2. Select the message manually (without hotkeys) using the mouse or keyboard
> 3. Copy it with Cmd + C (macOS) or Ctrl + C (Windows/Linux)
> 
> This way, the message is copied to the buffer and can be pasted elsewhere.

My version is  25.2.1. (I dont saw un update for  25.2.2.) and this workaround doesnt work for me on Windows

**Comment by arhayka** [comment]
Thank you for the investigation. We'll try to fix it.

**Comment by Matvey16** [comment]
Not reproducible anymore
