### ISSUE TITLE
5.1.4 after update Dbeaver isn't opening on ubuntu

### ISSUE THREAD

**Issue by CurvesTech** [dbeaver/dbeaver#3931]
I updated from 5.1.2 to 5.1.4 today Aug 6 2018, and dbeaver isn't opening up anymore. I launch it and the icon blinks in the launcher for a few seconds and the goes away. 
I am using ubuntu 16.04.

**Comment by serge-rider** [comment]
Could you try 5.1.5 EA - perhaps it is already fixed (https://dbeaver.io/files/ea)

Some users have problem starting DBeaver on Ubuntu, but some are not. Mayeb last fixed resolved this.
Also you could try to start dbeaver from terminal.

**Comment by CurvesTech** [comment]
Ok from terminal it starts up. but it is still not starting from the launcher.

**Comment by CurvesTech** [comment]
The problem persists in 5.1.5 EA as well.

**Comment by serge-rider** [comment]
Thanks for checking. I still can't reproduce this problem (Ubuntu 16) and have no clue why this is happening. It would be great to get some error log but I'm not sure that Gnome makes such logs..

**Comment by anophelesgreyhoe** [comment]
I have the same issue on Ubuntu 16.04 (since about a week ago when I upgraded). Also, the Ubuntu shortcut still shows as "DBeaver 5.1.2", not 5.1.4. The .desktop file looks fine, so it seems like it may be a problem with Unity's local application cache or similar.

I have been launching it via the terminal, but I am also getting very weird display glitches. @serge-rider , should I log a separate ticket about the display glitches?

**Comment by anophelesgreyhoe** [comment]
Downgrading to 5.1.3 fixed the startup issue for me, and probably the display glitches too (will take some time for me to confirm).

**Comment by theremon** [comment]
Same thing happens to me for both 5.1.4 and 5.1.5, on Windows 10 64bit.
The splash screen shows and before the progress bar appears, it starts to close & reopen the splash screen in an infinite loop.
Had to downgrade to 5.1.3 to be able to work again.

**Comment by serge-rider** [comment]
If this happens on Windows then this is completely different problem.
You could:
- Cleanup previous DBeaver version installation completely
- If this won't help - reset DBeaver workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

**Comment by theremon** [comment]
@serge-rider thanks for the reply.
Resetting the workspace didn't do much, but deleting the dbeaver folder and installing the new version did the trick.
Thanks again

**Comment by serge-rider** [comment]
Looks like this issue happens only on Ubuntu 16.04.

Actual error is
```
Java HotSpot(TM) Server VM warning: You have loaded library .../dbeaver/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.700.v20180518-1200/eclipse_1705.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

**Comment by serge-rider** [comment]
After recent fixes I don't see any issues with running DBeaver on Ubuntu 16.04.
If it will happen in 5.1.5 - please create new ticket.

**Comment by freefallfred** [comment]
Same issue is back with 5.2.3 (i downgraded back to 5.2.2 and it's fine)

**Comment by tboulis** [comment]
This one worked for me:
I tried to run dbeaver from the command line: `dbeaver`
Then i saw this java  error: `Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper at `...

What fixed the issue for me is [this](https://github.com/Microsoft/vscode-arduino/issues/644#issuecomment-415329398) comment
Hope this helps

**Comment by sgnl** [comment]
@tboulis saved the day for me. After updating today DBeaver-cd wouldn't show up after the loading screen (or immediately once I click on anything else)

Here's the contents of the comment to save you a click:


    This can be done by editing the accessibility.properties file for OpenJDK:
    sudo vim /etc/java-8-openjdk/accessibility.properties
    Comment out the following line:
    assistive_technologies=org.GNOME.Accessibility.AtkWrapper
