### ISSUE TITLE
DBeaver CE issues with AWS Redshift external DB tables

### ISSUE THREAD

**Issue by yasvanthav** [dbeaver/dbeaver#39435]
### Description

We are configured Glue DB's (external) into Redshift Serverless and we trying to access through DBeaver / Okta authentication. 
 
This configuration is working as expected Redshift internal DB/Tables and not working with glue DB's which are configured under Redshift. 
 
My colleague is not able to see tables under database in left side panel But can be able to run DDL queries successfully and able to see data in table. Somehow it is working fine for me I can see tables in left side panel but not working with my colleague, both are using different DBeaver CE versions. 
 

Working one configuration: DBeaver:
 
DBeaver Community Edition - Version 24.0.0.202403031740  (Release date March 04 2024) 
 
JDBC Driver version - redshift-jdbc42-2.1.0.28
 
Not working connection DBeaver details:
 
DBeaver Community Edition - Version 24.3.0.202412011650 (Dec 2 2024) 
 
JDBC Driver version - redshift-jdbc42-2.1.0.28

 
[https://aws.amazon.com/blogs/big-data/single-sign-on-with-amazon-redshift-serverless-with-okta-using-amazon-redshift-query-editor-v2-and-third-party-sql-clients/](https://url.us.m.mimecastprotect.com/s/EhF1CQWN80F4XxVpUksyuGTZcF?domain=aws.amazon.com/)
 
 As per the Github page someone reported same bug but don't see any solution yet. Please suggest? 

[AWS Redshift Spectrum external tables and Data share tables not being displayed in database tree objects · Issue #22293 · dbeaver/dbeaver](https://url.us.m.mimecastprotect.com/s/7B3tCR6MVoUPGVY1UqtYu1QoXi?domain=github.com)Working one configuration: DBeaver:
 

### DBeaver Version

DBeaver Community Edition - Version 24.3.0.202412011650 (Dec 2 2024)

### Operating System

Windows

**Comment by davestokes** [comment]
@yasvanthav Thank you for your report.  Please try to update the driver version to the latest. and then configure the connection manually.

**Comment by yasvanthav** [comment]
@davestokes Thank You for helping on this case. My colleague is tested with latest JDBC driver but no luck. Still not able to see tables under database in left side navigator panel. But I can able to see table details.


Working one configuration: DBeaver:

DBeaver Community Edition - Version 24.0.0.202403031740 (Release date March 04 2024)

JDBC Driver version - redshift-jdbc42-2.1.0.28

Not working connection DBeaver details:

DBeaver Community Edition - version 25.1.2

JDBC Driver version - redshift-jdbc42-2.2.0

https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/2.2.0/redshift-jdbc42-2.2.0.zip

**Comment by yasvanthav** [comment]
@davestokes Please review above comments and suggest? Thank You.

**Comment by yasvanthav** [comment]
@davestokes Please review above comments and suggest? Thank You.

**Comment by IvanGorshechnikov** [comment]
Can you reproduce your issue using the latest version of DBeaver?

**Comment by yasvanthav** [comment]
@IvanGorshechnikov   Yes, we tried that option as well. But no luck. same error.

**Comment by yasvanthav** [comment]
@davestokes   Any suggestion?

**Comment by ShadelessFox** [comment]
Unfortunately, we don't have any suggestions to offer. We're missing the environment required to troubleshoot the issue.

**Comment by yasvanthav** [comment]
@ShadelessFox   If possible, we can connect over the screenshare call and I can share my screen and show you. Please suggest? This bug only in community edition or it was there in enterprise edition also? 

Thank You.

**Comment by ShadelessFox** [comment]
> This bug only in community edition or it was there in enterprise edition also?

We don't know, as we can't reproduce the issue due to reasons I've mentioned before. You can get a trial license and check.

**Comment by yasvanthav** [comment]
@ShadelessFox @davestokes @IvanGorshechnikov Me and my colleague tested with DBeaver Lite licensed version. for me it is working fine, my colleague not able to see tables in left side navigate panel. Please suggest?  can we connect over screen share session?


My version details:

Version 25.2.0.202509081303

License ID: DB-961MUZ4Y-ZDBS

JDBC Driver - redshift-jdbc42-2.1.0.28


My colleague version details:

dbeaver version - dbeaver-le-25.2.0-win32.win32.x86_64
driver version - redshift-jdbc42-2.2.0
License ID : DB-961MUZGX-ZDE6

**Comment by ShadelessFox** [comment]
Hello @yasvanthav,

Please file a technical support ticket on our website: https://dbeaver.com/submit-ticket/. We'll be happy to help you there.

**Comment by Walkeer** [comment]
I have this exact problem: Glue DB's (external) in Redshift (regular, not serverless) in DBeaver CE. Using latest version (25.3.4), tried multiple RedShift JDBC drivers (2.1.0.8, 2.2.2, also the default one DBeaver downloads from web), tried defaultRowFetchSize = 100 and fetchsize = 100, but it does not work at all. 
Regular tables works fine.
This is crucial for me, so I have to switch to other SQL client. 

I am willing to help you debug it in my environment using some screenshare etc.

**Comment by yasvanthav** [comment]
@Walkeer  
Just wanted to let you know that after several debugging sessions with Dbeaver support. finally ended with one workaround. We purchased DBeaver Lite edition (Licensed), this one has 'Redshift serverless' driver, this driver works fine with Glue external DB's. But if we upgrade to later than 25.2.0 version they don't have 'Redshift serverless' driver. Mine is 'Redshift serverless' but your is standard cluster, it will different.

**Comment by arhayka** [comment]
Hi @Walkeer and @yasvanthav!
These issues have been fixed again in the new version 26.0.0.
It would be great if you could test it.

**Comment by Walkeer** [comment]
tried default RedShift JDBC drivers in 26.0.0 on mac and still broken, tried latest 2.2.4 JDBC and did not help.

**Comment by Walkeer** [comment]
I confirm its fixed in version 26.0.3 with default Redshift driver 2.2.4 against regular provisioned Redshift (not serverless)! thanks a lot
