### ISSUE TITLE
Can't start Dbeaver by desktop icon.

### ISSUE THREAD

**Issue by liangkuai** [dbeaver/dbeaver#3971]
I was unable to start Dbeaver by desktop icon when I updated to 5.1.4. It’s always no problem starting from the terminal. Today, I updated to 5.1.5.201808122132, but I still can't start.

My OS is Ubuntu 16.04. `dbeaver.desktop` is as follow
```
  1 [Desktop Entry]                                                                                                                                                
  2 Version=1.0
  3 Type=Application
  4 Terminal=false
  5 Name=DBeaver Community
  6 GenericName=UniversaL Database Manager
  7 Comment=Universal Database Manager and SQL Client.
  8 Path=/usr/share/dbeaver/
  9 Exec=/usr/share/dbeaver/dbeaver
 10 Icon=/usr/share/dbeaver/dbeaver.png
 11 Categories=IDE;Development
 12 WM_CLASS=DBeaver Community
 13 StartupWMClass=DBeaver Community
 14 StartupNotify=true
 15 Keywords=Database;SQL;IDE;JDBC;ODBC;MySQL;PostgreSQL
 16 MimeType=application/sql
```

**Comment by serge-rider** [comment]
Yep, this bug was reported in 5.1.4 (after migrating to Eclipse 4.8, see #3931).
Unfortunately I can't reproduce it on my Ubuntu (16.04 or 17).

Do you use deb installer or zip archive?

**Comment by liangkuai** [comment]
@serge-rider 
Yes, I have been saw this issue #3931 .
I use PPA repository.

**Comment by HUSSTECH** [comment]
I have the exact same issue as reported here. Ubuntu 16.04, installed using the deb installer. Let me know if you need any outputs/traces from me to help debug. 

This along with the display glitching is making 5.1.4 very hard to use. (Is there a way to downgrade? Executing an older version deb file does not seem to change the version).

**Comment by serge-rider** [comment]
5.1.5 was already released, display glitch issue was fixed there.
You always can downgrade using deb installer (archives are here: https://dbeaver.io/files/ or in GitHub releases).

Any logs/traces would be very welcome. Unfortunately I don't know where Gnome keeps them. Something is wrong with binaries, I guess. At the moment I don't have a clue how to fix this.

**Comment by anophelesgreyhoe** [comment]
I am still having this issue with the most recent version of the 5.1.5 release, installed from the AMD64 .deb file which I downloaded about 1 hour ago. I guess I'll revert to 5.1.3 again, for now.

**Comment by webjoel** [comment]
Same proble here: ubuntu 16.04, x64, Java 8, deb distribuiton dbeaver with version 5.1.6. I tested open dbeaver directally on folder installation and works fine, but in icon desktop not.

**Comment by liangkuai** [comment]
I just updated from 5.1.5.201808122132 to 5.1.6.201808262133. Now I can start DBeaver by desktop icon. Thanks.

**Comment by anophelesgreyhoe** [comment]
5.1.6 works for me, although the icon still shows 5.1.2 (not sure if that's because Unity has cached it)

**Comment by serge-rider** [comment]
@webjoel Thanks for the information
