### ISSUE TITLE
[Oracle] Error loading resultset filter

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3974]
As of 5.1.5 released last night, searching in column filter returns this error:

    SQL Error [911] [22019]: ORA-00911: invalid character
    
    Error : 911, Position : 88, Sql = SELECT col_name, count(*)
    FROM my_table
    WHERE col_name LIKE ?
    GROUP BY col_name, OriginalSql = SELECT col_name, count(*)
    FROM my_table
    WHERE col_name LIKE ?
    GROUP BY col_name, Error Msg = ORA-00911: carattere non valido
    
    ORA-00911: invalid character

To reproduce: open a table editor or a resultset, click on the filter icon on one of the columns, and type characters to search in the values list.

If the table involved is known to dbeaver it will throw this error. Otherwise (e.g. the schema containing the table is excluded by the schema filter, so metadata for the table is not loaded) it will not perform the query and it will offer as filter values only the ones in the currently loaded rows (default 200).

**Comment by serge-rider** [comment]
It is the same issue as in #3973.
I've published new 5.1.5 build, please try to re-download it.

**Comment by p91paul** [comment]
Good job, thanks for fixing it so fast.

However the second problem remains: 

> Otherwise (e.g. the schema containing the table is excluded by the schema filter, so metadata for the table is not loaded) it will not perform the query and it will offer as filter values only the ones in the currently loaded rows (default 200).

I'm going to open a new ticket as a feature request since I realized this never worked.
