### ISSUE TITLE
"Open Database Object" option throwing NullPointerException

### ISSUE THREAD

**Issue by renatodantas** [dbeaver/dbeaver#3993]
When I activate the `Open Database Object` option (`Ctrl` + `Shift` + `D`) and starts typing something to search, DBeaver throws a NullPointerException.

![captura-dbeaver](https://user-images.githubusercontent.com/11853349/44048501-e60427c6-9f07-11e8-9c82-9a78500ee7f3.png)

Some details that may help:
- My database connection is PostgreSQL;
- I have a default schema defined in `Connection settings` > `Initialization`;
- I have enabled the schema / users filter to bring me only those I need.
- I'm using the last DBeaver version: 5.1.5.201808122132

**Comment by serge-rider** [comment]
Can't reproduce. Please post error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by renatodantas** [comment]
Posting error log.

```
eclipse.buildId=unknown
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=pt_BR
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.core.jobs
Error
Mon Aug 13 14:46:42 BRT 2018
An internal error occurred during: "Items filtering".

java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.struct.AbstractObjectReference.getFullyQualifiedName(AbstractObjectReference.java:80)
	at org.jkiss.dbeaver.model.DBUtils.getObjectFullName(DBUtils.java:1229)
	at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.getElementName(GotoObjectDialog.java:151)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$HistoryComparator.compare(FilteredItemsSelectionDialog.java:3075)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections$SynchronizedList.sort(Collections.java:2461)
	at java.util.Collections.sort(Collections.java:175)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$ContentProvider.getSortedItems(FilteredItemsSelectionDialog.java:2701)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$ContentProvider.rememberResult(FilteredItemsSelectionDialog.java:2714)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2054)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:1998)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:1970)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:1957)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by blackPantherOS** [comment]
Same problem... do you want other logfile ?

**Comment by serge-rider** [comment]
No this log is good enough.
It will be fixed in the next version.

This happens because DBeaver can't find table's schema.
One question: do you use schema filters?

**Comment by blackPantherOS** [comment]
I can't use anything, because I tried browsing local Mariadb or demos SQLite databases after connection and the I getting random crash dialog.

**Comment by serge-rider** [comment]
For this particular problem (GoTo object dialog) you can get EA version from https://dbeaver.io/files/ea.
This bug is fixed there.
If you have some other issue - could you create a separate ticket with error details?

**Comment by blackPantherOS** [comment]
@serge-rider thanks. I will check today this version, if we found any other problem, we will create a new one ticket with logs.

**Comment by blackPantherOS** [comment]
I've tested the version 5.1.6 and problem is still exists. I will made a video with reprodecure and I will open a new ticket
