### ISSUE TITLE
Bug: Few editor shortcuts don't work (e.g. cntl+enter for execute query, cntl+z for undo) in certain cases

### ISSUE THREAD

**Issue by reddyshyam** [dbeaver/dbeaver#4006]
Hi Serge, 

Found the above issue on 5.1.5 (and early) and even on EA (5.1.6). Didn't know how to re-produce hence waited this long. The above happens if I do the following steps.

1. Connect to a database (my case, mysql or oracle)
2. Open an saved editor.
3. Close that and open another saved editor.
4. Now try any of the editor shutcuts. In my case they dont work. cntl+enter breaks the current line instead of executing it. cntl+z does nothing. I have to right click and select undo from context menu.

Hope you can reproduce this and fix it. Many thanks in advance.

If it helps, my System Windows 10 pro 64 bit (Insiders release 17738.1000 rs5 branch). Happened on 1803 current stable.

**Comment by serge-rider** [comment]
How do you open saved editor? 
From project explorer view, by shortcut?

**Comment by reddyshyam** [comment]
File -> Recent editors

I just have database navigator. Closed project explorer view and dont use anymore.

Connect to a database from database navigator by expanding it. Then open editor as said above

**Comment by serge-rider** [comment]
Unfortunately I still can't reproduce that.
Does switching active editor or switching to some view and then back to the editor resolves the problem?

Usually if Ctrl+enter inserts new line instead of executing a query this means that this SQL editor isn't associated with any connection. And thus it works like a regular text editor. 
Make sure you have some connection assigned (in the main toolbar).

**Comment by serge-rider** [comment]
I'm trying to reproduce but not luck so far.
Could you say:
- Does switching active editor or switching to some view and then back to the editor resolves the problem?
- Does clicking on "Execute statement" icon works in that case?

I'm trying to understand is execute command is unavailable or just shortcut was broken by some reason.

**Comment by reddyshyam** [comment]
Hi Serge,

Thanks a lot for your time.

- Switching active editor meaning going to a browser or notepad and coming back? The work around I use at the moment is Active broken editor view, disconnect from db, reconnect and open the saved editor. This works.
- Yes, all mouse clicks work as expected. Just the keyboard shortcuts do not work. Even 'delete' key doesnot work when I try to rejoin the broken line

I see some checkin, tried the latest EA released 17th, still the issue.

**Comment by serge-rider** [comment]
Ok.
Could you try to reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace).
Just delete workbench.xmi file and restart DBeaver.

**Comment by serge-rider** [comment]
I think I've finally reproduced that. Looks like some bug in Eclipse.
The stack:
```
2018-08-19 10:24:21.151 - Event loop exception
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:161)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:305)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:579)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:648)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:438)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:381)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:93)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1190)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1051)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Control.traverse(Control.java:4274)
	at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:4256)
	at org.eclipse.swt.widgets.Composite.translateTraversal(Composite.java:1297)
	at org.eclipse.swt.widgets.Display.translateTraversal(Display.java:4674)
	at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1208)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3530)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:162)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by reddyshyam** [comment]
Hi Sergey,

Thanks for the update. Such a relief! I really appreciate your hard work for such non-trivial thing. 

I checked error logs but didn't find anything related (Tried at 19th Aug 8pm local time). Please see the screenshot of un related events only related to yesterday and before. 

![screenshot_20180819_200135](https://user-images.githubusercontent.com/12392746/44309896-1cc33f80-a3eb-11e8-832f-9a3ea13cdb0c.png)

**Comment by serge-rider** [comment]
Additional fix committed. I've reverted one of my previous fixes which (I believe) caused this issue.
Please test in 5.1.6 and reopen if this problem still exists.

**Comment by reddyshyam** [comment]
Hi Serge, Tested the latest release 5.1.6.201808262133 and the problem persists.

**Comment by serge-rider** [comment]
Ok. could you post debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files). Perhaps it will contain some clues.

**Comment by reddyshyam** [comment]
Hi Serge,

I have enabled debug log from Window -> Preferences -> Error handling -> Error logs (${workspace}\.metadata\dbeaver-debug.log) but nothing is written to it when the scenario happens. Do I have to do anything?

**Comment by serge-rider** [comment]
I've been able to reproduce this once or twice.  Eventually I think I've fixed this (although I can't be 100% sure as it is not so easy to reproduce - but I never saw this problem after the fix). 
Please check this in 5.2.

**Comment by reddyshyam** [comment]
Hi Serge,

This is still not fixed as I have been testing 5.2 EA released on 27th August and later on 3rd September. But again this is not a show stopper nor important that it deserves your time. Lets safely ignore this until someone else complains.

Thanks again for your time. Have a great day!

**Comment by drawnfallow** [comment]
I am also encountering this bug.  I'm not sure if it's a bug in windows or in dbeaver.  It wasn't happening frequently before but with 6.2.2 it is happening all the time.

**Comment by amayii0** [comment]
As for @drawnfallow , I have the same issue using 6.1.0.201906091949.
This indeed seems to occur somewhere after loading a saved .SQL from File > Recent Editors.
I had it twice in a row, resetting UI in-between, and unable to reproduce it now.

Worth noting, I'm using a shared server (Windows 2016) having layouts for French and US keyboards.
I'm not sure but sometimes I also encounter a switch of layout (system shortcut, not admin of server, can't debug on this, I usually disable such shortcut).
Could that be a side effect of triggering an improper global shortcut?

**Comment by drawnfallow** [comment]
This still occurs in 7.0.0
