### ISSUE TITLE
Impala with Sentry authorization: User '' does not have privileges to execute 'SELECT' 

### ISSUE THREAD

**Issue by powelleric** [dbeaver/dbeaver#4240]
I have a new Impala database with Sentry authorization enabled.  I was able to create the connection and it seemed ok when clicking 'Test connection' however, I did not see the database in the dropdown under the connection in the object explorer.

Moreover, when I try to run a query I get an error like this: 
`errorMessage:AuthorizationException: User '' does not have privileges to execute 'SELECT' on: db.table
`
It is interesting because it looks like it is not getting the name of the user (e.g empty quotes).  I tried adding my username to the jdbc connection string like this: `jdbc:impala://impala1:21050;UID=IMPALA_USER;` but it didn't help.

Seems related to this: https://community.cloudera.com/t5/Interactive-Short-cycle-SQL/Impala-queries-through-impala-JDBC-is-running-with-empty/td-p/49964

**Comment by powelleric** [comment]
After reading the manual, I corrected my connection string to be:

`jdbc:impala://impala_ip:21050/mydb;AuthMech=2;UID=myuser`

Now, when I do 'Test Connection...' it just hangs forever at: Connect to [my connection string]: Connecting Main

To clarify, I am trying to connect to an Impala instance with Sentry enabled.  I do not use a password to connect.  I am not using LDAP.  Sentry is just providing a permission system based on linux username.

**Comment by lyc751** [comment]
Same issue.
Solved by connection string like this:
jdbc:impala://impala_ip:21050/mydb;AuthMech=3;UID=myuser;PWD=whatever;UseSasl=0
Gook Luck!

**Comment by powelleric** [comment]
Unfortunately, that did not work for me.  I am using AuthMech=2;  Authentication with username but no password.  After adding UseSasl=0, I still hangs as before.

**Comment by powelleric** [comment]
Finally got it thanks to some new activity on this [thread](http://community.cloudera.com/t5/Interactive-Short-cycle-SQL/Impala-queries-through-impala-JDBC-is-running-with-empty/m-p/84823#M5234).  The answer was simply leaving the password field blank:

`jdbc:impala://1.0.0.1:21050/mydb;AuthMech=3;UID=myuser;UseSasl=0;PWD=`
