### ISSUE TITLE
[BUG] Problem with autocomplete

### ISSUE THREAD

**Issue by AndrePaiva** [dbeaver/dbeaver#4482]
Since I updated DBeaver to latest version (5.2.3 - Released on October 22, 2018), autocomplete isn't working fine. It concatenates the characters I entered at the end of the suggestion I accepted.
Like this:

 select * from my ( then suggests my_table)

When I accept suggestion:

 select * from my_tablemy

instead of 
 select * from my_table

**Comment by serge-rider** [comment]
It is  known issue, it is already fixed and hotfix version has been releases 24.10. just re-download 5.2.3 version.

**Comment by AndrePaiva** [comment]
Oh. Sorry! Great!
I updated, and it's working fine. Thanks.

**Comment by Bullnados** [comment]
Download it onhHomepage after installation u should have 5.2.3.2018-10-23_2047 (without delimter)
But I still have the problem with actual version sequence is still wrong. See pic in #4484

**Comment by MacNetron** [comment]
You basically say that when dbeaver says there is a new version, then wait and do not download it as it contains bugs that will be hot-fixed.
After a week or 2, the version might be stable.

The version 5.2.3 that I can download now is not the same as I've downloaded and installed. That is wrong.
Especially because the dbeaver application says there is no update.

**Comment by serge-rider** [comment]
@MacNetron yes, you are right. This is because we had to release hotfix version right after 5.2.3 release. It differs only in build number and contains just one fix of critical bug of SQL completion.

Usually we never do such hotfix releases.

**Comment by k0R73z** [comment]
@serge-rider please do not do hidden updates, I was waiting for the update from dbeaver interface more than a week and that week was full of suffering and pain.
