### ISSUE TITLE
Dark theme: Palette issue

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5081]
#### System information: 
- win 10 x64
- DBeaver version 5.3.3

#### Describe the problem you're observing:
Dark theme isn't applied for Palette panel
![image](https://user-images.githubusercontent.com/31996417/51634005-1b7edb80-1f64-11e9-874b-7c191749c414.png)

**Comment by serge-rider** [comment]
Fixed (it was side effect of #5066 fix)

**Comment by uslss** [comment]
The defect still appeared 
![image](https://user-images.githubusercontent.com/31996417/51686188-f2605880-2000-11e9-84f5-3ac4143edbc8.png)

**Comment by uslss** [comment]
still reproducible against 21.0.3

**Comment by uslss** [comment]
fixed in 21.2.3
