### ISSUE TITLE
Number formatter: Changes don't work, can't reset to default

### ISSUE THREAD

**Issue by S-Man42** [dbeaver/dbeaver#5366]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 5.3.5
- Java version: 1.8.0
- Database: Postgres 11.2
- DB driver: org.postgresql.Driver, 42.2.5.jre7

#### Describe the problem you're observing:
Wanted to limit the fraction digits of numeric/decimal numbers in grid/text view. Changed "Maximum fraction digits" in Database -> Editors -> Data Editor -> Data Formats.

Default values was 10, I changed to 8. The sample below does not change (it always shows 6 fraction digits instead of 10 or 8). 

Trying on a query (SELECT 1/3.0) shows is still showing too many digits. Is there another setting I have to change?

Changing the Round Mode does not has any effect too (neither in sample nor in real query output)

Trying to reset using "Restore Defaults" also does not work for me.

**Comment by serge-rider** [comment]
Perhaps you have redefined these settings for you connection (connection-specific settings has higher priority than global settings).
Check it here:
![image](https://user-images.githubusercontent.com/6398845/53693830-d34ea680-3db6-11e9-82e2-e8c62f934f3c.png)

**Comment by S-Man42** [comment]
Hi,

no. This is not selected.

**Comment by cool-Blue** [comment]
Hi @S-Man42 , I had the same problem trying to eliminate grouping (commas) in integers.  I found that the change is not applied until you re-run the query.

**Comment by finsterdexter** [comment]
I noticed this issue as well, and also the decimal places is locked at 3 for numeric type columns. Changing the settings, hitting Apply and Close, and re-running the query did not help.

**Comment by kseniiaguzeeva** [comment]
Is it still actual for you? Which DBEaver version do you use now?

**Comment by uslss** [comment]
Restore default button has no effect on numbers settings in v.7.1

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
restore to default still doesn't work
![2020-06-17_18h01_24](https://user-images.githubusercontent.com/31996417/84914710-99490700-b0c4-11ea-94d9-a30f41e00f25.gif)

**Comment by serge-rider** [comment]
Reset to defaults fixed one more time

**Comment by uslss** [comment]
Format settings still not restored
![2020-06-17_19h18_31](https://user-images.githubusercontent.com/31996417/84923067-66584080-b0cf-11ea-83be-28699b8bcec2.gif)

**Comment by serge-rider** [comment]
Hmm. Can't reproduce

**Comment by uslss** [comment]
verified

**Comment by HazimCreditninja** [comment]
Version 7.3.2 restore default in preference doesn't work, and set fetch size doesn't work
