### ISSUE TITLE
clickhouse array support

### ISSUE THREAD

**Issue by morozovsk** [dbeaver/dbeaver#5598]
#### System information: 
- Operating system (distribution) and version - ubuntu 18.04
- DBeaver version - 6.0.1
- Java version - 1.8.0_201
- Additional extensions

#### Connection specification:
- Database name and version - clickhouse 19.4.1.1
- Driver name - Yandex ClickHouse ( ru.yandex.clickhouse.ClickHouseDriver )
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - no

#### Describe the problem you're observing:
Array(UInt32) and Array(String) work correctly but Array(Float32) and Array(Array(String)) don't.
#### Steps to reproduce, if exist:
I have this structure:
```sql
create table pinba.requests
(
   ...,
  `tags.name`       Array(String),
  `tags.value`      Array(String),
  `timers.hitCount` Array(UInt32),
  `timers.value`    Array(Float32),
  `timers.tagName`  Array(Array(String)),
  `timers.tagValue` Array(Array(String)),
)
```
And I don't see my data:
![screen300](https://user-images.githubusercontent.com/1822063/55115620-99d73580-50ed-11e9-8aeb-69b93d36e8eb.png)

But I can see it with [tabix](https://github.com/tabixio/tabix):
![screen298](https://user-images.githubusercontent.com/1822063/55116931-b7a69980-50f1-11e9-959d-4daa19ad6a6e.png)

#### Include any warning/errors/backtraces from the logs

```
org.jkiss.dbeaver.model.exec.DBCException: Can't extract array data from Java array
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromJavaArray(JDBCCollection.java:289)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:66)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: Can't resolve array element data type
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromJavaArray(JDBCCollection.java:281)
	... 11 more
```
	```
java.lang.RuntimeException: Parse exception: ByteFragment{[5d11a1771557<TAB><TAB>200<TAB>qweqewqweqewqweqweqweqew<TAB>xy/abcdef<TAB>0.072165<TAB>1499<TAB>6291456<TAB>3661824<TAB>0.027523<TAB>['country','os']<TAB>['us','ios']<TAB>[1,1,1,1]<TAB>[0.053563,15,10,11]<TAB>[['redis'],['redis2','redis4'],['redis3'],['false3','redis3']]<TAB>[['true'],['false','false4'],['false3'],['2','1']]<TAB>0000-00-00 00:00:00], start=152, len=62}
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:470)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalStateException
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:267)
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:154)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getArray(ClickHouseResultSet.java:299)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:461)
	... 10 more
```

```
java.lang.RuntimeException: Parse exception: ByteFragment{[5d11a1771557<TAB><TAB>200<TAB>qweqewqweqewqweqweqweqew<TAB>xy/abcdef<TAB>0.072165<TAB>1499<TAB>6291456<TAB>3661824<TAB>0.027523<TAB>['country','os']<TAB>['us','ios']<TAB>[1,1,1,1]<TAB>[0.053563,15,10,11]<TAB>[['redis'],['redis2','redis4'],['redis3'],['false3','redis3']]<TAB>[['true'],['false','false4'],['false3'],['2','1']]<TAB>0000-00-00 00:00:00], start=215, len=50}
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:470)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalStateException
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:267)
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:154)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getArray(ClickHouseResultSet.java:299)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:461)
	... 10 more
```

**Comment by serge-rider** [comment]
I've fixed the problem with float and double arrays. But Array(Array(String)) handling is failing inside Clickhouse driver. 
This should be handled by Clickhouse team I think..

**Comment by serge-rider** [comment]
Test queries:
```sql
select [1.1,2.3,3.4] as test_array;

select [['abc'], ['efg']] as test_array;
```

**Comment by uslss** [comment]
verified for floats array.
still reproduced for Array(Array(String)) - Clickhouse driver issue
