### ISSUE TITLE
Replacing an asterisk after a table name/alias by pressing Ctrl+Space does not work properly

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#5634]
#### System information: 
- Windows 10
- DBeaver 6.0.1
- Java 1.8.0_181

#### Connection specification:
- Database: PostgreSQL 11
- Driver: PostgreSQL 42.2.5

#### Describe the problem you're observing:
Pressing Ctrl+Space after an asterisk with a table alias does not lead to the expected result.

#### Steps to reproduce, if exist:
Simplified database layout:
domain (domain_id, domain_name, contract_id)
contract (contract_id, customer_id)

Example query:
```
SELECT domain_id, domain_name, d.contract_id, c.*
FROM "domain" d
INNER JOIN contract c USING (contract_id)
```

When pressing Ctrl+Space after the `c.*`, I’d expect the select clause to become
`SELECT domain_id, domain_name, d.contract_id, c.contract_id, c.customer_id`
or maybe
`SELECT domain_id, domain_name, d.contract_id, c.contract_id, customer_id`

Instead it becomes
`SELECT domain_iddomain_id, domain_name, contract_id`

Issues:
- Syntax error in the first column name (`domain_iddomain_id` instead of `domain_id`).
- The table alias `d` is removed from `d.contract_id`. Instead of `d.contract_id` it states only contract_id. When using a JOIN clause like `INNER JOIN contract c ON d.contract_id = c.contract_id` the query fails due to the ambiguity.
- All columns (except the first one) are replaced instead of just the `c.*` expression.
- The new columns in the `SELECT` clause are from the `domain` table, not the `contract` table.

So in short, instead of replacing the `c.*` expression with the `c` columns, the first column is kept and all others are replaced with `d` columns, also introducing a syntax error because there is no separation between the kept first column and the newly added `d` columns.

Notes:
- Column name completion after `c.<Ctrl+Space>` works fine. Suggested column names come from the `contract` table.
- With
`SELECT d.domain_id, domain_name, d.contract_id, c.*`
it becomes
`SELECT d.domain_iddomain_id, domain_name, contract_id`
so the table alias in the first column is kept.
- `SELECT c.*` is replaced by `SELECT c.domain_id, domain_name, contract_id` although there is no `domain_id` in `c`.

#### Include any warning/errors/backtraces from the logs
Error window shows

```
org.jkiss.dbeaver.model
Fehler
Tue Apr 02 15:15:31 CEST 2019
Dangling meta character '*' near index 37
([\p{L}0-9_$§#@\.\-\"]+)\s+(?:as\s)?(*[a-z]*)[\s,]+
                                     ^

java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 37
([\p{L}0-9_$§#@\.\-\"]+)\s+(?:as\s)?(*[a-z]*)[\s,]+
                                     ^
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.sequence(Pattern.java:2125)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.group0(Pattern.java:2907)
	at java.util.regex.Pattern.sequence(Pattern.java:2053)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.compile(Pattern.java:1698)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.makeProposalsFromQueryParts(SQLCompletionAnalyzer.java:202)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:85)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:367)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
after pressing Ctrl+Space.

**Comment by uslss** [comment]
cannot reproduce issue anymore.
if it is still actual for you - feel free to reopen the ticket

**Comment by maffe** [comment]
Using 7.0.0, expanding the `c.*` in the _Example query_ above results in
```
SELECT domain_iddomain_id, c.domain_name, c.contract_id 
FROM "domain" d
INNER JOIN contract c USING (contract_id)
```
so now the column `domain_name` gets the wrong table alias `c` instead of `d`. Also `domain_iddomain_id` is still wrong. Additionally, the resulting query should contain both `d.contract_id` (as in the original query) and `c.contract_id` (expanded from `c.*`).

On the plus side, the `PatternSyntaxException` is gone.

The tables I tried this with actually have some additional columns, not sure if they lead to different results. They should not matter regarding the described behaviour.

**Comment by serge-rider** [comment]
@maffe thanks for details.

Fixed.

**Comment by uslss** [comment]
issue is still reproducible.
Query 
```
select actor_id, first_name, fa.*
from actor a 
inner join film_actor fa using (actor_id);
```
results in 
```
select **actor_idactor_id,** fa.film_id, fa.last_update, fa.column1 
from actor a 
inner join film_actor fa using (actor_id);
```
The same issue appears in case of simple query like:
```
select actor_id, first_name, a.*
from actor a;
```
results in
```
select **actor_idactor_id,** a.first_name, a.last_name, a.last_update, a.column1, a.column2, a.column3, a.column4, a.column5 
from actor a;
```
![2020-03-18_20h17_56](https://user-images.githubusercontent.com/31996417/76990003-51e19c00-6958-11ea-83bd-1ccd3ff68b50.gif)

**Comment by serge-rider** [comment]
@uslss It is a different bug. Anyway - fixed too.
