### ISSUE TITLE
DB2 for z/OS: Navigator shows tables from other schemas

### ISSUE THREAD

**Issue by vysocan** [dbeaver/dbeaver#5750]
#### System information: 
- Linux RHEL 7.6 
- 6.0.2
- 1.8

#### Connection specification:
- DB2 V11 for z/OS
- DRIVER=3.71.32

#### Describe the problem you're observing:
After update from 6.0.0. the filter of schema does not seems to work properly. I see in Database Navigator tables from other schemas. 
Biggest problem is when I open any table(Edit Table), then the table content is not shown. Since in the SQL SELECT does not add schema prefix to table. And DB2 explicitly forces my userid as schema prefix. Information about table columns (Properties) works without problem.

#### Steps to reproduce, if exist:
Connect to DB2 on Z/OS and Edit any table.

#### Include any warning/errors/backtraces from the logs
SQL Error [42704]: CZ61947.API_KEY IS AN UNDEFINED NAME. SQLCODE=-204, SQLSTATE=42704, DRIVER=3.71.32

**Comment by MocniMax** [comment]
Hello,

I have same issues with DBeaver 6.0.2 on MS Windows. Shema view on zOS DB2 worked fine up to version 6.0.1.
Looks like data source is not passed to db2 driver getSchema call.

`
java.lang.AbstractMethodError: Method com/ibm/db2/jcc/t4/e.getSchemas(Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet; is abstract
	at com.ibm.db2.jcc.t4.e.getSchemas(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSchemas(JDBCDatabaseMetaDataImpl.java:197)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadSchemas(GenericMetaModel.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:503)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:777)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:108)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:68)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:204)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:593)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

Attached are DBeaver logs from version 6.0.1 and 6.02. and zOS DB2 connection screen shots.



[dbeaver-debug.log.6.0.1.txt](https://github.com/dbeaver/dbeaver/files/3111435/dbeaver-debug.log.6.0.1.txt)
[dbeaver-workspace.properties.6.0.1.txt](https://github.com/dbeaver/dbeaver/files/3111436/dbeaver-workspace.properties.6.0.1.txt)

[dbeaver-debug.log.6.0.2.txt](https://github.com/dbeaver/dbeaver/files/3111441/dbeaver-debug.log.6.0.2.txt)
[dbeaver-workspace.properties.6.0.2.txt](https://github.com/dbeaver/dbeaver/files/3111442/dbeaver-workspace.properties.6.0.2.txt)

![DBeaver 6 0 1](https://user-images.githubusercontent.com/26117076/56646498-f80d1f00-667f-11e9-9d40-f79d233cf328.jpg)
![DBeaver 6 0 2](https://user-images.githubusercontent.com/26117076/56646501-f9d6e280-667f-11e9-9ce2-063eece41066.jpg)

**Comment by MocniMax** [comment]
I just checked it with latest DBeaver version 6.0.3 and issue is still there.

![DBeaver 6 0 3](https://user-images.githubusercontent.com/26117076/56648536-ceee8d80-6683-11e9-99dc-6bae81b0ac3d.jpg)

Here are log files for versions 6.0.2 and 6.0.3.

[log.6.0.2.txt](https://github.com/dbeaver/dbeaver/files/3111551/log.6.0.2.txt)
[log.6.0.3.txt](https://github.com/dbeaver/dbeaver/files/3111553/log.6.0.3.txt)

Hope this will help in solving it. Currently, latest DBeaver versions are pretty useless for zOS DB2 without additional manual SQL adoption.

Regards,

**Comment by cniweb** [comment]
@serge-rider This issue is also highly relevant for us! We have connections to DB2 with multiple schemas (per environment - table names are the same).

**Comment by lorenzopuglioli** [comment]
Problem still here in version 6.0.5.
We're forced to use latest working version, 6.0.1

**Comment by lorenzopuglioli** [comment]
The problem has been fixed in version 6.1.1.

**Comment by vysocan** [comment]
Right, thanks for informing. It works again, great.
Thank you.

**Comment by flambchap** [comment]
A user of ours still experiences this issue. He suspects that those tables from the wrong schemas are actually synonyms. I think we can add a separate folder for synonyms, and the issue will disappear.
