### ISSUE TITLE
Null pointer exception appears when trying to create schema with name equal to db name

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5763]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.0.3

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Null pointer exception appears when trying to create schema with name equal to db name
#### Steps to reproduce, if exist:
1. Create db (e.g. Test)
2. Try to create schema with the same name.

![image](https://user-images.githubusercontent.com/31996417/56458292-6f476800-638d-11e9-8d35-a635622dc9b1.png)

Log: 
```
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Sat Apr 20 16:54:55 MSK 2019


java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:77)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$CreateJob.run(NavigatorHandlerObjectCreateBase.java:166)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Reopened.
Issue still reproducible in case db isn't opened.
`java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:77)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$CreateJob.run(NavigatorHandlerObjectCreateBase.java:166)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`
