### ISSUE TITLE
Columns and tables autocomplete/proposal not working properly

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#5955]
Hi.
Since version 6.0.3 or maybe even earlier I'm having an issue with autocompletion of column and table names. 
What I expect (and it did work like that) is when I start typing it would suggest me table names (perhaps only from those I've already put in FROM and JOINs) and then after I put a dot after the table name it would suggest me columns from this table.
What I get is when I start typing it would suggest me columns from the table set in FROM. It's not really helpful in "bigger" queries where some columns have the same names in different tables.

Changing settings **Use short object names** and **Use long object names** doesn't seem to help. Currently I have enabled the **Use short object names** setting.

**Comment by Speirs47** [comment]
It seems that it got fixed in 6.1.2

**Comment by jim256** [comment]
This is still an issue for me in 6.1.4
OS X Mojave 10.14.6 (18G87)
