### ISSUE TITLE
Firebird procedure default parameter

### ISSUE THREAD

**Issue by MebsSystem** [dbeaver/dbeaver#6059]
#### System information: 
- OSX 10
- DBeaver version 6.0.5
- Java version 8 update 201

#### Connection specification:
- Firebird 2.5

#### Describe the problem you're observing:
Firebird supports defaults values for stored procedure.
When creating procedure you can declare it with no problem.
CREATE PROCEDURE FOO(A INTEGER DEFAULT 0) AS ....
But when editing procedure the default value is no longer in the source code.
CREATE OR ALTER PROCEDURE FOO (A INTEGER) AS
Need to remember adding it every alter.

#### Steps to reproduce, if exist:
Create some procedure with default value for some parameter.
Right click on procedure in Database Navigator and Edit.
The default value is no longer in source code of the procedure.

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket

**Comment by vlbrodsky** [comment]
I have same problem with default parameters:

#### System information: 
- OS: Windows 10
- DBeaver version: 7.2.2.202010041557

#### Connection specification:
- DB version: Firebird 2.1 LI-V2.1.7.18553
- Driver: Jaybird JCA/JDBC driver 4.0.0

#### Steps to reproduce:
1. create procedure with default parametr: 
CREATE PROCEDURE TEST_DEFAULT_PARAM (
    param1 INTEGER DEFAULT NULL
)
AS
BEGIN
    -- test procedure with default param
END

2. show procedure in DBeaver:
CREATE OR ALTER PROCEDURE TEST_DEFAULT_PARAM (PARAM1 INTEGER)
AS
BEGIN
    -- test procedure with default param
END

**Comment by LonwoLonwo** [comment]
reproduced. there is no default column parameter in procedure DDL

**Comment by LonwoLonwo** [comment]
Now driver returns us an incorrect value for the parameters, we need to see if it will be possible to retrieve data from the RDB$PROCEDURES

**Comment by LonwoLonwo** [comment]
Fixed in scope with https://github.com/dbeaver/dbeaver/issues/10872

**Comment by uslss** [comment]
verified

**Comment by SolfacodeSoftware** [comment]
Problem still exists when you use domains.
Version of DBeaver: 23.0.0.202303040621

Egzample:

1. create procedure with default parametr:

CREATE OR ALTER PROCEDURE DBS$SYSTEMLOG_ADD_TEST("DBS$NAME" VARCHAR(64), DBS$LOG DBS$MEMO, DBS$DELETE DBS$BOOLEAN DEFAULT 0)
AS
BEGIN
-- test procedure with default param
END

2. show procedure in DBeaver:

CREATE OR ALTER PROCEDURE DBS$SYSTEMLOG_ADD_TEST ("DBS$NAME" VARCHAR(64), DBS$LOG DBS$MEMO, DBS$DELETE DBS$BOOLEAN)
AS
BEGIN
-- test procedure with default param
END

**Comment by LonwoLonwo** [comment]
Hello @SolfacodeSoftware 

Please create a ticket for your case. Default values do not show for domain procedures parameters
