### ISSUE TITLE
DBeaver display `NULL` instead of data for fields of custom data type

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#6228]
#### System information: 
- Linux Mint 19.1
- DBeaver version 6.0.0

#### Connection specification:
- PostgreSQL 10.4
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
![_](https://user-images.githubusercontent.com/799021/60720921-e7f1a580-9f34-11e9-9468-ff2608878b89.jpg)

#### Steps to reproduce, if exist:
Try to select data using `table` or `table.*` syntax for custom data types:
```
CREATE TYPE zzz AS ( id int, name TEXT );

;
SELECT z::zzz, (z::zzz).* FROM (
	SELECT * FROM ( VALUES ( 1, 2 ), (NULL, 3) ) t
) z;
```

**Comment by KES777** [comment]
There one warning exists:
```
z                                          |id|name|
-------------------------------------------|--|----|
1,2                                        | 1|2   |
NumberFormatException: For input string: ""|  |3   |
```
seems this is related to `DBeaver`, because `psql` does not return any warnings for same query:
```
   z   | id | name 
-------+----+------
 (1,2) |  1 | 2
 (,3)  |    | 3
(2 rows)
```

**Comment by serge-rider** [comment]
This bug was already fixed in 6.1. please download some recent version.

![image](https://user-images.githubusercontent.com/6398845/60722317-dad2b780-9f30-11e9-941a-f6b42edfda9c.png)

**Comment by KES777** [comment]
v6.1.1 still does not work:

![_](https://user-images.githubusercontent.com/799021/60733078-922cf580-9f54-11e9-9285-aa4e0b6cf28a.jpg)

**Comment by serge-rider** [comment]
Yep, in fact this was fixed only in 6.1.2 and can be tested only in Early Access version (https://dbeaver.io/files/ea).

**Comment by KES777** [comment]
=)

**Comment by KES777** [comment]
huh... still does not display correct data. see examples below:

![_](https://user-images.githubusercontent.com/799021/60756923-5ce3de80-a00c-11e9-9d44-8cc17e0bae82.jpg)

![_2](https://user-images.githubusercontent.com/799021/60756924-62412900-a00c-11e9-910e-fb75effce4a2.jpg)

**Comment by serge-rider** [comment]
How can I reproduce this? 

Some DDL would be helpful.

**Comment by KES777** [comment]
try this data:
```
?column?                                           |dt                                                                                                                                                                                                                               |id   |agreement_id|docn    |package_id|period_id|service_level_id|suma                |billed_to             |vm_id|docdate   |comment|app_period                                         |agreement_docn|bill_range                                         |checked|current|current_suma|
---------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----|------------|--------|----------|---------|----------------|--------------------|----------------------|-----|----------|-------|---------------------------------------------------|--------------|---------------------------------------------------|-------|-------|------------|
["2019-04-09 03:00:00+03","2019-05-09 03:00:00+03")|10805,1752,"2019-06-04 11:58:56.180046+03",20190102,26,1,0.000000000000000000,"2019-04-09 03:00:00+03",,,2004-04-09,этот,10,795,"[-infinity,infinity)","[""2019-06-26 23:52:55.299016+03"",""2019-07-05 19:07:21.518204+03"")"   |10805|        1752|20190102|        26|       10|               1|0.000000000000000000|2019-04-09 03:00:00+03|     |2004-04-09|этот   |[-infinity,infinity)                               |20190102      |["2019-04-09 03:00:00+03","2019-05-09 03:00:00+03")|    109|false  |     445.804|
empty                                              |10805,1752,"2019-06-04 11:58:56.180046+03",20190102,26,1,0.000000000000000000,"2019-04-09 03:00:00+03",,,2004-04-09,этот,10,3307,"[-infinity,""2019-04-01 00:00:00+03"")","[""2019-07-05 19:07:21.518204+03"",)"                 |10805|        1752|20190102|        26|       10|               1|0.000000000000000000|2019-04-09 03:00:00+03|     |2004-04-09|этот   |[-infinity,"2019-04-01 00:00:00+03")               |20190102      |["2019-04-09 03:00:00+03","2019-05-09 03:00:00+03")|    109|false  |            |
["2019-05-01 00:00:00+03","2019-05-09 03:00:00+03")|10805,1752,"2019-06-04 11:58:56.180046+03",20190102,26,1,0.000000000000000000,"2019-04-09 03:00:00+03",,,2004-04-09,этот,10,3308,"[""2019-05-01 00:00:00+03"",infinity)","[""2019-07-05 19:07:21.518204+03"",)"                  |10805|        1752|20190102|        26|       10|               1|0.000000000000000000|2019-04-09 03:00:00+03|     |2004-04-09|этот   |["2019-05-01 00:00:00+03",infinity)                |20190102      |["2019-04-09 03:00:00+03","2019-05-09 03:00:00+03")|    109|false  |            |
["2019-04-09 00:00:00+03","2019-05-01 00:00:00+03")|10805,1752,"2019-06-04 11:58:56.180046+03",20190102,26,1,0.000000000000000000,"2019-04-09 00:00:00+03",,,2004-04-09,этот,10,3309,"[""2019-04-01 00:00:00+03"",""2019-05-01 00:00:00+03"")","[""2019-07-05 19:07:21.518204+03"",)"|10805|        1752|20190102|        26|       10|               1|0.000000000000000000|2019-04-09 00:00:00+03|     |2004-04-09|этот   |["2019-04-01 00:00:00+03","2019-05-01 00:00:00+03")|20190102      |["2019-04-09 00:00:00+03","2019-05-09 00:00:00+03")|    109|false  |     448.352|
```
and query
```
SELECT t0.* FROM ( select app_period * bill_range, *,
  upper( bill_range ) <@ app_period() as current,
  order_total_suma( id, app_period * bill_range ) AS current_suma
from (
  SELECT ROW( o.* )::"order_bt" AS dt, o.id, o.agreement_id, o.docn, o.package_id, o.period_id, o.service_level_id,
    o.suma, o.billed_to, o.vm_id, o.docdate, o.comment,
    o.app_period,
    a.docn as agreement_docn,
    tstzrange(
      NULLIF( o.billed_to, 'infinity' ),
      NULLIF( o.billed_to +p.interval, 'infinity' )
    ) as bill_range,
    c.id as checked
  FROM "order_bt" o
  LEFT JOIN agreement a    ON a.id = o.agreement_id
  LEFT JOIN period p       ON p.id = o.period_id
  LEFT JOIN xcheck c      ON c.doc_id = o.id and c.doctype = 'OrderDetail'
  where o.id = 10805
) t )
 t0 WHERE ( ( bill_range && app_period() AND (NOT billed_to = 'infinity' ) ) ) ORDER BY agreement_docn, period_id
```

**Comment by KES777** [comment]
another problem for:

```
;CREATE TYPE zzz AS ( q int, x int, y tstzrange, z tstzrange ); 
 
; 
SELECT k.* FROM ( SELECT row(t.*)::zzz FROM ( VALUES(
     10, 795, tstzrange( '-infinity', 'infinity'), tstzrange( '2019-06-26', '2019-07-01' ) )
 ) t ( q, x, y, z ) ) k
```
Here is OK:
![_](https://user-images.githubusercontent.com/799021/60757065-5191b280-a00e-11e9-8d54-49868836f331.jpg)

but for next `k.*` becomes `row`, but first column **should be** a row:

![_2](https://user-images.githubusercontent.com/799021/60757072-68d0a000-a00e-11e9-8f54-c35f81575be2.jpg)

**Comment by KES777** [comment]
```
;CREATE TYPE zzw AS ( q int, x int ); 
 
; 
SELECT b FROM ( SELECT row(t.*)::zzw AS b FROM ( VALUES(
     10, 795 )
 ) t ( q, x ) ) k
 ```

![_](https://user-images.githubusercontent.com/799021/60757139-67ec3e00-a00f-11e9-99a2-d73b8a27fb2e.jpg)
![_2](https://user-images.githubusercontent.com/799021/60757140-6a4e9800-a00f-11e9-99da-647daee90316.jpg)

but `psql` result is:

![_3](https://user-images.githubusercontent.com/799021/60757141-70dd0f80-a00f-11e9-8c04-62710d200737.jpg)

**Comment by serge-rider** [comment]
Still can't reproduce problem with sid/interval columns as I don't know what source table data types are.

In regards to struct data types visualization. Generally this is controlled by context menu->View/Format->Structurize complex types option. However it doesn't work in case of PG structures (because of bug). I'll push the fix after 6.1.2 release.

**Comment by KES777** [comment]
ok. thank you. I will retest after release.

**Comment by KES777** [comment]
Some more data for testing. For next data `NULL` is not displayed:
```
qty|price|cost|suma  |o                                                                                                                                                                                                                                                              |c                                                                                                                                                                                      |p                                                          |ic                                                                                                                            |
---|-----|----|------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|
   |     |    |      |10805,1752,"2019-06-04 11:58:56.180046+03",20190102,26,1,0.000000000000000000,"2019-04-09 00:00:00+03",,,2004-04-09,этот,10,3707,"[""2019-04-01 00:00:00+03"",""2019-05-01 00:00:00+03"")","[""2019-07-08 22:05:29.742893+03"",)"                              |                                                                                                                                                                                       |                                                           |"(,,,,,)",,                                                                                                                   |
   |     |    |      |10805,1752,"2019-06-04 11:58:56.180046+03",20190102,26,1,0.000000000000000000,"2019-04-09 00:00:00+03",,,2004-04-09,этот,10,3707,"[""2019-04-01 00:00:00+03"",""2019-05-01 00:00:00+03"")","[""2019-07-08 22:05:29.742893+03"",)"                              |24852,10805,7,2048,,,,,7373,"[""2019-04-09 00:00:00+03"",infinity)","[""2019-06-04 12:01:17.227807+03"",infinity)",1                                                                   |                                                           |"(,,,,,)",,"[""2019-04-09 00:00:00+03"",""2019-05-01 00:00:00+03"")"                                                          |
  2|    9|  18|  13.2|10805,1752,"2019-06-04 11:58:56.180046+03",20190102,26,1,0.000000000000000000,"2019-04-09 00:00:00+03",,,2004-04-09,этот,10,3707,"[""2019-04-01 00:00:00+03"",""2019-05-01 00:00:00+03"")","[""2019-07-08 22:05:29.742893+03"",)"                              |24849,10805,5,2,,,,98,7360,"[""2019-04-09 00:00:00+03"",infinity)","[""2019-06-04 12:00:05.879421+03"",infinity)",1                                                                    |12,1,98,9.000000000000000000,1,1,,10,                      |"(8,1,2019-03-01,1,1,""[-infinity,infinity)"")",0.733333333333333282,"[""2019-04-09 00:00:00+03"",""2019-05-01 00:00:00+03"")"|
```

![_](https://user-images.githubusercontent.com/799021/61039559-a69b4300-a3d7-11e9-94f8-4912430145b9.jpg)

**Comment by KES777** [comment]
This is suggestion only. Does DBeaver try to display truncated data?
![_](https://user-images.githubusercontent.com/799021/61184658-048a8d80-a659-11e9-9bab-456d45000c6a.jpg)

![_2](https://user-images.githubusercontent.com/799021/61184661-0bb19b80-a659-11e9-8238-a7840860ef2e.jpg)

**Comment by borisperelshteyn** [comment]
DBeaver v23 on MacOS.  Solved in Settings -> Data Editor -> Data Formats.   Disabled formatting for date/time and numeric.
![image](https://github.com/dbeaver/dbeaver/assets/131305832/a258bb1c-fccf-4158-bfe2-df9a6703a5a9)
