### ISSUE TITLE
Renaming a column with F2 takes focus out of dialog

### ISSUE THREAD

**Issue by pipwilson** [dbeaver/dbeaver#6486]
#### System information: 
- Ubuntu 18.04
- 6.1.4.201908041900

#### Connection specification:
- MySQL database
- com.mysql.jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

If you try to rename a column using the F2 keyboard shortcut, the popup dialog appears, but focus is placed back in the list of columns behind it.

#### Steps to reproduce, if exist:

1. Select a database
2. Select a table
3. Press F4 to get to the properties tab for that table
4. Select a column name from the list
5. Press F2 to get the "Rename Column" dialog. Focus is briefly in the rename dialog but then returns to the column list, requiring another click to get focus back into the dialog

Using the context menu and selecting "Rename" does not exhibit this problem.

**Comment by serge-rider** [comment]
Must be fixed in #7908

**Comment by uslss** [comment]
still reproduces
[Screencast 2020-02-26 11:14:54.zip](https://github.com/dbeaver/dbeaver/files/4254230/Screencast.2020-02-26.11.14.54.zip)

**Comment by serge-rider** [comment]
Looks like some GTK-specific issue

**Comment by uslss** [comment]
seems that issue is fixed
