### ISSUE TITLE
ERROR: unknown function: pg_tablespace_location()

### ISSUE THREAD

**Issue by yazver** [dbeaver/dbeaver#6576]
- Windows 10 / 1903
- DBeaver 6.1.4/6.1.5

- cockroach:v19.1.3
- PostgreSQL JDBC Driver
- Direct connection 

After starting the application and opening any table the next error is showed: 

```  
  java.lang.reflect.InvocationTargetException
    SQL Error [42883]: ERROR: unknown function: pg_tablespace_location()
    SQL Error [42883]: ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()
```

Version 6.0.5 don't have this problem.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
Reopened.
Issue is still reproducible
![image](https://user-images.githubusercontent.com/31996417/63507264-0a894f00-c4e0-11e9-95db-df8ef3865dd4.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by kenhkelly** [comment]
This is still an issue

```
unknown function: pg_tablespace_location()

  java.lang.reflect.InvocationTargetException
    Internal driver error
    Internal driver error
      SQL Error [42883]: ERROR: unknown function: pg_tablespace_location()
      SQL Error [42883]: ERROR: unknown function: pg_tablespace_location()
        ERROR: unknown function: pg_tablespace_location()
        ERROR: unknown function: pg_tablespace_location()

```

DBeaver Version 7.1.0.202005311732
Cockroach 19.2.4

**Comment by giuliotripi** [comment]
I encountered the same issue with DBeaver version 22.1.1.202206261508
OS: Ubuntu 22.04 LTS
CockroachDB: v22.1.1 inside Docker
Driver: org.postgresql.Driver

```
ERROR: unknown function: pg_tablespace_location()


  InvocationTargetException
  java.lang.reflect.InvocationTargetException
    Errore SQL [42883]: ERROR: unknown function: pg_tablespace_location()
    Errore SQL [42883]: ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()
```

**EDIT: it is just necessary to select cockroachdb as database type when creating a new connection**

**Comment by amnagh017** [comment]
Getting the exact same error. 

> ERROR: unknown function: pg_tablespace_location()
  InvocationTargetException
  java.lang.reflect.InvocationTargetException
    Errore SQL [42883]: ERROR: unknown function: pg_tablespace_location()
    Errore SQL [42883]: ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()

DBeaver version 23.2.3.202310221533
OS: Windows 10
CockroachDB: v23.1.11
PostgreSQL JDBC Driver
Connecting to CockroachDB using host, username, and password.

**Comment by bluecrunch** [comment]
Getting the exact same error as amnagh017 and giuliotrpi.

```
ERROR: unknown function: pg_tablespace_location()
  InvocationTargetException
  java.lang.reflect.InvocationTargetException
    SQL Error [42883]: ERROR: unknown function: pg_tablespace_location()
    SQL Error [42883]: ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()
      ERROR: unknown function: pg_tablespace_location()
```

Version: 24.0.3.202404211624
OS: Windows 11
CockroachDB, connecting via host, username, and password.

**Comment by rymoore99** [comment]
Same error here

**Comment by edwardsa829** [comment]
ERROR: unknown function: pg_tablespace_location()
same.. and pops up all the time
DBeaver version 24.1.1
OS: Windows 11
CockroachDB
