### ISSUE TITLE
ERROR: column "oid" does not exist in x [Dbeaver-Redshift]

### ISSUE THREAD

**Issue by maximillianus** [dbeaver/dbeaver#6853]
I am trying to connect to redshift using dbeaver (I am using v5.2.0.2xxxx). Manage to see the schema, table, and row count statistics but when I tried to browse data, I encountered this error (`ERROR: column "oid" does not exist in x`).

I still manage to query my data just fine. So I wonder what error is this, why can't I browse my data in Data tab?

**Comment by serge-rider** [comment]
You need to upgrade to a more recent version. 
This bug was fixed a long time ago.

**Comment by maximillianus** [comment]
@serge-rider This issue still persists after I upgraded to ver6.2.1

**Comment by serge-rider** [comment]
Do you use Redshift driver or standard PostgreSQL driver? You should use Redshift driver, it has no issues with oids.

**Comment by maximillianus** [comment]
@serge-rider Thanks. It works.

**Comment by msweetnam** [comment]
So there's a checkbox in the "Properties" tab when you first open up the "View Table" tab.. the label is "Has Oids".. just uncheck that and your problem goes away. 
Good luck!

![image](https://user-images.githubusercontent.com/12866542/99298589-8ff8cd80-280f-11eb-92e4-82e2f8be8a3a.png)
