### ISSUE TITLE
Incorrect Display of Float

### ISSUE THREAD

**Issue by Darth-Skywalker** [dbeaver/dbeaver#6989]
I am using DBEaver 6.2.0 with SQL Server. I inserted some data programmetically into DBeaver, in one of the connections, and then used the feature Export Resultset to export to another server. But the data that was exported is all messed up. For example, a number 21.72 looks as 21.7199993133545.
Incidentally, it looks fine in the older version of DBeaver.

**Comment by gbreeze** [comment]
same issue on v7.0.0

**Comment by uslss** [comment]
unfortunately, cannot reproduce an issue.
do you use some special properties in Data Formats?

**Comment by gbreeze** [comment]
![0bf7ad52-ba18-4212-8c90-ee44c13bb61d](https://user-images.githubusercontent.com/1906169/76570715-39840400-64b6-11ea-9452-37bdefbf667e.gif)

**Comment by uslss** [comment]
could you try it against recent version?

**Comment by gbreeze** [comment]
Looks fine now. I like the automatic decimal rounding, thanks!

**Comment by gbreeze** [comment]
OK, but now the value is saved incorrect. 
If I save the value **43.2**, the value **43.20000076** is saved to the database.

**Comment by serge-rider** [comment]
Still can't reproduce this. 43.2 is saved as is.

**Comment by gbreeze** [comment]
![b0ce6cf3-defe-4629-b330-faab37ed686f](https://user-images.githubusercontent.com/1906169/81216665-9219de00-8fdb-11ea-8fa6-e1ffbf294a5e.gif)

**Comment by serge-rider** [comment]
@gbreeze Still can't reproduce with float, float4 or float8.
Could you try in dbeaver 7.0.4?
Also, what PostgreSQL server and driver version do you use? You can get it from Test Connection dialog (in connection properties).

**Comment by gbreeze** [comment]
same issue on 7.0.4

i'm using mysql 5.6
![image](https://user-images.githubusercontent.com/1906169/81217733-64359900-8fdd-11ea-9f38-dd09480990be.png)

**Comment by kseniiaguzeeva** [comment]
I can reproduce it for MySQL. @serge-rider you can see it in Kseniia.test_imp_create or use steps:
1. enter 43.2 in a column of float type
2. press F5
3. double click on the cell

Actual result: the value is changed on 43.20000076

**Comment by serge-rider** [comment]
Thanks.
Actual problem happened on client side during data read and formatting (in database values were stored correctly).

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by miqbal23** [comment]
Hello,
It seems that I face the same issue as previously solved here, and I'm using 7.3.3
![image](https://user-images.githubusercontent.com/12664445/110603001-21be8900-81b9-11eb-889c-febacbfd7631.png)
![image](https://user-images.githubusercontent.com/12664445/110603025-2a16c400-81b9-11eb-8508-fc446a9ef172.png)

Any solution to this?

**Comment by kseniiaguzeeva** [comment]
Could you please create a new ticket, tell your database and send DDL example?
Is it possible to make screenshot of Preferences>Data Editor>Data Formats?
![dbeaver_plW9XxsFZp](https://user-images.githubusercontent.com/51405061/110964311-1d829f00-8364-11eb-88e0-7867288301df.png)

**Comment by cpinamtz** [comment]
The issue persists. In this case with a Postgres connection with the official driver, `float8` and database's version 11.9.

https://user-images.githubusercontent.com/8851448/126995193-2e53d9d7-fa1c-4d52-99f7-d2a76ead98e4.mp4

**Comment by harryghgim** [comment]
@cpinamtz does the following helps you?

- go to `Preferences > Editors > Data Editor > Data Formats`
- check `Disable numeric formatting`

Hopefully your float values will look more precise than before.

In case someone is wondering, my environment is as follows:

OS: mac Catalina 10.15.7 
dbeaver version: Version 21.1.5.202108160727
database: mariadb 10.6
