### ISSUE TITLE
"case when format" for 6.2.4 version is bad

### ISSUE THREAD

**Issue by hopezhangbo** [dbeaver/dbeaver#7181]
![image](https://user-images.githubusercontent.com/20311966/68440258-6b821280-0205-11ea-9941-2b6c00d59dbe.png)
this is 6.2.3 version,format "case when".it's ok.

---------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/20311966/68440363-cae02280-0205-11ea-988e-91cebab602f4.png)
this is 6.2.4 version,format "case when". it's different and is bad.

**Comment by uslss** [comment]
Could you add additional info?
It is unclear what the problem appears

**Comment by hopezhangbo** [comment]
I submitted more information for your reference

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
reopened. still reproducible
![image](https://user-images.githubusercontent.com/31996417/68671435-5cca9100-0560-11ea-97a1-b4275b895169.png)

**Comment by p91paul** [comment]
don't you miss a comma after "as first_name"?

**Comment by hopezhangbo** [comment]
Your syntax is wrong, case when end needs comma

**Comment by uslss** [comment]
verified
