### ISSUE TITLE
Database Task: Export doesn't respect mapping to existing table

### ISSUE THREAD

**Issue by hlampert** [dbeaver/dbeaver#7225]
#### System information: 
- Operating system (distribution) and version: Windows 10, ver 1803
- DBeaver version: 6.2.4.201911031605
- Additional extensions: none

#### Connection specification:
- Database name and version:  From:  CSV    To:  PostgreSQL 10
- Driver name:  From:  Flat files / CSV,  To:   PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
When doing an export from a CSV data connection using a database task,  setting the Data Target type to Database and picking an existing table in the PostgreSQL connection, and perfroming the field mapping, and pressing start, the export creates a new table in the PostgreSQL schema with the same name as the source CSV, disregarding the choice of putting the data into an existing table.  This behavior is not exhibited when the CSV source is right-clicked and "Export Data" is selected;  in that case although the dialogue is similar, when an existing table with a different name than the source is selected data is exported to the existing table.

**Comment by michael-newsrx** [comment]
having this issue here with trying to export mariadb to mariadb from a select query, it keeps trying to create table with the name being the entire select query

This is even though I am selecting an existing table to export into.

![image](https://user-images.githubusercontent.com/5214185/70646309-a2888100-1c14-11ea-9631-2b52436e551e.png)

![image](https://user-images.githubusercontent.com/5214185/70646321-a87e6200-1c14-11ea-9a4d-64f844473db3.png)

**Comment by michael-newsrx** [comment]
having this issue here with trying to export mariadb to mariadb from a select query, it keeps trying to create table with the name being the entire select query

This is even though I am selecting an existing table to export into.

Downgrading to 6.2.5 seems to be a workaround.

![image](https://user-images.githubusercontent.com/5214185/70646309-a2888100-1c14-11ea-9631-2b52436e551e.png)

![image](https://user-images.githubusercontent.com/5214185/70646321-a87e6200-1c14-11ea-9a4d-64f844473db3.png)

**Comment by serge-rider** [comment]
Still can't reproduce. 
Generally data transfer checks that target table exists and creates it only if it doesn't.

Do you export into the same physical database or in another one?
Is there anything in the error log (https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by michael-newsrx** [comment]
I'm currently using 6.2.5 to perform my migration and I'm not in a 
position to retry 6.3.0 until this is complete.

I'm migrating between two mariadb instances.

I was also getting the same type of issues when trying to migrate from a 
CSV backed table where either a: it would try to create an existing 
table, or b: try and create columns via alter table based on original 
column names after I had added mappings to already existing columns.

It is behaving as if any (or most) of the changes to the initial 
auto-detected starting parameters are not being saved back into or 
picked being picked up by the actual export module.

**Comment by kseniiaguzeeva** [comment]
I have the same with "trying to export mariadb to mariadb from a select query, it keeps trying to create table with the name being the entire select query."
Thank you for the bug report.

**Comment by kseniiaguzeeva** [comment]
2. When I use Import task to import a csv file to an existed table:
-a mistake appears "Index -1 out of bounds for length 5" 
-the import fails 
Please try to import csv file "language" into Kseniia.language (MariaDB/MySQL)

P.S. The same import is successful in DB Navigator.

[_language__202001122200.txt](https://github.com/dbeaver/dbeaver/files/4051209/_language__202001122200.txt)
[.log](https://github.com/dbeaver/dbeaver/files/4051210/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4051211/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by serge-rider** [comment]
Fixed2

**Comment by kseniiaguzeeva** [comment]
Task still can't be run.
[run_202001171528_5.log](https://github.com/dbeaver/dbeaver/files/4076775/run_202001171528_5.log)
[.log](https://github.com/dbeaver/dbeaver/files/4076776/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4076777/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Seems to be corrupted task config (no target database schema specified).
Is it reproducible?

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it now- verified (case with "to create table with the name being the entire select query.")

Please reopen the ticket if other described here cases still can be reproduced.
