### ISSUE TITLE
er diagram export fails

### ISSUE THREAD

**Issue by jernejkubuntu** [dbeaver/dbeaver#7300]
#6929 was fixed for me in 6.2.4.

#### System information: 
Kubunutu 19.10
- DBeaver version
6.2.5
- Additional extensions
none

#### Steps to reproduce, if exist:
When exporting as a gif, to new file name:
!ENTRY org.jkiss.dbeaver.model 4 0 2019-11-27 07:03:33.760
!MESSAGE Index 923536 out of bounds for length 923536
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 923536 out of bounds for length 923536
	at org.eclipse.swt.graphics.ImageLoader.save(ImageLoader.java:519)
	at org.jkiss.dbeaver.ext.erd.export.ERDExportRasterImage.exportDiagram(ERDExportRasterImage.java:86)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.saveDiagramAs(ERDEditorPart.java:677)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.doSaveAs(ERDEditorPart.java:289)
	at org.eclipse.ui.internal.handlers.SaveAsHandler.execute(SaveAsHandler.java:45)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
	at jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by hemantachhami19** [comment]
+1

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D35](https://dbeaver.testquality.com/project/8805/result/1743407/defect/6070). Do not remove or edit.

**Comment by serge-rider** [comment]
Perhaps it was fixed in latest Eclipse. Please check 6.3.2

**Comment by jernejkubuntu** [comment]
6.3.2 - does **not** work

opened an existing diagram, export image, overide existing png file, give error:
> Index 544544 out of bounds for length 544544

new diagram, not connected to db, inside just a note lement.
empty test model used:[test.erd.tar.gz](https://github.com/dbeaver/dbeaver/files/4029446/test.erd.tar.gz)
result: 
![t23](https://user-images.githubusercontent.com/43403419/71878218-63722080-312b-11ea-9f6a-f4d2dfb2bfdb.png)
corrupted img.

**Comment by uslss** [comment]
Confirmed. Still reproducible
![Untitled](https://user-images.githubusercontent.com/31996417/71971368-87149400-321b-11ea-948f-fc9288ef5e44.png)

**Comment by maurom** [comment]
I get the same results as @uslss, and can confirm that this is not new. I haven't been able to generate an useful diagram since 6.2.5 at least, no matter if it's bmp, gif or png. 

No error message on image generation, though.

Tested: 6.2.5 up to 6.3.2
Current:
```
2020-01-09 10:10:01.707 - DBeaver 6.3.2.202001051908 is starting
2020-01-09 10:10:01.709 - OS: Linux 5.4.8 (amd64)
2020-01-09 10:10:01.710 - Java version: 11.0.5 by Debian (64bit)
2020-01-09 10:10:01.710 - Install path: '/usr/share/dbeaver'
2020-01-09 10:10:01.711 - Instance path: 'file:/home/user/.local/share/DBeaverData/workspace6/'
```
[startup.log](https://github.com/dbeaver/dbeaver/files/4040514/startup.log)

I'll do my best to test some previous versions.

**Comment by maurom** [comment]
Tested 

6.2.0 some tables end up out of the canvas at the right border, but otherwise ok
6.2.1 idem
6.2.2 java.lang.ArrayIndexOutOfBoundsException on some ERDs
6.2.3 some tables end up out of the canvas at the right border, but otherwise ok
6.2.4 idem
6.2.5 Index 2658320 out of bounds for length 2658320 on some ERDs, broken image on others
...
6.3.5 idem

Indeed, it seems something got broken between 6.2.4 and 6.2.5

**Comment by serge-rider** [comment]
Seems to be a bug in Eclipse platform 2019-06+
We migrated to it in 6.2.2.

**Comment by uslss** [comment]
custom diagram export log
```
> eclipse.buildId=unknown
> java.version=11.0.4
> java.vendor=Oracle Corporation
> BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
> Command-line arguments:  -os linux -ws gtk -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Sun Jan 12 15:50:04 MSK 2020
> Index 9566260 out of bounds for length 9566260
> 
> java.lang.ArrayIndexOutOfBoundsException: Index 9566260 out of bounds for length 9566260
> 	at org.eclipse.swt.graphics.ImageLoader.save(ImageLoader.java:515)
> 	at org.jkiss.dbeaver.ext.erd.export.ERDExportRasterImage.exportDiagram(ERDExportRasterImage.java:86)
> 	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.saveDiagramAs(ERDEditorPart.java:677)
> 	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.doSaveAs(ERDEditorPart.java:289)
> 	at org.eclipse.ui.internal.handlers.SaveAsHandler.execute(SaveAsHandler.java:45)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
> 	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:785)
> 	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:762)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5676)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4935)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4429)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:232)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
> 
```

**Comment by felangga** [comment]
My temporary solution was downgrade to 6.2.0

**Comment by serge-rider** [comment]
Fixed (the bug was in 8bit color translator).
Additionally HighDPI monitors support was fixed.

**Comment by uslss** [comment]
verified
