### ISSUE TITLE
Connection type issue

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7316]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.3.0

#### Describe the problem you're observing:
Connection type is reset after type editing
#### Steps to reproduce, if exist:
1. Open Edit connection (F4) - General
2. Change Connection Type (e.g. from Development to Production)
3, Click Edit button and switch back to previous window - Check Connection Type - it is reset to development

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Reopened. Issue is still reproducible
![2019-12-05_14h36_32](https://user-images.githubusercontent.com/31996417/70232118-c22f2d80-176c-11ea-98d5-a2e709eef55e.gif)

**Comment by serge-rider** [comment]
Changing connection type in edit dialog doesn't affect particular connection settings.

We'll make UI less confusing: 
![image](https://user-images.githubusercontent.com/6398845/70977571-3d72d680-20bf-11ea-81e6-fc3e9b6e1419.png)

**Comment by uslss** [comment]
verified
