### ISSUE TITLE
Oracle: incorrect behaviour when trigger for View is created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7320]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.0 EA

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
There is no checks if "Create or replace" statement used by user, so if I paste Trigger declaration and try to save it - error appears, because mentioned statement is used twice
![image](https://user-images.githubusercontent.com/31996417/69903751-d5c64700-13ae-11ea-84d8-77aaf413e2e3.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible. alter session and create or replace statements are added in all cases
![image](https://user-images.githubusercontent.com/31996417/70906643-e960e700-2017-11ea-9e69-e6bc40a6b967.png)

**Comment by serge-rider** [comment]
Also fixed

**Comment by uslss** [comment]
verified
