### ISSUE TITLE
Database task error

### ISSUE THREAD

**Issue by moizsherwani** [dbeaver/dbeaver#7502]
#### System information:

- Windows Server 2016 Standard
- DBeaver 6.3.1.201912221734

#### Connection specification:

- Postgre 
- PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

I am trying to import from one postgre table to another and save the import process as a database task. Everything works fine when it is done the first time and the data is imported. Now if I try to edit the task it shows a completely different set of steps and the result of which is that once the database task is edited and saved it cannot be run again and comes up with an error

#### Steps to reproduce, if exist:

![Step 1](<https://user-images.githubusercontent.com/18292994/71605842-50f26700-2bc0-11ea-8ec5-4bd816badc5c.PNG>)<br>

![Step 2](<https://user-images.githubusercontent.com/18292994/71605843-50f26700-2bc0-11ea-9a8d-19215adcd743.PNG>)<br>

![Step 3](<https://user-images.githubusercontent.com/18292994/71605844-50f26700-2bc0-11ea-9558-cf63dd2f7802.PNG>)<br>

![Step 4](<https://user-images.githubusercontent.com/18292994/71605846-518afd80-2bc0-11ea-91c5-ce1cb9777c03.PNG>)<br>

![Step 5](<https://user-images.githubusercontent.com/18292994/71605847-518afd80-2bc0-11ea-82e5-aae2560548b6.PNG>)<br>

![Step 6](<https://user-images.githubusercontent.com/18292994/71605849-518afd80-2bc0-11ea-91be-187e2c97f030.PNG>)<br>

![Step 7](<https://user-images.githubusercontent.com/18292994/71605850-52239400-2bc0-11ea-85e4-f4fa498cad27.PNG>)<br>

![Step 8](<https://user-images.githubusercontent.com/18292994/71605851-52239400-2bc0-11ea-9e4a-314da764c44f.PNG>)<br>

![Step 9](<https://user-images.githubusercontent.com/18292994/71605852-52239400-2bc0-11ea-8b9b-3e0c67414aed.PNG>)<br>

![Step 10](<https://user-images.githubusercontent.com/18292994/71605853-52239400-2bc0-11ea-98ad-ecca33a372bb.PNG>)<br>

![Step 11](<https://user-images.githubusercontent.com/18292994/71605854-52bc2a80-2bc0-11ea-99ba-a00a561a4bb0.PNG>)<br>

![Step 12](<https://user-images.githubusercontent.com/18292994/71605855-52bc2a80-2bc0-11ea-8709-f4df0b135f27.PNG>)

**Comment by serge-rider** [comment]
@kseniiaguzeeva coudl you take a look?

**Comment by kseniiaguzeeva** [comment]
Have the same. @serge-rider please try following steps to reproduce:
1. select "import data" in DB Navigator (postgres.Kseniia.partners2)>Table>Next btn
2. select source table (postgres.public.partners)>go through the Wizard> press "save configuration as task">press "Start"
3. Go to "Database tasks" panel and open this task.

Actual result:
1. 2 tables (source and target) in "import into" field
2. The next wizard steps are not "import" steps
![Y09YcKS97X](https://user-images.githubusercontent.com/51405061/71776825-c6877a00-2fa8-11ea-8376-a6d3892ad1bd.gif)

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D46](https://dbeaver.testquality.com/project/8805/result/1761191/defect/6101). Do not remove or edit.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Unfortunately the bug still exists.
![wFjaUycWV6](https://user-images.githubusercontent.com/51405061/71805050-3ca5e280-3076-11ea-8a17-d6e318875bb1.gif)

**Comment by serge-rider** [comment]
Pages initialization was fixed.
Import config pages (db->db) will turn into export config pages (db->db) after saving to task. This is ok, from my perspective. These pages do basically the same but export config has more options.

**Comment by serge-rider** [comment]
Also please test it with export/import with CSV files.

**Comment by kseniiaguzeeva** [comment]
Verified.
Just in case please note, db-db and csv-db import task wizards are different now if you reopen them for editing.
![1](https://user-images.githubusercontent.com/51405061/71846061-ba033e80-30da-11ea-9bd2-a13d1059c704.png)
![2](https://user-images.githubusercontent.com/51405061/71846068-bec7f280-30da-11ea-87e1-2c004a2576be.png)
