### ISSUE TITLE
Snowflake: View issues

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7688]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Snowflake

#### Describe the problem you're observing:
1. View cannot be edited - Create View statement is always used
2. View could be saved only with fully qualified name 
![image](https://user-images.githubusercontent.com/31996417/72682356-36cfe880-3add-11ea-866e-1539ff447155.png)
3. After view saving and reopening additional ";" appears
![image](https://user-images.githubusercontent.com/31996417/72682374-70085880-3add-11ea-8ba0-84842d083381.png)

**Comment by serge-rider** [comment]
Fixed (we will use fully qualified names in CREATE VIEW statement)

**Comment by uslss** [comment]
Reopened

1. View cannot be edited - Create View statement is always used - **Not fixed**
2. View could be saved only with fully qualified name - **Fixed**
3. After view saving and reopening additional ";" appears - **Not fixed**

**Comment by serge-rider** [comment]
1. cannot be implemented. We get view definition from snowflake server.
3. Fixed

**Comment by uslss** [comment]
verified
