### ISSUE TITLE
Export from Query not working, giving Task Execution Failed w/ no reason 

### ISSUE THREAD

**Issue by Arkamedez** [dbeaver/dbeaver#7731]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise Edition 64-bit OS Build 18362.592
- DBeaver version: 6.3.3.202001191557
- Additional extensions: None

#### Connection specification:
- Database name and version: IBM Informix Dynamic Server and Netezza
- Driver name : ifxjdbc.jar and nzjdbc.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
Export from Query not working, giving Task Execution Failed w/ no reason 

#### Steps to reproduce, if exist:
Right Click SQL statement > Execute Menu > Execute From Query
Target is CSV, 
![image](https://user-images.githubusercontent.com/23586875/73015323-cc26f180-3de9-11ea-91e6-c100cde8050d.png)

Choose default output options

![image](https://user-images.githubusercontent.com/23586875/73015349-d943e080-3de9-11ea-86ff-1ee7384c0a9d.png)

Confirmation screen
![image](https://user-images.githubusercontent.com/23586875/73015446-0b554280-3dea-11ea-9ac1-7dc4f055b799.png)

#### Include any warning/errors/backtraces from the logs
from .log file

!ENTRY org.jkiss.dbeaver.model 4 0 2020-01-23 14:09:54.354
!MESSAGE Error transfering data from SELECT * FROM store_inventory
where inventory_date = '2020-01-20'
and store_nbr = 3328 to store_inventory_202001231409.csv
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-01-23 14:09:54.354
!MESSAGE 
!STACK 0
java.lang.IllegalArgumentException: 
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:50)
	at org.jkiss.dbeaver.model.text.parser.TPRuleBasedScanner.checkRange(TPRuleBasedScanner.java:116)
	at org.jkiss.dbeaver.model.text.parser.TPRuleBasedScanner.setRange(TPRuleBasedScanner.java:88)
	at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.parseParameters(SQLScriptParser.java:524)
	at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:93)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:214)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:159)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:138)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2020-01-23 14:09:54.423
!MESSAGE 
!STACK 0
java.lang.IllegalArgumentException: 
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:50)
	at org.jkiss.dbeaver.model.text.parser.TPRuleBasedScanner.checkRange(TPRuleBasedScanner.java:116)
	at org.jkiss.dbeaver.model.text.parser.TPRuleBasedScanner.setRange(TPRuleBasedScanner.java:88)
	at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.parseParameters(SQLScriptParser.java:524)
	at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:93)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:214)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:159)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:138)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Screenshot of error
![image](https://user-images.githubusercontent.com/23586875/73015487-20ca6c80-3dea-11ea-93f8-e107ea88c8a8.png)

**Comment by Cris70** [comment]
I'm seeing this too. I'm on Linux, same DBeaver release.

**Comment by vitortle** [comment]
Facing the same problem. Same version, windows 10.

**Comment by bnielsen1504** [comment]
Same.  Mac OS current.

**Comment by j-coates** [comment]
Also getting this on one of my SQL Server connections, but not one of my Oracle connections.  Windows 7

**Comment by tourdownunder** [comment]
I've just come across this on 6.3.3 as well on Windows 10 with redshift driver.

I uninstalled and reinstall 6.3.2 with success.

**Comment by braiam** [comment]
Curiously, using "Export data..." from the result panel doesn't fail.

**Comment by alexsah** [comment]
Been experiencing the same on Mac OS 10.14.6 

This is on MYSQL and DB2.

I am at least getting a java.lang.NullPointerException from the Details for both:
![Screen Shot 2020-01-29 at 10 42 16 am](https://user-images.githubusercontent.com/964199/73315415-2a3d5400-4284-11ea-97c3-5a4b4850a47c.png)

**Comment by wdiclemente** [comment]
Same issue, 
Mac OS 10.14.6
DBeaver 6.3.3

**Comment by amzbiz** [comment]
Same issue, Windows 10 & PostgreSQL. This is major, going back to old version.

**Comment by dbeaveroo** [comment]
Same problem. MySQL...

**Comment by j-coates** [comment]
Possibly fixed in 6.3.4 if anyone else can also confirm.

**Comment by wdiclemente** [comment]
> Possibly fixed in 6.3.4 if anyone else can also confirm.

It still did not work for me on 6.3.4

**Comment by alexsah** [comment]
This is working inconsistently for me.

Some queries no problem. 

Seems to be consistent, query to query though. Let me know if there's anything I can forward you to assist.

**Comment by msebzd494** [comment]
Same issue for me.

**Comment by serge-rider** [comment]
There were a few fixes in SQL parser and in XLSX exporter. I can't reproduce these errors anymore.
Please check in Early Access version (https://dbeaver.io/files/ea).

**Comment by tourdownunder** [comment]
> There were a few fixes in SQL parser and in XLSX exporter. I can't reproduce these errors anymore.
> Please check in Early Access version (https://dbeaver.io/files/ea).

I just installed dbeaver-ce-6.3.5-x86_64-setup.exe  a short time ago on windows 10 and it worked perfectly. Thanks

**Comment by alexsah** [comment]
It worked for one query - and failed for two others. no real difference between the three apart from date ranges, but it doesn't even attempt to execute the query for me.

Across both DB2 and MYSQL - first time seemed to work and then failed all subsequent attempts.
![Screen Shot 2020-02-10 at 10 53 12 am](https://user-images.githubusercontent.com/964199/74112789-9197c400-4bf3-11ea-957e-a00086fc76f5.png)


This is dbeaver-ce-6.3.5-macosx.cocoa.x86_64

**Comment by serge-rider** [comment]
@alexsah please try EA version (see above), this bug has to be fixed there.

**Comment by alexsah** [comment]
> @alexsah please try EA version (see above), this bug has to be fixed there.

I did.

Downloaded again just to confirm - still failing on subsequent attempts.
<img width="626" alt="Screen Shot 2020-02-11 at 2 15 20 pm" src="https://user-images.githubusercontent.com/964199/74208798-29231280-4cd9-11ea-82dc-162fd1c3fdfb.png">

**Comment by serge-rider** [comment]
@alexsah Please post error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)
I can't reproduce this.

**Comment by serge-rider** [comment]
@alexsah Also, it is possible that job fails because it has old configuration format. If nothing helps try to recreate task.

**Comment by serge-rider** [comment]
Reproduced + one more fix committed.

**Comment by uslss** [comment]
verified

**Comment by matek075** [comment]
I still have this issue 

![Image](https://github.com/user-attachments/assets/dbdca271-0aa3-4055-8079-5e5e96720169)
