### ISSUE TITLE
[MySQL] Export from Query to DB table doesn't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7910]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 6.3.5

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Export from Query to DB table doesn't work.

#### Steps to reproduce, if exist:
Write any select query in SQL Editor
Select Export fron Query in context menu of SQL Editor or in Resultset
Select "Target": Database and press Next
Press Browse or New for Target column>Error message appears: No database selected
Go through the wizard and press Start

Actual result:
Error message appears: No database selected
The export is failed

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4204344/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/4204348/default.log)
![3CDNBCMWMd](https://user-images.githubusercontent.com/51405061/74530295-c0d36b80-4f3a-11ea-8797-746e4b2388fc.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Export from resultset still doesn't work, but another error is displayed.
Steps:

1. Execute a select query
2. Make export from query to a database> the result is successful
3. Make export from resultset to a database.
Actual result:
Error message appears "Field 'smth' doesn't have a default value".
The imported tables appears without a content.

P.S. Another error message appears if "timestamp" column exists in the exported table: "Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]" (in the settings format "yyyy-MM-dd HH:mm:ss" is set in database and global settings
[.log](https://github.com/dbeaver/dbeaver/files/4207915/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4207916/dbeaver-debug.log)
![3mJQMcgf22](https://user-images.githubusercontent.com/51405061/74584461-a0132080-4fe3-11ea-8748-4040c38b286b.gif)

**Comment by kseniiaguzeeva** [comment]
Described export works on the latest version.
