### ISSUE TITLE
Production connection type causes error on Informix editor

### ISSUE THREAD

**Issue by jmhg92** [dbeaver/dbeaver#8007]
#### System information: 
- Operating system (distribution) and version
Windows 7 x64

- DBeaver version
6.3.5.202002151353

- Additional extensions
N/A

#### Connection specification:
- Database name and version
IBM Informix Dynamic Server Version 12.10.FC8W2

- Driver name
ifxjdbc

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
If I go to `Edit Connection > General` and select `Connection type: Production`, whenever I open an editor associated with this connection I get the following error:

    Can't open editor connection
    
    Reason:
    SQL Error [IX000]: Must terminate transaction before closing database.

If I select `Connection type: Development` the error doesn't occur. I even tried changing the settings for the production type but still doesn't work.

#### Include any warning/errors/backtraces from the logs
    Connect with 'PROD-informix' (informix-1708194876a-1112987c4c300631)
    Execution context opened (PROD-informix; Main; 29)
    Execution context opened (PROD-informix; Metadata; 30)
    Connected (informix-1708194876a-1112987c4c300631, IBM Informix JDBC Driver for IBM Informix Dynamic Server [4.10.JC2])
    Execution context opened (PROD-informix; SQLEditor <informix-prod.sql>; 31)
    Error while initializing context state
    org.jkiss.dbeaver.model.exec.DBCException: SQL Error [IX000]: Must terminate transaction before closing database.
    	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:160)
    	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:188)
    	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:138)
    	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:120)
    	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:581)
    	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    Caused by: java.sql.SQLException: Must terminate transaction before closing database.
    	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
    	at com.informix.jdbc.IfxSqli.a(IfxSqli.java:3127)
    	at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3407)
    	at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2324)
    	at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2249)
    	at com.informix.jdbc.IfxSqli.c(IfxSqli.java:1321)
    	at com.informix.jdbc.IfxSqli.executeExecute(IfxSqli.java:2179)
    	at com.informix.jdbc.IfxSqli.executeExecute(IfxSqli.java:2132)
    	at com.informix.jdbc.IfxResultSet.b(IfxResultSet.java:394)
    	at com.informix.jdbc.IfxStatement.a(IfxStatement.java:1333)
    	at com.informix.jdbc.IfxPreparedStatement.d(IfxPreparedStatement.java:449)
    	at com.informix.jdbc.IfxPreparedStatement.execute(IfxPreparedStatement.java:434)
    	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
    	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:156)
    	... 6 more
    Caused by: java.sql.SQLException
    	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
    	at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3412)
    	... 17 more
    org.jkiss.dbeaver.model.exec.DBCException: SQL Error [IX000]: Must terminate transaction before closing database.
    	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:241)
    	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:1)
    	at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:371)
    	at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:328)
    	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:588)
    	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    Caused by: java.sql.SQLException: Must terminate transaction before closing database.
    	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
    	at com.informix.jdbc.IfxSqli.a(IfxSqli.java:3127)
    	at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3407)
    	at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2324)
    	at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2249)
    	at com.informix.jdbc.IfxSqli.c(IfxSqli.java:1321)
    	at com.informix.jdbc.IfxSqli.executeExecute(IfxSqli.java:2179)
    	at com.informix.jdbc.IfxSqli.executeExecute(IfxSqli.java:2132)
    	at com.informix.jdbc.IfxResultSet.b(IfxResultSet.java:394)
    	at com.informix.jdbc.IfxStatement.a(IfxStatement.java:1333)
    	at com.informix.jdbc.IfxPreparedStatement.d(IfxPreparedStatement.java:449)
    	at com.informix.jdbc.IfxPreparedStatement.execute(IfxPreparedStatement.java:434)
    	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
    	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:237)
    	... 6 more
    Caused by: java.sql.SQLException
    	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
    	at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3412)
    	... 17 more
    Execution context closed (PROD-informix, 29)
    Execution context closed (PROD-informix, 30)
    Execution context closed (PROD-informix, 31)
    Disconnected (informix-1708194876a-1112987c4c300631)

**Comment by finlbi** [comment]
I'm experiencing the same issue and I'm able to reliably reproduce the error in 6.3.5 and 7.0.0

**Comment by finlbi** [comment]
It's possible this is being caused by a combination of using the "Production" connection type and having "Auto-commit by default" setting (under DBeaver > Connection Types) unselected.

**Comment by cesaralves** [comment]
> It's possible this is being caused by a combination of using the "Production" connection type and having "Auto-commit by default" setting (under DBeaver > Connection Types) unselected.

Setting connection default to auto-commit allows me to bypass the problem. After connecting you can switch back to manual commit

**Comment by serge-rider** [comment]
I've improved SQL editor connection init. 
1. It shouldn't re-set active database if it is the same as connection default
2. Active database switch error isn't fatal (even if it will fail connection will be established).

**Comment by uslss** [comment]
verified

**Comment by jmhg92** [comment]
> verified

The error message still appears in version 7.0.1.202003211804 but now it allows to execute SQL scripts.

**Comment by uslss** [comment]
still reproducible against 7.2.0

**Comment by LonwoLonwo** [comment]
Now Informix support is in [Dbeaver-EE](https://dbeaver.com/download/) version. There the problem of changing the default database in the production mode was fixed.
Workaround for the CE version - enable the auto-commit mode before opening the SQL-editor.

**Comment by jmhg92** [comment]
The error message is still present in version 7.2.2.202010041557

    Error setting default catalog/schema for new connection
    
    Reason:
    SQL Error [IX000]: Must terminate transaction before closing database.

As for the workaround:

> Now Informix support is in [Dbeaver-EE](https://dbeaver.com/download/) version. There the problem of changing the default database in the production mode was fixed.
> Workaround for the CE version - enable the auto-commit mode before opening the SQL-editor.

Setting the production connection to `auto-commit` by default works, but this seems like a security risk since one might forget to set it back to manual mode on connection before modifying something on a production DB. This would defeat the purpose of having a production connection type in my opinion.

**Comment by LonwoLonwo** [comment]
@jmhg92 Error fixed in DbeaverEE-version. Early access will be here soon: https://dbeaver.com/files/ea/

**Comment by jmhg92** [comment]
> @jmhg92 Error fixed in DbeaverEE-version. Early access will be here soon: https://dbeaver.com/files/ea/

Sorry to bother again with this issue but is there a CE version number when the fix will be implemented?

I installed the early access version 7.3.1.202012141915 and the error is still present.

**Comment by LonwoLonwo** [comment]
Hello @jmhg92 
As mentioned above, we have fixed a bug in the EE version. We are not planning to fix the CE version. You can use the specified workaround or [use EE version](https://dbeaver.com/)
Best regards, DBeaver team
