### ISSUE TITLE
[DB2] References are not displayed properly

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8063]
## System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.0

#### Connection specification:
- Database name and version DB2 LUW

#### Describe the problem you're observing:
I Table references are not displayed if to press Ctrl+1 in Data Editor.

1. Open a source table in Data Editor
2. Press "Ctrl+1"
Actual result:
"no reference" sign is displayed in the opened popup.

II Only all rows of referenced table are displayed in reference panel.

1. Open Reference Panel for the same table
2. Select 1 row only in the source table.
Actual result:
All rows of referenced table are displayed in Reference table

_P.S. Schema TEST can be used to see the issue._
![oqsRMTTveL](https://user-images.githubusercontent.com/51405061/75760695-bd1c5300-5d48-11ea-9bd8-a756d2ddab31.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Unfortunately the bug still exists:
1. Ctrl+1 doesn't display references in Source table.
2. All rows of Reference table are displayed in Reference Panel even if only one row is selected in Source table

Steps.
1. Open table TEST.8063
2. Open Reference Panel
3. Select 1 row in table TEST.8063
4. Press Ctrl+1

Actual result:
1. All rows of Reference table are displayed in Reference Panel.
2. Popup (displayed after pressing Ctrl+1) doesn't dispay the reference

![dbeaver_ycLvFy1PKA](https://user-images.githubusercontent.com/51405061/76159059-b1a49f80-612d-11ea-984a-b5e0713c8ae3.png)

**Comment by kseniiaguzeeva** [comment]
verified
