### ISSUE TITLE
[PostgreSQL] Backup "Discard objects owner" is silently ignored in some cases

### ISSUE THREAD

**Issue by rogerioyuuki** [dbeaver/dbeaver#8074]
#### System information: 
- Windows 10 Enterprise
- DBeaver v7.0.0

#### Connection specification:
- PostgreSQL 11
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When doing the backup of a PostgreSQL database with this options:
![image](https://user-images.githubusercontent.com/11280342/75816971-ebb02300-5d74-11ea-8729-31e86a752311.png)

This backup will restore the objects owners even with the "Discard objects owner" option checked.

According to the [documentation](https://www.postgresql.org/docs/11/app-pgdump.html), pg_dump's `--no-owner` option is only valid when the format is plain, and apparently from my experience this is silently ignored otherwise.

When the format is not plain-text, the `--no-owner` option must be used during the [restore](https://www.postgresql.org/docs/11/app-pgrestore.html) instead of the backup. So the following screenshot is a valid workaround for this issue.

![image](https://user-images.githubusercontent.com/11280342/75817505-f8814680-5d75-11ea-82ca-0eaab70327b0.png)

#### Steps to reproduce, if exist:

Backup a database with format "custom" and "discard objects owner"

Restore the backup in another database without any extra arguments. It will restore the owner of the objects even though the backup had the option to discard it.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by eSargin** [comment]
the problem still persists
![apeiron-api](https://user-images.githubusercontent.com/18756378/146376523-d170d21f-baa2-462d-a916-3442ff8514a0.gif)
