### ISSUE TITLE
SEC$ tables and other system objects shows for Firebird 3.0 userspace without special flag

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#8181]
#### System information: 
- Operating system (distribution) and version
Linux Mint
- DBeaver version
7.0.0
- Additional extensions
No
#### Connection specification:
- Database name and version
Firebird 3.0
- Driver name
maven:/org.firebirdsql.jdbc:jaybird-jdk18:RELEASE 3.0.8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
System tables shows near user tables, but there is "no/false" in flag "show system tabes"
#### Steps to reproduce, if exist:
Create any void fdb file, connect to it.

It seems there is 2 filters for system objects: name by XXX$**** and system flag in metadata. In this case flag is ignored, but there is no other system tables. The flag in metadata is universal filter for Firebird 2.5+, but prefix in names can be changed/added by developers of FB.

![image](https://user-images.githubusercontent.com/41448637/76605002-c6fc3e00-6520-11ea-866c-39ade42fd669.png)

The same with sequences
![image](https://user-images.githubusercontent.com/41448637/76605745-0ecf9500-6522-11ea-8b21-ad50e58398a2.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Done. We used JDBC API for FB tables read, now I query RDB$RELATIONS directly so we have a real system table flag.

**Comment by mkgrgis** [comment]
Reopened for 7.1.1+ (tested for 7.1.4)
Linux, Firebird 3.0, org.firebirdsql.jdbc.FBDriver , 4.0.0.java8
maven:/org.firebirdsql.jdbc:jaybird:RELEASE 

![изображение](https://user-images.githubusercontent.com/41448637/89927859-a2131080-dc0f-11ea-8dce-a76eebaaf5a8.png)

**Comment by LonwoLonwo** [comment]
@mkgrgis the problem is still actual for you? Does the problem remain in full or partially?

**Comment by mkgrgis** [comment]
7.2.5 issue is actual. There is 50 system tables in userspace catalogue of tables.

**Comment by LonwoLonwo** [comment]
@mkgrgis thanks for the bug report.

**Comment by akilovich** [comment]
The issue also exists on the 2.5 version of Firebird.

**Comment by LonwoLonwo** [comment]
Hello @mkgrgis 
Have you tried using "Custom view" with no flags?
![2021-02-20 14_38_11-](https://user-images.githubusercontent.com/45152336/108594188-770d3480-7389-11eb-8d15-efb4bb96e49a.png)

![2021-02-20 14_35_00-DBeaver Enterprise 21 0 0 - RDB$INDEX_NAME](https://user-images.githubusercontent.com/45152336/108594189-783e6180-7389-11eb-833a-a5c6871114b0.png)

In this mode I don't see system tables in my connection.

**Comment by mkgrgis** [comment]
Thanks, @LonwoLonwo, this flags works. It was the problem with _advanced_ mode as default.

**Comment by LonwoLonwo** [comment]
Advanced is advanced) 

I have added triggers and sequences in system object list. Now with settings - custom view without any flags - system tables, views, triggers and sequences are not in object list. In Firebird.

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Also you can change "Show system objects" filter here
![2021-02-24 12_55_31-](https://user-images.githubusercontent.com/45152336/109025747-12771000-76d0-11eb-9250-1e08a2f79689.png)
