### ISSUE TITLE
Column filter works incorrectly with date type

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8225]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.1

#### Describe the problem you're observing:
**Exasol**
When I try to filter date column using filter icon, value isn't quoted and error appears
![2020-03-19_15h05_21](https://user-images.githubusercontent.com/31996417/77065885-265fbf80-69f3-11ea-86fd-c9a658b867c7.gif)
**PostgreSQL**
In the same case timestamp values, if they are quoted, become double-quoted and it leads to error
![2020-03-19_15h08_23](https://user-images.githubusercontent.com/31996417/77066131-a554f800-69f3-11ea-9137-bc88366f5d6f.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
issue is still reproducible for exasol.
Date format values aren't quoted

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
reopened.
Values are triple-quoted now
![image](https://user-images.githubusercontent.com/31996417/77633648-d045cb80-6f60-11ea-9ab2-b76d237ea42c.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
