### ISSUE TITLE
Generated DDL against SQL Server adds column width to certain datatypes though not applicable

### ISSUE THREAD

**Issue by DanielAdeniji** [dbeaver/dbeaver#8282]
#### System information: 
- Microsoft Windows 10
- DBeaver Version :- 7.1
- Additional extensions

#### Connection specification:
- Database Version :- Microsoft SQL Server - v2017
- Driver name :- Microsoft JDBC v 4
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 

#### Describe the problem you're observing:
When Dbeaver generates a DDL against a table it will sometime add column widths.

In some cases column widths can not be explicitly stated for certain datatypes.

Datatypes that do not support column widths include 

1) picture
2) timestamp

##### DDL - Original ( Hand Entered )
use [tempdb]
go

create schema [datatype] authorization [dbo]
go

create table [datatype].[personImage]
    (
          [id]                int not null  identity(1,1)
        , [tag]              binary(20) not null
        , [fingerPrint]  varbinary(4000) null
        , [signature]    binary null
        , [picture]        image
        , [ts]                timestamp not null
 )
go

##### DDL Generated
CREATE TABLE tempdb.datatype.personImage (
	id int IDENTITY(1,1) NOT NULL,
	tag binary(20) NOT NULL,
	fingerPrint varbinary(4000) NULL,
	signature binary(1) NULL,
	picture image(16) NULL,
	ts timestamp(8) NOT NULL
) GO;

#### Include any warning/errors/backtraces from the logs

Error 1
Msg 102, Level 15, State 1, Line 8
Incorrect syntax near 'GO'.

Error 2
Msg 2716, Level 16, State 1, Line 7
Column, parameter, or variable #5: Cannot specify a column width on data type image.

Error 3
Msg 2716, Level 16, State 1, Line 7
Column, parameter, or variable #6: Cannot specify a column width on data type timestamp.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible for image type
![image](https://user-images.githubusercontent.com/31996417/80391404-5b92e380-88b6-11ea-855c-fe0451a5f1d2.png)

**Comment by serge-rider** [comment]
Umm, it is `image`, not `picture`. 
Fixed

**Comment by uslss** [comment]
verified
