### ISSUE TITLE
Mysql Sessions Manager Execution Plan fails even for SELECT statements

### ISSUE THREAD

**Issue by fanis** [dbeaver/dbeaver#8401]
#### System information: 
- Windows 10 x64, 1909
- DBeaver 7.0
- Additional extensions: none

#### Connection specification:
- Mysql 5.5.8
- Mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

In Session Manager selecting a `SELECT` query and clicking on the "Execution Plan" tab brings up an alert saying the following if the query itself has a comment in front of it, like those running from within DBeaver:

`Only SELECT statements could produce execution plan`

#### Steps to reproduce, if exist:

Execute any long-running SELECT query from within DBeaver. 
It will get a /* comment */ added to its SQL and it will be visible in the Sessions Manager.
Click on that query in the Sessions Manager and click Execution Plan.
You will get the above error.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible in this case
![image](https://user-images.githubusercontent.com/31996417/80092653-ccab6180-856b-11ea-90b9-1fb643e9ba81.png)
but not reproducible in case there is no crlf after comment
![image](https://user-images.githubusercontent.com/31996417/80092696-e9e03000-856b-11ea-9411-a726af243889.png)

**Comment by serge-rider** [comment]
One more fix added

**Comment by uslss** [comment]
verified
