### ISSUE TITLE
.csv or excel import to DBeaver

### ISSUE THREAD

**Issue by Goldstoned** [dbeaver/dbeaver#8556]
Hi

I am very used to SQL Server Management Studio running on Windows OS, but my recent migration to Mac OS no longer allows me to use SSMS as there is no version available. Someone advised to try dbeaver which looks great. The problem I am having is being able to import data from a .csv or .xls using a wizard that also creates the table, much the same as you would in SSMS,. Any ideas? 

Many Thanks

David

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
1. Import Data is available for connection/Catalog(postgresql). Error appears after this option is chosen
![image](https://user-images.githubusercontent.com/31996417/89908450-8d764e80-dbf6-11ea-8d40-09f48ba0a8a7.png)
Stacktrace is empty

**Comment by uslss** [comment]
2. Error appears after choosing import data for Schemas/Database
![image](https://user-images.githubusercontent.com/31996417/89908715-e3e38d00-dbf6-11ea-83b9-3f12ee00f453.png)

**Comment by uslss** [comment]
3. '?' is shown instead of target table. It is clickable - looks quite strange 
![2020-08-11_17h22_10](https://user-images.githubusercontent.com/31996417/89909122-64a28900-dbf7-11ea-91bf-02e68a9925ab.gif)

**Comment by uslss** [comment]
4. Source settings is empty. Csv settings are shown as target settings
![image](https://user-images.githubusercontent.com/31996417/89909909-40937780-dbf8-11ea-94d9-d5d07aaf171a.png)

**Comment by serge-rider** [comment]
1, 2, 4 fixed

**Comment by serge-rider** [comment]
3 is a result of 2. Should be fixed as well.

**Comment by uslss** [comment]
Issues 3 and 4 still reproducible for import to non-existing table.
works ok for import to existing table

**Comment by serge-rider** [comment]
Settings page fixed.
Question mark in the first mapping page is ok. It means that target table is not specified yet.

**Comment by uslss** [comment]
verified
