### ISSUE TITLE
Key error when editing a cell

### ISSUE THREAD

**Issue by lucasMesquitaBorges** [dbeaver/dbeaver#8576]
Hi! Thanks for this project. I enjoy using dbeaver.

I'm having a problem when trying to make inline editing in a cell when the table key are not listed in the result set. The following error is displayed:

> Can't update attribute 'column_name' - attributes of key 'owner.table_name' are missing in result set

I've read [Wiki - Virtual Keys](https://github.com/dbeaver/dbeaver/wiki/Data-Viewing-and-Editing#defining-virtual-keys) but if I understood it right, virtual keys are needed when the table itself doesn't has unique keys, wich it's not my case. I'm just not retrieving the table key at the SQL clause, when I retrieve the key with the cells I want to edit, the editing is done without errors.

I know this doesn't blocks using inline cell editing, I just have to return the table key on the SQL, but without having to do it would really help in daily use.

Is there a way to improve how the row identifier is obtained? Maybe somehow retrieve the key column as hidden when it's not include in the SQL?

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. This make sence.

_P.S. Steps
1. Execute SELECT customer_id, staff_id, rental_id, amount, payment_date
FROM public.payment; for Postgresql.pagila
2. Try to edit a cell in Resultset._

**Comment by serge-rider** [comment]
I think this issue was fixed in 7.1.3 or so.

**Comment by kseniiaguzeeva** [comment]
I can reproduce it in  7.2.0.202008110753. Steps:
1. Execute SELECT customer_id, staff_id, rental_id, amount, payment_date FROM public.payment; for Postgresql.pagila
2. Try to edit a cell in Resultset.

**Comment by lucasMesquitaBorges** [comment]
I'm currently at latest `7.1.4.202008021649` and the problem still occurs. If needed i can show an example table where this problem happens.

Sorry for not being able to help more and again thank you!

**Comment by serge-rider** [comment]
I've improved unique key detection. Now dbeaver won't rely on columns which are not included in the resultset.

**Comment by kseniiaguzeeva** [comment]
Now the window appears to define e a virtual key for a table in ResultSet. The changes become possible as soon as it is created.
Verified
