### ISSUE TITLE
MySQL user management syntax without FLUSH PRIVILEGES

### ISSUE THREAD

**Issue by doublizer** [dbeaver/dbeaver#8857]
#### System information: 
- Operating system (distribution) and version: Linux Mint 19.3 Cinnamon
- DBeaver version: 7.1.0

#### Connection specification:
- Database name and version: MySQL 5.6.10
- Driver name: Driver for MySQL 4.x+
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH Tunnel, yes

#### Describe the problem you're observing:
Wouldn't call it a problem, more like an inconvenient I'm facing on my particular case that I would like to find a workaround:
Using DBeaver's GUI to create or update an user, I noticed that the query used is like the following:
```
GRANT Usage ON *.* TO 'test'@'10.1.%.%';
CREATE USER 'test'@'10.1.%.%';
UPDATE mysql.user SET Password=PASSWORD('example') WHERE User='test' AND Host='10.1.%.%';
GRANT Select ON example.* TO 'test'@'10.1.%.%';
FLUSH PRIVILEGES;
```
Well in my case I don't have server permissions to execute FLUSH PRIVILEGES, making it impossible for me to use the GUI to update user password/privileges using that kind of syntax.
What I would love would be to have the option to use an alternative syntax that does not require FLUSH PRIVILEGES to take effect. 
Perhaps DBeaver could intelligently suggest it based on the currently connected user RELOAD permission, or have any way to set that preference, or simply suggest both (one could appear as commented code, for example)

#### Steps to reproduce, if exist:
Create New User through GUI

Thanks in advance and sorry if this isn't acceptable, but it's a little detail that would help me and probably more people.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
DBeaver uses new syntax (`ALTER USER` instead of `UPDATE mysql.user`) for MariaDB >= 10.2 and MySQL >= 5.7. 
In this case FLUSH PRIVILEGES won't be added to the final script (I've just committed the fix).
Otherwise there is no other way to refresh user privileges.

**Comment by uslss** [comment]
verified

**Comment by doublizer** [comment]
Hi
Just checked you released the new version with the fix, great work, thanks a lot !
Although I just noticed that it still won't solve the problem where mysql version is < 5.7 (which is my case)
I'm wondering if it would be possible/feasible to use this alternative syntax for those cases?
`SET PASSWORD FOR 'user-name-here'@'hostname' = PASSWORD('new-password')`

Sorry for not mentioning it earlier.
Thanks once again and congratulations on this project!
