### ISSUE TITLE
Conditional property visibility

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8923]
Property needs the ability to check Database Management System version
![2020-06-08 17_55_30-Window](https://user-images.githubusercontent.com/45152336/84053245-4f706a80-a9ba-11ea-927a-e9508c6353aa.png)
for example, the parameters for vacuum from the picture only work in the version PostgreSQL 12

**Comment by serge-rider** [comment]
Done.
You can use @Property.visibleIf property.
It can check target database version. See PostgreToolBaseVacuumSettings.isTruncated for sample

**Comment by uslss** [comment]
options like "Skip locked" are still shown for postgresql 11

**Comment by serge-rider** [comment]
Particular properties visibility is tracked in the #8893 . This ticket is about model changes and providing possibility to hide a property.
