### ISSUE TITLE
error with Maven driver artifact after restart

### ISSUE THREAD

**Issue by kgeis** [dbeaver/dbeaver#8925]
#### System information: 
- OS: macOS Catalina 10.15.5
- DBeaver 7.1.0.202005311732
- No additional extensions

#### Connection specification:
- Database: [Teiid](http://teiid.io/) 14.0
- Driver name: Teiid
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
Using Database->Driver Manager->New, I created a new driver for Teiid. I used "Add Artifact" with coordinates org.teiid:teiid-client:14.0.0. I clicked Download/Update. When I expanded the artifact, it looked like this:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/2237299/84110844-7ccd1080-a9da-11ea-9fb0-0522422c7893.png">

I created a connection and it worked.

When I restart DBeaver, I try to connect with the same connection, and I get the error:
```
Can't create driver instance
  Error creating driver 'Teiid' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.
Reason: can't load driver class 'org.teiid.jdbc.TeiidDriver'
  Error creating driver 'Teiid' instance.
    org.teiid.jdbc.TeiidDriver
```

To investigate, I go in to the driver manager, and the artifact looks like this:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/2237299/84110581-f87a8d80-a9d9-11ea-86c0-fc4b211a0faa.png">

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
You need to disable "Legacy JDBC" mode in the driver settings:
![image](https://user-images.githubusercontent.com/6398845/84244688-adad6280-ab0c-11ea-85a5-44ce02562310.png)

It is enabled by default for new drivers. It is a bug. 
Fixed.

**Comment by uslss** [comment]
still reproducible
![image](https://user-images.githubusercontent.com/31996417/84384641-f2152d00-abf6-11ea-9ddc-6628a9050bfc.png)

**Comment by serge-rider** [comment]
@kgeis Could you test in Early Access version? (https://dbeaver.io/files/ea)

@uslss what exactly is reproducible? Enabled legacy JDBC flag or non-working Teiid driver or both?

**Comment by serge-rider** [comment]
@uslss driver settings save fixed

**Comment by uslss** [comment]
verified

**Comment by kgeis** [comment]
@serge-rider I installed the EA that you linked to, and it is still broken.

For testing, I set up two drivers for the same database type, and the difference between them is that one has "Use legacy JDBC instantiation" disabled and the other has it enabled. I set up a connection for each of these drivers to test them easily.

As before, the artifact files disappear when I restart DBeaver, regardless of this setting.

**Comment by kgeis** [comment]
@uslss or @serge-rider I have tested this in the EA release and it failed. I see that the EA releases are dated June 3. Can you update them to make sure that serge-rider's fix is included when I test again?

**Comment by serge-rider** [comment]
@kgeis it has to be resolved by now. Could you check it?

**Comment by kgeis** [comment]
Yes, it is working. Thanks.
