### ISSUE TITLE
Triggers and indexes are not shown in the task object selection area

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8974]
![2020-06-15 12_30_43-Window](https://user-images.githubusercontent.com/45152336/84658378-7977de80-af1e-11ea-9a99-9ff8aaf93157.png)
![2020-06-15 15_37_24-Window](https://user-images.githubusercontent.com/45152336/84658380-7a107500-af1e-11ea-9893-3bf93f400084.png)
Triggers in PostgreSQL, Indices in Oracle

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible both for oracle and postgres
![image](https://user-images.githubusercontent.com/31996417/86141799-25165680-bafb-11ea-80b4-8df011146731.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
