### ISSUE TITLE
[Oracle] Export to SQL INSERT statements - not oracle conform

### ISSUE THREAD

**Issue by kasparwalter** [dbeaver/dbeaver#9173]
#### System information: 
- DBeaver version: 7.1.2

#### Connection specification:
- Oracle 12.2
- JDBC

#### Describe the problem you're observing:
The syntax for exporting the Resultset with the "Export to SQL INSERT statements" option is not Oracle conform.
Here is the query that is generated:
`INSERT INTO "emp" (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES 
(7369,'SMITH','CLERK',7902,TIMESTAMP '1980-12-17 00:00:00.000000',800,NULL,20)
,(7499,'ALLEN','SALESMAN',7698,TIMESTAMP '1981-02-20 00:00:00.000000',1600,300,30)
,(7521,'WARD','SALESMAN',7698,TIMESTAMP '1981-02-22 00:00:00.000000',1250,500,30)
;`

**1. Problem:** The tablename has to be without any quotes.

**2. Problem:** Oracle can not insert multiple valuesets like other db's. Eather you generate a lot of single statements, or you use the insert all syntax (that I'm also not very used to).

Example single-inserts:
'INSERT INTO emp (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES 
(7369,'SMITH','CLERK',7902,TIMESTAMP '1980-12-17 00:00:00.000000',800,NULL,20);
INSERT INTO emp (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES 
(7499,'ALLEN','SALESMAN',7698,TIMESTAMP '1981-02-20 00:00:00.000000',1600,300,30);
INSERT INTO emp (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES 
(7521,'WARD','SALESMAN',7698,TIMESTAMP '1981-02-22 00:00:00.000000',1250,500,30);'

Example multi-insert:
`insert ALL INTO scott.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES 
(7369,'SMITH','CLERK',7902,TIMESTAMP '1980-12-17 00:00:00.000000',800,NULL,20)
into scott.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values 
(7499,'ALLEN','SALESMAN',7698,TIMESTAMP '1981-02-20 00:00:00.000000',1600,300,30)
into scott.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values
(7521,'WARD','SALESMAN',7698,TIMESTAMP '1981-02-22 00:00:00.000000',1250,500,30)
select 1 from dual;`

As a reference; Toad an sqldeveloper both do the single-inserts that generate a lot of single Statements.

#### Steps to reproduce, if exist:
Export some query-Results with the "Export to SQL INSERT statements" option

**Comment by serge-rider** [comment]
Thanks for the bug report.

Fixed

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by AllenGFLiu** [comment]
> #### System information:
> * DBeaver version: 7.1.2
> 
> #### Connection specification:
> * Oracle 12.2
> * JDBC
> 
> #### Describe the problem you're observing:
> The syntax for exporting the Resultset with the "Export to SQL INSERT statements" option is not Oracle conform. Here is the query that is generated: `INSERT INTO "emp" (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES (7369,'SMITH','CLERK',7902,TIMESTAMP '1980-12-17 00:00:00.000000',800,NULL,20) ,(7499,'ALLEN','SALESMAN',7698,TIMESTAMP '1981-02-20 00:00:00.000000',1600,300,30) ,(7521,'WARD','SALESMAN',7698,TIMESTAMP '1981-02-22 00:00:00.000000',1250,500,30) ;`
> 
> **1. Problem:** The tablename has to be without any quotes.
> 
> **2. Problem:** Oracle can not insert multiple valuesets like other db's. Eather you generate a lot of single statements, or you use the insert all syntax (that I'm also not very used to).
> 
> Example single-inserts: 'INSERT INTO emp (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES (7369,'SMITH','CLERK',7902,TIMESTAMP '1980-12-17 00:00:00.000000',800,NULL,20); INSERT INTO emp (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES (7499,'ALLEN','SALESMAN',7698,TIMESTAMP '1981-02-20 00:00:00.000000',1600,300,30); INSERT INTO emp (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES (7521,'WARD','SALESMAN',7698,TIMESTAMP '1981-02-22 00:00:00.000000',1250,500,30);'
> 
> Example multi-insert: `insert ALL INTO scott.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES (7369,'SMITH','CLERK',7902,TIMESTAMP '1980-12-17 00:00:00.000000',800,NULL,20) into scott.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7499,'ALLEN','SALESMAN',7698,TIMESTAMP '1981-02-20 00:00:00.000000',1600,300,30) into scott.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7521,'WARD','SALESMAN',7698,TIMESTAMP '1981-02-22 00:00:00.000000',1250,500,30) select 1 from dual;`
> 
> As a reference; Toad an sqldeveloper both do the single-inserts that generate a lot of single Statements.
> 
> #### Steps to reproduce, if exist:
> Export some query-Results with the "Export to SQL INSERT statements" option

[#1745](https://github.com/dbeaver/dbeaver/issues/1745) said they add **some options on the Import Wizard screen**， but still no **options** in Export Resultset screen , so the problem still exists.

**Comment by luupqvinh** [comment]
I have the same problem. Any update on this issue plz?
