### ISSUE TITLE
The dbeaver executable launcher was unable to locate its companion launcher jar

### ISSUE THREAD

**Issue by kintrupf** [dbeaver/dbeaver#9322]
#### System information: 
- Operating system (distribution) and version   Windows 10 1709
- DBeaver version   7.1.3   (7.1.1 and 7.1.2 had the same problem)
- Additional extensions    none

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Clean install from chocolatey package "dbeaver" or downloaded "dbeaver-ce-latest-x86_64-setup.exe".
Launching dbeaver.exe failes with the error message "The dbeaver executable launcher was unable to locate its companion launcher jar".
If I copy the contents of "dbeaver-ce-7.1.3-win32.win32.x86_64.zip" into the install folder it works, so some missing files are obviously added.

I noticed that dbeaver.ini references the file "plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.**jar**" which is NOT installed by chocolatey or the .exe-installer. However, it is present in the .zip-file (which is 10 MB larger than the .exe-installer).
The .exe-installer only includes a file org.eclipse.equinox.launcher_1.5.700.v20200207-2156.**pack**.

I used the .exe-installer on a second machine with Windows 10 1909. Same result.

#### Include any warning/errors/backtraces from the logs

No log is produces, since dbeaver does not start...

**Comment by kseniiaguzeeva** [comment]
Please try to delete DBeaver and make clear install again using https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe

**Comment by kintrupf** [comment]
> Please try to delete DBeaver and make clear install again using https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe

I just tried it on another computer with the .exe-installer you linked above. This computer has never seen dbeaver before, so there was no need to delete anything. Same result, "The dbeaver executable launcher was unable to locate its companion launcher jar". And indeed, there is still no launcher jar in the plugin folder. Windows version this time is Windows 10 Pro 1909.

**Comment by kseniiaguzeeva** [comment]
Could you please see Installator log (where progress runs)? What is written there?
As a workaround you can use zip version for now. While I cannot reproduce it.

**Comment by kintrupf** [comment]
I was able to capture some details from the log and found the smoking gun:

```
Unpack jar "C:\Program Files\DBeaver\plugins\com.github.jsqlparser_3.2.0.packf"
TCC: C:\Program Files\DBeaver\install.cmd [6]  Unknown command "jre\bin\unpack200.exe"

```
TCC is my command processor (replacement for cmd.exe) and my comspec environment variable is set to it.
"C:\Program Files\DBeaver\jre\bin\unpack200.exe" exists, but maybe the current working directory is set wrong, so that "jre\bin\unpack200.exe" is not found?

Setting the comspec environment variable to cmd.exe before launching the installation works.
But I still think there could be something wrong in the installer, I'm using TCC for many years on all of my systems, and there never has been any compatibility issue like this.

But I'll check first if there is any compatibility switch in TCC settings that can fix this on my side.

**Comment by kseniiaguzeeva** [comment]
Finally I manage to reproduce it with TCC LE.

**Comment by kintrupf** [comment]
The strange thing is: I managed to "capture" the install.cmd batch file from "C:\Program Files\dbeaver" which is launched during the install. The batch file fails during the install process with the reported error "Unknown command "jre\bin\unpack200.exe".
But if I launch this batch file directly from the TCC LE prompt from the folder "C:\Program Files\dbeaver" and the parameter "plugins" it works, TCC LE executes it without problems and the .jar files are created.

`C:\Program Files\dbeaver> install.cmd plugins`

**Comment by serge-rider** [comment]
Installer was fixed (I got rid of standard cmd.exe usage)

**Comment by kintrupf** [comment]
That sounds great! Thank you very much for your  #effort 😊

**Comment by kseniiaguzeeva** [comment]
Still can reproduce (7.1.3.202007260900). Steps:
1. run TCC LE https://jpsoft.com/products/tcc-le.html
2. go to directory with DBeaver exe file (cd...)
3. enter file name (dbeaver-ce-7.1.3-x86_64-setup.exe) and press Enter
4. install DBeaver
5. Open installed DBeaver.

Actual result:
Error appears "The dbeaver executable launcher was unable to locate its companion launcher jar"

**Comment by lmayer32** [comment]
Windows 10 Version 1809 OS build 17763.1397

I receive the same result installing:  dbeaver-ce-7.1.5-x86_64-setup.exe

Error appears "The dbeaver executable launcher was unable to locate its companion launcher jar"
I have found 2 files in the ZIP that were not installed - and copied them over.
Now I am on this error:

!SESSION Fri Aug 28 14:10:48 PDT 2020 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2020-08-28 14:10:48.056
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

**Comment by serge-rider** [comment]
The problem is in pack200 archiver invocation during setup process.
On some Windows systems it fails (by different reasons).

Generally all similar problems will be solved closer to version 8. 
We plan to get rid of pack200 archiver in all installers (as it is deprecated anyway).

Workaround - use zip archive instead of installer.

**Comment by lmayer32** [comment]
Thanks for the Suggesting Serge-Rider

I tried the ZIP file also - that failed  it was not complete.

In the end, I used the installer, and then opened the ZIP file to another location - and found the files in the ZIP file that were missing from the installer.  On the version I was attempting to install, neither the ZIP file nor the Installer had all the necessary files - but between the two of them - all the files were present.

**Comment by serge-rider** [comment]
Must be fixed in recent installers version (as we got rid of pack200)

**Comment by Alhimeg** [comment]
Still relevant. Broke after update.

Linux Mint 20.3
dbeaver-ce 22.1.2

**Comment by JaldeaR** [comment]
Broke after update same message:
"The dbeaver executable launcher was unable to locate its companion shared library"

Tried uninstalling doesnt fix it.

Linux Pop!_OS 22.04 LTS
dbeaver-ce 22.1.2

last workig version:
dbeaver-ce 22.1.1

**Comment by cristianslv** [comment]
Hi guys, this worked for me:

1- Download latest version: https://dbeaver.io/download/
2 - Purge it and install it
```
$ cd Downloads
$ sudo dpkg --purge dbeaver-ce
$ sudo dpkg -i dbeaver-ce_22.1.2_amd64.deb 
```

Ubuntu 20.04.4 LTS

**Comment by secondl1ght** [comment]
> Broke after update same message: "The dbeaver executable launcher was unable to locate its companion shared library"
> 
> Tried uninstalling doesnt fix it.
> 
> Linux Pop!_OS 22.04 LTS dbeaver-ce 22.1.2
> 
> last workig version: dbeaver-ce 22.1.1

Just commenting to document another break after updating, same specs as above.

`sudo apt remove dbeaver-ce --purge` and then re-install worked for me.

**Comment by shulard** [comment]
Same here, got the error on Ubuntu 22.04. I needed to uninstall (with `--purge`) and install it again, now it works.

**Comment by AnharMiah** [comment]
Same here, but for Ubuntu 20.04, as per @shulard first uninstalled it using `--purge` and then re-installed the `.deb` package. I also took a backup of the data under `~/.local/share/DBeaverData` but this wasn't needed as the re-installed kept all the connections and scripts :+1:

**Comment by dreamerworks** [comment]
Same problem on Debian 11. 

Solved:
sudo apt remove --purge dbeaver-ce
sudo apt install dbeaver-ce

The old connections were not lost.

**Comment by JaldeaR** [comment]
As of the new version 22.1.3 this issue was resolved.

**Comment by JaldeaR** [comment]
> Broke after update same message: "The dbeaver executable launcher was unable to locate its companion shared library"
> 
> Tried uninstalling doesnt fix it.
> 
> Linux Pop!_OS 22.04 LTS dbeaver-ce 22.1.2
> 
> last workig version: dbeaver-ce 22.1.1

As of the new version 22.1.3 this issue was resolved.

**Comment by besza** [comment]
Still an issue with dbeaver-ce 22.1.3 on Windows.

OS: Microsoft Windows 11 Enterprise (10.0.22000 Build 22000)
Dist: dbeaver-ce 22.1.3 x86_64 ZIP
Working fallback: dbeaver-ce 22.1.1 x86_64 ZIP

**Comment by olin000** [comment]
It might help when you check your dbeaver.ini file and see if there is a reference to plugins:
```
--launcher.library
plugins/some_sample_plugin_folder
```
or
```
-startup/
plugins/some_sample_plugin.jar
```
Updating names of the respective folder or .jar file or alternatively removing the reference might help to solve the issue.

**Comment by chengjingchun** [comment]
I use the zip FIle is Successed
