### ISSUE TITLE
`Error caching database model. Unknown table 'check_constraints' in information_schema` when view ER Diagram of database in mariaDB 10.1

### ISSUE THREAD

**Issue by yyjdelete** [dbeaver/dbeaver#9371]
#### System information: 
- Operating system (distribution) and version: win10
- DBeaver version: 7.1.3 x64
- Additional extensions

#### Connection specification:
- Database name and version: mariaDB 10.1.x
- Driver name: org.mariadb.jdbc:mariadb-java-client: 2.4.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
Error caching database model.
 Unknown table 'check_constraints' in information_schema

Seems something new in #6069, and maybe some db version checks is still missing

#### Steps to reproduce, if exist:
1. Open an database conn with mariaDB 10.1.x;
2. Choose any database, and press F4(View Database);
3. Switch to `ER Diagram` tab(, and press F5(Refresh) if it's already opened before);
4. See the error window;

#### Include any warning/errors/backtraces from the logs

No related logs can be found.

**Comment by yyjdelete** [comment]
It should be easy to reproduced.
1. Download and install DBeaver CE 7.1.3 from https://dbeaver.io/download/;
2. Download and install mariaDB 10.1.45(win_x64 I used) from https://mariadb.org/download/#entry-header
3. Create an conn in DBeaver  to the database;
4. Open database `information_schema`, and press F4(View Database);
5. Switch to `ER Diagram` tab

**Comment by DrkDigglr** [comment]
Also getting this same error by just clicking on the ER diagram tab.

![image](https://user-images.githubusercontent.com/3864776/88675258-a94fff80-d0e2-11ea-8b41-64772a7934ba.png)

**Comment by kseniiaguzeeva** [comment]
It should be fixed in 7.1.4 release. Could you test in EA version https://dbeaver.io/files/ea/?

**Comment by yyjdelete** [comment]
![image](https://user-images.githubusercontent.com/1819074/89045696-86da1280-d37e-11ea-9d2f-b828b65ce9f7.png)


@kseniiaguzeeva 
Still the same in EA version(Version 7.1.4.202007291911)

**Comment by LonwoLonwo** [comment]
@yyjdelete yeah. Find it yet. Fix error in 7.1.4

**Comment by kseniiaguzeeva** [comment]
@yyjdelete Could you test the latest release https://dbeaver.io/download/?

**Comment by yyjdelete** [comment]
@kseniiaguzeeva 
Verified it's fixed in 7.1.4

**Comment by kseniiaguzeeva** [comment]
Thank you for looking at this!

**Comment by RastaTaz** [comment]
Not it is not fixed : I have 7.1.4.202008021649 (debian paackage) and still have the issue.

![DeepinScreenshot_select-area_20200814121512](https://user-images.githubusercontent.com/28950854/90239529-f264bb00-de27-11ea-9a8d-cd121f0de127.png)

**Comment by LonwoLonwo** [comment]
@RastaTaz probably fixed in other tiket https://github.com/dbeaver/dbeaver/issues/9450 in version 7.1.5
version 7.1.5 you can find here https://dbeaver.io/files/ea/
