### ISSUE TITLE
Mac Editor: Problem with POS1/END key

### ISSUE THREAD

**Issue by MeboGit** [dbeaver/dbeaver#9414]
• Operating system (distribution) and version
MacOS 10.15.5
• DBeaver version
Version 7.1.2.202007051953
• Database name and version
10.4.12-MariaDB-1:10.4.12+maria~buster-log

Mac Editor: Problem with POS1/END key

![Bildschirmfoto 2020-07-30 um 23 00 06](https://user-images.githubusercontent.com/15740317/88975449-7eb89f00-d2ba-11ea-8ca6-ec82e14dede1.png)

I configured key POS1 to Line Start and key END to Line End (because cross platform). That works ok for about 5 - 10 minutes editing. After that key POS1/END switches to Text Start/Text END even though "Show key binding when command is invoked/Through keyboard" shows "Line Start" but executes "Text Start" (see picture).

The problem is I can not reproduce it with some special combination of keys entered. It just happens after some minutes of editing.

It's not a big thing but it is really annoying since I have to restart IDE every time this happens because I need those keys.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by MeboGit** [comment]
Also CTRL-S on Windows seems not to work even though it shows the hint "CTRL-S Apply Changes". Only save via menu works...

And further more:
Pasting the following phrase (including leading blanks) into the editor results in some missing characters (Mac and Windows)

        '"date":', '"', date, '"', ','

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response. Are described issues still actual for you?
1. '"date":', '"', date, '"', ','  - SQL Editor transforms this statement, you can undo it clicking the popup in the lower right corner (it appears after inserting)
2. Command+S - is correct command for Mac. You can see and change keys in Window>Preferences>General>Keys
![Screenshot 2020-10-08 at 13 41 21](https://user-images.githubusercontent.com/51405061/95449253-2ca49180-096d-11eb-8704-753d33962ee0.png)

**Comment by MeboGit** [comment]
Thanks for your response. 
1. Ok, that is a workaround
2. I did not change those keys, also in Windows/File/Save there it shows Ctrl-S for saving sql-script, but it does not save! 
![image](https://user-images.githubusercontent.com/15740317/96385967-aae80b80-1197-11eb-9f22-324bf303582b.png)
It shows "apply changes" in the hint but the file is not saved (there is still a star in the tab caption)

3. Any idea about my main issue (POS1/END-Key) on Mac? This issue makes it impossible for me to use DBeaver on Mac!

Seems to be general issue with keys. It shows the wright keys/function in the Hint-Windows but does not execute those?!

Thanks and regards

Mebo

**Comment by MeboGit** [comment]
When removing "Save Ctrl-S" and reassign then it works for some time: 
![image](https://user-images.githubusercontent.com/15740317/96386293-129f5600-119a-11eb-8453-c7f3b13b3f37.png)

But after some editing Ctrl-S changes into "Apply changes".
Also POS1/END-Keys gets lost after some editing.

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response.
1 great
2 By default Ctrl+S works as apply changes in Data Editor and ResultSet of SQL Editor. If you want to save SQL Script in SQL Editor field, you use CMD+S, because it is different editor with different shortcut. Can it be that **Save** and **Apply changes** appear in hint depending on where you press it - in Data Editor/ResultSet of SQL Editor or in SQL Editor query field?
3 I cannot reproduce the issue with text/line start/end. Is it possible to record a gif? What keyboard and locale do you use?

**Comment by MeboGit** [comment]
2. As mentioned in my previous replies DBeaver/Win executes "Ctrl+S - Save" (see hint window that comes from DBeaver, "Preferences/Keys/Show key binding when command ist invoked") when I press Ctrl+S after a new Start of DBeaver. But after some time (maybe 20 minutes) suddenly "Ctrl+S - Apply changes" is executed when I press Ctrl+S. In Windows this problem is not that big because I can still use File-Menu/Save. But anyhow I still lost some scripting because of this Bug.
3. Yes, I also cannot reproduce this issue with DBeaver/Mac. It also happens after some time (20 to 60 minutes), maybe after some specific combination of keys/shortcuts (I'm using Ctrl-Enter (execute current statement) very often, maybe there is some problem with that)?! But the problem with this is when I'm working in line 3000 and every time I press POS1 and it jumps to line 1 instead of beginning of current line that is annoying. And after having to restart every time this happened I now avoid using DBeaver for Mac.

There seems to be some problem with DBeaver key/shortcut/combination of keys/shortcuts interpretation. I'm using DBeaver on Mac/Parallels/Win, maybe DBeaver hast a problem with this?! But then again DBeaver would be the only program I'm having this issue.

**Comment by MeboGit** [comment]
Just to mention again, I now only work with the Windows-Version, I cannot work with the Mac-Version because of that POS1/END issue.

**Comment by kseniiaguzeeva** [comment]
Thank you for the details. Trying to reproduce..

**Comment by kseniiaguzeeva** [comment]
POS1/END and Ctrl+S work correctly for me. Please try for example https://apps.apple.com/us/app/giphy-capture-the-gif-maker/id668208984?mt=12 to record a gif where you use them with enabled **Show key binding when command is invoked**.
It should help us to find a reason and fix it

**Comment by MeboGit** [comment]
Sorry for the Delay.

Here the gifs...

After doing some work in Script-Editor (POS1/END jumps to Begin/End of text):
![Pos1_End_Text](https://user-images.githubusercontent.com/15740317/101218912-3a804580-3684-11eb-9142-042924b0aac6.gif)

After restart POS1/END works as expected again:
![Pos1_End_Line](https://user-images.githubusercontent.com/15740317/101218930-3e13cc80-3684-11eb-95bb-98a92dd285d2.gif)

**Comment by JCapriotti** [comment]
Was this able to be reproduced after @MeboGit's example? It happens for me too; not the biggest bug in the world but when you're editing text and your cursor unexpectedly jumps to the start/end of the file, it is pretty frustrating.

For now I'll retrain my brain to use the default shortcuts rather than customized ones.

**Comment by kseniiaguzeeva** [comment]
Unfortunatelly I still cannot reproduce it. It is a bad bug and I appreciate your help. Am I right, that you changed default shortcuts on custom ones and faced the issue?

**Comment by MeboGit** [comment]
Shortcuts are defined as follows:

![image](https://user-images.githubusercontent.com/15740317/109861884-1a9af680-7c60-11eb-910d-40958e3e2985.png)

**Comment by Tekka90** [comment]
Just to mention that I use v21.0.1.202103211229 now, on Big Sure, and do the exact same setup as described, and get the exact same result...
I am getting nuts with it, always jumping to begin end of the page, very frustrating !

**Comment by hfcheng66** [comment]
same issue here for HOME/END buttons for go to line start/end.
DBeaver Version 21.0.2.202104042040 on Catalina version 10.15.7.
restart DBeaver fixes it, but issue comes back after sometime.

**Comment by DustinMeldrumRoot** [comment]
same issue here for HOME/END buttons for go to line start/end.
DBeaver Version 21.0.2.202104042040 on Big Sur version 11.2.3
restart DBeaver fixes it, but issue comes back after sometime.

**Comment by phildebrand** [comment]
I have the same issue. Remapped the HOME/END buttons but stops working after a few minutes. A restart fixes it (for a short while). The current version I use is 21.0.4.202105021514 on Big Sur but it has been an issue for me since I started using DBeaver and that is already a few years now.

**Comment by kseniiaguzeeva** [comment]
I still cannot reproduce it with 3 different keyboards (I also tried to reproduce it in standalone DBeaver and in Eclipse). I've found a couple of articles where people forced the same issue and managed it. Could you please try their workarounds to solve the problem http://www.evansweb.info/2005/03/24/mac-os-x-and-home-end-keys/ and https://apple.stackexchange.com/questions/16135/remap-home-and-end-to-beginning-and-end-of-line? 
I'll really appreciate any feedback on this and hope that a solution will be found soon.

**Comment by atjshop** [comment]
I have those config in the file DefaultKeyBinding.dict. 
This issue still happens.

**Comment by phildebrand** [comment]
> I have those config in the file DefaultKeyBinding.dict.
> This issue still happens.

Same here. It wouldn't have been an issue if eclipse/dbeaver would have taken over those settings.

**Comment by andrew-dixon** [comment]
Same here. It works initially but after some time it then jumps to beginning / end of document. So frustrating.  I also have the configs mentioned in the workarounds and they works for other apps like VS Code, Word, etc... just not in dbeaver.

**Comment by Matvey16** [comment]
@MeboGit @andrew-dixon @phildebrand @atjshop @Tekka90 
Ok, it looks like I found where this issue can be. It still was not reproducible for me, but I noticed that after you edit custom key binds for `Line start` and `Line end` as HOME/END those bindings are still present for `Text start` and `Text end` which doesn't actually make sense. So as temporary workaround you need to manually disable or change keybinds for `Text start` and `Text end` while we must try to fix it so those keybinds would disable automatically

**Comment by andrew-dixon** [comment]
@Matvey16 I noticed that as well when I was looking as to why it wasn't working and disabled them but it makes no difference.

![Screenshot 2021-09-07 at 08 09 58](https://user-images.githubusercontent.com/7441801/132300307-f7b8daa5-dae0-4552-8a19-2f8234e7e88a.png)

![Screenshot 2021-09-07 at 08 09 37](https://user-images.githubusercontent.com/7441801/132300310-84552363-016a-481a-9b6e-8642ae24e45d.png)

**Comment by Matvey16** [comment]
@andrew-dixon even with those disabled after some time HOME button brings a caret to a start of the document?

**Comment by andrew-dixon** [comment]
@Matvey16 Yes, if I leave DBeaver open, which I tend to do most of the time as I come back to it often to do something in the DB, it will start going to the start/end of the document instead of start and end of the line. There doesn't seem to be anything in particular you have to do to get it to do it, it only seems to be related to "time" and maybe switching windows, e.g. going to a different app(s) and coming back to DBeaver at some point later, but just opening DBeaver, switching apps and then coming back to DBeaver doesn't cause it immediately, so it is mainly a time based issue.

**Comment by andrew-dixon** [comment]
@Matvey16 I don't think this is significant, as I'm sure it has happened quicker in the past, but it's just been almost exactly 24 hours since I opened DBeaver last and the issue just started happening.

**Comment by flambchap** [comment]
Looks like a duplicate of https://github.com/dbeaver/dbeaver/issues/4483

**Comment by flzpenteado** [comment]
> same issue here for HOME/END buttons for go to line start/end.
> DBeaver Version 21.0.2.202104042040 on Big Sur version 11.2.3
> restart DBeaver fixes it, but issue comes back after sometime.

Same problem here...

**Comment by andrew-dixon** [comment]
I think I might have figured out the cause of this issue, I think it is Karabiner Elements that is the "cause" of it. Since I uninstalled Karabiner Elements about a week ago I've not had this issue. I assume that the key remapping that Karabiner is doing is somehow interfering with the remapping in DBeaver.

**Comment by phildebrand** [comment]
> I think I might have figured out the cause of this issue, I think it is Karabiner Elements that is the "cause" of it. Since I uninstalled Karabiner Elements about a week ago I've not had this issue. I assume that the key remapping that Karabiner is doing is somehow interfering with the remapping in DBeaver.

I'm not using Karabiner and still have the issue.

**Comment by andrew-dixon** [comment]
@phildebrand Maybe you are using another similar app that remaps keys at a system level?

**Comment by phildebrand** [comment]
I only added the file `DefaultKeyBinding.dict` to the folder `~/Library/KeyBindings`
With the following contents:

```
{
/* Remap Home / End keys to be correct */
"\UF729" = "moveToBeginningOfLine:"; /* Home */
"\UF72B" = "moveToEndOfLine:"; /* End */
"$\UF729" = "moveToBeginningOfLineAndModifySelection:"; /* Shift + Home */
"$\UF72B" = "moveToEndOfLineAndModifySelection:"; /* Shift + End */
"^\UF729" = "moveToBeginningOfDocument:"; /* Ctrl + Home */
"^\UF72B" = "moveToEndOfDocument:"; /* Ctrl + End */
"$^\UF729" = "moveToBeginningOfDocumentAndModifySelection:"; /* Shift + Ctrl + Home */
"$^\UF72B" = "moveToEndOfDocumentAndModifySelection:"; /* Shift + Ctrl + End */
}
```

**Comment by danilabagroff** [comment]
I have remapped keys in the same way as @phildebrand did and besides this I used Karabiner a while ago but uninstall did not help.

**Comment by jyk4100** [comment]
also having the same issue. I am windows users using mac for work and I want to use 'home' and 'end' key to go to the start/end of the **line** and not the **entire text**. I changed key mappings on preference but it works intermittently. Yes it is not the biggest bug but this make me jump around my sql script unintentionally.

**Comment by Skydiveroid** [comment]
Probably will be fixed in Eclipse 2012-12

**Comment by MarkFergusonTN** [comment]
This is a problem for me as well and I will not be able to continue to use DBeaver until this is addressed, unfortunately.

**Comment by ShadelessFox** [comment]
It looks like the issue was fixed in Eclipse 2021-12 (DBeaver 21.3.3 and higher).

It is still needed to remove default keybindings for <kbd>Text Start</kbd> and <kbd>Text End</kbd> because they're set to use <kbd>Home</kbd> and <kbd>End</kbd> by default on macOS.

Please upgrade to the newest version of DBeaver and let me know if the issue persists.

**Comment by MarkA1** [comment]
Referencing issue #5931 here, as it's likely the same issue, opened in 2019, custom key bindings on Mac for Home/End, and I can confirm it's still happening in DBeaver 21.3.4.202202051448 on current MacOs 12.2.1.  They work on start-up but are then lost during the session at some point.  Really bad when working in the middle of a hundreds or thousands of lines long file and all of a sudden the END key goes to the end of the file when it's mapped to go to end of line.

**Comment by ShadelessFox** [comment]
That's unfortunate. Thanks for verifying.

**Comment by celiosilva** [comment]
Same here

**Comment by phildebrand** [comment]
I can confirm it's not fixed yet.

**Comment by derfryday** [comment]
same issue here

**Comment by andrew-dixon** [comment]
The problem persists in Version 22.0.0.202203060510 released on 7th March.

**Comment by ShadelessFox** [comment]
Hello everyone,

We are aware that the issue persists against the newest version.

We have scheduled this ticket for the 22.0.2 release.

**Comment by wiwwo** [comment]
Please guys, this is reeeeally annoying... :(

**Comment by tomsafekeep** [comment]
The issue persists on DBeaver 22.0.4.202205011839
Mac OS X Monterey. 
No DefaultKeyBinding.dict file
Both with and without karabiner, the issue appears again after ~10 minutes of using DBeaver.

**Comment by tomsafekeep** [comment]
Workaround:

1. Install and open karabiner
2. Go to Complex modifications
3. Click "add rule"
4. Click "Import rules from the internet"
5. Search and import "Home and End" (https://ke-complex-modifications.pqrs.org/#command_arrows)
6. Enable both rules
7. Restart DBeaver

Works well so far even after several hours. Shift+Home still selects to the text's start, so it does not solve the whole problem, but perhaps this could be tweaked in karabiner as well. 
Tested with an Apple keyboard.

**Comment by hfcheng66** [comment]
> Workaround:
> 
> 1. Install and open karabiner
> 2. Go to Complex modifications
> 3. Click "add rule"
> 4. Click "Import rules from the internet"
> 5. Search and import "Home and End" (https://ke-complex-modifications.pqrs.org/#command_arrows)
> 6. Enable both rules
> 7. Restart DBeaver
> 
> Works well so far even after several hours. Shift+Home still selects to the text's start, so it does not solve the whole problem, but perhaps this could be tweaked in karabiner as well. Tested with an Apple keyboard.

Thanks for posting the workaround, works for me so far!

**Comment by andrew-dixon** [comment]
The workaround from @tomsafekeep worked for a bit but today I'm back to the issue (having not closed and reopened DBeaver), so pretty much the same as before, it just took a bit longer to start occurring.

**Comment by rocket-yg** [comment]
While using an external keyboard, if I press the HOME or END keys, the cursor gets thrown straight up to top of the SQL script. That said, the `cmd` + `arrow-keys` on the mac built in keyboard works just fine. Can anyone help me with a TL:DR of the above thread since I am not well versed in the technicalities of this workbench.

**Comment by andrew-dixon** [comment]
@rocket-yg the TL:DR is, it's a bug and needs fixing but hasn't been as of yet.

**Comment by rocket-yg** [comment]
Oh! Understood. Thanks @andrew-dixon for prompt response.

**Comment by tomsafekeep** [comment]
@andrew-dixon for me, it works almost all the time (at least for now). It greatly improved after resetting keyboard setting, clearing karabiner settings and using only the home and end configuration.

**Comment by nicolas-gouteux-sonarsource** [comment]
I confirm this bug is annoying.

Symptom: Home/End redirection to Line Start/Line End work for some time and then flip back to TextStart/TextEnd although the ppup mentions Line Start/Line End. 

MacOs 12.4 Dbeaver 22.1.2

Can this one be addressed?
Thanks

**Comment by andrew-dixon** [comment]
@nicolas-gouteux-sonarsource It's been added to the slate for release 22.2.0 which looks to be currently scheduled for early September, so 🤞

**Comment by hozn** [comment]
This has been driving me crazy.  Home/End configured as above and stops working after a bit of time in the editor (seems like just a couple minutes for me.)  I'm glad I finally found the correct issue, so I can watch for a fix.  I'll try the Karabiner workaround as this makes the dbeaver editor pretty much unusable for me for larger queries -- using home/end while editing is way too ingrained. (I use another editor and then paste in the SQL 😒 )

**Comment by jyk4100** [comment]
I am still having the same issue post upgrade to 22.2.0 (version: 22.1.5.202208211008). Although the time that take to "Home/End redirection to Line Start/Line End" to stop working has increased from 10 minutes to say 30 minutes 😃  (rough estimates). Anyone else still having the same problem after upgrading to 22.2.0?

https://user-images.githubusercontent.com/14896560/186223109-454e5202-92f7-4faf-a6ce-d0ca6ab61ff6.mov

**Comment by hozn** [comment]
Concur; same issue after upgrade, though also agree that it takes more than a couple minutes now. ( Maybe it did before; it's hard to time it :) )

**Comment by derfryday** [comment]
still broken, basically right after launching dbeaver too.

**Comment by d13g0** [comment]
> now. ( Maybe it did before; it's hard to time it :) )

Same here I can't wait for the fix

**Comment by cacio-costa** [comment]
I just update to DBeaver Version 22.1.5.202208211008, and macOS Monterey 12.5.1, M1 chip. The issue persists.

**Comment by zyzil** [comment]
I'm having this same issue with DBeaver Version 22.2.1.202209251341. I hope it gets fixed soon, very frustrating.

**Comment by dannywells1** [comment]
Just got the latest, 22.2.1.202209270815 still an issue :(

**Comment by derfryday** [comment]
still broken on 22.2.2.202210092258

**Comment by wysokinskim** [comment]
Had same problem, it turned out that workbench.xmi file was broken. Same key combination (home, end) pointed to two different commands. I have manually fixed it by stopping dbeaver and removing commands that pointed to home,end keys except endLine and startLine commands. After this fix home and end brings me to the start and end of line.

**Comment by andrew-dixon** [comment]
@wysokinskim Where is that file located? Thanks

**Comment by zyzil** [comment]
@andrew-dixon - I believe these are the locations. I was hoping duplicate mapping might be my problem as well but it was not the case.

Windows: `%APPDATA%\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi`
MacOS: `~/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi`
Linux: `$XDG_DATA_HOME/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi`

**Comment by wysokinskim** [comment]
@zyzil, @andrew-dixon  Some people says stopping dbeaver and removingworkbench.xmi helps.

**Comment by andrew-dixon** [comment]
No duplicate mapping for me either. As mentioned several times above, restarting DBeaver does fix the problem for a while, but it soon comes back.

**Comment by jyk4100** [comment]
Thanks @wysokinskim @zyzil the solution is working for me on MacOS!! I removed the binding for "HOME" and "END" from the workbench.xmi files e.g. remove line `<bindings xmi:id="_QXaBQFQIEe2DIaJoywBTIw" keySequence="END" command="_QXdDxVQIEe2DIaJoywBTIw">`
edit +1 (2022-10-28 16:50:00): after hour still reverts to behavior where "HOME" key take to the beginning of the script and not the beginning of the current line 😢

**Comment by wysokinskim** [comment]
@jyk4100 I set home and end to endLine and startLine in GUI and removed any other binding for home and end from workbench.xmi. It's still working for me

**Comment by TARehman** [comment]
Chiming in as this is happening to me as well. Ventura 13.0, DBeaver 22.2.4. When starting up DBeaver, remapped Home and End keys perform as expected; however, after executing a query or two, suddenly the End key jumps me to the end of the document, not to the end of the line. It's not obvious what's causing it.

**Comment by andrew-dixon** [comment]
So, removing the "HOME" and "END" mapping from the workbench.xmi file as suggest above by @zyzil and @jyk4100 seems to have done the trick. I removed these line last Friday and have not closed DBeaver since and the home and end is still working as expected. I believe you need to be using Karabiner Elements as well to map the home and end "PC" version of the keys, again discussed above.

**Comment by MarkA1** [comment]
Removing HOME/END bindings entries from workbench.xmi has been working for me too, for more than a week now (and I never went more than an hour or two without the issue starting up again previously).

Some more detail though:  I started by commenting out the HOME/END bindings from workbench.xmi (running on MacOS) to test the change.  On DBeaver restart, the commented entries were deleted and new HOME/END bindings were generated, but the issue was fixed and the problem has not returned.  However and interestingly, the new HOME/END binding entries in that file don't have unique xmi:id strings or command strings, as they match a few other lines in the file that don't seem to be HOME/END related commands, but still is OK so far.

So it seems like something is getting mixed up with duplicate or wrong entries in that workbench.xmi file, but again, mine is working great thus far since my initial commenting/removal of the two entries, and I had been experiencing this issue since May of 2019 with this other still-open issue I opened then: #5931

Also, I do not use nor have Karabiner Elements on my system.

**Comment by phildebrand** [comment]
Removing the entries works for me too. Nice find!

**Comment by Destrolaric** [comment]
@wysokinskim Thank you, nice find!
It would be great if anyone could send the duplicate entries here before deleting them.

**Comment by hozn** [comment]
I've removed the entries as others mention, but the problem persists for me (comes back after some usage).  I must be missing something ...

**Comment by andrew-dixon** [comment]
@hozn Mine did that as well after updating to a new version. I just had to go back into the `workbench.xmi` file and remove them again.

**Comment by hozn** [comment]
@andrew-dixon  -- thank you!  I will keep removing them in hopes that they stay removed! :)

**Comment by MarkA1** [comment]
How timely: after 11 days of this working with removed bindings (longer than it ever went before), the issue came back today.

@Destrolaric:  Here are the bindings I removed, the commands with matching IDs, and the new bindings that get auto-generated on restart/exit after removing the initial bindings:

```
Version 22.2.4.202211061524
At removal of END/HOME bindings, removed these two:

<bindings xmi:id="_iwY1IVi4Ee2xrvDjta-X0g" keySequence="END" command="_FNZBlmHFEeyLzYSG852Qkw">
  <tags>type:user</tags>
</bindings>
<bindings xmi:id="_iwaDQFi4Ee2xrvDjta-X0g" keySequence="HOME" command="_FNZBuGHFEeyLzYSG852Qkw">
  <tags>type:user</tags>
</bindings>


Items with IDs matching the END command above:

<commands xmi:id="_FNZBLmHFEeyLzYSG852Qkw" elementId="org.eclipse.ui.edit.text.showRulerAnnotationInformation" commandName="Show Ruler Annotation Tooltip" description="Displays annotation information for the caret line in a focused hover" category="_FNZCg2HFEeyLzYSG852Qkw"/>

<commands xmi:id="_FNZBlmHFEeyLzYSG852Qkw" elementId="org.eclipse.ui.edit.text.goto.lineEnd" commandName="Line End" description="Go to the end of the line of text" category="_FNZCg2HFEeyLzYSG852Qkw"/>


Items with IDs matching the HOME command above:

<commands xmi:id="_FNZBuGHFEeyLzYSG852Qkw" elementId="org.eclipse.ui.edit.text.goto.lineStart" commandName="Line Start" description="Go to the start of the line of text" category="_FNZCg2HFEeyLzYSG852Qkw"/>

<commands xmi:id="_FNZBTmHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.create" commandName="Create Object" description="Create new database object" category="_FNZCfmHFEeyLzYSG852Qkw">
  <parameters xmi:id="_FNZBT2HFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.type" name="Object type"/>
  <parameters xmi:id="_FNZBUGHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.typeName" name="Object type name"/>
  <parameters xmi:id="_FNZBUWHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.typeIcon" name="Object type icon"/>
  <parameters xmi:id="_FNZBUmHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.folder" name="Object is folder"/>
</commands>



After restart/exit of DBeaver after removing the above bindings, new bindings are generated, with different xmi:id, but still pointing at the same multiple commands:

<bindings xmi:id="_kN8boWeHEe2vROZOIm5HBA" keySequence="END" command="_FNZBlmHFEeyLzYSG852Qkw">
  <tags>type:user</tags>
</bindings>
<bindings xmi:id="_kN9CsGeHEe2vROZOIm5HBA" keySequence="HOME" command="_FNZBuGHFEeyLzYSG852Qkw">
  <tags>type:user</tags>
</bindings>

```
One other item of note, which may just be a coincidence, I had the bindings file open in a Sublime Text editor during most/all of the 11 days it worked.  While I don't think that stops external edits to a file (assuming by DBeaver here), I had just closed that file out of the editor earlier today before the problem re-appeared.

**Comment by weaver543** [comment]
I REALLY hope this bug is fixed soon.  DBeaver is amazing on Windows but since forced to migrate to Mac, I just cannot get used to using different keys for beginning/end of line, other than home/end, which works fine remapped in all other Mac applications

**Comment by petrvalkoun-gooddata** [comment]
Guys, this is really bad, I cannot use the editor at all because of this issue. please fix it

**Comment by derfryday** [comment]
> Guys, this is really bad, I cannot use the editor at all because of this issue. please fix it

@petrvalkoun-gooddata check your config, I had multiple mappings for the home and end keys, clearing those up fixed it for me like 1 or 2 versions of Dbeaver ago.

**Comment by cardalda** [comment]
I also had have mapping problems, and after editing the DefaulltKeyBinding, it works perfectly.
But...

After a while the mapping stops working and keys are behaving as before.
It's hard to reproduce, but I managed to make it happen a few times within a few seconds.
After you restart dBeaver, the mapping works according to your file.
What I did is try to change a query (which is auto loaded in the editor).
The query itself is not important, but for the sake of reproduction, I was editing this query:

```sql
select ag.*
     , cm.name, cm.image
     , ev.msg_content
  from (
    select camp_id
         , max(id)   as last_id --➜ obtain last event 
         , count(*)  as total
         , ***
     from events
    where target_id = 2
    group by camp_id
 ) ag
     join events    ev on ev.id = ag.last_id
left join campaigns cm on cm.id = ag.camp_id
;
```

Now select the *** and start typing --> 
, sum(case when x is null then 1 e 

after pressing the last "e", and you wait a bit, an autocompletions wants to popup (displaying "else") but you keep typing,
there is a chance the key mapping gets lost.
Play around with timing and eventually, it will happen, only by playing with your keyboard...

When this happens; save your work, close and reopen...

**Comment by mistaecko** [comment]
I can reliably replicate this bug in DBeaver `22.3.1.202212251901` (macOS 12.6) using the following setup:

1. Spin up mysql

```bash
docker run -e MYSQL_ALLOW_EMPTY_PASSWORD=true -p '3306:3306' mysql:5.7
```

2. Create database and table

Connect from DBeaver (localhost, 3306, root, no password), and run:

```sql
CREATE database test;

USE test;

CREATE TABLE `institution` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `some_other_key` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
);
```

3. Run query

```sql
SELECT *  
FROM institution foobar;
```

4. Break it

Trigger auto-complete by selecting a specific column from `foobar.` - as soon as the auto-complete shows and exits (either using ESC or completing a column name) the key bindings for HOME/END are broken:

```sql
SELECT foobar.id  
FROM institution foobar
```

Note that typing out the entire column selector `foobar.id` reliably triggers the bug for me, and restarting DBeaver fixes it. 
I am not certain whether the alias name matters, but I was unable to replicate using `x` as table alias. It seemed that a longer alias name triggered it more reliably.

**Comment by hozn** [comment]
This is helpful; I thought I was going crazy or doing something different from the other commenters, as I also have this problem continually resurface, despite fixing (editing) the file.  The fact that it may be tied to auto-complete makes sense; I hadn't been able to pinpoint when it happens.

**Comment by mgdelmonte** [comment]
Same bug for me (and this is not the only issue, there are related issues).  Happens all the time.

DBeaver Version 22.3.3.202301211053
Mac OS: Ventura 13.1

I'm using an external keyboard and it's the same thing as in https://github.com/dbeaver/dbeaver/issues/4483 and probably a few others.  Keybindings randomly just stop working.  Only solution is to restart the program.

It sucks because DBeaver is great but this one thing makes it nearly impossible to use.

**Comment by dnicolaev** [comment]
This Issue  has started very long time for me.
END button jumps to the end of text in SQL Editor instead of moving the cursor to the End of line.

Still actual.
DBeaver: Version 22.3.5.202302180832
Mac OS: Ventura 13.2.1

**Comment by vince-vanh** [comment]
Very frustrating. I suffered with this and mostly stopped using DBeaver in the fall, then after some upgrade it DBeaver had no problem with retaining customized key combination. Now after upgrading to 23.0.2.202304091457, it has returned.
MacOS: Ventura, 13.3.1 (22E261)

Also: once you've exported key customizations to a csv, how can you bring them back in?

**Comment by nicchristeller** [comment]
Some information I haven't seen mentioned above: this issue appears _not_ to be related to the Home and End keys themselves.

I have bound the "Line Start" action to the letter "P", and the "Line End" action to the letter "L".

As others have described, these actions work as expected when DBeaver first launches, but after some time **they revert back to their "normal" operation (i.e. typing the letters)** and no longer move the cursor to line start or end, despite the "show binding" prompt indicating that those commands have been executed.

This indicates to me that the problem is with those commands themselves, not the Home/End keys. Others are seeing the behaviour revert to start/end document because that is the "normal", unbinded operation of the Home/End keys on Mac.

 Start line keybinding
<img width="1105" alt="line-start-keybinding" src="https://github.com/dbeaver/dbeaver/assets/21079106/807b29d5-6deb-4649-a07a-7aff61a2673d">

Actions working initially

https://github.com/dbeaver/dbeaver/assets/21079106/bf829ccb-f764-4cc1-9c9c-506cb0f6c86c

Actions not working after some time - "P" and "L" are typed as letters

https://github.com/dbeaver/dbeaver/assets/21079106/8e7ff033-ca92-454a-8405-3634d89c5521

**Comment by wiwwo** [comment]
Any news?
Using DBeaver on Mac is just irritating.
Moving to another client.
So long, and thanks for all the frustration.

**Comment by nicchristeller** [comment]
I've managed a workaround using karabiner; e.g. this maps "home" to "shift+home" then "left arrow" (since shift+home has always been correctly selecting to start of line, followed by a left arrow to clear the selection). 

Home, and every combination of modifiers with it, are working as expected for me. YMMV.

```
"rules": [
    {
        "description": "dbeaver home/end keys",
        "manipulators": [
            {
                "conditions": [
                    {
                        "bundle_identifiers": [
                            "^org\\.jkiss\\.dbeaver\\.core\\.product$"

                        ],
                        "type": "frontmost_application_if"
                    }
                ],
                "from": {
                    "key_code": "home"
                },
                "to": [
                    {
                        "key_code": "home",
                        "modifiers": [
                            "shift"
                        ]
                    },
                    {
                        "key_code": "left_arrow"
                    }
                ],
                "type": "basic"
            },
            {
                "conditions": [
                    {
                        "bundle_identifiers": [
                            "^org\\.jkiss\\.dbeaver\\.core\\.product$"

                        ],
                        "type": "frontmost_application_if"
                    }
                ],
                "from": {
                    "key_code": "home",
                    "modifiers": {
                        "mandatory": [
                            "command"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "home",
                        "modifiers": [
                            "command",
                            "shift"
                        ]
                    },
                    {
                        "key_code": "left_arrow"
                    }
                ],
                "type": "basic"
            },
            {
                "conditions": [
                    {
                        "bundle_identifiers": [
                            "^org\\.jkiss\\.dbeaver\\.core\\.product$"

                        ],
                        "type": "frontmost_application_if"
                    }
                ],
                "from": {
                    "key_code": "end"
                },
                "to": [
                    {
                        "key_code": "end",
                        "modifiers": [
                            "shift"
                        ]
                    },
                    {
                        "key_code": "right_arrow"
                    }
                ],
                "type": "basic"
            },
            {
                "conditions": [
                    {
                        "bundle_identifiers": [
                            "^org\\.jkiss\\.dbeaver\\.core\\.product$"

                        ],
                        "type": "frontmost_application_if"
                    }
                ],
                "from": {
                    "key_code": "end",
                    "modifiers": {
                        "mandatory": [
                            "command"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "end",
                        "modifiers": [
                            "command",
                            "shift"
                        ]
                    },
                    {
                        "key_code": "right_arrow"
                    }
                ],
                "type": "basic"
            }
        ]
    }
]        
```

**Comment by malcolm-smith-mck** [comment]
Very much agree with the comments - I've been battling with each new upgrade of dBeaver home and end keys just don't work and remapping them also fails after just a few minutes.  

I've taken the karbiner approach above - with some tweaks 
{
    "conditions": [
        {
            "bundle_identifiers": [
                "^com\\.apple\\.Terminal$"
            ],
            "type": "frontmost_application_unless"
        }
    ],
    "description": "New Rule in dBeaver map home and end keys to the right ones)",
    "manipulators": [
        {
            "from": {
                "key_code": "end",
                "modifiers": {
                    "mandatory": [
                        "left_command"
                    ],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "down_arrow",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "home",
                "modifiers": {
                    "mandatory": [
                        "left_command"
                    ],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "up_arrow",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "home",
                "modifiers": {
                    "mandatory": [],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_arrow",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "end",
                "modifiers": {
                    "mandatory": [],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "right_arrow",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}

**Comment by ricson-chua** [comment]
When will this work? Need another video to show that the problem exists?

**Comment by ricson-chua** [comment]
> How timely: after 11 days of this working with removed bindings (longer than it ever went before), the issue came back today.
> 
> @Destrolaric: Here are the bindings I removed, the commands with matching IDs, and the new bindings that get auto-generated on restart/exit after removing the initial bindings:
> 
> ```
> Version 22.2.4.202211061524
> At removal of END/HOME bindings, removed these two:
> 
> <bindings xmi:id="_iwY1IVi4Ee2xrvDjta-X0g" keySequence="END" command="_FNZBlmHFEeyLzYSG852Qkw">
>   <tags>type:user</tags>
> </bindings>
> <bindings xmi:id="_iwaDQFi4Ee2xrvDjta-X0g" keySequence="HOME" command="_FNZBuGHFEeyLzYSG852Qkw">
>   <tags>type:user</tags>
> </bindings>
> 
> 
> Items with IDs matching the END command above:
> 
> <commands xmi:id="_FNZBLmHFEeyLzYSG852Qkw" elementId="org.eclipse.ui.edit.text.showRulerAnnotationInformation" commandName="Show Ruler Annotation Tooltip" description="Displays annotation information for the caret line in a focused hover" category="_FNZCg2HFEeyLzYSG852Qkw"/>
> 
> <commands xmi:id="_FNZBlmHFEeyLzYSG852Qkw" elementId="org.eclipse.ui.edit.text.goto.lineEnd" commandName="Line End" description="Go to the end of the line of text" category="_FNZCg2HFEeyLzYSG852Qkw"/>
> 
> 
> Items with IDs matching the HOME command above:
> 
> <commands xmi:id="_FNZBuGHFEeyLzYSG852Qkw" elementId="org.eclipse.ui.edit.text.goto.lineStart" commandName="Line Start" description="Go to the start of the line of text" category="_FNZCg2HFEeyLzYSG852Qkw"/>
> 
> <commands xmi:id="_FNZBTmHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.create" commandName="Create Object" description="Create new database object" category="_FNZCfmHFEeyLzYSG852Qkw">
>   <parameters xmi:id="_FNZBT2HFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.type" name="Object type"/>
>   <parameters xmi:id="_FNZBUGHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.typeName" name="Object type name"/>
>   <parameters xmi:id="_FNZBUWHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.typeIcon" name="Object type icon"/>
>   <parameters xmi:id="_FNZBUmHFEeyLzYSG852Qkw" elementId="org.jkiss.dbeaver.core.object.folder" name="Object is folder"/>
> </commands>
> 
> 
> 
> After restart/exit of DBeaver after removing the above bindings, new bindings are generated, with different xmi:id, but still pointing at the same multiple commands:
> 
> <bindings xmi:id="_kN8boWeHEe2vROZOIm5HBA" keySequence="END" command="_FNZBlmHFEeyLzYSG852Qkw">
>   <tags>type:user</tags>
> </bindings>
> <bindings xmi:id="_kN9CsGeHEe2vROZOIm5HBA" keySequence="HOME" command="_FNZBuGHFEeyLzYSG852Qkw">
>   <tags>type:user</tags>
> </bindings>
> ```
> 
> One other item of note, which may just be a coincidence, I had the bindings file open in a Sublime Text editor during most/all of the 11 days it worked. While I don't think that stops external edits to a file (assuming by DBeaver here), I had just closed that file out of the editor earlier today before the problem re-appeared.

I managed to get this working. What I ended up doing is keeping a file with the final bindings and run an hourly cron to keep overwriting workbench.xmi so whenever I encounter issues I will just restart Dbeaver and everything is back in order.

**Comment by cesarmansur** [comment]
I noticed that while I'm using DBeaver, every 5 minutes there is something writing the `HOME` and `END` key bindings back to the `workbench.xmi` file. If DBeaver is idle, nothing happens. But as soon as I start using it again, then the `workbench.xmi` file is updated every 5 minutes again. So, manually deleting the `HOME` and `END` key bindings from the `workbench.xmi` file works just for a few minutes, then the issue is back.

```
2025-01-15 14:45:21 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-15 14:50:21 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-15 15:30:21 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-15 18:05:52 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-16 13:10:53 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-16 16:40:53 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-16 16:45:53 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-16 17:45:53 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-17 14:05:11 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-17 14:20:11 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-17 14:25:11 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-17 15:10:11 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-17 16:25:12 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-17 16:30:12 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
2025-01-17 16:45:12 /Users/*****/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
```

So I created the `fix_key_bindings.sh` script, that monitors the `workbench.xmi` and when the file is written it removes the `HOME` and `END` key bindings from it.

This is the WA to get rid of the annoying issue:

1) install `fswatch` with `brew install`:
`brew install fswatch`

2) create the `.DBeaver` folder in your home dir:
`mkdir ~/.DBeaver`

3) save the `fix_key_bindings.sh` script inside the `.DBeaver`:

```
#!/bin/bash

FILE=/Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi

while true; do
    /opt/homebrew/bin/fswatch -1 -t -f "%Y-%m-%d %H:%M:%S" "$FILE"
    sed -i '' '/<bindings[^>]*keySequence="HOME"[^>]*>/,/<\/bindings>/d' "$FILE"
    sed -i '' '/<bindings[^>]*keySequence="END"[^>]*>/,/<\/bindings>/d' "$FILE"
done
```

* replace `<user>` with your user and fix the path if your `workbench.xmi` file is located anywhere else

4) make it executable:
`chmod +x ~/.DBeaver/fix_key_bindings.sh`

5) save the `com.user.fix_key_bindings.plist` file inside the `~/Library/LaunchAgents/` folder to launch the job automatically:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.fix_key_bindings</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>/Users/<user>/.DBeaver/fix_key_bindings.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/Users/<user>/.DBeaver/fix_key_bindings.out</string>
    <key>StandardErrorPath</key>
    <string>/Users/<user>/.DBeaver/fix_key_bindings.err</string>
</dict>
</plist>
```

* replace `<user>` with your user

6) restart your Mac and enjoy!

You can check the contents of the `fix_key_bindings.out` file and you'll see how many times it saved you from going crazy!

I'm using DBeaver for a few weeks now smoothly.


This is a WA. Ideally the `HOME` and `END` key bindings should not be written back to `workbench.xmi` file, but in face of it, this is how I got rid of the pain.

**Comment by MarkA1** [comment]
> So I created the `fix_key_bindings.sh` script, that monitors the `workbench.xmi` and when the file is written it removes the `HOME` and `END` key bindings from it.
> 
@cesarmansur - Although the work-around does modify the `workbench.xmi` file nicely and is a nice piece of work (and is preferable to installing yet another tool like karabiner which some have done), DBeaver does not seem to recognize the updates until its restarted, at least on my MacBook.  I implemented it, restarted DBeaver and about an hour later the issue was back.  In checking the output, the `workbench.xmi` had been modified correctly about 15 times but I still had to restart DBeaver again.  So this saved the manual `workbench.xmi` edit but that was it.

Also, the example script had the wrong fswatch path after a fresh Homebrew fswatch install on my MacBook and didn't run. For me I had to modify the path to `/usr/local/bin/fswatch`.

What really needs to happen here is that the DBeaver folks prioritize this and get a fix out.  It's been the most annoying issue with DBeaver for all of the 7 years I've been using it.  There are three separate GitHub issues here related to this (I opened issue #5931 in May 2019), and these keep getting planned/scheduled and then un-scheduled over and over.

The related issues (at least that I'm aware of currently):
#4483 [(some) Emacs keybindings randomly break](https://github.com/dbeaver/dbeaver/issues/4483), opened in Oct 2018.
#5931 [Custom key bindings stop working while in SQL Editor tab](https://github.com/dbeaver/dbeaver/issues/5931), opened in May 2019.
#9414 [Mac Editor: Problem with POS1/END key](https://github.com/dbeaver/dbeaver/issues/9414), this issue, opened July 2020.

**Comment by kyberplayer** [comment]
I'm having the same issue

**Comment by cesarmansur** [comment]
@MarkA1  I totally agree with you, really hope that the DBeaver folks fix this annoying issue.

As I said in my post, it was a WA that worked really well for me for a few weeks. But, after leaving my MacBook on all weekend, with the screen locked, this Monday I had the issue again. So I had to close DBeaver, unload the plist, load it again, then open DBeaver and the WA started working again. This is annoying as well! I don't know why, but I think it's something to do with the locked screen and how macOS manages user sessions and background processes... So I changed the WA a little. Instead of using the plist, I'm starting the job in cron. I didn't have the issue again after that.

It's pretty much simpler now:

---

1) install `fswatch` with `brew install`:

```
brew install fswatch
```

<br>

2) create the `.DBeaver` folder in your home dir:

```
mkdir ~/.DBeaver
```

<br>

3) save the `fix_key_bindings.sh` script inside the `.DBeaver`:

```
#!/bin/bash

FILE=/Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi

while true; do
    /opt/homebrew/bin/fswatch -1 -t -f "%Y-%m-%d %H:%M:%S" "$FILE"
    sed -i '' '/<bindings[^>]*keySequence="HOME"[^>]*>/,/<\/bindings>/d' "$FILE"
    sed -i '' '/<bindings[^>]*keySequence="END"[^>]*>/,/<\/bindings>/d' "$FILE"
done
```

* replace `<user>` with your user
* update the `FILE` path if your `workbench.xmi` file is located anywhere else
* update the `fswatch` path if your `fswatch` is installed anywhere else

<br>

4) make it executable:

```
chmod +x ~/.DBeaver/fix_key_bindings.sh
```

<br>

5) run `crontab -e` and append the following lines to it:

```
@reboot /Users/<user>/.DBeaver/fix_key_bindings.sh >> /Users/<user>/.DBeaver/fix_key_bindings.log 2>&1
@daily pkill -f /Users/<user>/.DBeaver/fix_key_bindings.sh; /Users/<user>/.DBeaver/fix_key_bindings.sh >> /Users/<user>/.DBeaver/fix_key_bindings.log 2>&1
```

* replace `<user>` with your user

<br>

6) restart your Mac and enjoy!

<br>

---

**Comment by cesarmansur** [comment]
@MarkA1 

I just came up with a much better WA.

<br>

1 - Close DBeaver

<br>

2 - Run these 2 commands to remove the **HOME** and **END** bindings from the `workbench.xmi` file:

```
sed -i '' '/<bindings[^>]*keySequence="HOME"[^>]*>/,/<\/bindings>/d' "/Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi"
```

```
sed -i '' '/<bindings[^>]*keySequence="END"[^>]*>/,/<\/bindings>/d' "/Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi"
```

<br>

3 - Then run this command to make the file immutable. This means the file cannot be modified, deleted, or renamed, even by the root user, unless the flag is removed.

```
sudo chflags schg /Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
```

PS: replace `<user>` with your user name and update the file path if it differs on your system

<br>

4 - Reopen DBeaver

<br>

---

If you need to remove the flag for some reason, use this command:

```
sudo chflags noschg /Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
```

**Comment by diego-phealth** [comment]
> [@MarkA1](https://github.com/MarkA1)
> 
> I just came up with a much better WA.
> 
> 
> 1 - Close DBeaver
> 
> 
> 2 - Run these 2 commands to remove the **HOME** and **END** bindings from the `workbench.xmi` file:
> 
> ```
> sed -i '' '/<bindings[^>]*keySequence="HOME"[^>]*>/,/<\/bindings>/d' "/Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi"
> ```
> 
> ```
> sed -i '' '/<bindings[^>]*keySequence="END"[^>]*>/,/<\/bindings>/d' "/Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi"
> ```
> 
> 
> 3 - Then run this command to make the file immutable. This means the file cannot be modified, deleted, or renamed, even by the root user, unless the flag is removed.
> 
> ```
> sudo chflags schg /Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
> ```
> 
> PS: replace `<user>` with your user name and update the file path if it differs on your system
> 
> 
> 4 - Reopen DBeaver
> 
> 
> If you need to remove the flag for some reason, use this command:
> 
> ```
> sudo chflags noschg /Users/<user>/Library/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
> ```

Thank you 😭!!

**Comment by MarkA1** [comment]
@cesarmansur 

> 3 - Then run this command to make the file immutable. This means the file cannot be modified, deleted, or renamed, even by the root user, unless the flag is removed.

That's an interesting brute-force work-around, and yeah, I'll bet it does work.  However, there are a LOT of configuration values in workbench.xmi that obviously will all be locked for the duration.  I would be interested to hear if you find any drawbacks after using this for a bit.  I've not really studied all the values in there.

And still, here's hoping for a DBeaver code fix, assuming it's on the DBeaver side and not an Eclipse issue.

The behavior of entries in that workbench.xmi is pretty odd and seems like a funky design with the 5 minute refreshes where the binding ID and command IDs change.  And if one looks at the commands that match the command IDs for HOME/END bindings, there is overlap/duplication, which also changes to other commands during some of those refreshes, where we have a command for HOME/END keys, but that same ID seems to also get assigned to other commands during those auto updates.  And from what I understand, the setting at DBeaver->Settings->General->Workbench Save Interval is what controls the timing on those file re-writes, but have not had time to play around with any of that.

I did look for some Eclipse documentation today on workbench.xmi briefly but didn't find any, as this workbench file and save interval is an Eclipse setting item, but it seems as though DBeaver can function fine with those key mappings even if wiped from the workbench.xmi.  I'm wondering if DBeaver is caching the values or has its own copy and not refreshing them on the DBeaver code side appropriately after some condition happens in the sql editor, or other, where the binding basically becomes invalid or pointing at some other command that messes up DBeaver's mappings.  And this issue seems to be getting worse with each release (happens more frequently), though not sure why that would be.

**Comment by cesarmansur** [comment]
@MarkA1

Yeah, it's a brute force workaround, but for me, it's the one that works best. The previous one, using `fswatch`, sometimes fails, and from what I noticed, it fails when the system is highly loaded. DBeaver updates the file, adding back the HOME and END bindings, but in the meantime, between the file being saved and reloaded, my script tries to remove the HOME and END bindings from it. It's tricky, and sometimes they are removed late...

There is one thing that I noticed. For me, it's not a drawback, but a side effect. As I'm locking the `workbench.xmi` file, when I close DBeaver and reopen it, I don't see the editor tabs that I left open, but the ones that were open when I locked the file. This is not a problem for me. Actually, I locked the `workbench.xmi` with the tabs that are usual for me. So whenever I launch DBeaver, my usual tabs are open. As I'm using the auto-save option enabled, all my SQL tabs are saved into the Scripts folder, so that's okay for me. And I can always remove the immutable flag from the `workbench.xmi` file if I need to update anything. For me, it's much better than dealing with the wrong HOME and END bindings in my editor.

@serge-rider / @uslss

I've been using DBeaver for a long time, since the first versions. Recently, my company replaced my Windows laptop with a Mac, and I started facing this issue. As I'm not allowed to install Karabiner, I did this workaround. I really like DBeaver and I don't want to stop using it because of this annoying issue. I see this thread has been open since 2020, but I'm still hoping for a code fix as well.

**Comment by msenol86** [comment]
any solution to this? I have setup my DefaultKeyBindings.dict and home and end keys work properly on most apps. However home and end keys never works as intended on DBeaver or Slack.

**Comment by mrstig** [comment]
One workaround seems to be turning off "Enable auto activation" in Editors>SQL Editor>Code Completion, so there might be some race condition when the popup overrides Home/End to be the top/bottom of the popup list, or rather when the override is removed.

**Comment by cesarmansur** [comment]
> One workaround seems to be turning off "Enable auto activation" in Editors>SQL Editor>Code Completion, so there might be some race condition when the popup overrides Home/End to be the top/bottom of the popup list, or rather when the override is removed.

This WA works perfectly. I've turned off the "Enable auto activation" option a few weeks ago and the issue with HOME/END bindings is gone! Thanks, @mrstig .

Sadly, we have to choose between autocomplete (which is a great feature!) or HOME/END bindings working as expected. This is really frustrating and after all this time (ticket is open for >5 years!!) no news from DBeaver team.

**Comment by patschwork** [comment]
I was going crazy because I doubted myself, as I kept reconfiguring it over and over again, but then luckily I found this issue here - and I'm not alone with this....

DBeaver is a great product in many ways, but how can such an annoying bug remain unresolved for so long?

Thanks, @cesarmansur for this hint 👍 , but sad, that it needs such a workaround 😔

**Comment by hdstig** [comment]
I had Fable come up with a fix, and after some iterations this is the result: https://github.com/hdstig/dbeaver/tree/fix/9414-assist-handler-guard . I've used a build based on 25.3.4 with these changes for a week or so, and I've not experienced a Home/End reset even with code completion turned on.
I don't know enough about the dbeaver project to evaluate whether this is a _good_ fix, or just AI slop with unexpected side effects, but maybe someone else has the knowledge to tackle bringing this up to standards and creating a PR.
