### ISSUE TITLE
Error altering table via UI on Redshift

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#9449]
#### System information: 
- Operating system: Ubuntu 20.04
- DBeaver version: 7.1.4
- Additional extensions: No

#### Connection specification:
- Database name and version: Redshift

#### Describe the problem you're observing:
When altering a field type or size via UI and click apply I get this error:
[Amazon](500310) Invalid operation: ALTER TABLE ALTER COLUMN cannot run inside a transaction block;

It's trying to run this, it gives me error too executing it manually (a different one)
(SQL Error [500310] [0A000]: [Amazon](500310) Invalid operation: ALTER TABLE ALTER COLUMN does not support USING expression;):
ALTER TABLE schema.table ALTER COLUMN automone TYPE varchar(200) USING automone::varchar;

if I execute the statement without the last part it works perfectly:
ALTER TABLE schema.table ALTER COLUMN automone TYPE varchar(200);

I think there are two unrelated issues, but not sure

That's it, thank you!

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by alejandrofm** [comment]
Still failing with a different error:
`[Amazon](500310) Invalid operation: ALTER TABLE ALTER COLUMN does not support USING expression;
`
I thing it shouldn't have " USING field::type;" for redshift
