### ISSUE TITLE
Adding values to arrays in UI not working

### ISSUE THREAD

**Issue by nheilbuth** [dbeaver/dbeaver#9965]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **7.2.2.202010041557**
- Additional extensions: **No**

#### Connection specification:
- Database name and version: **Postgres (tested on 9.6 and 11)**
- Driver name: **PostgreSQL JDBC Driver**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : **No**

#### Describe the problem you're observing:
When editing a cell of type array (tested with uuid[] and text[]), in the editor right clicking and choosing "Add element", will add an element with value NULL. This NULL value is not editable (it used to be). 
This means that it is not possible to add new actual values.

#### Steps to reproduce, if exist:
```
CREATE TABLE test (
	id uuid,
	testuuid uuid[],
	testtext text[],
        PRIMARY KEY (id)
);
```

```
INSERT INTO test
	VALUES 
		('40340e1a-49a4-46d7-9c67-43d96e778f4a', '{"fc201ae4-5ba3-4fe2-b8be-391822bfda56"}', '{"Test"}');
```

```		
SELECT * FROM test;
```

Mark one of the array cells and shift+enter to open editor.
Then right click to choose "Add element".
![image](https://user-images.githubusercontent.com/1744634/95050291-93b31380-06eb-11eb-8d79-cc47e4c13b4a.png)

This will add a new element with the value NULL
![image](https://user-images.githubusercontent.com/1744634/95050361-b2190f00-06eb-11eb-9070-32591ed36e66.png)

It used to be possible to double click the value in order to edit it and insert the actual value. This does not seem possible now, hence making is impossible to add actual values through the UI.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by ShadelessFox** [comment]
Probably was fixed after #9964

**Comment by nheilbuth** [comment]
No still not working on 7.2.3.202010191702

**Comment by nheilbuth** [comment]
Testing 7.2.4 gives me two different behaviours.
When running the repro stes above its still not working (as described in the original bug report).

When running a test on an existing table in one of applications, the field now lets me click to edit and it lets me put in a value, but when pressing save and returning to the main UI the inserted value is suddenly changed to NULL
![image](https://user-images.githubusercontent.com/1744634/98072470-64b4cc80-1e66-11eb-84e2-84186a833fff.png)
![image](https://user-images.githubusercontent.com/1744634/98072495-74341580-1e66-11eb-9c23-bd667a0673d2.png)
![image](https://user-images.githubusercontent.com/1744634/98072519-82823180-1e66-11eb-8c8b-6d0df76596ad.png)
![image](https://user-images.githubusercontent.com/1744634/98072663-d12fcb80-1e66-11eb-9416-72a40ab269dd.png)

Not really sure what the difference is between the repro steps and the application db (same db server, same dbeaver version etc.)

**Comment by LonwoLonwo** [comment]
![2020-11-05 17_10_56-DBeaver Enterprise 7 3 0 - test_arrays](https://user-images.githubusercontent.com/45152336/98251576-ec472c00-1f89-11eb-83bd-977ef6ba2a7a.png)
@nheilbuth Do you use ENTER at this step? when I don't use enter and the field is still visible as editable, and when I press save, it turns the new value into a NULL, yes. but if I use the ENTER after entering the value, then everything is entered and saved correctly

**Comment by nheilbuth** [comment]
Ah yes. Seems to work if I press enter. My bad.
All issues seems to have been fixed in the latest version
